(() => {
  'use strict';
  window.PARTICLELAB_MANDARIN_GLOBAL={
    'See the physics, then learn how to explain it.':'先看懂物理现象，再学会如何准确解释。',
    'This version is built to make the topic easier to follow: short explanations first, animated models second, then the exact exam language and a quick check.':'本版本按清晰学习顺序设计：先看简短解释，再观察动画模型，然后学习准确的考试表述并完成快速检查。',
    'interactive models':'互动模型',
    'AQA spec sections':'AQA 规格小节',
    'checkpoint questions':'检查问题',
    'formula helpers':'公式辅助工具',
    'Main app navigation':'应用主导航',
    'Recommended route':'推荐学习路线',
    'Learn the whole topic in a sensible order':'按合理顺序学习整个主题',
    'Start with zero assumed knowledge, master each learning chunk, use the simulation to investigate the physics, then pass the lesson check before moving on.':'从零基础开始，逐段掌握知识，用模拟探究物理现象，并通过课末检查后再继续。',
    'Use each 3D model as an investigation: predict first, change one variable, inspect labelled objects, then explain the result in AQA language.':'把每个 3D 模型当作一次探究：先预测，只改变一个变量，观察标注对象，再用 AQA 规范语言解释结果。',
    'Interactive physics simulation':'互动式物理模拟',
    'Loading 3D engine…':'正在加载 3D 引擎……',
    'Drag to rotate':'拖动旋转',
    'Wheel to zoom':'滚轮缩放',
    'Rotate':'旋转',
    'These are teaching models. Nuclear and atomic scales are deliberately exaggerated. Quarks and exchange particles are represented schematically because they are not tiny visible balls.':'这些是教学模型。核尺度和原子尺度经过有意放大。夸克和交换粒子使用示意表示，因为它们并不是可直接看见的小球。',
    'Big picture':'整体结构',
    'Interactive topic map':'互动主题地图',
    'Choose any box to see why it matters and jump to the relevant simulation.':'选择任意主题框，查看其重要性并跳转到对应模拟。',
    'Concept map of AQA Particles and Radiation':'AQA 粒子与辐射概念图',
    'Reference':'参考资料',
    'Compare families, charge, quark content and quantum numbers without memorising a giant table all at once.':'比较粒子家族、电荷、夸克组成与量子数，不必一次死记整张大表。',
    'Conservation-law checker':'守恒定律检查器',
    'Work across the reaction one quantity at a time: charge, baryon number, lepton number and strangeness.':'逐项检查反应：电荷、重子数、轻子数和奇异数。',
    'Choose a reaction':'选择一个反应',
    'Method:':'方法：',
    'add each quantum number on the left, then on the right. If one conserved quantity changes, the reaction is not allowed.':'分别求反应左、右两侧每个量子数的总和。若任何必须守恒的量发生变化，则该反应不允许。',
    'Maths support':'数学支持',
    'Pick a calculation, enter values and the app shows the substitution as well as the answer.':'选择一种计算，输入数值，应用会同时显示代入过程和答案。',
    'Calculation':'计算',
    'Worked calculation':'计算示例',
    'Practice':'练习',
    'Low-pressure knowledge check':'轻量知识检查',
    'You get feedback immediately. Use the hint if you need it before answering.':'提交后立即获得反馈；需要时可先查看提示。',
    'Question':'题目',
    'correct':'正确',
    'streak':'连续正确',
    'Restart quiz':'重新开始测验',
    'Show a hint':'显示提示',
    'Next question':'下一题',
    'Specification coverage':'规格覆盖',
    'AQA 7408 section 3.2 checklist':'AQA 7408 第 3.2 节清单',
    'Every core Particles and Radiation section is included. Rutherford is kept as a clearly labelled Nuclear Physics extension.':'粒子与辐射的全部核心小节均已包含。卢瑟福散射明确标注为核物理扩展。',
    'Useful extension:':'有用扩展：',
    'Rutherford alpha scattering is in AQA 3.8.1.1 Nuclear Physics, not 3.2. It remains in this app because it helps students understand how the nuclear model developed.':'卢瑟福 α 粒子散射属于 AQA 3.8.1.1 核物理，而不是 3.2。本应用保留它，以帮助理解核式原子模型的发展。',
    'Built as a teaching model for AQA A-level Physics. Always use your teacher\'s course materials alongside the simulations.':'本应用作为 AQA A-level 物理教学模型。使用模拟时也应结合教师提供的课程资料。',

    'Atomic structure':'原子结构',
    'Specific charge':'比荷',
    'Nuclear force':'核力',
    'Alpha & beta decay':'α 与 β 衰变',
    'Antimatter & photons':'反物质与光子',
    'Exchange particles':'交换粒子',
    'Particle families':'粒子家族',
    'Quark builder':'夸克构建器',
    'Photoelectric effect':'光电效应',
    'Electron collisions':'电子碰撞',
    'Energy levels':'能级',
    'Electron diffraction':'电子衍射',
    'Rutherford extension':'卢瑟福扩展',

    'Build isotopes and compare the nucleus with the electron cloud.':'构建同位素，并比较原子核与电子云。',
    'The nucleus contains protons and neutrons. Electrons occupy the space around it. The cloud is a probability-style picture, not tiny planets on fixed circular tracks.':'原子核包含质子和中子，电子分布在核外空间。电子云表示概率分布，并不是电子像小行星一样沿固定圆轨道运行。',
    'State charge and mass clearly, then use Z for proton number and A for total nucleons. For a neutral atom, number of electrons = Z.':'清楚写出电荷和质量；Z 表示质子数，A 表示核子总数。中性原子的电子数 = Z。',
    'The nucleus is tiny compared with the atom. The visual scale is exaggerated so you can see both.':'原子核相对整个原子非常小；模型故意夸大比例以便观察。',

    'Change nuclear charge, mass number and ion charge to see Q/m change.':'改变核电荷、质量数和离子电荷，观察 Q/m 的变化。',
    'Specific charge tells you how much charge there is for each kilogram of mass. Large charge and small mass gives a large specific charge.':'比荷表示每千克质量所带的电荷。电荷大而质量小时，比荷的绝对值更大。',
    'Use specific charge = total charge / total mass. For a nucleus, charge = Ze. For an ion, use the net ion charge.':'使用 比荷 = 总电荷 / 总质量。原子核电荷 Q = Ze；离子使用净电荷。',
    'Use the mass of the whole particle or ion, not just one proton mass unless that approximation is intended.':'应使用整个粒子或离子的质量，除非题目明确允许近似为一个质子质量。',

    'Move two nucleons together and watch the force change with separation.':'移动两个核子，观察强核力随距离变化。',
    'At normal nuclear distances the strong force pulls nucleons together. If they get extremely close it pushes them apart. Beyond a few femtometres it becomes negligible.':'正常核距离下强核力吸引核子；极近距离时变为排斥；超过几飞米后可忽略。',
    'AQA expects: attractive up to about 3 fm; repulsive closer than about 0.5 fm.':'AQA 要求：约 3 fm 内存在吸引；小于约 0.5 fm 时为排斥。',
    'Do not say the strong force has infinite range. Its range is very short.':'不要说强核力作用范围无限；它是非常短程的相互作用。',

    'Learn core alpha and beta-minus decay first; revisit beta-plus here when studying weak interactions in 3.2.1.4.':'先掌握核心 α 和 β⁻ 衰变；学习 3.2.1.4 弱相互作用时再回到 β⁺。',
    'Radioactive decay changes an unstable nucleus into a different state. Alpha throws out a helium nucleus; beta processes change a proton or neutron.':'放射性衰变使不稳定原子核转变为另一状态。α 衰变发射氦核；β 过程涉及质子/中子性质的改变。',
    'α: A −4, Z −2. β⁻: A unchanged, Z +1 and an electron antineutrino is emitted. β⁺: A unchanged, Z −1 and an electron neutrino is emitted.':'α：A−4，Z−2。β⁻：A 不变，Z+1，并发射电子反中微子。β⁺：A 不变，Z−1，并发射电子中微子。',
    'The beta electron is created in the decay; it was not an orbital electron waiting inside the nucleus.':'β 电子在衰变过程中产生，并不是原先存在于原子核里的轨道电子。',

    'Run annihilation and pair production while tracking energy and momentum.':'运行湮灭与成对产生，同时追踪能量和动量。',
    'Matter and antimatter can disappear together and their energy appears as photons. A high-energy photon can also create a particle–antiparticle pair near another body.':'物质与反物质可以一起湮灭，其能量转化为光子。高能光子也可在附近物体参与下产生粒子—反粒子对。',
    'For slow e⁻ and e⁺, total rest energy is 1.022 MeV. In the centre-of-momentum frame two gamma photons move in opposite directions.':'对于低速 e⁻ 和 e⁺，总静止能量为 1.022 MeV。在质心系中，两个 γ 光子向相反方向运动。',
    'Pair production in empty space from one photon alone cannot conserve momentum.':'单个光子在真空中独自产生成对粒子无法满足动量守恒。',

    'Switch between electromagnetic and weak interaction diagrams.':'在电磁与弱相互作用图之间切换。',
    'In the exchange-particle model, interacting particles exchange another particle. AQA uses virtual photons for electromagnetic interactions and W bosons for the weak processes you study.':'交换粒子模型中，相互作用粒子通过交换另一粒子来描述相互作用。AQA 用虚光子表示电磁相互作用，用 W 玻色子表示本课程的弱过程。',
    'Know simple diagrams for β⁻, β⁺, electron capture and electron–proton collisions, plus virtual-photon exchange for electromagnetic forces.':'需要会读 β⁻、β⁺、电子俘获、电子—质子碰撞的简单图，以及电磁作用的虚光子交换图。',
    'Do not add gluons or Z⁰ bosons to an AQA answer unless specifically given; they are not tested in this section.':'除非题目明确给出，否则不要在本节 AQA 答案中加入胶子或 Z⁰ 玻色子；它们不在本节考查范围。',

    'Explore the particle family tree and see which particles feel the strong interaction.':'探索粒子家族树，判断哪些粒子参与强相互作用。',
    'First ask: does it take part in the strong interaction? If yes, it is a hadron. Then decide baryon or meson. If no, common AQA examples are leptons.':'先问粒子是否参与强相互作用。若参与，它是强子，再判断是重子还是介子；若不参与，AQA 常见例子为轻子。',
    'Baryons: proton, neutron and antiparticles. Mesons: pions, kaons. Leptons: electron, muon, their neutrinos and antiparticles.':'重子：质子、中子及其反粒子。介子：π 介子、K 介子。轻子：电子、μ 子、对应中微子及反粒子。',
    '“Hadron” is the larger family. Baryons and mesons are both hadrons.':'“强子”是更大的家族；重子和介子都属于强子。',

    'Build protons, neutrons, pions and kaons and check charge, B and S.':'构建质子、中子、π 介子和 K 介子，并检查电荷、B 与 S。',
    'Hadrons are built from quarks. AQA only requires up, down and strange flavours and their antiquarks.':'强子由夸克构成。AQA 本节只要求上、下、奇异夸克及其反夸克。',
    'u: Q=+⅔e, B=⅓, S=0. d: Q=−⅓e, B=⅓, S=0. s: Q=−⅓e, B=⅓, S=−1. Antiquarks have opposite quantum numbers.':'u：Q=+⅔e，B=⅓，S=0；d：Q=−⅓e，B=⅓，S=0；s：Q=−⅓e，B=⅓，S=−1。反夸克具有相反的加性量子数。',
    'Do not reverse the strange-quark sign: s has strangeness −1; anti-s has +1.':'不要弄反奇异数符号：s 的 S=−1，反 s 的 S=+1。',

    'Change frequency, intensity and work function to see when electrons are emitted.':'改变频率、强度和逸出功，观察何时发射电子。',
    'Each photon gives energy hf to one electron. If hf is below the work function, nothing comes out. If hf is above it, the leftover energy becomes electron kinetic energy.':'每个光子把 hf 的能量给一个电子。若 hf 小于逸出功，不会发射；若 hf 大于逸出功，剩余能量转化为电子动能。',
    'hf = φ + KEmax. Threshold frequency f₀ = φ/h. KEmax = eVₛ.':'hf = φ + KEmax；阈频 f₀ = φ/h；KEmax = eVₛ。',
    'Intensity changes the number of emitted electrons per second, not KEmax, when frequency is unchanged.':'频率不变时，强度改变每秒发射电子数，而不改变 KEmax。',

    'Fire electrons at an atom and compare no change, excitation and ionisation.':'让电子撞击原子，比较无变化、激发和电离。',
    'An atom can absorb only certain energy amounts for excitation. If enough energy is supplied to remove an electron completely, ionisation occurs.':'原子在激发时只能吸收特定离散能量；若提供足够能量使电子完全离开原子，则发生电离。',
    'Excitation transfers an exact level difference. Ionisation needs at least the ionisation energy. Convert eV ↔ J using 1 eV = 1.602 × 10⁻¹⁹ J.':'激发需要转移恰好对应能级差的能量；电离至少需要电离能。使用 1 eV = 1.602 × 10⁻¹⁹ J 转换 eV ↔ J。',
    'If incident energy is between two allowed excitation energies, the atom cannot take an arbitrary fraction just to fit.':'若入射能量位于两个允许激发能之间，原子不能随意吸收任意部分能量来“凑数”。',

    'Choose an atomic transition and connect it to photon frequency, wavelength and line spectra.':'选择一个原子跃迁，把它与光子频率、波长和线状光谱联系起来。',
    'Atoms have allowed energy levels. When an electron falls to a lower level, one photon carries away the energy difference.':'原子具有允许能级；电子降到较低能级时，一个光子带走能级差。',
    'ΔE = hf = hc/λ. Line spectra are evidence for discrete atomic energy levels.':'ΔE = hf = hc/λ。线状光谱是原子能级离散的证据。',
    'The spectrum line colour comes from photon energy, not from the electron physically travelling along a coloured path.':'谱线颜色来自光子能量，而不是电子沿某条“有颜色的路径”运动。',

    'Increase electron momentum and watch the de Broglie wavelength and diffraction pattern change.':'增大电子动量，观察德布罗意波长和衍射图样变化。',
    'Electrons can produce diffraction patterns like waves. Higher momentum means shorter de Broglie wavelength.':'电子可以像波一样产生衍射图样。动量越大，德布罗意波长越短。',
    'λ = h/p. For non-relativistic electrons p = mv. Increasing p decreases λ and therefore reduces diffraction for a fixed structure.':'λ = h/p。非相对论电子 p = mv。p 增大使 λ 减小，因此在相同结构下衍射角通常减小。',
    'Wave–particle duality does not mean the particle flips between being a classical ball and a classical water wave.':'波粒二象性并不意味着粒子在“经典小球”和“经典水波”之间切换。',

    'Extension: use impact parameter and nuclear charge to alter alpha-particle deflection.':'扩展：改变碰撞参数和核电荷，观察 α 粒子偏转。',
    'Most alpha particles miss the tiny nucleus and travel almost straight through. A few pass close to the positive nucleus and are strongly repelled.':'大多数 α 粒子远离极小的原子核而几乎直穿；少数靠近带正电的原子核并受到强烈排斥。',
    'Most straight through → atom mostly empty space. Some large deflections → positive charge concentrated. Very few backwards → nucleus tiny and massive.':'大多数直穿 → 原子大部分为空；部分大角度偏转 → 正电荷集中；极少数后向散射 → 原子核很小且集中大部分质量。',
    'Rutherford scattering is AQA 3.8.1.1 Nuclear Physics, not part of core 3.2.':'卢瑟福散射属于 AQA 3.8.1.1 核物理，不属于核心 3.2。',

    'Proton':'质子','Neutron':'中子','Antiproton':'反质子','Antineutron':'反中子',
    'Positive pion':'正 π 介子','Negative pion':'负 π 介子','Positive kaon':'正 K 介子','Negative kaon':'负 K 介子',
    'Electron':'电子','Positron':'正电子','Electron neutrino':'电子中微子','Electron antineutrino':'电子反中微子',
    'Muon':'μ 子','Antimuon':'反 μ 子','Muon neutrino':'μ 子中微子','Photon':'光子',
    'Stable baryon and the only stable baryon in the AQA classification statement.':'稳定重子，也是 AQA 分类表述中唯一稳定的重子。',
    'A free neutron can beta-minus decay to a proton.':'自由中子可通过 β⁻ 衰变成为质子。',
    'Antiparticle of the proton.':'质子的反粒子。',
    'Antiparticle of the neutron.':'中子的反粒子。',
    'Pions are used by AQA as exchange particles for the strong nuclear force between nucleons.':'AQA 使用 π 介子作为核子之间强核力的交换粒子。',
    'A meson: one quark plus one antiquark.':'介子：一个夸克加一个反夸克。',
    'A strange meson. It can be produced strongly and decay weakly.':'奇异介子；可经强相互作用产生，并经弱相互作用衰变。',
    'Contains a strange quark, so S = −1.':'含奇异夸克，因此 S = −1。',
    'Fundamental electron-family lepton.':'电子家族的基本轻子。',
    'Electron antiparticle.':'电子的反粒子。',
    'Electron-family neutrino.':'电子家族中微子。',
    'Needed in beta-minus decay to conserve electron lepton number.':'β⁻ 衰变中需要它以满足电子轻子数守恒。',
    'Muon-family lepton; unstable and decays to lighter leptons.':'μ 子家族轻子；不稳定并会衰变成更轻的轻子。',
    'Muon antiparticle.':'μ 子的反粒子。',
    'Muon-family neutrino.':'μ 子家族中微子。',
    'Quantum of electromagnetic radiation; virtual photons model electromagnetic interactions.':'电磁辐射的量子；虚光子用于描述电磁相互作用。',

    'Beta-minus decay':'β⁻ 衰变','Beta-plus decay':'β⁺ 衰变','Electron capture':'电子俘获',
    'Electron–positron annihilation':'电子—正电子湮灭','Weak kaon decay example':'K 介子弱衰变示例','Impossible proton decay example':'不允许的质子衰变示例',
    'Allowed. At quark level d → u + W⁻.':'允许。夸克层面为 d → u + W⁻。',
    'Allowed when energy conditions permit inside an unstable nucleus.':'在不稳定原子核中，若能量条件满足则允许。',
    'Allowed weak process.':'允许的弱相互作用过程。',
    'Allowed if energy and momentum are also conserved.':'若能量和动量也守恒，则允许。',
    'Strangeness changes by −1, which is allowed in a weak interaction.':'奇异数改变 −1；弱相互作用允许这种变化。',
    'Not allowed by the AQA conservation laws shown here.':'根据这里使用的 AQA 守恒定律，该反应不允许。',
    'Check each quantity':'逐项检查',
    'Quantity':'物理量','Before':'反应前','After':'反应后','Check':'检查',
    '✓ conserved':'✓ 守恒','✕ violated':'✕ 不守恒',
    'weak interaction':'弱相互作用','electromagnetic interaction':'电磁相互作用','not allowed interaction':'不允许的相互作用',

    'Photon energy from frequency':'由频率求光子能量',
    'Photon energy from wavelength':'由波长求光子能量',
    'Photoelectric KE and stopping potential':'光电效应动能与遏止电势',
    'de Broglie wavelength':'德布罗意波长',
    'Specific charge':'比荷',
    'eV to joules':'eV 转焦耳',
    'Frequency f':'频率 f','Wavelength λ (m)':'波长 λ (m)','Work function φ (eV)':'逸出功 φ (eV)',
    'Momentum p (kg m s⁻¹)':'动量 p (kg m s⁻¹)','Charge Q (C)':'电荷 Q (C)','Mass m (kg)':'质量 m (kg)','Energy (eV)':'能量 (eV)',
    'photon energy from frequency':'由频率求光子能量','photon energy from wavelength':'由波长求光子能量',
    'photoelectric equation':'光电方程','stopping potential':'遏止电势','charge-to-mass ratio':'荷质比','energy conversion':'能量转换',

    'Which statement describes isotopes?':'哪一项正确描述同位素？',
    'Same Z, different neutron number':'Z 相同，中子数不同','Different Z, same neutron number':'Z 不同，中子数相同','Same A, different Z':'A 相同，Z 不同','Different numbers of protons and electrons only':'仅质子数和电子数不同',
    'Keep the element the same: proton number must stay the same.':'元素不变意味着质子数必须保持相同。',
    'Isotopes are atoms of the same element, so they have the same proton number Z but different neutron numbers.':'同位素属于同一种元素，因此质子数 Z 相同，但中子数不同。',
    'What is the specific charge of a particle?':'粒子的比荷是什么？',
    'mass ÷ charge':'质量 ÷ 电荷','charge ÷ mass':'电荷 ÷ 质量','charge × mass':'电荷 × 质量','number of protons ÷ mass':'质子数 ÷ 质量',
    'Look at the unit C kg⁻¹.':'注意单位 C kg⁻¹。',
    'Specific charge is Q/m and is measured in C kg⁻¹.':'比荷为 Q/m，单位 C kg⁻¹。',
    'At a nucleon separation of about 1 fm, the strong nuclear force is mainly…':'核子间距约 1 fm 时，强核力主要是……',
    'attractive':'吸引','zero':'零','electrostatic only':'只有静电作用','repulsive at all distances':'所有距离都排斥',
    '1 fm lies between the very-short repulsive region and the ~3 fm limit.':'1 fm 位于极短程排斥区与约 3 fm 作用范围之间。',
    'At typical nuclear separations the strong nuclear force is attractive.':'典型核距离下强核力为吸引力。',
    'During beta-minus decay, the proton number Z…':'β⁻ 衰变中，质子数 Z……',
    'decreases by 2':'减少 2','decreases by 1':'减少 1','stays the same':'保持不变','increases by 1':'增加 1',
    'A neutron changes into a proton.':'中子性质转变为质子性质。',
    'A increases by 0 and Z increases by 1 in β⁻ decay.':'β⁻ 衰变中 A 不变，Z 增加 1。',
    'Which pair has equal mass and opposite charge?':'哪一对粒子质量相同且电荷相反？',
    'electron and proton':'电子与质子','electron and positron':'电子与正电子','proton and neutron':'质子与中子','photon and electron':'光子与电子',
    'Think particle and antiparticle.':'想一想粒子与反粒子。',
    'The positron is the electron antiparticle: same mass, opposite charge.':'正电子是电子的反粒子：质量相同，电荷相反。',
    'A photon has energy…':'光子的能量为……','mc² only':'只有 mc²','hf':'hf','mv':'mv','Q/m':'Q/m',
    'Use Planck constant h.':'使用普朗克常量 h。','Photon energy is E = hf.':'光子能量 E = hf。',
    'What exchange particle models the electromagnetic interaction?':'电磁相互作用用哪一种交换粒子表示？',
    'pion':'π 介子','W⁻ only':'只有 W⁻','virtual photon':'虚光子','neutrino':'中微子',
    'It belongs to the same radiation family as light, but is virtual in the force model.':'它与光同属光子概念，但在力的交换模型中是虚光子。',
    'AQA uses virtual photons as exchange particles for electromagnetic interactions.':'AQA 使用虚光子作为电磁相互作用的交换粒子。',
    'Which exchange particles are required for the weak interactions in this topic?':'本主题弱相互作用需要哪些交换粒子？',
    'W⁺ and W⁻':'W⁺ 和 W⁻','gluons only':'只有胶子','pions only':'只有 π 介子','photons only':'只有光子',
    'Think beta processes.':'想一想 β 过程。','AQA requires W⁺ and W⁻ for the weak-interaction diagrams.':'AQA 的弱相互作用图要求 W⁺ 和 W⁻。',
    'Which particle is a meson?':'哪一个粒子是介子？','proton':'质子','electron':'电子','kaon':'K 介子','neutron':'中子',
    'Mesons are hadrons made from quark + antiquark.':'介子是由一个夸克和一个反夸克组成的强子。','Kaons and pions are the AQA meson examples.':'K 介子和 π 介子是 AQA 要求的介子例子。',
    'Which statement about strange particles is correct?':'关于奇异粒子，哪一项正确？',
    'They are produced weakly and decay strongly':'经弱作用产生、强作用衰变','They are produced strongly and decay weakly':'经强作用产生、弱作用衰变','They are all leptons':'它们都是轻子','Strangeness never changes':'奇异数永不改变',
    'Remember the “strange” lifetime clue.':'记住奇异粒子的产生与衰变方式。','AQA describes strange particles as produced through the strong interaction and decaying through the weak interaction.':'AQA 描述奇异粒子经强相互作用产生、经弱相互作用衰变。',
    'What is the quark content of a proton?':'质子的夸克组成是什么？','udd':'udd','uud':'uud','uuu':'uuu','u d̄':'u d̄',
    'Two up quarks give +4/3e and one down gives −1/3e.':'两个 u 给 +4/3e，一个 d 给 −1/3e。','A proton is uud.':'质子为 uud。',
    'What is the strangeness of an s quark?':'s 夸克的奇异数是多少？','+1':'+1','0':'0','−1':'−1','+1/3':'+1/3',
    'Antistrange has the opposite sign.':'反奇异夸克符号相反。','The strange quark has S = −1; anti-s has S = +1.':'奇异夸克 S=−1；反 s 的 S=+1。',
    'Why is an antineutrino included in beta-minus decay?':'为什么 β⁻ 衰变中需要反中微子？',
    'to conserve baryon number only':'只为了守恒重子数','to conserve electron lepton number and energy/momentum':'为了守恒电子轻子数以及能量/动量','to make the charge +1':'为了使电荷变成 +1','because every neutron contains a neutrino':'因为每个中子都含中微子',
    'Check the lepton number before and after.':'检查反应前后的轻子数。','The antineutrino is needed for conservation laws including electron lepton number, energy and momentum.':'反中微子用于满足电子轻子数、能量和动量等守恒定律。',
    'In a strong interaction, strangeness must…':'强相互作用中，奇异数必须……',
    'always increase by 1':'总是增加 1','always decrease by 1':'总是减少 1','be conserved':'守恒','equal baryon number':'等于重子数',
    'Weak interactions are the ones where S can change by 0 or ±1.':'弱相互作用中 S 可以改变 0 或 ±1。','Strangeness is conserved in strong interactions.':'强相互作用中奇异数守恒。',
    'Light is below the threshold frequency. Increasing intensity will…':'光的频率低于阈频。增大强度会……',
    'release higher-energy electrons':'释放更高能电子','eventually cause emission':'最终会造成发射','still cause no photoelectron emission':'仍不会发射光电子','increase photon energy':'增加光子能量',
    'Intensity changes photon rate, not hf.':'强度改变光子到达率，而不是 hf。','Below threshold frequency each photon has insufficient energy, so no emission occurs.':'低于阈频时每个光子能量不足，因此不会发射。',
    'Which equation is the photoelectric equation?':'哪一个是光电方程？','F = ma':'F = ma','λ = h/p only':'只有 λ = h/p','Q = It':'Q = It',
    'Photon energy is split into removal energy and remaining kinetic energy.':'光子能量分为克服逸出功的能量和剩余动能。','hf = φ + KEmax.':'hf = φ + KEmax。',
    'Excitation means…':'激发是指……','removing an electron completely':'完全移走电子','moving an electron to a higher bound level':'电子移动到更高束缚能级','creating a proton':'产生质子','splitting the nucleus':'裂开原子核',
    'The electron stays in the atom.':'电子仍留在原子中。','Excitation raises an electron to a higher allowed level without removing it.':'激发使电子进入更高允许能级，但不会把它从原子中移走。',
    '1 eV is equal to approximately…':'1 eV 约等于……','1.60 × 10⁻¹⁹ J':'1.60 × 10⁻¹⁹ J','6.63 × 10⁻³⁴ J':'6.63 × 10⁻³⁴ J','9.11 × 10⁻³¹ J':'9.11 × 10⁻³¹ J','3.00 × 10⁸ J':'3.00 × 10⁸ J',
    'It uses the elementary charge in coulombs.':'它使用以库仑表示的基本电荷。','1 eV = 1.602 × 10⁻¹⁹ J.':'1 eV = 1.602 × 10⁻¹⁹ J。',
    'Why does an atomic line spectrum contain separate lines?':'为什么原子线状光谱包含分立谱线？',
    'atoms have discrete energy levels':'原子具有离散能级','electrons can have any energy':'电子可以有任意能量','photons have mass':'光子有质量','all wavelengths are absorbed':'所有波长都被吸收',
    'Think allowed energy differences.':'考虑允许的能级差。','Discrete levels give specific ΔE values and therefore specific photon frequencies.':'离散能级产生特定 ΔE，因此产生特定光子频率。',
    'If an electron drops to a lower energy level, the atom…':'电子降到较低能级时，原子……',
    'absorbs a photon':'吸收光子','emits a photon':'发射光子','changes proton number':'改变质子数','must ionise':'必须电离',
    'Energy leaves the atom.':'能量离开原子。','A downward transition emits a photon with energy equal to the level difference.':'向下跃迁会发射能量等于能级差的光子。',
    'Electron diffraction is evidence that electrons have…':'电子衍射说明电子具有……','only particle properties':'只有粒子性质','wave properties':'波动性质','zero momentum':'零动量','positive charge':'正电荷',
    'Diffraction is a wave behaviour.':'衍射是波动行为。','Electron diffraction demonstrates wave-like behaviour of matter.':'电子衍射说明物质具有波动性。',
    'If particle momentum doubles, de Broglie wavelength…':'粒子动量加倍时，德布罗意波长……','doubles':'加倍','halves':'减半','stays constant':'保持不变','becomes zero':'变为零',
    'λ = h/p.':'λ = h/p。','Since λ is inversely proportional to p, doubling p halves λ.':'λ 与 p 成反比，因此 p 加倍时 λ 减半。',
    'Which quantity is conserved in all particle interactions studied here?':'本课程研究的所有粒子相互作用中，哪一个量都守恒？',
    'charge':'电荷','strangeness':'奇异数','number of particles':'粒子数','kinetic energy separately':'单独的动能',
    'One option is universal; strangeness depends on interaction type.':'其中一个量始终守恒；奇异数取决于相互作用类型。','Electric charge is conserved in all the interactions considered.':'所考虑的所有相互作用中电荷都守恒。',
    'Which statement best links the two quantum-phenomena experiments?':'哪一项最准确地联系两种量子现象实验？',
    'Photoelectric effect shows light can act as particles; electron diffraction shows matter can act as waves':'光电效应说明光可表现粒子性；电子衍射说明物质可表现波动性',
    'Both prove electrons have no mass':'两者都证明电子没有质量','Both show light is only a wave':'两者都说明光只有波动性','Both are nuclear decay experiments':'两者都是核衰变实验',
    'One experiment gives particle evidence for light, the other wave evidence for electrons.':'一个实验提供光的粒子性证据，另一个提供电子的波动性证据。',
    'Together they motivate wave–particle duality.':'两者共同支持波粒二象性。',

    'Correct — keep going.':'正确——继续。',
    'Not quite — use the simple explanation above, then try the idea again later.':'还不完全正确——先看上方简单解释，稍后再尝试。',
    'Correct.':'正确。',
    'Not quite.':'还不完全正确。'
  };

  Object.assign(window.PARTICLELAB_MANDARIN_GLOBAL,{
    "Current state":"当前状态",
    "Unstable nucleus":"不稳定原子核",
    "Weak change inside the nucleus":"原子核内部发生弱相互作用变化",
    "Emitted particles separate":"发射粒子彼此分离",
    "Daughter nucleus remains":"留下子核",
    "Particles/photon approach":"粒子/光子接近",
    "Energy is concentrated at the interaction":"能量集中在相互作用位置",
    "New photons or pair appear":"产生新的光子或粒子对",
    "Energy and momentum are checked":"检查能量与动量守恒",
    "Incoming particles":"入射粒子",
    "Exchange particle carries the interaction":"交换粒子传递相互作用",
    "Interaction vertex":"相互作用顶点",
    "Outgoing particles":"出射粒子",
    "Photon approaches metal":"光子接近金属表面",
    "Photon energy transfers to one electron":"光子能量传递给一个电子",
    "Electron overcomes work function":"电子克服逸出功",
    "Photoelectron leaves the surface":"光电子离开表面",
    "Electron approaches":"电子接近",
    "Collision occurs":"发生碰撞",
    "Excitation or ionisation happens":"发生激发或电离",
    "Particles leave with conserved energy":"粒子离开且总能量守恒",
    "Electron begins on upper level":"电子起始于较高能级",
    "Electron changes energy":"电子能量发生变化",
    "Photon is emitted":"发射光子",
    "Electron remains on lower level":"电子留在较低能级",
    "Electron beam travels":"电子束传播",
    "Electron reaches diffracting structure":"电子到达衍射结构",
    "Wave-like diffraction occurs":"出现波动性的衍射",
    "Ring pattern is observed":"观察到环形衍射图样",
    "Alpha particle approaches":"α 粒子接近",
    "Coulomb repulsion increases near nucleus":"靠近原子核时库仑排斥增强",
    "Trajectory bends":"轨迹发生弯曲",
    "Detector records the scattering angle":"探测器记录散射角",
    'electrons':'电子',
    'protons':'质子',
    'neutrons':'中子',
    'mass number':'质量数',
    'proton number':'质子数',
    "Quick isotope preset":"快速同位素预设",
    "Protons · Z":"质子 · Z",
    "Neutrons · N":"中子 · N",
    "Mass number · A":"核子数 · A",
    "Proton number Z":"质子数 Z",
    "Nucleon number A":"核子数 A",
    "Electrons present":"电子数",
    "Nucleon separation":"核子间距",
    "Decay type":"衰变类型",
    "Process":"过程",
    "Interaction":"相互作用",
    "Highlight family":"高亮粒子家族",
    "Build a hadron":"构建强子",
    "Photon frequency":"光子频率",
    "Light intensity":"光强",
    "Work function φ":"逸出功 φ",
    "Incident electron energy":"入射电子能量",
    "Model threshold set":"模型阈值组",
    "Hydrogen transition":"氢原子跃迁",
    "Electron accelerating voltage":"电子加速电压",
    "Impact parameter":"碰撞参数",
    "Nuclear charge Z":"核电荷 Z",
    "Open its simulation":"打开对应模拟",
    "Open lesson":"打开课程",
    "Open simulation":"打开模拟",
    "− neutron":"− 中子",
    "+ neutron":"+ 中子",
    "Make neutral":"变为中性",
    "Make +1 ion":"变为 +1 离子",
    "Make −1 ion":"变为 −1 离子",
    "Run decay":"运行衰变",
    "Run animation":"运行动画",
    "alpha decay":"α 衰变",
    "beta-minus decay":"β⁻ 衰变",
    "beta-plus decay":"β⁺ 衰变",
    "annihilation: e⁻ + e⁺ → γ + γ":"湮灭：e⁻ + e⁺ → γ + γ",
    "pair production near a nucleus":"原子核附近的成对产生",
    "electromagnetic: like charges repel":"电磁相互作用：同号电荷相斥",
    "beta-minus":"β⁻",
    "beta-plus":"β⁺",
    "electron capture":"电子俘获",
    "electron–proton collision":"电子—质子碰撞",
    "all particles":"所有粒子",
    "hadrons":"强子",
    "baryons":"重子",
    "mesons":"介子",
    "leptons":"轻子",
    "proton p = uud":"质子 p = uud",
    "neutron n = udd":"中子 n = udd",
    "hydrogen example: excitation 10.2 eV, ionisation 13.6 eV":"氢原子示例：激发 10.2 eV，电离 13.6 eV",
    "simplified fluorescent-tube teaching example: 4 eV, 8 eV":"简化荧光灯教学示例：4 eV、8 eV",
    "Build an isotope:":"构建同位素：",
    "Change isotope:":"改变同位素：",
    "Z stays fixed":"Z 保持不变",
    "Rules:":"规则：",
    "element = Z":"元素由 Z 决定",
    "isotope changes N":"同位素改变 N",
    "A = Z + N":"A = Z + N",
    "neutral atom: electrons = Z":"中性原子：电子数 = Z",
    "ion formation changes electrons only.":"形成离子时只改变电子数。",
    "Custom isotope / ion":"自定义同位素 / 离子",
    "Hydrogen-1 · ¹₁H":"氢-1 · ¹₁H",
    "Carbon-12 · ¹²₆C":"碳-12 · ¹²₆C",
    "Carbon-14 · ¹⁴₆C":"碳-14 · ¹⁴₆C",
    "Oxygen-16 · ¹⁶₈O":"氧-16 · ¹⁶₈O",
    "Sodium-23 · ²³₁₁Na":"钠-23 · ²³₁₁Na",
    "Chlorine-35 · ³⁵₁₇Cl":"氯-35 · ³⁵₁₇Cl",
    "Chlorine-37 · ³⁷₁₇Cl":"氯-37 · ³⁷₁₇Cl",
    "Gold-197 · ¹⁹⁷₇₉Au":"金-197 · ¹⁹⁷₇₉Au",
    'Diagnostic & lesson hub':'诊断与课程中心',
    "Nucleus":"原子核",
    "Electron cloud":"电子云",
    "Mass of the ion/nucleus":"离子/原子核质量",
    "Electrons":"电子",
    "Proton / nucleon":"质子 / 核子",
    "Force region":"作用力区域",
    "Parent nucleus":"母核",
    "Emitted charged particle":"发射的带电粒子",
    "Neutrino / antineutrino":"中微子 / 反中微子",
    "Matter particle":"物质粒子",
    "Antiparticle / products":"反粒子 / 产物",
    "Energy conversion":"能量转化",
    "Incoming particle":"入射粒子",
    "Exchange particle":"交换粒子",
    "Outgoing particle":"出射粒子",
    "Baryons":"重子",
    "Mesons":"介子",
    "Leptons":"轻子",
    "Quark content":"夸克组成",
    "Hadron binding model":"强子结合模型",
    "Photon":"光子",
    "Metal surface":"金属表面",
    "Photoelectron":"光电子",
    "Incident electron":"入射电子",
    "Atom":"原子",
    "After the collision":"碰撞之后",
    "Allowed energy levels":"允许能级",
    "Electron transition":"电子跃迁",
    "Electron beam":"电子束",
    "Diffraction screen":"衍射屏",
    "Diffraction rings":"衍射环",
    "Positive nucleus":"带正电的原子核",
    "Close alpha path":"近距离 α 路径",
    "Distant alpha path":"远距离 α 路径",
    "Live 3D explanation":"实时 3D 解释",
    "Explore the model":"探索模型",
    "Science":"物理原理",
    "Exam link":"考试联系",
    "Inspect 3D":"查看 3D 标注",
    "Hide 3D labels":"隐藏 3D 标注",
    "Use the Model guide beside the simulation to identify each object. The 3D scene now contains only the physics model.":"使用模拟旁的模型指南识别每个对象。3D 场景只显示物理模型。",
    'Learning tools':'学习工具',
    'Glossary':'词汇表',
    'Evidence Lab':'证据实验室',
    'Start here':'从这里开始',
    'No prior knowledge required':'无需先备知识',
    'Your route':'你的学习路线',
    'From zero → confident A-level learner':'从零基础 → 自信的 A-level 学习者',
    'Readiness':'学习准备度',
    'Begin Lesson 1':'开始第 1 课',
    'Baseline check':'基础诊断',
    'What do you already know?':'你已经掌握什么？',
    'Check my starting point':'检查我的起点',
    'Result':'结果',
    'Prerequisite bridge':'先备知识衔接',
    'Six things to know before Lesson 1':'第 1 课前需要掌握的六项内容',
    'Big picture':'整体结构',
    'How the whole topic connects':'整个主题如何连接',
    'Vocabulary ladder':'词汇阶梯',
    'Words you will meet repeatedly':'会反复出现的关键词',
    'Build the minimum maths, GCSE science and vocabulary needed before Lesson 1.':'补齐开始第 1 课所需的最低限度数学、GCSE 科学和词汇基础。',
    'Take the diagnostic first. If anything is unfamiliar, complete the matching bridge cards, then begin Lesson 1. You can return here at any time.':'先完成诊断。如果有任何陌生内容，请完成对应的衔接卡片，再开始第 1 课。你可以随时回到这里。',
    'This does not affect mastery scores. It simply tells you what to revise before starting.':'这不会影响掌握度评分，只用于提示开始前需要复习什么。',
    'No prerequisite gaps detected.':'未发现先备知识缺口。',
    'Mark each card secure only when you could explain the check question without looking.':'只有当你不看答案也能解释检查题时，才把该卡片标记为已掌握。',
    'Use this before learning the topic and again during revision. Every later idea grows from an earlier one.':'学习主题前使用一次，复习时再使用。后面的每个概念都建立在前面的知识上。',
    'Do not memorise all of these before starting. Use this as a quick reference whenever a lesson uses unfamiliar language.':'开始前不必一次记住全部内容；课程中遇到陌生术语时可随时查阅。',

    'Revision hub':'复习中心',
    'Retrieve · repair · repeat':'检索 · 修补 · 重复',
    'Today':'今天',
    'Build a 20-minute revision session':'建立 20 分钟复习计划',
    'Generate today’s session':'生成今天的复习计划',
    'Lesson sequence':'课程序列',
    'Revision status':'复习状态',
    'Priority map':'优先复习地图',
    'Revise weakest first':'先复习最薄弱内容',
    '20-minute session':'20 分钟复习',
    'Do this in order':'按此顺序完成',
    'Open':'打开',
    'Spaced retrieval':'间隔检索',
    'Again':'再来一次',
    'Hard':'困难',
    'Good':'良好',
    'Easy':'简单',
    'Exam-style retrieval':'考试式检索',
    '20-question mixed check':'20 题混合检查',
    'Mark test':'批改测试',
    'Reset answers':'重置答案',
    'Formula retrieval':'公式检索',
    'Definition retrieval':'定义检索',
    'Say or write the answer before revealing it':'显示答案前先说出或写出答案',
    'Reveal':'显示',
    'Next':'下一项',
    'Reference':'参考资料',
    'Searchable glossary':'可搜索词汇表',
    'Clear':'清除',
    'AQA coverage':'AQA 覆盖',
    'Full specification checklist':'完整规格清单',
    'Whole topic at a glance':'整个主题一览',
    'Particles & Radiation knowledge organiser':'粒子与辐射知识整理表',
    'Print / save as PDF':'打印 / 保存为 PDF',
    'Open lesson sequence':'打开课程序列',
    'Atoms & nuclei':'原子与原子核',
    'Decay':'衰变',
    'Photons & antiparticles':'光子与反粒子',
    'Interactions':'相互作用',
    'Particle families':'粒子家族',
    'Quarks':'夸克',
    'Conservation':'守恒定律',
    'Collisions & eV':'碰撞与 eV',
    'Wave–particle duality':'波粒二象性',
    'Common traps':'常见陷阱',
    'Rutherford extension · 3.8.1.1':'卢瑟福扩展 · 3.8.1.1',
    'Repair mistakes':'修正错误',
    'Error log':'错题记录',
    'Clear all':'全部清除',
    'I can explain this now':'我现在能够解释',
    'Use retrieval practice and spaced review rather than only rereading notes.':'使用检索练习和间隔复习，而不是只反复阅读笔记。',
    'The session generator prioritises weak topics from your quiz errors and app activity.':'复习计划会根据测验错误和应用活动优先安排薄弱主题。',
    'Click the card to reveal the answer, then grade how well you remembered it.':'点击卡片显示答案，然后评价自己的回忆程度。',
    'Answer without notes, then submit once. Wrong answers are added to your error log and lower that topic’s revision score.':'不看笔记作答，然后一次提交。错误答案会加入错题记录，并降低该主题的复习评分。',
    'Tick a point only when you could explain it without notes and answer a question on it.':'只有当你不用笔记就能解释该知识点并回答相关问题时，才勾选它。',
    'Use this after learning the topic. It is a summary, not a replacement for the lesson explanations.':'学习主题后使用。这是总结，不是对课程讲解的替代。',
    'Wrong mixed-test answers stay here until you remove them after successful correction.':'混合测试中的错误会保留在这里，直到你完成订正后手动移除。',
    'No logged errors. Complete the mixed test to create a targeted error list.':'目前没有记录错误。完成混合测试后可生成针对性的错题清单。',

    'Exam skills':'考试技巧',
    'Turn knowledge into marks':'把知识转化为分数',
    'AQA language':'AQA 答题语言',
    'Command-word coach':'指令词辅导',
    'Calculation routine':'计算步骤',
    'Use the same method every time':'每次使用同一套方法',
    'Worked calculations':'计算示例',
    'Step-by-step examples':'分步示例',
    'Long answers':'长答题',
    'Physics explanation builder':'物理解释构建器',
    'Avoid these':'避免这些错误',
    'Common mark killers':'常见失分点',
    'Command words, calculation method, explanation structure and common mark-losing errors.':'学习指令词、计算方法、解释结构以及常见失分错误。',

    'Evidence lab':'证据实验室',
    'Evidence Lab':'证据实验室',
    'AQA evidence and practical links':'AQA 证据与实验联系',
    'Language support':'语言支持',
    'Particles & Radiation glossary':'粒子与辐射词汇表',
    'Classroom controls':'课堂控制',
    'Teaching mode':'教学模式',
    'Explanation level':'解释层级',
    '🔊 Read aloud':'🔊 朗读',
    'Predict before reveal':'显示答案前先预测',
    'Need help':'需要帮助',
    'Nearly there':'接近掌握',
    'Confident':'有信心',
    'Required weak-interaction diagrams':'必会弱相互作用图',
    'Interaction diagram trainer':'相互作用图训练',
    'Process':'过程',
    'Search a term and see the definition in AQA-friendly language.':'搜索术语并查看符合 AQA 表述的定义。',
    'Start with what you would observe, then connect it to the model and the exam conclusion.':'先写你会观察到什么，再把现象与模型及考试结论联系起来。',
    'Follow incoming particles → exchange particle → outgoing particles.':'按照 入射粒子 → 交换粒子 → 出射粒子 的顺序分析。',

    'Practice studio':'练习工作室',
    'Targeted practice':'针对性练习',
    'Adaptive route':'自适应路线',
    'Interaction builder':'相互作用构建器',
    'Decay equations':'衰变方程',
    'Misconceptions':'易错概念',
    'Exam studio':'考试训练',
    'Recommended next':'推荐下一步',
    'Open teaching simulation':'打开教学模拟',
    'Build the interaction':'构建相互作用',
    'Interaction type':'相互作用类型',
    'Exchange particle':'交换粒子',
    'Check my model':'检查我的模型',
    'Daughter A':'子核 A',
    'Daughter Z':'子核 Z',
    'Emitted particle(s)':'发射粒子',
    'Check equation':'检查方程',
    'New example':'新例题',
    'Method':'方法',
    'True':'正确',
    'False':'错误',
    'Your answer':'你的答案',
    'Save answer':'保存答案',
    'Hint':'提示',
    'Reveal mark points':'显示评分点',
    'Self-mark':'自我评分',
    'Previous':'上一项',
    'Open related simulation':'打开相关模拟',
    'Move from supported practice to independent exam answers. All questions here are original teaching questions.':'从有支持的练习逐步过渡到独立考试作答。这里的题目均为原创教学题。',
    'The route prioritises topics you have not yet marked secure. Re-rate yourself after practice.':'路线会优先安排尚未标记为掌握的主题；练习后重新评价自己。',
    'Write your answer first, then reveal the mark points.':'先写答案，再显示评分点。',
    'Diagram is schematic: exchange particles represent the interaction rather than visible paths.':'图示为示意图：交换粒子表示相互作用，而不是可直接看见的真实路径。',

    'Diagnostic & lessons':'诊断与课程',
    'Find the gap, then fix it':'找出知识缺口，再针对修补',
    'Diagnostic':'诊断',
    'Lesson launcher':'课程启动器',
    'Compare particles':'比较粒子',
    'Data & evidence':'数据与证据',
    'Exam command words':'考试指令词',
    'Finish diagnostic':'完成诊断',
    'Diagnostic result':'诊断结果',
    'Open reteaching simulation':'打开重新教学模拟',
    'Retake diagnostic':'重新诊断',
    'Open Practice Studio':'打开练习工作室',
    'Topic':'主题',
    'Lesson length':'课程时长',
    'Open AQA checklist':'打开 AQA 清单',
    'Reason from evidence':'根据证据推理',
    'Reveal reasoning':'显示推理',
    'Command-word translator':'指令词转换器',
    'A short AQA diagnostic, targeted reteaching, classroom lesson launcher, particle comparison and data-reasoning practice.':'提供简短 AQA 诊断、针对性重新教学、课程启动、粒子比较以及数据推理练习。',
    'Choose up to four particles. Use the quantum-number rows to practise conservation checks.':'最多选择四种粒子，并用量子数行练习守恒检查。'
  });
})();