'use strict';
// Keep the supplied six activities; strengthen their checking and interaction.
const $=id=>document.getElementById(id);
GraphGrid.prototype.draw=function(){const ctx=this.ctx,w=this.canvas.width,h=this.canvas.height,p=this.padding;ctx.clearRect(0,0,w,h);ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,w,h);const step=range=>{const raw=range/8,base=10**Math.floor(Math.log10(raw));return [1,2,5,10].find(n=>n*base>=raw)*base;};const sx=step(this.xMax-this.xMin),sy=step(this.yMax-this.yMin);const grid=(minor,color)=>{ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();for(let x=this.xMin;x<=this.xMax+1e-8;x+=sx/minor){ctx.moveTo(this.mapX(x),p);ctx.lineTo(this.mapX(x),h-p);}for(let y=this.yMin;y<=this.yMax+1e-8;y+=sy/minor){ctx.moveTo(p,this.mapY(y));ctx.lineTo(w-p,this.mapY(y));}ctx.stroke();};grid(5,'#e2e8f0');grid(1,'#bfcddb');ctx.strokeStyle='#334155';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p,p);ctx.lineTo(p,h-p);ctx.lineTo(w-p,h-p);ctx.stroke();ctx.fillStyle='#475569';ctx.font='12px system-ui';ctx.textAlign='center';ctx.textBaseline='top';for(let x=this.xMin;x<=this.xMax+1e-8;x+=sx)ctx.fillText(Number(x.toFixed(3)),this.mapX(x),h-p+7);ctx.textAlign='right';ctx.textBaseline='middle';for(let y=this.yMin;y<=this.yMax+1e-8;y+=sy)ctx.fillText(Number(y.toFixed(3)),p-8,this.mapY(y));ctx.fillStyle='#173c59';ctx.font='bold 13px system-ui';ctx.textAlign='center';ctx.fillText(this.xLabel,w/2,h-19);ctx.save();ctx.translate(18,h/2);ctx.rotate(-Math.PI/2);ctx.fillText(this.yLabel,0,0);ctx.restore();};
relationships.inverse.fn=x=>x>0?200/x:NaN;
relationships.inverse_square.fn=x=>x>0?1000/(x*x):NaN;
const progressKey='revision-graph-skills-v1';
let graphProgress={skills:{},lastModule:'module-plotting',latestTest:null,bestScore:0};
try{const saved=JSON.parse(localStorage.getItem(progressKey));if(saved&&typeof saved.skills==='object')graphProgress={...graphProgress,...saved};}catch{}
let fitPoints=[],quizSolved=false,areaSolved=false,barsSolved=false,messageTimer;
const relationshipNotes={
 proportional:'A straight line through the origin: y/x is constant. Doubling x doubles y.',
 linear:'A straight line with a non-zero intercept has constant gradient, but y/x is not constant.',
 inverse:'For y = k/x, doubling x halves y; xy is constant. The curve never reaches x = 0.',
 quadratic:'For y = kx², doubling x multiplies y by four. The gradient increases as x increases.',
 inverse_square:'For y = k/x², doubling x divides y by four; yx² is constant.',
 exponential:'Over equal intervals, the same fraction remains. Radioactive decay approaches zero.',
 plateau:'The rate rises then approaches a limit, for example when all enzyme active sites are occupied.'
};
function saveProgress(){try{localStorage.setItem(progressKey,JSON.stringify(graphProgress));}catch{}updateProgress();}
function completeSkill(id){graphProgress.skills[id]=true;saveProgress();}
function updateProgress(){const count=Object.values(graphProgress.skills).filter(Boolean).length;const box=$('graph-progress');if(!box)return;box.innerHTML=`<strong>${count} of 5 skills practised</strong><progress value="${count}" max="5" aria-label="Skills practised"></progress><small>${graphProgress.latestTest?`Last test: ${graphProgress.latestTest.score}/5 · Best: ${graphProgress.bestScore}/5<br>`:''}Saved on this device. You can revisit any activity.</small>`;document.querySelectorAll('.graph-workspace nav li button').forEach(button=>{const id=button.id.replace('tab-module-','');const name=button.dataset.label||button.textContent.trim();button.dataset.label=name;button.textContent=name+(graphProgress.skills[id]?' ✓':'');});}
function showMessage(msg,isSuccess=true){const box=$('custom-alert');$('alert-message').textContent=msg;box.classList.toggle('bg-red-900',!isSuccess);box.classList.toggle('bg-green-900',isSuccess);$('alert-icon-success').classList.toggle('hidden',!isSuccess);$('alert-icon-error').classList.toggle('hidden',isSuccess);box.classList.remove('opacity-0','-translate-y-4','pointer-events-none');clearTimeout(messageTimer);messageTimer=setTimeout(()=>box.classList.add('opacity-0','-translate-y-4','pointer-events-none'),8000);}
function feedback(id,msg,success){const node=$(id);if(!node)return;node.textContent=msg;node.classList.remove('hidden');node.style.color=success?'#166534':'#9f1239';showMessage(msg,success);}
function switchTab(id){if(!$(id))id='module-plotting';document.querySelectorAll('.module-section').forEach(el=>el.classList.toggle('hidden',el.id!==id));document.querySelectorAll('.graph-workspace nav li button').forEach(button=>{const active=button.id==='tab-'+id;button.classList.toggle('bg-slate-800',active);button.classList.toggle('border-blue-500',active);button.classList.toggle('border-transparent',!active);button.setAttribute('aria-current',active?'step':'false');});graphProgress.lastModule=id;saveProgress();resizeCanvases();window.scrollTo({top:0,behavior:'instant'});}
function changeDataset(){
 currentDatasetKey=$('dataset-selector').value;const ds=datasets[currentDatasetKey];
 const rand=(low,high)=>Math.round((low+Math.random()*(high-low))*10)/10;
 if(currentDatasetKey==='cooling'){const room=Math.round(rand(18,24)),amp=rand(50,65),rate=.03+Math.random()*.03;ds.idealFn=x=>amp*Math.exp(-rate*x)+room;ds.xs=[10,20,30,40,50];ds.interpX=25;ds.extrapX=55;ds.contextAns='decrease';ds.contextQ='Does the magnitude of the cooling rate increase or decrease as the liquid approaches room temperature?';ds.uncertainty=2;ds.tolerance=3;}
 if(currentDatasetKey==='spring'){const slope=rand(1.5,2.4);ds.yMax=40;ds.idealFn=x=>slope*x;ds.xs=[2,4,6,8,10];ds.interpX=7;ds.extrapX=13;ds.contextAns=GraphMath.springConstant(slope);ds.contextQ='Calculate the spring constant in N/m. Convert extension from cm to m before using k = F / extension.';ds.uncertainty=.2;ds.tolerance=.6;}
 if(currentDatasetKey==='filament'){const coefficient=rand(1.1,1.4);ds.idealFn=x=>coefficient*Math.sqrt(x);ds.xs=[2,4,6,8,10];ds.interpX=5;ds.extrapX=15;ds.contextAns='increase';ds.contextQ='Does the resistance increase or decrease as voltage increases?';ds.uncertainty=.1;ds.tolerance=.25;}
 if(currentDatasetKey==='enzyme'){const optimum=Math.floor(rand(6,8));ds.yLabel='Rate of reaction (a.u.)';ds.vars[1]=ds.yLabel;ds.idealFn=x=>100*Math.exp(-.1*(x-optimum)**2);ds.xs=[3,5,7,9,11];ds.interpX=6;ds.extrapX=13;ds.contextAns=optimum;ds.contextQ='What is the optimum pH?';ds.uncertainty=3;ds.tolerance=6;}
 if(currentDatasetKey.startsWith('bank:')){
   const model=RevisionGraphBank.build(currentDatasetKey.slice(5),crypto.getRandomValues(new Uint32Array(1))[0]);
   const width=model.xMax-model.xMin;
   Object.assign(ds,{xMin:model.xMin,xMax:model.xMax,yMin:model.yMin,yMax:model.yMax,xLabel:model.context.x,yLabel:model.context.y,vars:[model.context.x,model.context.y,'Controlled variable','Repeated measurement'],desc:model.context.title+'. '+model.context.interpretation,idealFn:model.fn,xs:[.15,.3,.45,.6,.75].map(f=>Number((model.xMin+width*f).toPrecision(4))),interpX:Number((model.xMin+width*.525).toPrecision(4)),extrapX:Number((model.xMin+width*.9).toPrecision(4)),uncertainty:(model.yMax-model.yMin)*.005,tolerance:(model.yMax-model.yMin)*.03});
   const left=ds.xs[0],right=ds.xs[4];ds.contextAns=(ds.idealFn(right)-ds.idealFn(left))/(right-left);ds.contextQ='Calculate the mean gradient of the model between x = '+left+' and x = '+right+'. Use change in y / change in x.';
 }
 const anomalyIndex=1+Math.floor(Math.random()*3);
 activeData=ds.xs.map((x,i)=>{const base=ds.idealFn(x),offset=i===anomalyIndex?ds.tolerance*4*(base+ds.tolerance*4>ds.yMax?-1:1):rand(-.3,.3)*ds.uncertainty;return{x,y:currentDatasetKey.startsWith('bank:')?Number((base+offset).toPrecision(4)):Math.round((base+offset)*10)/10,found:false,anomaly:i===anomalyIndex};});
 ds.interpY=ds.idealFn(ds.interpX);ds.extrapY=ds.idealFn(ds.extrapX);ds.interpQ=`Read ${ds.yLabel} at ${ds.xLabel} = ${ds.interpX}.`;ds.extrapQ=`Estimate ${ds.yLabel} at ${ds.xLabel} = ${ds.extrapX}. This is outside the measured range, so the prediction is less reliable.`;
 variablesConfirmed=false;anomalyIdentified=false;fitPoints=[];userLine={start:null,end:null};showIdealLine=false;missedClicks=[];currentPlotTool='plot';
 $('step-2-container').classList.add('opacity-50');$('step-2-container').classList.remove('pointer-events-none');
 for(const id of ['var-x-select','var-y-select']){$(id).innerHTML='<option value="">Select a variable</option>'+ds.vars.map(v=>`<option>${v}</option>`).join('');}
 $('scenario-desc').textContent=ds.desc+' Results include one anomalous reading.';$('th-x').textContent=ds.xLabel;$('th-y').textContent=ds.yLabel;
 for(const id of ['var-feedback','plotting-feedback','anomaly-step','lobf-step','interp-step','extrap-step','context-step','tool-anomaly'])$(id).classList.add('hidden');
 for(const id of ['interp-input','extrap-input','context-input','coordinate-x','coordinate-y'])if($(id))$(id).value='';
 $('tool-line').disabled=true;plottingGrid=new GraphGrid(plottingCanvas,ds.xMin,ds.xMax,ds.yMin,ds.yMax,ds.xLabel,ds.yLabel);updatePlotTable();setPlotTool('plot');
 if($('error-note'))$('error-note').textContent=`Error bars show an illustrative measurement uncertainty of ±${ds.uncertainty} in the y-axis units. They do not prove a reading is anomalous.`;
}
function checkVariables(){const ds=datasets[currentDatasetKey];variablesConfirmed=$('var-x-select').value===ds.xLabel&&$('var-y-select').value===ds.yLabel;$('step-2-container').classList.toggle('opacity-50',!variablesConfirmed);feedback('var-feedback',variablesConfirmed?'Correct. The variable you change goes on x; the variable you measure goes on y.':'Recheck the experiment: put the independent variable on x and the dependent variable on y.',variablesConfirmed);}
function setPlotTool(tool){currentPlotTool=tool;for(const name of ['plot','anomaly','line']){const b=$('tool-'+name);b.setAttribute('aria-pressed',String(tool===name));b.classList.toggle('ring-2',tool===name);b.classList.toggle('ring-blue-300',tool===name);}if($('coordinate-action'))$('coordinate-action').textContent=tool==='line'?'Add best-fit point':tool==='anomaly'?'Identify this point':'Plot coordinates';drawPlottingModule();}
function handlePlotClick(e){if(e.cancelable)e.preventDefault();const pos=getPointerPos(e,plottingCanvas);plotCoordinate(plottingGrid.unmapX(pos.x),plottingGrid.unmapY(pos.y));}
function plotCoordinate(x,y){
 if(!variablesConfirmed)return showMessage('Confirm the variables before plotting.',false);
 const ds=datasets[currentDatasetKey];if(!Number.isFinite(x)||!Number.isFinite(y)||x<ds.xMin||x>ds.xMax||y<ds.yMin||y>ds.yMax)return showMessage('Enter coordinates inside the graph axes.',false);
 if(currentPlotTool==='anomaly'){if(!activeData.every(p=>p.found))return showMessage('Plot every result first.',false);const pt=activeData.find(p=>p.anomaly&&Math.abs(p.x-x)<=.025*(ds.xMax-ds.xMin)&&Math.abs(p.y-y)<=.025*(ds.yMax-ds.yMin));if(pt){anomalyIdentified=true;$('tool-line').disabled=false;$('lobf-step').classList.remove('hidden');feedback('plotting-feedback','That reading is far from the trend. Repeat the measurement and check the method before deciding whether to exclude it.',true);setPlotTool('line');}else feedback('plotting-feedback','Look for the reading furthest from the overall pattern.',false);}
 else if(currentPlotTool==='line'){if(!anomalyIdentified)return showMessage('Identify the anomalous reading first.',false);if(fitPoints.some(p=>Math.abs(p.x-x)<.02))return showMessage('Choose a different x coordinate for the next fit point.',false);fitPoints.push({x,y});showIdealLine=false;showMessage(`${fitPoints.length} best-fit points added. Check the fit when it spans the reliable data.`);}
 else{const pt=activeData.find(p=>!p.found&&Math.abs(p.x-x)<=.018*(ds.xMax-ds.xMin)&&Math.abs(p.y-y)<=.018*(ds.yMax-ds.yMin));if(pt){pt.found=true;updatePlotTable();if(activeData.every(p=>p.found)){$('tool-anomaly').classList.remove('hidden');$('anomaly-step').classList.remove('hidden');showMessage('All results plotted. Now select Find anomaly.');}else showMessage(`Plotted (${pt.x}, ${pt.y}).`);}else{missedClicks=[{x,y}];feedback('plotting-feedback','The position does not match an unplotted result. Check both axes and their scales.',false);}}
 drawPlottingModule();
}
function checkBestFit(){const ds=datasets[currentDatasetKey];if(!anomalyIdentified)return showMessage('Plot the results and identify the anomaly first.',false);const reliable=activeData.filter(p=>!p.anomaly);const error=GraphMath.fitError(fitPoints,reliable);if(error<=ds.tolerance){showIdealLine=true;$('interp-step').classList.remove('hidden');$('interp-question').textContent=ds.interpQ;$('extrap-question').textContent=ds.extrapQ;feedback('plotting-feedback','Your fit follows the reliable results. Dashed blue shows a model for comparison. Read from the graph; a prediction beyond the data is less certain.',true);}else feedback('plotting-feedback','The fit must span all reliable results and follow their trend. For a curved trend, add several points; avoid forcing a straight line through it.',false);drawPlottingModule();}
function drawFunction(grid,fn,color='#2563eb',dashed=false){const ctx=grid.ctx;ctx.save();ctx.beginPath();ctx.rect(grid.padding,grid.padding,grid.canvas.width-2*grid.padding,grid.canvas.height-2*grid.padding);ctx.clip();ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=3;ctx.setLineDash(dashed?[6,5]:[]);let started=false;for(let i=0;i<=300;i++){const x=grid.xMin+(grid.xMax-grid.xMin)*i/300,y=fn(x);if(!Number.isFinite(y)||y<grid.yMin||y>grid.yMax){started=false;continue;}if(!started){ctx.moveTo(grid.mapX(x),grid.mapY(y));started=true;}else ctx.lineTo(grid.mapX(x),grid.mapY(y));}ctx.stroke();ctx.restore();}
function drawPlottingModule(){if(!plottingGrid)return;plottingGrid.draw();const ctx=plottingGrid.ctx,ds=datasets[currentDatasetKey];for(const p of activeData.filter(p=>p.found)){plottingGrid.drawCross(p.x,p.y,p.anomaly&&anomalyIdentified?'#d97706':'#15803d');if($('toggle-error-bars').checked){ctx.strokeStyle='#475569';ctx.lineWidth=1.5;const x=plottingGrid.mapX(p.x),y1=plottingGrid.mapY(p.y-ds.uncertainty),y2=plottingGrid.mapY(p.y+ds.uncertainty);ctx.beginPath();ctx.moveTo(x,y1);ctx.lineTo(x,y2);ctx.moveTo(x-5,y1);ctx.lineTo(x+5,y1);ctx.moveTo(x-5,y2);ctx.lineTo(x+5,y2);ctx.stroke();}if(p.anomaly&&anomalyIdentified){ctx.strokeStyle='#d97706';ctx.beginPath();ctx.arc(plottingGrid.mapX(p.x),plottingGrid.mapY(p.y),12,0,2*Math.PI);ctx.stroke();}}
 missedClicks.forEach(p=>plottingGrid.drawCross(p.x,p.y,'#dc2626'));
 if(fitPoints.length){const sorted=[...fitPoints].sort((a,b)=>a.x-b.x);ctx.strokeStyle='#7c3aed';ctx.lineWidth=2.5;ctx.beginPath();sorted.forEach((p,i)=>i?ctx.lineTo(plottingGrid.mapX(p.x),plottingGrid.mapY(p.y)):ctx.moveTo(plottingGrid.mapX(p.x),plottingGrid.mapY(p.y)));ctx.stroke();sorted.forEach(p=>plottingGrid.drawCross(p.x,p.y,'#7c3aed',4));}
 if(showIdealLine)drawFunction(plottingGrid,ds.idealFn,'#2563eb',true);
}
function checkInterpolation(){const ds=datasets[currentDatasetKey];if(!showIdealLine)return;const ok=GraphMath.close($('interp-input').value,ds.interpY,ds.tolerance);feedback('interp-feedback',ok?'Correct reading within the measured range.':`Read upwards from x = ${ds.interpX}, then across to the y-axis. Include a decimal where needed.`,ok);if(ok)$('extrap-step').classList.remove('hidden');}
function checkExtrapolation(){const ds=datasets[currentDatasetKey],ok=GraphMath.close($('extrap-input').value,ds.extrapY,ds.tolerance);feedback('extrap-feedback',ok?'Reasonable estimate. Beyond the measured range, the trend may change.':'Extend the overall trend, rather than joining to the anomalous result.',ok);if(ok){$('context-step').classList.remove('hidden');$('context-question').textContent=ds.contextQ;}}
function checkContext(){const ds=datasets[currentDatasetKey],value=$('context-input').value.trim().toLowerCase();const ok=typeof ds.contextAns==='string'?(ds.contextAns==='increase'?/^(?:increase|increases|increasing)$/.test(value):/^(?:decrease|decreases|decreasing)$/.test(value)):GraphMath.close(value,ds.contextAns,currentDatasetKey==='spring'?2:currentDatasetKey.startsWith('bank:')?Math.max(Math.abs(ds.contextAns)*.03,1e-10):.5);feedback('context-feedback',ok?'Correct. Plotting, fitting and reading skills practised.':currentDatasetKey==='spring'?'Use k = F / extension in metres. A gradient in cm/N must be converted before taking its reciprocal.':'Use the trend and the axis units to explain the result.',ok);if(ok)completeSkill('plotting');}
function updateModeButtons(ids,selected){for(const id of ids){const b=document.getElementById(id),active=id===selected;b.setAttribute('aria-pressed',String(active));b.classList.toggle('bg-white',active);b.classList.toggle('text-blue-600',active);}}
function setInterpretingMode(mode){updateModeButtons(['btn-learn-mode','btn-quiz-mode'],mode==='quiz'?'btn-quiz-mode':'btn-learn-mode');isQuizMode=mode==='quiz';quizSolved=false;document.querySelectorAll('input[name=relationship]').forEach(r=>r.disabled=false);document.querySelectorAll('.relation-desc').forEach(el=>el.classList.toggle('hidden',isQuizMode));$('interpreting-title').textContent=isQuizMode?'Which relationship is shown?':'Select a relationship';$('btn-next-quiz').classList.toggle('hidden',!isQuizMode);$('interpreting-takeaway-box').classList.toggle('hidden',isQuizMode);$('quiz-feedback').classList.add('hidden');if(isQuizMode)nextQuizQuestion();else{document.querySelector('input[name="relationship"]').checked=true;updateInterpreting();}}
function nextQuizQuestion(){const keys=Object.keys(relationships);currentQuizAnswer=keys[Math.floor(Math.random()*keys.length)];quizSolved=false;document.querySelectorAll('input[name="relationship"]').forEach(r=>{r.checked=false;r.disabled=false;});$('quiz-feedback').classList.add('hidden');drawInterpretingModule(relationships[currentQuizAnswer].fn);}
function updateInterpreting(){const selected=document.querySelector('input[name="relationship"]:checked');if(!selected)return;if(isQuizMode){const ok=selected.value===currentQuizAnswer;feedback('quiz-feedback',ok?relationshipNotes[currentQuizAnswer]:'Look at the intercept, curvature and whether the graph approaches a limit.',ok);if(ok){quizSolved=true;completeSkill('interpreting');document.querySelectorAll('input[name="relationship"]').forEach(r=>r.disabled=true);}}else{$('interpreting-takeaway').textContent=relationshipNotes[selected.value];drawInterpretingModule(relationships[selected.value].fn);}}
function drawInterpretingModule(fn){if(!interpretingGrid)interpretingGrid=new GraphGrid(interpretingCanvas,0,100,0,200,'Variable x','Variable y');interpretingGrid.draw();const selected=document.querySelector('input[name="relationship"]:checked');drawFunction(interpretingGrid,fn||(isQuizMode?relationships[currentQuizAnswer].fn:relationships[selected?.value||'proportional'].fn),'#7c3aed');}
function setGradMode(mode){updateModeButtons(['btn-grad-linear','btn-grad-curve'],mode==='curve'?'btn-grad-curve':'btn-grad-linear');isCurveMode=mode==='curve';$('grad-step-1-desc').textContent=isCurveMode?'Select a point on the curve to draw its tangent, then choose two well-spaced points on that tangent.':'Select two well-spaced points on the line. You can click or use x coordinates below.';generateRandomGradientLine();}
function generateRandomGradientLine(){mLine=Math.round((.5+Math.random()*1.6)*10)/10*(Math.random()<.3?-1:1);cLine=mLine<0?110:Math.round(Math.random()*15);resetGradient();}
function resetGradient(){pt1=null;pt2=null;tanPt=null;hoverPt=null;$('grad-step-2').classList.add('opacity-50');$('grad-step-3').classList.add('opacity-50');$('grad-step-4').classList.add('hidden');$('grad-feedback').classList.add('hidden');$('grad-p1').textContent='(?, ?)';$('grad-p2').textContent='(?, ?)';$('calc-dx').textContent='?';$('calc-dy').textContent='?';$('grad-input').value='';$('grad-unit').value='';drawGradientModule();}
function gradientPoint(x){const y=isCurveMode?(tanPt?(.08*tanPt.x)*x+tanPt.y-.08*tanPt.x**2:.04*x*x):mLine*x+cLine;return{x,y};}
function handleGradInteraction(e){if(!gradGrid)return;const pos=getPointerPos(e,gradCanvas);hoverPt=gradientPoint(Math.max(0,Math.min(50,Math.round(gradGrid.unmapX(pos.x)/2)*2)));drawGradientModule();}
function handleGradClick(e){if(e.cancelable)e.preventDefault();handleGradInteraction(e);selectGradientPoint(hoverPt.x);}
function selectGradientPoint(x){if(!Number.isFinite(x)||x<0||x>50)return showMessage('Choose an x coordinate between 0 and 50 s.',false);const p=gradientPoint(x);if(p.y<0||p.y>120)return showMessage('Choose a point on the visible part of the line or tangent.',false);if(pt1&&pt2)return showMessage('Reset the triangle to choose new points.');if(isCurveMode&&!tanPt){tanPt=p;showMessage('Tangent drawn. Now choose two well-spaced points on it.');}else if(!pt1){pt1=p;$('grad-step-2').classList.remove('opacity-50');}else{if(Math.abs(x-pt1.x)<10)return showMessage('Use a larger triangle: separate the points by at least 10 s.',false);pt2=p;$('grad-step-3').classList.remove('opacity-50');$('calc-dy').textContent=`${pt2.y.toFixed(1)} − ${pt1.y.toFixed(1)} = ${(pt2.y-pt1.y).toFixed(1)}`;$('calc-dx').textContent=`${pt2.x} − ${pt1.x} = ${pt2.x-pt1.x}`;}if(pt1)$('grad-p1').textContent=`(${pt1.x}, ${pt1.y.toFixed(1)})`;if(pt2)$('grad-p2').textContent=`(${pt2.x}, ${pt2.y.toFixed(1)})`;drawGradientModule();}
function drawGradientModule(){if(!gradGrid)gradGrid=new GraphGrid(gradCanvas,0,50,0,120,'Time (s)','Velocity (m/s)');gradGrid.draw();drawFunction(gradGrid,isCurveMode?x=>.04*x*x:x=>mLine*x+cLine,'#173c59');if(tanPt)drawFunction(gradGrid,x=>.08*tanPt.x*x+tanPt.y-.08*tanPt.x**2,'#e11d48');if(hoverPt&&!pt2)gradGrid.drawCross(hoverPt.x,hoverPt.y,'#64748b',4);if(pt1)gradGrid.drawCross(pt1.x,pt1.y,'#2563eb');if(pt2){gradGrid.drawCross(pt2.x,pt2.y,'#7c3aed');const ctx=gradGrid.ctx;ctx.strokeStyle='#d97706';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(gradGrid.mapX(pt1.x),gradGrid.mapY(pt1.y));ctx.lineTo(gradGrid.mapX(pt2.x),gradGrid.mapY(pt1.y));ctx.lineTo(gradGrid.mapX(pt2.x),gradGrid.mapY(pt2.y));ctx.stroke();ctx.setLineDash([]);}}
function checkGradient(){if(!pt1||!pt2)return feedback('grad-feedback','Choose two well-spaced points first.',false);const actual=GraphMath.gradient(pt1,pt2),ok=GraphMath.close($('grad-input').value,actual,.1)&&$('grad-unit').value==='m/s²';feedback('grad-feedback',ok?'Correct. Velocity ÷ time gives acceleration in m/s².':`Δy = ${(pt2.y-pt1.y).toFixed(1)} m/s; Δx = ${pt2.x-pt1.x} s. Divide Δy by Δx, keeping the sign. Unit: m/s².`,ok);if(ok){completeSkill('gradient');if(!isCurveMode)$('grad-step-4').classList.remove('hidden');}}
function checkIntercept(){const ok=GraphMath.close($('intercept-input').value,cLine,.5);feedback('intercept-feedback',ok?'Correct. This is the velocity at t = 0 s.':'Read the velocity where the line crosses the y-axis at t = 0.',ok);}
function generateRandomAreaProblem(){aX=5+Math.floor(Math.random()*10);aY1=10+Math.floor(Math.random()*16);aY2=aY1+10+Math.floor(Math.random()*20);areaSolved=false;$('area-feedback').classList.add('hidden');$('area-context-step').classList.add('hidden');$('area-rect-input').value='';$('area-tri-input').value='';if($('area-data'))$('area-data').textContent=`Graph data: speed increases in a straight line from ${aY1} m/s at 0 s to ${aY2} m/s at ${aX} s.`;drawAreaModule();}
function checkAreaAnswer(){const rect=aX*aY1,tri=.5*aX*(aY2-aY1);areaSolved=GraphMath.close($('area-rect-input').value,rect,.01)&&GraphMath.close($('area-tri-input').value,tri,.01);feedback('area-feedback',areaSolved?`Correct. Rectangle ${rect} m + triangle ${tri} m = ${rect+tri} m travelled.`:`Rectangle = ${aX} × ${aY1} = ${rect} m. Triangle = ½ × ${aX} × (${aY2} − ${aY1}) = ${tri} m. Use the change in speed for the triangle height.`,areaSolved);if(areaSolved)$('area-context-step').classList.remove('hidden');}
function checkAreaContext(){const ok=areaSolved&&$('area-context-select').value==='distance';showMessage(ok?'Correct. Area under a speed–time graph is distance: (m/s) × s = m.':'Calculate the areas first, then use the axis units to identify the quantity.',ok);if(ok)completeSkill('area');}
function handleBarInteraction(e){const pos=getPointerPos(e,barCanvas),sw=(barCanvas.width-120)/11;if(e.type==='pointerdown'){for(let i=0;i<5;i++)if(pos.x>60+sw+i*2*sw&&pos.x<60+2*sw+i*2*sw){barDrag=i;barCanvas.setPointerCapture(e.pointerId);}}if(barDrag!==-1){if(e.cancelable)e.preventDefault();barVals[barDrag]=Math.max(0,Math.min(40,Math.round((barCanvas.height-60-pos.y)/(barCanvas.height-120)*40)));$('bar-value-'+barDrag).value=barVals[barDrag];barsSolved=false;drawBarChartModule();}if(e.type==='pointerup'||e.type==='pointercancel')barDrag=-1;}
function checkBarChart(){barsSolved=barVals.every((v,i)=>GraphMath.close(v,barTargs[i],1));showMessage(barsSolved?'The bar heights match the data. Gaps distinguish the categories.':'Check each height against the table. All bars use the same scale.',barsSolved);if(barsSolved)$('barchart-context-step').classList.remove('hidden');}
function checkBarContext(){const ok=barsSolved&&$('barchart-context-select').value==='gas';showMessage(ok?'Correct. Gas is the modal category because it has the highest percentage.':'Check the bar heights first, then identify the largest category.',ok);if(ok)completeSkill('barchart');}
const originalDrawBars=drawBarChartModule;
drawBarChartModule=function(){originalDrawBars();const ctx=barCanvas.getContext('2d');ctx.fillStyle='#475569';ctx.font='12px system-ui';ctx.textAlign='right';ctx.textBaseline='middle';for(let n=0;n<=40;n+=10)ctx.fillText(n,52,barCanvas.height-60-n/40*(barCanvas.height-120));};
function initTestModule(){testState={currentQ:0,score:0,questions:[generateTestQ1(),generateTestQ2(),generateTestQ3(),generateTestQ4(),generateTestQ5()],answers:[],answered:false};$('test-completion-screen').classList.add('hidden');$('btn-submit-test').classList.remove('hidden');$('test-input-container').classList.remove('hidden');$('next-test').hidden=true;renderTestQuestion();updateTestScore();}
const originalRenderTest=renderTestQuestion;
renderTestQuestion=function(){if(testState.currentQ>=testState.questions.length)return;originalRenderTest();$('test-feedback').classList.add('hidden');$('btn-submit-test').disabled=false;$('next-test').hidden=true;for(const input of $('test-input-container').querySelectorAll('input')){input.disabled=false;input.setAttribute('aria-label',input.type==='radio'?input.value:'Test numeric answer');if(input.type==='number')input.step='any';}};
function submitTestAnswer(){if(testState.answered||testState.currentQ>=testState.questions.length)return;const q=testState.questions[testState.currentQ],answer=q.type==='mcq'?document.querySelector('input[name="test-mcq"]:checked')?.value:$('test-num-input').value;const correct=GraphMath.gradeTest(testState,answer);if(correct===null)return feedback('test-feedback','Select an answer or enter a valid number before submitting.',false);$('btn-submit-test').disabled=true;$('test-input-container').querySelectorAll('input').forEach(i=>i.disabled=true);feedback('test-feedback',(correct?'Correct. ':'Review: ')+q.explanation,correct);$('next-test').hidden=false;$('next-test').textContent=testState.currentQ===4?'See results':'Next question';updateTestScore();}
function nextTest(){if(!testState.answered)return;testState.currentQ++;testState.answered=false;if(testState.currentQ<testState.questions.length)renderTestQuestion();else finishTest();}
function finishTest(){$('test-completion-screen').classList.remove('hidden');$('final-score-text').textContent=`${testState.score} / 5`;$('btn-submit-test').classList.add('hidden');$('test-input-container').classList.add('hidden');$('next-test').hidden=true;graphProgress.latestTest={score:testState.score,at:new Date().toISOString()};graphProgress.bestScore=Math.max(graphProgress.bestScore,testState.score);saveProgress();const review=$('test-review');review.replaceChildren();for(const a of testState.answers){const li=document.createElement('li'),heading=document.createElement('strong');heading.textContent=(a.correct?'✓ ':'Review · ')+a.question;li.append(heading,document.createTextNode(`Your answer: ${a.answer}. ${a.explanation}`));review.append(li);}}
const originalQ1=generateTestQ1;
generateTestQ1=function(){const q=originalQ1();q.explanation=`The independent variable is changed; the dependent variable is measured. Here the answer is ${q.correctAnswer}.`;return q;};
const originalQ2=generateTestQ2;
generateTestQ2=function(){const q=originalQ2();q.explanation=`This is ${q.correctAnswer.toLowerCase()}. Compare the intercept and the way the gradient changes.`;return q;};
function generateTestQ3(){const m=(1+Math.floor(Math.random()*5))/2*(Math.random()<.3?-1:1),c=m<0?110:10;return{type:'input',text:'Calculate the acceleration from this velocity–time graph (m/s²). Use the two marked points.',correctAnswer:m,tolerance:.05,unit:'m/s²',needsGraph:true,graphType:'gradient',m,c,explanation:`Gradient = (v₂ − v₁) / (t₂ − t₁) = ${m} m/s². A negative gradient means velocity decreases.`};}
function generateTestQ4(){const start=80+Math.floor(Math.random()*10),fn=x=>start*Math.exp(-.04*x),targetX=25,ans=fn(targetX);return{type:'input',text:`Estimate the temperature at ${targetX} min by interpolation. Give your answer in °C.`,correctAnswer:ans,tolerance:2,unit:'°C',needsGraph:true,graphType:'interp',fn,targetX,explanation:`Read from 25 min to the curve, then across to the temperature axis: approximately ${ans.toFixed(1)} °C. Readings within ±2 °C are accepted.`};}
function generateTestQ5(){const x=4+Math.floor(Math.random()*6),y1=10+Math.floor(Math.random()*10),y2=y1+10+Math.floor(Math.random()*15),area=x*(y1+y2)/2;return{type:'input',text:'Calculate the total distance travelled from the speed–time graph (m).',correctAnswer:area,unit:'m',tolerance:.01,needsGraph:true,graphType:'area',x,y1,y2,explanation:`Distance = rectangle + triangle = (${x} × ${y1}) + (½ × ${x} × ${y2-y1}) = ${area} m.`};}
const originalDrawTestGraph=drawTestGraph;
drawTestGraph=function(q){if(q.graphType==='area')return originalDrawTestGraph(q);if(!testGrid)testGrid=new GraphGrid(testCanvas,0,60,0,100,'Time (min)','Temperature (°C)');if(q.graphType==='relationship'){Object.assign(testGrid,{xMax:100,yMax:200,xLabel:'Variable x',yLabel:'Variable y'});testGrid.draw();drawFunction(testGrid,q.fn,'#7c3aed');return;}if(q.graphType==='gradient'){Object.assign(testGrid,{xMax:50,yMax:120,xLabel:'Time (s)',yLabel:'Velocity (m/s)'});testGrid.draw();drawFunction(testGrid,x=>q.m*x+q.c,'#15803d');testGrid.drawCross(10,q.m*10+q.c,'#173c59');testGrid.drawCross(40,q.m*40+q.c,'#173c59');return;}testGrid.xMax=60;testGrid.yMax=100;testGrid.xLabel='Time (min)';testGrid.yLabel='Temperature (°C)';testGrid.draw();drawFunction(testGrid,q.fn,'#b45309');for(let x=0;x<=60;x+=10)testGrid.drawCross(x,q.fn(x),'#b45309',5);const ctx=testGrid.ctx;ctx.strokeStyle='#64748b';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(testGrid.mapX(q.targetX),testGrid.mapY(0));ctx.lineTo(testGrid.mapX(q.targetX),testGrid.mapY(100));ctx.stroke();ctx.setLineDash([]);};
function resizeCanvases(){document.querySelectorAll('.canvas-container').forEach(container=>{if(container.closest('.module-section').classList.contains('hidden'))return;const canvas=container.querySelector('canvas');if(canvas){canvas.width=Math.round(container.clientWidth);canvas.height=Math.round(container.clientHeight);}});if(!$('module-plotting').classList.contains('hidden'))drawPlottingModule();if(!$('module-interpreting').classList.contains('hidden'))drawInterpretingModule();if(!$('module-gradient').classList.contains('hidden'))drawGradientModule();if(!$('module-area').classList.contains('hidden'))drawAreaModule();if(!$('module-barchart').classList.contains('hidden'))drawBarChartModule();if(!$('module-test').classList.contains('hidden')&&testState.currentQ<testState.questions.length){const q=testState.questions[testState.currentQ];if(q.needsGraph)drawTestGraph(q);}}
function exportActiveGraph(){const library=$('module-library');if(library&&!library.classList.contains('hidden')){const svg=$('library-graph').querySelector('svg');if(!svg)return;const exported=svg.cloneNode(true);exported.setAttribute('xmlns','http://www.w3.org/2000/svg');const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(exported)],{type:'image/svg+xml'})),a=document.createElement('a');a.href=url;a.download='revision-graph-library.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}const active=['plotting','interpreting','gradient','area','barchart','test'].find(id=>!$('module-'+id).classList.contains('hidden'));if(active==='test'&&!testState.questions[testState.currentQ]?.needsGraph)return showMessage('This question has no graph to export.',false);const canvas=$('canvas-'+active);canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`revision-graph-${active}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
window.onload=function(){
 const nav=document.querySelector('.graph-workspace>nav');const savedModule=graphProgress.lastModule;const progress=document.createElement('div');progress.id='graph-progress';progress.className='graph-progress';nav.insertBefore(progress,nav.lastElementChild);
 const plottingForm=document.createElement('form');plottingForm.className='coordinate-entry';plottingForm.innerHTML='<strong>Keyboard plotting / best fit</strong><div class="fields"><label>X coordinate<input id="coordinate-x" type="number" step="any" required></label><label>Y coordinate<input id="coordinate-y" type="number" step="any" required></label></div><button id="coordinate-action">Plot coordinates</button>';
 plottingForm.addEventListener('submit',e=>{e.preventDefault();plotCoordinate(GraphMath.numeric($('coordinate-x').value),GraphMath.numeric($('coordinate-y').value));});$('step-2-container').append(plottingForm);
 const fitControls=document.createElement('div');fitControls.className='coordinate-entry';fitControls.innerHTML='<p>Add endpoints for a straight fit, or several points along a curved trend. Span the reliable results; the anomalous reading should not pull the fit away from them.</p><button type="button" id="check-fit">Check best fit</button> <button type="button" id="undo-fit">Undo fit point</button><p id="error-note" class="graph-note"></p>';$('lobf-step').append(fitControls);$('check-fit').onclick=checkBestFit;$('undo-fit').onclick=()=>{fitPoints.pop();showIdealLine=false;drawPlottingModule();};
 const gradForm=document.createElement('form');gradForm.className='coordinate-entry';gradForm.innerHTML='<label>Choose x on the line / tangent (s)<input id="gradient-x" type="number" min="0" max="50" step="any" required></label><button>Select point</button>';gradForm.onsubmit=e=>{e.preventDefault();selectGradientPoint(GraphMath.numeric($('gradient-x').value));};$('grad-step-1').append(gradForm);
 const areaData=document.createElement('p');areaData.id='area-data';areaData.className='graph-note';$('module-area').querySelector('h3').after(areaData);
 const bars=document.createElement('div');bars.className='coordinate-entry';bars.innerHTML='<strong>Enter heights or drag the bars</strong>'+['Coal','Wind','Solar','Nuclear','Gas'].map((name,i)=>`<label class="bar-entry">${name} (%)<input id="bar-value-${i}" type="number" min="0" max="40" step="1" value="0"></label>`).join('');$('module-barchart').querySelector('.bg-white').append(bars);bars.addEventListener('input',e=>{const i=Number(e.target.id.replace('bar-value-',''));const value=GraphMath.numeric(e.target.value);if(Number.isInteger(i)&&i>=0&&i<5&&Number.isFinite(value)){barVals[i]=Math.max(0,Math.min(40,value));barsSolved=false;drawBarChartModule();}});
 const next=document.createElement('button');next.id='next-test';next.type='button';next.className='mt-4 w-full bg-indigo-600 text-white font-bold py-3 px-4 rounded-lg';next.hidden=true;next.onclick=nextTest;$('btn-submit-test').after(next);
 const review=document.createElement('ol');review.id='test-review';review.className='test-review';$('test-completion-screen').append(review);
 for(const canvas of document.querySelectorAll('canvas')){canvas.setAttribute('role','img');canvas.setAttribute('aria-label',({plotting:'Plotting grid. Results are listed in the adjacent table; use the coordinate fields to plot without a pointer.',interpreting:'Relationship graph. Explore the named relationships and read the explanation in Learn mode.',gradient:'Velocity–time graph. Select x coordinates using the keyboard form; point values and changes are shown beside it.',area:'Speed–time graph shaded as a rectangle and a triangle.',barchart:'Energy source bar chart. Use the labelled height fields to build each bar.',test:'Graph for the current test question.'})[canvas.id.replace('canvas-','')]);}
 for(const [id,label] of Object.entries({'dataset-selector':'Experiment','var-x-select':'X-axis independent variable','var-y-select':'Y-axis dependent variable','interp-input':'Interpolation answer','extrap-input':'Extrapolation answer','context-input':'Science explanation answer','grad-input':'Gradient value','grad-unit':'Gradient unit','intercept-input':'Y-intercept','area-rect-input':'Rectangle area in metres','area-tri-input':'Triangle area in metres','area-context-select':'Quantity represented by area','barchart-context-select':'Modal energy category'}))$(id)?.setAttribute('aria-label',label);
 for(const input of document.querySelectorAll('input[type="number"]'))input.step='any';
 plottingCanvas.addEventListener('pointerdown',handlePlotClick);gradCanvas.addEventListener('pointerdown',handleGradClick);gradCanvas.addEventListener('pointermove',handleGradInteraction);
 for(const type of ['pointerdown','pointermove','pointerup','pointercancel'])barCanvas.addEventListener(type,handleBarInteraction);
 window.addEventListener('resize',resizeCanvases);changeDataset();generateRandomGradientLine();generateRandomAreaProblem();drawBarChartModule();initTestModule();switchTab(savedModule);updateProgress();
};
