// Generated from the bundled course data by scripts/catalog.cjs.
window.REVISION_CATALOG = {
  "courses": [
    {
      "id": "gcse-biology",
      "level": "gcse",
      "subject": "biology",
      "title": "GCSE Biology",
      "spec": "AQA GCSE Biology 8461",
      "summary": "Combined and Separate Science. Lessons, practicals and exam practice.",
      "progressKey": "gcse-science-progress-v1",
      "href": "courses/gcse/index.html?subject=biology"
    },
    {
      "id": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "title": "GCSE Chemistry",
      "spec": "AQA GCSE Chemistry 8462",
      "summary": "Combined and Separate Science. Lessons, practicals and exam practice.",
      "progressKey": "gcse-science-progress-v1",
      "href": "courses/gcse/index.html?subject=chemistry"
    },
    {
      "id": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "title": "GCSE Physics",
      "spec": "AQA GCSE Physics 8463",
      "summary": "Combined and Separate Science. Lessons, practicals and exam practice.",
      "progressKey": "gcse-science-progress-v1",
      "href": "courses/gcse/index.html?subject=physics"
    },
    {
      "id": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "title": "A-level Physics",
      "spec": "AQA 7408",
      "summary": "Core topics, Paper 3 options and required practicals.",
      "progressKey": "alevel-course-progress-v1",
      "href": "courses/alevel/index.html?subject=physics"
    },
    {
      "id": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "title": "A-level Biology",
      "spec": "AQA 7402",
      "summary": "From biological molecules to ecosystems and gene expression.",
      "progressKey": "alevel-biology-progress-v1",
      "href": "courses/alevel/index.html?subject=biology"
    },
    {
      "id": "alevel-chemistry",
      "level": "alevel",
      "subject": "chemistry",
      "title": "A-level Chemistry",
      "spec": "AQA 7405",
      "summary": "Physical, inorganic and organic chemistry, step by step.",
      "progressKey": "alevel-chemistry-progress-v1",
      "href": "courses/alevel/index.html?subject=chemistry"
    },
    {
      "id": "gcse-maths",
      "level": "gcse",
      "subject": "maths",
      "title": "GCSE Mathematics",
      "spec": "AQA GCSE Mathematics 8300",
      "summary": "Number, algebra, ratio, geometry, probability and statistics. Textbook chapters, worked examples and practice.",
      "progressKey": "subject-course-progress:maths",
      "href": "courses/subjects/index.html?subject=maths"
    },
    {
      "id": "gcse-geography",
      "level": "gcse",
      "subject": "geography",
      "title": "GCSE Geography",
      "spec": "AQA GCSE Geography 8035",
      "summary": "Physical and human geography, geographical skills, case studies and fieldwork.",
      "progressKey": "subject-course-progress:geography",
      "href": "courses/subjects/index.html?subject=geography"
    }
  ],
  "topics": [
    {
      "id": "b1",
      "course": "gcse-biology",
      "level": "gcse",
      "subject": "biology",
      "code": "B1",
      "title": "Cell biology",
      "summary": "AQA GCSE Biology 4.1: Cell structure; Cell division; Transport in cells.",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 22,
      "combinedLessonCount": 19,
      "search": "Eukaryotic and prokaryotic cells Animal cell structures and functions Plant cell structures and functions Specialised animal cells Specialised plant cells Cell differentiation Light and electron microscopy Magnification, image size and real size Required practical: microscopy Culturing microorganisms and aseptic technique Bacterial growth calculations and colony areas Required practical: antibiotics and antiseptics Chromosomes, DNA and genes The cell cycle Mitosis, growth and repair Stem cells and differentiation Stem-cell treatments, risks and ethics Diffusion and concentration gradients Surface area to volume ratio and exchange surfaces Osmosis Required practical: osmosis in plant tissue Active transport",
      "href": "courses/gcse/index.html?subject=biology&topic=b1"
    },
    {
      "id": "b2",
      "course": "gcse-biology",
      "level": "gcse",
      "subject": "biology",
      "code": "B2",
      "title": "Organisation",
      "summary": "AQA GCSE Biology 4.2: Principles of organisation; Animal tissues, organs and organ systems; Plant tissues, organs and systems.",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 24,
      "combinedLessonCount": 24,
      "search": "Cells, tissues, organs and organ systems The human digestive system Enzymes and active sites Temperature, pH and enzyme activity Carbohydrases, proteases and lipases Bile and fat digestion Required practical: food tests Required practical: pH and amylase Heart structure and double circulation Lungs and gas exchange Arteries, veins and capillaries Pacemakers and heart-rate control Blood components and their functions Coronary heart disease Stents, statins, valves and transplants Health, disease and interactions Risk factors, correlation and causation Lifestyle and cardiovascular disease Obesity, diabetes, alcohol and smoking risks Cancer: benign and malignant tumours Plant tissues and leaf structure Xylem and water transport Phloem and translocation Transpiration and stomata",
      "href": "courses/gcse/index.html?subject=biology&topic=b2"
    },
    {
      "id": "b3",
      "course": "gcse-biology",
      "level": "gcse",
      "subject": "biology",
      "code": "B3",
      "title": "Infection and response",
      "summary": "AQA GCSE Biology 4.3: Communicable diseases; Monoclonal antibodies (Biology only, HT); Plant disease (Biology only).",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 16,
      "combinedLessonCount": 11,
      "search": "Pathogens, infection and transmission Viral diseases: measles, HIV and TMV Bacterial diseases: Salmonella and gonorrhoea Fungal disease: rose black spot Protist disease: malaria Non-specific human defence systems White blood cells, phagocytosis and antibodies Vaccination and population protection Antibiotics and painkillers Drug discovery and sources Preclinical testing, clinical trials and peer review Producing monoclonal antibodies Uses of monoclonal antibodies Plant diseases, pests and mineral deficiencies Detecting and identifying plant disease Plant physical, chemical and mechanical defences",
      "href": "courses/gcse/index.html?subject=biology&topic=b3"
    },
    {
      "id": "b4",
      "course": "gcse-biology",
      "level": "gcse",
      "subject": "biology",
      "code": "B4",
      "title": "Bioenergetics",
      "summary": "AQA GCSE Biology 4.4: Photosynthesis; Respiration.",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 11,
      "combinedLessonCount": 11,
      "search": "Photosynthetic reaction and equation Light intensity and photosynthesis rate Carbon dioxide, temperature and chlorophyll as limiting factors Inverse square law and photosynthesis Required practical: photosynthesis rate Uses of glucose in plants Aerobic respiration Anaerobic respiration in animals Anaerobic respiration in plants and yeast Exercise, oxygen debt and recovery Metabolism and synthesis of molecules",
      "href": "courses/gcse/index.html?subject=biology&topic=b4"
    },
    {
      "id": "b5",
      "course": "gcse-biology",
      "level": "gcse",
      "subject": "biology",
      "code": "B5",
      "title": "Homeostasis and response",
      "summary": "AQA GCSE Biology 4.5: Homeostasis; The human nervous system; Hormonal coordination in humans; Plant hormones (Biology only).",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 30,
      "combinedLessonCount": 15,
      "search": "Homeostasis and control systems Negative feedback as a control principle Nervous system organisation Reflex arcs and synapses Required practical: reaction time The brain: regions and functions Investigating the brain Eye structure and function Accommodation Myopia, hyperopia and correction Thermoregulation The endocrine system Insulin and blood glucose Type 1 and Type 2 diabetes Glucagon and negative feedback Water balance, osmosis and excretion Kidney filtration and selective reabsorption Deamination and urea formation ADH and water balance Kidney failure, dialysis and transplant Reproductive hormones and puberty FSH, LH, oestrogen and progesterone Hormonal and non-hormonal contraception Fertility treatment and IVF Adrenaline and fight-or-flight Thyroxine and negative feedback Auxin and plant tropisms Gibberellins and ethene Required practical: plant responses Uses of plant hormones",
      "href": "courses/gcse/index.html?subject=biology&topic=b5"
    },
    {
      "id": "b6",
      "course": "gcse-biology",
      "level": "gcse",
      "subject": "biology",
      "code": "B6",
      "title": "Inheritance, variation and evolution",
      "summary": "AQA GCSE Biology 4.6: Reproduction; Variation and evolution; Development of understanding of genetics and evolution; Classification of living organisms.",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 28,
      "combinedLessonCount": 21,
      "search": "Sexual reproduction Asexual reproduction and clones Meiosis and gamete formation Sexual versus asexual reproduction DNA, genes, chromosomes and the genome DNA structure and nucleotides Protein synthesis: transcription and translation Gene expression and mutations Genetic inheritance vocabulary Monohybrid genetic crosses and probabilities Inherited disorders and embryo screening Sex determination Genetic and environmental variation Mutations and new variants Evolution by natural selection Formation of new species Selective breeding Genetic engineering principles Genetic engineering process Darwin and natural selection Speciation Mendel and the development of genetics Evidence for evolution Fossil formation and the fossil record Extinction Antibiotic-resistant bacteria Linnaean classification and binomial naming Three-domain system and modern classification",
      "href": "courses/gcse/index.html?subject=biology&topic=b6"
    },
    {
      "id": "b7",
      "course": "gcse-biology",
      "level": "gcse",
      "subject": "biology",
      "code": "B7",
      "title": "Ecology",
      "summary": "AQA GCSE Biology 4.7: Adaptations, interdependence and competition; Organisation of an ecosystem; Biodiversity and human interaction; Trophic levels in an ecosystem (Biology only); Food production (Biology only).",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 32,
      "combinedLessonCount": 19,
      "search": "Communities, ecosystems and interdependence Competition in plants and animals Stable communities Abiotic factors Biotic factors Structural, behavioural and functional adaptations Extremophiles Food chains, producers and consumers Predator-prey cycles Quadrats, transects and ecological sampling Required practical: field sampling The carbon cycle The water cycle and material recycling Factors affecting decomposition Composting and biogas Required practical: temperature and decay Environmental change and species distribution Biodiversity and ecosystem stability Waste management and pollution Land use and peat bogs Deforestation Global warming: biological consequences Maintaining biodiversity Trophic levels and decomposers Pyramids of biomass Biomass losses between trophic levels Efficiency of biomass transfer Food security Intensive farming and energy transfer Sustainable fisheries Mycoprotein production Biotechnology, insulin and GM crops",
      "href": "courses/gcse/index.html?subject=biology&topic=b7"
    },
    {
      "id": "c1",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C1",
      "title": "Atomic structure and the periodic table",
      "summary": "AQA GCSE Chemistry 4.1: A simple model of the atom, symbols, relative atomic mass, electronic charge and isotopes; The periodic table; Properties of transition metals (Chemistry only).",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 19,
      "combinedLessonCount": 17,
      "search": "Atoms, elements and compounds Writing formulae and balancing equations Mixtures and physical separation Development of the atomic model Subatomic particles and relative charge Atomic size, nuclear size and mass Isotopes Relative atomic mass from isotope abundance Electronic structure of the first 20 elements Modern periodic table and electronic structure Development of the periodic table and Mendeleev Metals and non-metals in the periodic table Group 0 noble gases Group 1 alkali metals: reactions Group 1 reactivity trend Group 7 halogens: properties and compounds Group 7 displacement reactions Transition metals compared with Group 1 Transition-metal ions, coloured compounds and catalysts",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c1"
    },
    {
      "id": "c2",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C2",
      "title": "Bonding, structure and properties of matter",
      "summary": "AQA GCSE Chemistry 4.2: Chemical bonds, ionic, covalent and metallic; How bonding and structure are related to properties; Structure and bonding of carbon; Bulk and surface properties including nanoparticles (Chemistry only).",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 22,
      "combinedLessonCount": 20,
      "search": "Comparing ionic, covalent and metallic bonding Formation of ions and ionic bonding Dot-and-cross diagrams for ionic compounds Giant ionic lattices and empirical formulae Covalent bonding and shared electron pairs Representing molecules and giant covalent structures Metallic bonding and delocalised electrons Particle model and the three states of matter State symbols in chemical equations Properties of ionic compounds Properties of small molecular substances Molecular size and intermolecular forces Polymers: structure and properties Giant covalent structures Properties of metals and alloys Metals as electrical and thermal conductors Diamond structure and properties Graphite structure and properties Graphene Fullerenes and carbon nanotubes Nanoparticles and surface-area-to-volume ratio Uses, benefits and risks of nanoparticles",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c2"
    },
    {
      "id": "c3",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C3",
      "title": "Quantitative chemistry",
      "summary": "AQA GCSE Chemistry 4.3: Chemical measurements, conservation of mass and quantitative equations; Amount of substance and masses of pure substances; Yield and atom economy (Chemistry only); Concentrations in mol/dm3 (Chemistry only, HT); Amount of substance and gas volumes (Chemistry only, HT).",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 16,
      "combinedLessonCount": 10,
      "search": "Conservation of mass and balanced equations Relative formula mass and percentage by mass Mass changes involving gases Measurement uncertainty and range The mole and Avogadro constant Mole calculations from mass Reacting masses from balanced equations Using moles to balance equations Limiting reactants Concentration in g per dm3 Percentage yield Atom economy Yield versus atom economy Concentration in mol per dm3 Titration calculations using moles Gas volumes at room temperature and pressure",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c3"
    },
    {
      "id": "c4",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C4",
      "title": "Chemical changes",
      "summary": "AQA GCSE Chemistry 4.4: Reactivity of metals; Reactions of acids; Electrolysis.",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 19,
      "combinedLessonCount": 17,
      "search": "Metal oxides, oxidation and reduction The reactivity series Metal displacement reactions Extraction of metals and reduction with carbon Redox in terms of electrons Acids reacting with metals Neutralisation and salt formation Acids with carbonates Making soluble salts from insoluble bases pH scale and indicators Hydrogen ions, hydroxide ions and neutralisation Titration technique Strong and weak acids Electrolytes and the process of electrolysis Half equations in electrolysis Electrolysis of molten ionic compounds Electrolysis for extracting reactive metals Electrolysis of aqueous solutions Required practical: electrolysis of aqueous solutions",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c4"
    },
    {
      "id": "c5",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C5",
      "title": "Energy changes",
      "summary": "AQA GCSE Chemistry 4.5: Exothermic and endothermic reactions; Chemical cells and fuel cells (Chemistry only).",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 9,
      "combinedLessonCount": 5,
      "search": "Exothermic and endothermic energy transfers Required practical: temperature changes in reactions Reaction profiles and activation energy Bond breaking and bond making Bond-energy calculations Simple chemical cells and voltage Batteries and rechargeable cells Hydrogen fuel cells Fuel-cell half equations",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c5"
    },
    {
      "id": "c6",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C6",
      "title": "Rate and extent of chemical change",
      "summary": "AQA GCSE Chemistry 4.6: Rate of reaction; Reversible reactions and dynamic equilibrium.",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 16,
      "combinedLessonCount": 16,
      "search": "Calculating rates of reaction Instantaneous rate and tangents Effect of concentration on rate Required practical: concentration and reaction rate Effect of pressure on gas reaction rate Effect of surface area on rate Effect of temperature on rate Collision theory and activation energy Catalysts and activation energy Reversible reactions Energy changes in reversible reactions Dynamic equilibrium in closed systems Le Chatelier principle Concentration and equilibrium Temperature and equilibrium Pressure and equilibrium",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c6"
    },
    {
      "id": "c7",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C7",
      "title": "Organic chemistry",
      "summary": "AQA GCSE Chemistry 4.7: Carbon compounds as fuels and feedstock; Reactions of alkenes and alcohols (Chemistry only); Synthetic and naturally occurring polymers (Chemistry only).",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 18,
      "combinedLessonCount": 8,
      "search": "Crude oil as a mixture of hydrocarbons First four alkanes and formulae Fractional distillation of crude oil Petrochemicals and modern materials Hydrocarbon size and boiling point Combustion of hydrocarbons Cracking hydrocarbons Alkenes and the bromine-water test Structure and formulae of alkenes Addition reactions of alkenes Alcohols: functional group and homologous series Reactions and uses of alcohols Carboxylic acids and functional group Reactions of carboxylic acids and esterification Addition polymerisation Condensation polymerisation Amino acids and polypeptides DNA and naturally occurring polymers",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c7"
    },
    {
      "id": "c8",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C8",
      "title": "Chemical analysis",
      "summary": "AQA GCSE Chemistry 4.8: Purity, formulations and chromatography; Identification of common gases; Identification of ions by chemical and spectroscopic means (Chemistry only).",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 17,
      "combinedLessonCount": 9,
      "search": "Pure substances and melting/boiling points Formulations Chromatography: stationary and mobile phases Rf calculations and chromatogram interpretation Required practical: paper chromatography Test for hydrogen Test for oxygen Test for carbon dioxide Test for chlorine Flame tests for metal ions Metal hydroxide precipitate tests Test for carbonate ions Test for halide ions Test for sulfate ions Required practical: identifying ions in unknown compounds Instrumental methods in chemical analysis Flame emission spectroscopy",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c8"
    },
    {
      "id": "c9",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C9",
      "title": "Chemistry of the atmosphere",
      "summary": "AQA GCSE Chemistry 4.9: Composition and evolution of the atmosphere; Carbon dioxide and methane as greenhouse gases; Common atmospheric pollutants and their sources.",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 13,
      "combinedLessonCount": 13,
      "search": "Modern atmospheric composition Earth’s early atmosphere How oxygen increased How carbon dioxide decreased Greenhouse gases and the greenhouse effect Human activities increasing carbon dioxide Human activities increasing methane Evidence, peer review and climate models Potential effects of global climate change Carbon footprints and reduction strategies Products and pollutants from burning fuels Carbon monoxide and particulate pollution Sulfur dioxide, nitrogen oxides and acid rain",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c9"
    },
    {
      "id": "c10",
      "course": "gcse-chemistry",
      "level": "gcse",
      "subject": "chemistry",
      "code": "C10",
      "title": "Using resources",
      "summary": "AQA GCSE Chemistry 4.10: Using Earth’s resources and obtaining potable water; Life cycle assessment and recycling; Using materials (Chemistry only); Haber process and NPK fertilisers (Chemistry only).",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 17,
      "combinedLessonCount": 10,
      "search": "Natural, finite and renewable resources Sustainable development and chemistry Potable water versus pure water Producing potable water from freshwater and seawater Required practical: analysis and purification of water Waste-water treatment Phytomining and bioleaching Life cycle assessment stages Limitations and value judgements in LCAs Reduce, reuse and recycle Corrosion and rusting Preventing corrosion and sacrificial protection Alloys as useful materials Ceramics, polymers and composites Haber process raw materials and reaction Haber process conditions and compromise NPK fertilisers and nutrient ions",
      "href": "courses/gcse/index.html?subject=chemistry&topic=c10"
    },
    {
      "id": "p1",
      "course": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "code": "P1",
      "title": "Energy",
      "summary": "AQA GCSE Physics 4.1: Energy changes in a system; Conservation and dissipation of energy; National and global energy resources.",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 11,
      "combinedLessonCount": 10,
      "search": "Energy stores, systems and transfer pathways Kinetic energy calculations Gravitational potential energy Elastic potential energy and springs Specific heat capacity and thermal energy Power: rate of energy transfer Conservation of energy and dissipation Reducing unwanted energy transfers Required practical: thermal insulation Efficiency of energy transfers Renewable and non-renewable energy resources",
      "href": "courses/gcse/index.html?subject=physics&topic=p1"
    },
    {
      "id": "p2",
      "course": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "code": "P2",
      "title": "Electricity",
      "summary": "AQA GCSE Physics 4.2: Current, potential difference and resistance; Series and parallel circuits; Domestic uses and safety; Energy transfers; Static electricity (Physics only).",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 15,
      "combinedLessonCount": 13,
      "search": "Circuit symbols and drawing circuits Charge, current and time Potential difference, current and resistance Required practical: resistance of wires and resistor combinations Ohmic conductors, filament lamps, diodes, thermistors and LDRs Required practical: I-V characteristics Series circuits Parallel and mixed circuits Direct and alternating potential difference Mains wiring and electrical safety Electrical power Electrical energy transferred by appliances The National Grid Static charge and transfer of electrons Electric fields and electrostatic forces",
      "href": "courses/gcse/index.html?subject=physics&topic=p2"
    },
    {
      "id": "p3",
      "course": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "code": "P3",
      "title": "Particle model of matter",
      "summary": "AQA GCSE Physics 4.3: Changes of state and the particle model; Internal energy and energy transfers; Particle model and pressure.",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 8,
      "combinedLessonCount": 6,
      "search": "Density and the particle model Changes of state and conservation of mass Internal energy of a system Specific heat capacity and heating curves Specific latent heat and state changes Particle motion, temperature and gas pressure Pressure and volume of a gas Doing work on a gas",
      "href": "courses/gcse/index.html?subject=physics&topic=p3"
    },
    {
      "id": "p4",
      "course": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "code": "P4",
      "title": "Atomic structure",
      "summary": "AQA GCSE Physics 4.4: Atoms and isotopes; Atoms and nuclear radiation; Hazards, uses and background radiation (Physics only); Nuclear fission and fusion (Physics only).",
      "scope": "combined",
      "paper": 1,
      "lessonCount": 13,
      "combinedLessonCount": 8,
      "search": "Structure and scale of the atom Atomic number, mass number and isotopes Development of the atomic model Radioactive decay, activity and count rate Alpha, beta and gamma: penetration and ionisation Nuclear equations Half-life and random radioactive decay Irradiation, contamination and radiation risk Background radiation and radiation dose Half-life, activity and long-term hazard Medical uses of nuclear radiation Nuclear fission and chain reactions Nuclear fusion",
      "href": "courses/gcse/index.html?subject=physics&topic=p4"
    },
    {
      "id": "p5",
      "course": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "code": "P5",
      "title": "Forces",
      "summary": "AQA GCSE Physics 4.5: Forces and their interactions; Work done and energy transfer; Forces and elasticity; Moments, levers and gears (Physics only); Pressure in fluids (Physics only); Forces and motion; Momentum (Higher Tier).",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 28,
      "combinedLessonCount": 23,
      "search": "Scalar and vector quantities Contact and non-contact forces Gravity, mass and weight Resultant forces and free-body diagrams Work done by forces Elastic and inelastic deformation Hooke's law and spring constant Required practical: force and extension Moments and balanced turning effects Pressure on surfaces and in fluids Liquid pressure with depth and upthrust Atmospheric pressure Distance and displacement Speed and average speed Velocity and changing direction Distance-time graphs Acceleration and velocity-time graphs Newton's First Law Newton's Second Law and inertial mass Required practical: force, mass and acceleration Newton's Third Law Stopping distance, thinking distance and braking distance Reaction time and thinking distance Factors affecting braking distance Braking forces, kinetic energy and deceleration Momentum of moving objects Conservation of momentum Force and change of momentum",
      "href": "courses/gcse/index.html?subject=physics&topic=p5"
    },
    {
      "id": "p6",
      "course": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "code": "P6",
      "title": "Waves",
      "summary": "AQA GCSE Physics 4.6: Waves in air, fluids and solids; Electromagnetic waves; Black body radiation (Physics only).",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 17,
      "combinedLessonCount": 9,
      "search": "Transverse and longitudinal waves Wave properties: amplitude, wavelength, frequency and period Measuring wave speed and using the wave equation Required practical: wave speed, frequency and wavelength Reflection, transmission and absorption of waves Required practical: reflection and refraction of light Sound waves, the ear and hearing range Ultrasound, seismic waves and echo sounding The electromagnetic spectrum Reflection, refraction, absorption and transmission of EM waves Required practical: infrared emission and absorption Generation, absorption and hazards of EM radiation Uses of electromagnetic waves Lenses and image formation Visible light, colour, filters and surfaces Emission and absorption of infrared radiation Radiation balance and Earth temperature",
      "href": "courses/gcse/index.html?subject=physics&topic=p6"
    },
    {
      "id": "p7",
      "course": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "code": "P7",
      "title": "Magnetism and electromagnetism",
      "summary": "AQA GCSE Physics 4.7: Permanent and induced magnetism, magnetic forces and fields; The motor effect; Induced potential, transformers and the National Grid (Physics only, HT).",
      "scope": "combined",
      "paper": 2,
      "lessonCount": 12,
      "combinedLessonCount": 6,
      "search": "Permanent magnets, induced magnets and poles Magnetic fields and field-line patterns Magnetic fields around currents and solenoids The motor effect and Fleming's left-hand rule Motor-effect force calculations Electric motors Loudspeakers and headphones Generator effect and induced potential Alternators and dynamos Microphones and the generator effect Transformers and turns ratio Transformer power and efficient transmission",
      "href": "courses/gcse/index.html?subject=physics&topic=p7"
    },
    {
      "id": "p8",
      "course": "gcse-physics",
      "level": "gcse",
      "subject": "physics",
      "code": "P8",
      "title": "Space physics",
      "summary": "AQA GCSE Physics 4.8: Solar system, orbital motions and satellites; Red-shift and the expanding Universe.",
      "scope": "triple",
      "paper": 2,
      "lessonCount": 6,
      "combinedLessonCount": 0,
      "search": "The Solar System, galaxies and star formation Life cycle of Sun-like stars Massive stars, supernovae and element formation Orbital motion and satellites Red-shift and galaxy recession Big Bang evidence, dark matter and dark energy",
      "href": "courses/gcse/index.html?subject=physics&topic=p8"
    },
    {
      "id": "measurements",
      "course": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "code": "AQA 3.1",
      "title": "Measurements and their errors",
      "summary": "SI units, prefixes, uncertainty, error, significant figures, gradients, logs and practical data handling.",
      "year": "Year 12",
      "moduleCount": 1,
      "search": "Measurements & Errors SI base units, derived units and prefixes Orders of magnitude and estimation Accuracy, precision and resolution Random and systematic errors Absolute, fractional and percentage uncertainty Combining uncertainties Graphs, error bars, gradients and intercepts Measurement mastery and practical data clinic",
      "href": "courses/alevel/index.html?subject=physics&view=course&topic=measurements&module=0"
    },
    {
      "id": "particles",
      "course": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "code": "AQA 3.2",
      "title": "Particles and radiation",
      "summary": "Particles, antiparticles, photons, particle interactions, quarks, conservation laws and wave–particle duality.",
      "year": "Year 12",
      "moduleCount": 1,
      "search": "Particles & Radiation Atomic structure, nuclides and isotopes Stable and unstable nuclei Particles, antiparticles and photons Annihilation and pair production The four fundamental interactions Exchange particles and interaction diagrams Hadrons, baryons and mesons Leptons and lepton number Quarks and antiquarks Conservation laws in particle reactions The photoelectric effect Electron collisions, excitation and ionisation Energy levels and line spectra Wave–particle duality and de Broglie wavelength Particles and quantum phenomena mastery",
      "href": "courses/alevel/index.html?subject=physics&view=course&topic=particles&module=0"
    },
    {
      "id": "waves",
      "course": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "code": "AQA 3.3",
      "title": "Waves",
      "summary": "Progressive and stationary waves, interference, diffraction, refraction, optics and wave behaviour.",
      "year": "Year 12",
      "moduleCount": 1,
      "search": "Waves Progressive waves and wave quantities Longitudinal and transverse waves Polarisation Phase difference and wave graphs Superposition and interference Stationary waves Harmonics on strings Refraction and refractive index Total internal reflection and optical fibres Young double-slit interference Diffraction Diffraction gratings Wave practical analysis and uncertainty Waves mastery and synoptic problems",
      "href": "courses/alevel/index.html?subject=physics&view=course&topic=waves&module=0"
    },
    {
      "id": "mechanics-materials",
      "course": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "code": "AQA 3.4",
      "title": "Mechanics and materials",
      "summary": "Vectors, motion, forces, momentum, work and energy, followed by materials, stress, strain and Young modulus.",
      "year": "Year 12",
      "moduleCount": 2,
      "search": "Mechanics Materials Scalars and vectors Resolving vectors and equilibrium Displacement, velocity and acceleration Motion graphs Constant acceleration equations Projectile motion Determining g by free fall Newton’s laws of motion Free-body diagrams, drag and terminal speed Momentum and impulse Conservation of momentum Work, energy and power Efficiency and energy transfers Moments and couples Density and material behaviour Hooke’s law and force–extension graphs Stress, strain and Young modulus Young modulus required practical Mechanics and materials mastery",
      "href": "courses/alevel/index.html?subject=physics&view=course&topic=mechanics-materials&module=0"
    },
    {
      "id": "electricity",
      "course": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "code": "AQA 3.5",
      "title": "Electricity",
      "summary": "Current, charge, potential difference, resistance, resistivity, circuits, power, emf and internal resistance.",
      "year": "Year 12",
      "moduleCount": 1,
      "search": "Electricity Charge, current and charge carriers Potential difference and electrical energy Resistance and Ohm’s law Current–voltage characteristics Resistivity Resistivity required practical Electrical power and energy Series circuits Parallel circuits Circuit problem solving Potential dividers Sensors in potential dividers EMF and internal resistance EMF and internal resistance practical Electricity mastery",
      "href": "courses/alevel/index.html?subject=physics&view=course&topic=electricity&module=0"
    },
    {
      "id": "further-mechanics",
      "course": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "code": "AQA 3.6",
      "title": "Further mechanics and thermal physics",
      "summary": "Circular motion, SHM, resonance, thermal physics, ideal gases and kinetic theory.",
      "year": "Year 13",
      "moduleCount": 1,
      "search": "Further Mechanics & Thermal Radians and angular speed Centripetal acceleration Centripetal force and circular systems Defining simple harmonic motion SHM displacement, velocity and acceleration Mass–spring and pendulum systems Energy in SHM SHM required practical Damping, forced oscillations and resonance Internal energy and the first-law idea Specific heat capacity Specific latent heat and phase change Gas laws and absolute temperature Ideal gas equation and gas-law practical Molecular kinetic theory and thermal mastery",
      "href": "courses/alevel/index.html?subject=physics&view=course&topic=further-mechanics&module=0"
    },
    {
      "id": "fields",
      "course": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "code": "AQA 3.7",
      "title": "Fields and their consequences",
      "summary": "Gravitational, electric and magnetic fields, orbits, capacitance and electromagnetic induction.",
      "year": "Year 13",
      "moduleCount": 1,
      "search": "Fields The field concept Gravitational field strength Gravitational potential Gravitational potential graphs Orbits and satellite motion Kepler-style orbital relationships Electric fields and Coulomb’s law Electric potential Uniform electric fields Capacitance and charge storage Energy stored by capacitors Capacitor charge and discharge Capacitor required practical Magnetic flux density and force on currents Charged particles in magnetic fields Magnetic flux and flux linkage Electromagnetic induction Fields mastery",
      "href": "courses/alevel/index.html?subject=physics&view=course&topic=fields&module=0"
    },
    {
      "id": "nuclear",
      "course": "alevel-physics",
      "level": "alevel",
      "subject": "physics",
      "code": "AQA 3.8",
      "title": "Nuclear physics",
      "summary": "Rutherford scattering, radioactivity, nuclear radius and density, mass–energy, fission, fusion and reactors.",
      "year": "Year 13",
      "moduleCount": 1,
      "search": "Nuclear Physics Rutherford scattering and the nuclear atom Alpha, beta and gamma radiation Inverse-square law and background radiation Random decay, activity and decay constant Exponential radioactive decay Half-life and logarithmic analysis Nuclear instability and decay modes Nuclear energy levels and gamma emission Closest approach and nuclear radius Electron diffraction and nuclear radius Nuclear radius relation and density Mass defect and binding energy Fission, fusion and nuclear power Nuclear physics mastery",
      "href": "courses/alevel/index.html?subject=physics&view=course&topic=nuclear&module=0"
    },
    {
      "id": "bio-molecules",
      "course": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "code": "AQA 3.1",
      "title": "Biological molecules",
      "summary": "The shared chemistry of life: carbohydrates, lipids, proteins, enzymes, nucleic acids, ATP, water and inorganic ions.",
      "year": "Year 12",
      "moduleCount": 8,
      "search": "Monomers and polymers Monomers and polymers, aligned to AQA 3.1.1. Master the core knowledge and terminology in 3.1.1. Apply monomers and polymers to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Carbohydrates Carbohydrates, aligned to AQA 3.1.2. Master the core knowledge and terminology in 3.1.2. Apply carbohydrates to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Lipids Lipids, aligned to AQA 3.1.3. Master the core knowledge and terminology in 3.1.3. Apply lipids to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Proteins Proteins, aligned to AQA 3.1.4. Master the core knowledge and terminology in 3.1.4. Apply proteins to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Nucleic acids are important information-carrying molecules Nucleic acids are important information-carrying molecules, aligned to AQA 3.1.5. Master the core knowledge and terminology in 3.1.5. Apply nucleic acids are important information-carrying molecules to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ATP ATP, aligned to AQA 3.1.6. Master the core knowledge and terminology in 3.1.6. Apply atp to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Water Water, aligned to AQA 3.1.7. Master the core knowledge and terminology in 3.1.7. Apply water to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Inorganic ions Inorganic ions, aligned to AQA 3.1.8. Master the core knowledge and terminology in 3.1.8. Apply inorganic ions to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ",
      "href": "courses/alevel/index.html?subject=biology&view=course&topic=bio-molecules&module=0"
    },
    {
      "id": "bio-cells",
      "course": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "code": "AQA 3.2",
      "title": "Cells",
      "summary": "Cell ultrastructure, cell division, membrane transport, cell recognition and immunity.",
      "year": "Year 12",
      "moduleCount": 4,
      "search": "Cell structure Cell structure, aligned to AQA 3.2.1. Master the core knowledge and terminology in 3.2.1. Apply cell structure to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. All cells arise from other cells All cells arise from other cells, aligned to AQA 3.2.2. Master the core knowledge and terminology in 3.2.2. Apply all cells arise from other cells to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Transport across cell membranes Transport across cell membranes, aligned to AQA 3.2.3. Master the core knowledge and terminology in 3.2.3. Apply transport across cell membranes to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Cell recognition and the immune system Cell recognition and the immune system, aligned to AQA 3.2.4. Master the core knowledge and terminology in 3.2.4. Apply cell recognition and the immune system to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ",
      "href": "courses/alevel/index.html?subject=biology&view=course&topic=bio-cells&module=0"
    },
    {
      "id": "bio-exchange",
      "course": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "code": "AQA 3.3",
      "title": "Organisms exchange substances with their environment",
      "summary": "Exchange surfaces, gas exchange, digestion and absorption, and mass transport in animals and plants.",
      "year": "Year 12",
      "moduleCount": 4,
      "search": "Surface area to volume ratio Surface area to volume ratio, aligned to AQA 3.3.1. Master the core knowledge and terminology in 3.3.1. Apply surface area to volume ratio to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Gas exchange Gas exchange, aligned to AQA 3.3.2. Master the core knowledge and terminology in 3.3.2. Apply gas exchange to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Digestion and absorption Digestion and absorption, aligned to AQA 3.3.3. Master the core knowledge and terminology in 3.3.3. Apply digestion and absorption to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Mass transport Mass transport, aligned to AQA 3.3.4. Master the core knowledge and terminology in 3.3.4. Apply mass transport to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ",
      "href": "courses/alevel/index.html?subject=biology&view=course&topic=bio-exchange&module=0"
    },
    {
      "id": "bio-genetic-info",
      "course": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "code": "AQA 3.4",
      "title": "Genetic information, variation and relationships between organisms",
      "summary": "DNA and protein synthesis, genetic diversity, selection, taxonomy, biodiversity and investigating variation.",
      "year": "Year 12",
      "moduleCount": 7,
      "search": "DNA, genes and chromosomes DNA, genes and chromosomes, aligned to AQA 3.4.1. Master the core knowledge and terminology in 3.4.1. Apply dna, genes and chromosomes to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. DNA and protein synthesis DNA and protein synthesis, aligned to AQA 3.4.2. Master the core knowledge and terminology in 3.4.2. Apply dna and protein synthesis to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Genetic diversity can arise as a result of mutation or during meiosis Genetic diversity can arise as a result of mutation or during meiosis, aligned to AQA 3.4.3. Master the core knowledge and terminology in 3.4.3. Apply genetic diversity can arise as a result of mutation or during meiosis to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Genetic diversity and adaptation Genetic diversity and adaptation, aligned to AQA 3.4.4. Master the core knowledge and terminology in 3.4.4. Apply genetic diversity and adaptation to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Species and taxonomy Species and taxonomy, aligned to AQA 3.4.5. Master the core knowledge and terminology in 3.4.5. Apply species and taxonomy to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Biodiversity within a community Biodiversity within a community, aligned to AQA 3.4.6. Master the core knowledge and terminology in 3.4.6. Apply biodiversity within a community to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Investigating diversity Investigating diversity, aligned to AQA 3.4.7. Master the core knowledge and terminology in 3.4.7. Apply investigating diversity to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ",
      "href": "courses/alevel/index.html?subject=biology&view=course&topic=bio-genetic-info&module=0"
    },
    {
      "id": "bio-energy",
      "course": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "code": "AQA 3.5",
      "title": "Energy transfers in and between organisms",
      "summary": "Photosynthesis, respiration, productivity, energy transfer and nutrient cycling.",
      "year": "Year 13",
      "moduleCount": 4,
      "search": "Photosynthesis Photosynthesis, aligned to AQA 3.5.1. Master the core knowledge and terminology in 3.5.1. Apply photosynthesis to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Respiration Respiration, aligned to AQA 3.5.2. Master the core knowledge and terminology in 3.5.2. Apply respiration to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Energy and ecosystems Energy and ecosystems, aligned to AQA 3.5.3. Master the core knowledge and terminology in 3.5.3. Apply energy and ecosystems to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Nutrient cycles Nutrient cycles, aligned to AQA 3.5.4. Master the core knowledge and terminology in 3.5.4. Apply nutrient cycles to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ",
      "href": "courses/alevel/index.html?subject=biology&view=course&topic=bio-energy&module=0"
    },
    {
      "id": "bio-response",
      "course": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "code": "AQA 3.6",
      "title": "Organisms respond to changes in their internal and external environments",
      "summary": "Receptors, nervous coordination, muscles and homeostasis.",
      "year": "Year 13",
      "moduleCount": 4,
      "search": "Stimuli, both internal and external, are detected and lead to a response Stimuli, both internal and external, are detected and lead to a response, aligned to AQA 3.6.1. Master the core knowledge and terminology in 3.6.1. Apply stimuli, both internal and external, are detected and lead to a response to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Nervous coordination Nervous coordination, aligned to AQA 3.6.2. Master the core knowledge and terminology in 3.6.2. Apply nervous coordination to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Skeletal muscles are stimulated to contract by nerves and act as effectors Skeletal muscles are stimulated to contract by nerves and act as effectors, aligned to AQA 3.6.3. Master the core knowledge and terminology in 3.6.3. Apply skeletal muscles are stimulated to contract by nerves and act as effectors to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Homeostasis is the maintenance of a stable internal environment Homeostasis is the maintenance of a stable internal environment, aligned to AQA 3.6.4. Master the core knowledge and terminology in 3.6.4. Apply homeostasis is the maintenance of a stable internal environment to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ",
      "href": "courses/alevel/index.html?subject=biology&view=course&topic=bio-response&module=0"
    },
    {
      "id": "bio-populations",
      "course": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "code": "AQA 3.7",
      "title": "Genetics, populations, evolution and ecosystems",
      "summary": "Inheritance, Hardy–Weinberg, evolution, speciation and population ecology.",
      "year": "Year 13",
      "moduleCount": 4,
      "search": "Inheritance Inheritance, aligned to AQA 3.7.1. Master the core knowledge and terminology in 3.7.1. Apply inheritance to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Populations Populations, aligned to AQA 3.7.2. Master the core knowledge and terminology in 3.7.2. Apply populations to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Evolution may lead to speciation Evolution may lead to speciation, aligned to AQA 3.7.3. Master the core knowledge and terminology in 3.7.3. Apply evolution may lead to speciation to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Populations in ecosystems Populations in ecosystems, aligned to AQA 3.7.4. Master the core knowledge and terminology in 3.7.4. Apply populations in ecosystems to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ",
      "href": "courses/alevel/index.html?subject=biology&view=course&topic=bio-populations&module=0"
    },
    {
      "id": "bio-gene-expression",
      "course": "alevel-biology",
      "level": "alevel",
      "subject": "biology",
      "code": "AQA 3.8",
      "title": "The control of gene expression",
      "summary": "Mutation, regulation of gene expression, genome projects and gene technologies.",
      "year": "Year 13",
      "moduleCount": 4,
      "search": "Alteration of the sequence of bases in DNA can alter the structure of proteins Alteration of the sequence of bases in DNA can alter the structure of proteins, aligned to AQA 3.8.1. Master the core knowledge and terminology in 3.8.1. Apply alteration of the sequence of bases in dna can alter the structure of proteins to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Gene expression is controlled by a number of features Gene expression is controlled by a number of features, aligned to AQA 3.8.2. Master the core knowledge and terminology in 3.8.2. Apply gene expression is controlled by a number of features to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Using genome projects Using genome projects, aligned to AQA 3.8.3. Master the core knowledge and terminology in 3.8.3. Apply using genome projects to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. Gene technologies allow the study and alteration of gene function Gene technologies allow the study and alteration of gene function, aligned to AQA 3.8.4. Master the core knowledge and terminology in 3.8.4. Apply gene technologies allow the study and alteration of gene function to data, practical and exam-style contexts. Connect this section to the wider A-Level Biology course. ",
      "href": "courses/alevel/index.html?subject=biology&view=course&topic=bio-gene-expression&module=0"
    },
    {
      "id": "chem-physical",
      "course": "alevel-chemistry",
      "level": "alevel",
      "subject": "chemistry",
      "code": "AQA 3.1",
      "title": "Physical chemistry",
      "summary": "Atomic structure, quantitative chemistry, bonding, energetics, kinetics, equilibria, thermodynamics, electrochemistry and acids and bases.",
      "year": "Years 12–13",
      "moduleCount": 12,
      "search": "Atomic structure Atomic structure, aligned to AQA 3.1.1. Master the core knowledge and terminology in 3.1.1. Apply atomic structure to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Amount of substance Amount of substance, aligned to AQA 3.1.2. Master the core knowledge and terminology in 3.1.2. Apply amount of substance to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Bonding Bonding, aligned to AQA 3.1.3. Master the core knowledge and terminology in 3.1.3. Apply bonding to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Energetics Energetics, aligned to AQA 3.1.4. Master the core knowledge and terminology in 3.1.4. Apply energetics to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Kinetics Kinetics, aligned to AQA 3.1.5. Master the core knowledge and terminology in 3.1.5. Apply kinetics to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Chemical equilibria, Le Chatelier’s principle and Kc Chemical equilibria, Le Chatelier’s principle and Kc, aligned to AQA 3.1.6. Master the core knowledge and terminology in 3.1.6. Apply chemical equilibria, le chatelier’s principle and kc to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Oxidation, reduction and redox equations Oxidation, reduction and redox equations, aligned to AQA 3.1.7. Master the core knowledge and terminology in 3.1.7. Apply oxidation, reduction and redox equations to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Thermodynamics Thermodynamics, aligned to AQA 3.1.8. Master the core knowledge and terminology in 3.1.8. Apply thermodynamics to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Rate equations Rate equations, aligned to AQA 3.1.9. Master the core knowledge and terminology in 3.1.9. Apply rate equations to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Equilibrium constant Kp for homogeneous systems Equilibrium constant Kp for homogeneous systems, aligned to AQA 3.1.10. Master the core knowledge and terminology in 3.1.10. Apply equilibrium constant kp for homogeneous systems to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Electrode potentials and electrochemical cells Electrode potentials and electrochemical cells, aligned to AQA 3.1.11. Master the core knowledge and terminology in 3.1.11. Apply electrode potentials and electrochemical cells to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Acids and bases Acids and bases, aligned to AQA 3.1.12. Master the core knowledge and terminology in 3.1.12. Apply acids and bases to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. ",
      "href": "courses/alevel/index.html?subject=chemistry&view=course&topic=chem-physical&module=0"
    },
    {
      "id": "chem-inorganic",
      "course": "alevel-chemistry",
      "level": "alevel",
      "subject": "chemistry",
      "code": "AQA 3.2",
      "title": "Inorganic chemistry",
      "summary": "Periodicity, Group 2, Group 7, Period 3 chemistry, transition metals and reactions of aqueous ions.",
      "year": "Years 12–13",
      "moduleCount": 6,
      "search": "Periodicity Periodicity, aligned to AQA 3.2.1. Master the core knowledge and terminology in 3.2.1. Apply periodicity to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Group 2, the alkaline earth metals Group 2, the alkaline earth metals, aligned to AQA 3.2.2. Master the core knowledge and terminology in 3.2.2. Apply group 2, the alkaline earth metals to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Group 7(17), the halogens Group 7(17), the halogens, aligned to AQA 3.2.3. Master the core knowledge and terminology in 3.2.3. Apply group 7(17), the halogens to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Properties of Period 3 elements and their oxides Properties of Period 3 elements and their oxides, aligned to AQA 3.2.4. Master the core knowledge and terminology in 3.2.4. Apply properties of period 3 elements and their oxides to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Transition metals Transition metals, aligned to AQA 3.2.5. Master the core knowledge and terminology in 3.2.5. Apply transition metals to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Reactions of ions in aqueous solution Reactions of ions in aqueous solution, aligned to AQA 3.2.6. Master the core knowledge and terminology in 3.2.6. Apply reactions of ions in aqueous solution to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. ",
      "href": "courses/alevel/index.html?subject=chemistry&view=course&topic=chem-inorganic&module=0"
    },
    {
      "id": "chem-organic",
      "course": "alevel-chemistry",
      "level": "alevel",
      "subject": "chemistry",
      "code": "AQA 3.3",
      "title": "Organic chemistry",
      "summary": "Organic nomenclature and mechanisms through synthesis, polymers, biomolecules, spectroscopy and chromatography.",
      "year": "Years 12–13",
      "moduleCount": 16,
      "search": "Introduction to organic chemistry Introduction to organic chemistry, aligned to AQA 3.3.1. Master the core knowledge and terminology in 3.3.1. Apply introduction to organic chemistry to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Alkanes Alkanes, aligned to AQA 3.3.2. Master the core knowledge and terminology in 3.3.2. Apply alkanes to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Halogenoalkanes Halogenoalkanes, aligned to AQA 3.3.3. Master the core knowledge and terminology in 3.3.3. Apply halogenoalkanes to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Alkenes Alkenes, aligned to AQA 3.3.4. Master the core knowledge and terminology in 3.3.4. Apply alkenes to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Alcohols Alcohols, aligned to AQA 3.3.5. Master the core knowledge and terminology in 3.3.5. Apply alcohols to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Organic analysis Organic analysis, aligned to AQA 3.3.6. Master the core knowledge and terminology in 3.3.6. Apply organic analysis to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Optical isomerism Optical isomerism, aligned to AQA 3.3.7. Master the core knowledge and terminology in 3.3.7. Apply optical isomerism to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Aldehydes and ketones Aldehydes and ketones, aligned to AQA 3.3.8. Master the core knowledge and terminology in 3.3.8. Apply aldehydes and ketones to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Carboxylic acids and derivatives Carboxylic acids and derivatives, aligned to AQA 3.3.9. Master the core knowledge and terminology in 3.3.9. Apply carboxylic acids and derivatives to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Aromatic chemistry Aromatic chemistry, aligned to AQA 3.3.10. Master the core knowledge and terminology in 3.3.10. Apply aromatic chemistry to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Amines Amines, aligned to AQA 3.3.11. Master the core knowledge and terminology in 3.3.11. Apply amines to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Polymers Polymers, aligned to AQA 3.3.12. Master the core knowledge and terminology in 3.3.12. Apply polymers to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Amino acids, proteins and DNA Amino acids, proteins and DNA, aligned to AQA 3.3.13. Master the core knowledge and terminology in 3.3.13. Apply amino acids, proteins and dna to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Organic synthesis Organic synthesis, aligned to AQA 3.3.14. Master the core knowledge and terminology in 3.3.14. Apply organic synthesis to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Nuclear magnetic resonance spectroscopy Nuclear magnetic resonance spectroscopy, aligned to AQA 3.3.15. Master the core knowledge and terminology in 3.3.15. Apply nuclear magnetic resonance spectroscopy to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. Chromatography Chromatography, aligned to AQA 3.3.16. Master the core knowledge and terminology in 3.3.16. Apply chromatography to data, practical and exam-style contexts. Connect this section to the wider A-Level Chemistry course. ",
      "href": "courses/alevel/index.html?subject=chemistry&view=course&topic=chem-organic&module=0"
    },
    {
      "id": "maths-number",
      "course": "gcse-maths",
      "level": "gcse",
      "subject": "maths",
      "code": "",
      "title": "Number",
      "summary": "Build fluency with signed numbers, fractions, powers, accuracy and financial calculations.",
      "lessonCount": 7,
      "search": "Integers, decimals and order of operations Factors, multiples and primes Fractions and mixed numbers Percentages and financial mathematics Indices and standard form Rounding, estimation and bounds Surds, fractional indices and exact values",
      "href": "courses/subjects/index.html?subject=maths&topic=maths-number&view=textbook"
    },
    {
      "id": "maths-algebra",
      "course": "gcse-maths",
      "level": "gcse",
      "subject": "maths",
      "code": "",
      "title": "Algebra",
      "summary": "Manipulate expressions, solve equations, interpret graphs and explain relationships.",
      "lessonCount": 9,
      "search": "Expressions, substitution and formulae Expanding and factorising Linear equations and inequalities Sequences and nth terms Coordinates and straight-line graphs Quadratics and simultaneous equations Higher equations, functions and iteration Graph shapes, transformations and rates Algebraic fractions and proof",
      "href": "courses/subjects/index.html?subject=maths&topic=maths-algebra&view=textbook"
    },
    {
      "id": "maths-ratio-and-proportion",
      "course": "gcse-maths",
      "level": "gcse",
      "subject": "maths",
      "code": "",
      "title": "Ratio and proportion",
      "summary": "Connect ratios, rates, percentages, scales and changing quantities.",
      "lessonCount": 4,
      "search": "Ratio, sharing and scale Rates, units and best buys Direct and inverse proportion Growth, decay and proportional modelling",
      "href": "courses/subjects/index.html?subject=maths&topic=maths-ratio-and-proportion&view=textbook"
    },
    {
      "id": "maths-geometry-and-measures",
      "course": "gcse-maths",
      "level": "gcse",
      "subject": "maths",
      "code": "",
      "title": "Geometry and measures",
      "summary": "Reason about shapes, construction, trigonometry, vectors and measures.",
      "lessonCount": 7,
      "search": "Angles, polygons and reasoning Constructions, loci and bearings Perimeter, area and circles Volume, surface area and similarity Pythagoras and right-angle trigonometry Transformations and vectors Circle theorems and non-right triangles",
      "href": "courses/subjects/index.html?subject=maths&topic=maths-geometry-and-measures&view=textbook"
    },
    {
      "id": "maths-probability",
      "course": "gcse-maths",
      "level": "gcse",
      "subject": "maths",
      "code": "",
      "title": "Probability",
      "summary": "Describe uncertainty, combine events and distinguish independent from conditional events.",
      "lessonCount": 4,
      "search": "Probability models and relative frequency Sample spaces, tables and Venn diagrams Tree diagrams and combined events Conditional probability and independence",
      "href": "courses/subjects/index.html?subject=maths&topic=maths-probability&view=textbook"
    },
    {
      "id": "maths-statistics",
      "course": "gcse-maths",
      "level": "gcse",
      "subject": "maths",
      "code": "",
      "title": "Statistics",
      "summary": "Collect representative data, choose summaries and interpret diagrams critically.",
      "lessonCount": 4,
      "search": "Sampling and data collection Averages, spread and frequency tables Charts, scatter graphs and time series Histograms, cumulative frequency and box plots",
      "href": "courses/subjects/index.html?subject=maths&topic=maths-statistics&view=textbook"
    },
    {
      "id": "geography-natural-hazards",
      "course": "gcse-geography",
      "level": "gcse",
      "subject": "geography",
      "code": "",
      "title": "Natural hazards",
      "summary": "Tectonic hazards, weather hazards, climate change and contrasting responses.",
      "lessonCount": 5,
      "search": "Plate margins and hazard risk Nepal 2015 and Chile 2010 Atmospheric circulation and tropical storms UK extreme weather and Somerset flooding Climate change evidence and responses",
      "href": "courses/subjects/index.html?subject=geography&topic=geography-natural-hazards&view=textbook"
    },
    {
      "id": "geography-the-living-world",
      "course": "gcse-geography",
      "level": "gcse",
      "subject": "geography",
      "code": "",
      "title": "The living world",
      "summary": "Ecosystem relationships, tropical rainforests, hot deserts and cold environments.",
      "lessonCount": 4,
      "search": "Ecosystems, food webs and nutrient cycles Amazon rainforest structure and deforestation Hot deserts and the Thar Cold environments and Alaska",
      "href": "courses/subjects/index.html?subject=geography&topic=geography-the-living-world&view=textbook"
    },
    {
      "id": "geography-uk-physical-landscapes",
      "course": "gcse-geography",
      "level": "gcse",
      "subject": "geography",
      "code": "",
      "title": "UK physical landscapes",
      "summary": "Processes and management of coasts, rivers and glaciated landscapes. Select your school’s two landscape options.",
      "lessonCount": 5,
      "search": "Coastal erosion, transport and landforms Coastal management and Holderness River processes, landforms and the Tees Flood hydrographs and river management Glaciation and the Lake District",
      "href": "courses/subjects/index.html?subject=geography&topic=geography-uk-physical-landscapes&view=textbook"
    },
    {
      "id": "geography-urban-issues-and-challenges",
      "course": "gcse-geography",
      "level": "gcse",
      "subject": "geography",
      "code": "",
      "title": "Urban issues and challenges",
      "summary": "Urban growth, Rio, London, regeneration and sustainability.",
      "lessonCount": 3,
      "search": "Urbanisation and Rio de Janeiro London, migration and regeneration Sustainable urban living",
      "href": "courses/subjects/index.html?subject=geography&topic=geography-urban-issues-and-challenges&view=textbook"
    },
    {
      "id": "geography-the-changing-economic-world",
      "course": "gcse-geography",
      "level": "gcse",
      "subject": "geography",
      "code": "",
      "title": "The changing economic world",
      "summary": "Measures of development, the development gap, Nigeria and UK change.",
      "lessonCount": 4,
      "search": "Development indicators and demographic change Reducing the development gap and Jamaica Nigeria, industry and global links UK economic change and regional inequality",
      "href": "courses/subjects/index.html?subject=geography&topic=geography-the-changing-economic-world&view=textbook"
    },
    {
      "id": "geography-resource-management",
      "course": "gcse-geography",
      "level": "gcse",
      "subject": "geography",
      "code": "",
      "title": "Resource management",
      "summary": "UK resource patterns and global food, water and energy options.",
      "lessonCount": 4,
      "search": "UK food, water and energy Global food security and sustainable production Global water security and management Global energy security and sustainable choices",
      "href": "courses/subjects/index.html?subject=geography&topic=geography-resource-management&view=textbook"
    },
    {
      "id": "geography-geographical-skills-and-fieldwork",
      "course": "gcse-geography",
      "level": "gcse",
      "subject": "geography",
      "code": "",
      "title": "Geographical skills and fieldwork",
      "summary": "Maps, graphical skills, investigations, reliability and issue evaluation.",
      "lessonCount": 4,
      "search": "Maps, graphs and quantitative skills Designing physical and human investigations Presenting results and evaluating fieldwork Issue evaluation and decision making",
      "href": "courses/subjects/index.html?subject=geography&topic=geography-geographical-skills-and-fieldwork&view=textbook"
    }
  ]
};
