(() => {
 'use strict';
 const $=id=>document.getElementById(id),{el,button}=window.REVISION_ACTIVITY_UI,data=window.REVISION_TEACHER_DATA;
 let context,preview=[],savedId=null,selectedClass='';
 const dateString=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
 const config=cid=>{const c=context.state.classes.find(c=>c.id===cid);return {level:c?.level==='A-level'?'alevel':'gcse',subject:['biology','chemistry','physics'].includes(c?.subject?.toLowerCase())?c.subject.toLowerCase():$('planner-subject').value};};
 function init(api){context=api;const panel=el('section',undefined,'teacher-panel');panel.id='planner-panel';panel.append(el('h2','Homework planner'));
  const controls=el('div',undefined,'workspace-controls');for(const [id,title,type]of [['planner-class','Class','select'],['planner-subject','Subject','select'],['planner-name','Plan name','text'],['planner-start','First release date','date'],['planner-weeks','Weeks','number']]){const l=el('label',title),i=el(type==='select'?'select':'input');i.id=id;i.setAttribute('aria-label',title);if(type!=='select')i.type=type;l.append(i);controls.append(l);}
  panel.append(controls);$('workspace-set-work').append(panel);$('planner-subject').replaceChildren(...['biology','chemistry','physics'].map(s=>new Option(s,s)));$('planner-subject').value='physics';$('planner-name').value='Half-term homework';$('planner-name').maxLength=120;$('planner-start').value=dateString(new Date());$('planner-weeks').value=6;$('planner-weeks').min=1;$('planner-weeks').max=52;
  $('planner-class').onchange=()=>{selectedClass=$('planner-class').value;rows();};$('planner-subject').onchange=rows;$('planner-weeks').onchange=rows;$('planner-start').onchange=()=>clear();$('planner-name').oninput=()=>clear();
  const list=el('div');list.id='planner-weeks-list';panel.append(list);const generate=button('Preview weekly homework','planner-preview','','teacher-button');generate.onclick=build;panel.append(generate);const result=el('div');result.id='planner-preview-list';panel.append(result);const saved=el('div');saved.id='planner-saved';panel.append(saved);
  const alerts=el('section',undefined,'teacher-panel');alerts.id='teacher-alerts';$('workspace-dashboard').prepend(alerts);
 }
 function clear(){preview=[];savedId=null;$('planner-preview-list').replaceChildren();}
 function rows(){clear();const cid=$('planner-class').value,c=config(cid),list=$('planner-weeks-list');list.replaceChildren();const topics=window.REVISION_ACTIVITIES.topics(c.level,c.subject,'combined'),weeks=Number($('planner-weeks').value);if(!Number.isInteger(weeks)||weeks<1||weeks>52)return;
  for(let n=0;n<weeks;n++){const row=el('div',undefined,'workspace-controls');row.dataset.week=n;row.append(el('strong','Week '+(n+1)));
   for(const [title,cls,values]of [['Topic','planner-topic',topics.map(t=>[t.id,t.title])],['Lesson','planner-lesson',[['','All lessons']]],['Activity','planner-mode',[['quiz','Retrieval quiz'],['lesson','Revision lesson'],['mixed','Mixed practice'],['exam','Exam questions'],['test','Topic assessment']]]]){const label=el('label',title),s=el('select');s.className=cls;s.setAttribute('aria-label',`Week ${n+1} ${title}`);values.forEach(([v,t])=>s.append(new Option(t,v)));label.append(s);row.append(label);}
   row.querySelector('.planner-topic').value=topics[n%topics.length]?.id||'';
   const lessons=()=>{const topic=row.querySelector('.planner-topic').value,s=row.querySelector('.planner-lesson');s.replaceChildren(new Option('All lessons',''),...window.REVISION_PRACTICE.lessons.filter(l=>l.level===c.level&&l.subject===c.subject&&l.topic===topic&&l.scope!=='triple').map(l=>new Option(l.title,l.id)));clear();};row.querySelector('.planner-topic').onchange=lessons;lessons();row.querySelector('.planner-lesson').onchange=clear;row.querySelector('.planner-mode').onchange=clear;list.append(row);
  }
 }
 function build(){clear();const cid=$('planner-class').value,c=config(cid),start=$('planner-start').value,name=$('planner-name').value.trim();if(!cid||!name||!start)return context.showNotice('Choose a class, plan name and first release date.','error');
  try{for(const row of $('planner-weeks-list').children){const week=Number(row.dataset.week),release=new Date(start+'T08:00:00');release.setDate(release.getDate()+week*7);const due=new Date(release);due.setDate(due.getDate()+6);due.setHours(23,59,59);const mode=row.querySelector('.planner-mode').value,lesson=row.querySelector('.planner-lesson').value;
    const activity=window.REVISION_ACTIVITIES.generate({...c,pathway:'combined',topic:row.querySelector('.planner-topic').value,kind:['exam','test'].includes(mode)?'exam':mode==='quiz'?'quiz':'revision',count:mode==='test'?12:6,includeWritten:['exam','test'].includes(mode),seed:week+10,lessonIds:lesson?[lesson]:undefined});
    activity.attempts_limit=mode==='test'?1:2;activity.feedback_mode='after_final_attempt';activity.allow_late=true;if(mode==='lesson')activity.study_material=window.REVISION_PRACTICE.lessons.filter(l=>activity.questions.some(q=>q.lessonId===l.id)).map(l=>({title:l.title,text:l.core}));
    preview.push({meta:{class_id:cid,title:(name+' · Week '+(week+1)+' · '+activity.topicTitle).slice(0,120),assignment_type:mode==='test'?'test':'homework',instructions:'Complete the weekly '+mode+' task.',start_at:release.toISOString(),due_at:due.toISOString(),recipient_ids:null,target_score:75,estimated_minutes:15,activity_mode:mode},activity});}
    const target=$('planner-preview-list');target.append(el('h3',`${preview.length} weeks ready to review`));preview.forEach((p,i)=>{const d=el('details');d.append(el('summary',`Week ${i+1} · ${p.activity.topicTitle} · ${new Date(p.meta.start_at).toLocaleDateString()} → ${new Date(p.meta.due_at).toLocaleDateString()} · ${p.activity.questions.length} questions`));p.activity.questions.forEach(q=>d.append(el('h4',q.prompt),el('p','Mark scheme: '+q.key.solution.join(' · '))));target.append(d);});
    for(const [title,action]of [['Save plan','save'],['Schedule all','schedule']]){const b=button(title,'planner-'+action,'','teacher-button');b.onclick=()=>save(action==='schedule',b);target.append(b);}}
  catch(e){preview=[];context.showNotice(e.message,'error');}
 }
 async function save(schedule,b){b.disabled=true;try{if(!preview.length)throw Error('Preview the plan first.');if(!savedId){const r=await revisionSupabase.from('revision_homework_plans').insert({teacher_id:context.state.user.id,class_id:$('planner-class').value,name:$('planner-name').value.trim(),payload:{entries:preview}}).select('*').single();if(r.error)throw r.error;savedId=r.data.id;}if(schedule)await schedulePlan(savedId);else{context.showNotice('Homework plan saved.');await context.loadTeacherData();}}catch(e){context.showNotice(e.message,'error');}finally{b.disabled=false;}}
 async function schedulePlan(id){const r=await revisionSupabase.rpc('revision_schedule_plan',{p_plan_id:id});if(r.error)throw r.error;context.showNotice(`${r.data.length} weekly assignments scheduled.`);clear();await context.loadTeacherData();}
 function render(){if(!context)return;const s=$('planner-class'),v=s.value;s.replaceChildren(...context.state.classes.filter(c=>!c.archived).map(c=>new Option(c.name,c.id)));if([...s.options].some(o=>o.value===v))s.value=v;if(selectedClass!==s.value){selectedClass=s.value;rows();}
  const target=$('planner-saved');target.replaceChildren(el('h3','Saved homework plans'));for(const p of context.state.homeworkPlans||[]){const d=el('details');d.append(el('summary',`${p.name} · ${p.scheduled_at?'Scheduled':'Draft'}`));(p.payload?.entries||[]).forEach(e=>{d.append(el('h4',e.meta.title));e.activity.questions.forEach(q=>d.append(el('p',q.prompt),el('p',q.key.solution.join(' · '))));});if(!p.scheduled_at){const b=button('Schedule saved plan','schedule-saved',p.id,'teacher-button');b.onclick=async()=>{b.disabled=true;try{await schedulePlan(p.id);}catch(e){context.showNotice(e.message,'error');}finally{b.disabled=false;}};d.append(b);}target.append(d);}renderAlerts();
 }
 function renderAlerts(){const target=$('teacher-alerts'),dismissed=new Set((context.state.alertState||[]).map(a=>a.alert_key));target.replaceChildren(el('h2','Teacher alerts and weekly summary'));const alerts=data.alerts(context.state).filter(a=>!dismissed.has(a.key));
  if(!alerts.length)target.append(el('p','No new alerts.','panel-copy'));for(const a of alerts){const row=el('div',undefined,'workspace-controls');row.append(el('span',a.title));const open=button(a.topic?'Set recommended work':'View progress','open-alert','','teacher-button');open.onclick=()=>{if(a.topic)window.REVISION_INSIGHTS.targetWork(a.classId,[],{topic:a.topic,title:a.title});else if(a.studentId){const m=context.state.members.find(m=>m.class_id===a.classId&&m.student_id===a.studentId);if(m)window.REVISION_TEACHER_WORKSPACE.profile(m);}else{window.REVISION_TEACHER_WORKSPACE.show('dashboard');$('assignment-filter-class').value=a.classId;$('assignment-filter-class').dispatchEvent(new Event('change'));$('assignment-list').scrollIntoView({behavior:'smooth'});}};const dismiss=button('Dismiss','dismiss-alert','','mini-button');dismiss.onclick=async()=>{const r=await revisionSupabase.rpc('revision_dismiss_alert',{p_key:a.key});if(r.error)context.showNotice(r.error.message,'error');else{context.state.alertState.push({alert_key:a.key});renderAlerts();}};row.append(open,dismiss);target.append(row);}
  for(const c of context.state.classes){const s=data.weeklySummary(context.state,c.id);target.append(el('p',`${c.name} · Last 7 days: ${s.completed} completed results from ${s.students} students · ${s.average===null?'No marked average':s.average+'% average'}`));}
 }
 window.REVISION_PLANNER={init,render,reset(){clear();selectedClass='';$('planner-weeks-list').replaceChildren();}};
})();
