(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;let installPrompt=null;
function ensureManifest(){if(!document.querySelector('link[rel="manifest"]')){const l=document.createElement('link');l.rel='manifest';l.href='manifest.webmanifest';document.head.appendChild(l);}if(!document.querySelector('link[rel="icon"]')){const l=document.createElement('link');l.rel='icon';l.href='app-icon.svg';document.head.appendChild(l);}}
ensureManifest();
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}
function render(root){const online=navigator.onLine,sw='serviceWorker'in navigator;root.innerHTML=`<div class="tool-three"><div class="tool-panel"><small>Connection</small><div class="tool-score">${online?'Online':'Offline'}</div><p>The app state itself is stored on this device.</p></div><div class="tool-panel"><small>Offline engine</small><div class="tool-score">${sw?'Supported':'Unavailable'}</div><p>${sw?'Core app files can be cached after a successful visit.':'This browser does not expose Service Workers.'}</p></div><div class="tool-panel"><small>Install</small><div class="tool-score">${installPrompt?'Ready':'Browser menu'}</div><p>${installPrompt?'An install prompt is available.':'Your browser may offer Add to Home screen / Install app from its menu.'}</p></div></div><div class="tool-panel"><h3>Offline/PWA mode</h3><p>After the service worker has cached this version, the practical simulations, Lab Book and Learning Tools can open without a network connection. External web links and externally hosted fonts may still require internet access.</p><div class="tool-callout">Lab Book and progress use browser storage. Keep a JSON backup from the Evidence Pack feature if the data matters, because clearing site data can remove local records.</div><div class="tool-actions"><button class="primary-btn" id="pwaInstall" ${installPrompt?'':'disabled'}>Install app</button><button class="secondary-btn" id="pwaRefresh">Refresh offline cache</button><button class="secondary-btn" id="pwaBackup">Download data backup</button></div><div id="pwaOut"></div></div><div class="tool-panel"><h3>Offline readiness checklist</h3><ul><li>Open the app once while online after an update.</li><li>Wait for the service worker to finish installing.</li><li>Keep the app on the same browser/profile so local Lab Book data remains available.</li><li>Use Evidence Pack → JSON backup before clearing browser/site data.</li></ul></div>`;root.querySelector('#pwaInstall').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;root.querySelector('#pwaOut').innerHTML='<div class="tool-feedback">Install request handled by the browser.</div>';T.mark(15,true);};root.querySelector('#pwaRefresh').onclick=async()=>{if(!sw){return;}const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs)await r.update();root.querySelector('#pwaOut').innerHTML='<div class="tool-feedback">Service worker update check requested. Reload once online to use the newest cache.</div>';T.mark(15,true);};root.querySelector('#pwaBackup').onclick=()=>T.download('practical-lab-backup.json',JSON.stringify(state,null,2),'application/json');}
window.addEventListener('online',()=>document.querySelector('#view-tools.active')&&T.renderHome());window.addEventListener('offline',()=>document.querySelector('#view-tools.active')&&T.renderHome());
T.register(15,{title:'Offline / PWA mode',kicker:'INSTALL · CACHE · BACKUP',description:'Install the app, cache core files for offline use and protect local Lab Book data with backups.',icon:'📱',render});
})();