(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const V={
1:{s:'Instead of varying vibrating length, investigate how resonant frequency depends on string tension.',q:'Which change best adapts the method?',c:['Keep L and μ fixed, vary tension using known hanging loads, find resonance each time, and test f² against T.','Vary length and tension together.','Keep tension fixed and change only frequency without recording the load.'],a:0,w:'From f=(1/2L)√(T/μ), with L and μ fixed, f² is proportional to T.'},
2:{s:'Use a diffraction grating with known spacing to determine an unknown wavelength.',q:'What data should be prioritised?',c:['Measure diffraction angle for identified order(s), use d sinθ=nλ, and compare symmetric orders where possible.','Measure screen brightness only.','Move the source until a familiar colour appears.'],a:0,w:'Order and angle provide the quantities needed by the grating equation. Optical alignment remains teacher-supervised.'},
3:{s:'Determine g using several release heights but the timer has a small fixed electronic delay.',q:'How can the analysis reveal the problem?',c:['Use h against t² and inspect the intercept/systematic departure rather than calculating g from one point.','Use only the largest height.','Subtract an arbitrary delay until g=9.81.'],a:0,w:'A multi-point graph can expose systematic offsets; arbitrary correction to force an expected answer is not valid.'},
4:{s:'Compare the Young modulus of two wire materials.',q:'What must be measured independently for each wire?',c:['Diameter/cross-sectional area and original length, then stress and strain within the elastic region.','Only the applied mass.','Only extension because both wires look similar.'],a:0,w:'Stress depends on area and strain depends on original length, so geometry must be measured for each specimen.'},
5:{s:'An unknown resistance wire is supplied. Determine its resistivity.',q:'Which combination is sufficient?',c:['Measure diameter, obtain R for several lengths, find gradient of R-L, then use ρ=gradient×A.','Measure current once.','Measure total wire mass and divide by length.'],a:0,w:'The R-L gradient gives ρ/A and micrometer data gives A.'},
6:{s:'Compare two cells with different internal resistances.',q:'How should the comparison be made?',c:['For each cell independently obtain a V-I best-fit line and compare intercepts and gradient magnitudes.','Connect the cells directly together.','Compare one terminal-voltage reading at different currents.'],a:0,w:'Each source needs its own consistent V-I data set; intercept and gradient have direct physical meanings.'},
7:{s:'Use a mass-spring oscillator to determine the spring constant dynamically.',q:'What graph should be used?',c:['Plot T² against oscillating mass m; gradient=4π²/k.','Plot T against 1/m.','Plot amplitude against time and call the gradient k.'],a:0,w:'The SHM period relationship linearises as T²=(4π²/k)m for the ideal model.'},
8:{s:'A different syringe has a different plunger seal diameter.',q:'What must change in the Boyle calculation?',c:['Re-measure the seal diameter and recalculate plunger area before converting hanging force to pressure.','Use the old area because pressure is independent of apparatus.','Add mg/A to atmospheric pressure for the hanging-mass geometry.'],a:0,w:'The force-per-area term depends directly on the new plunger area; the app’s AQA-style hanging-mass geometry uses Patm−mg/A.'},
9:{s:'The resistor is changed while the same capacitor is used.',q:'What prediction can be tested?',c:['The time constant τ=RC should change in proportion to R; compare log-linear gradients.','The initial voltage must double.','Capacitance must change with R.'],a:0,w:'For fixed C, τ is proportional to R and the discharge log gradient is −1/RC.'},
10:{s:'Investigate F=BIL by varying active wire length instead of current.',q:'What should be kept constant?',c:['B and I, while measuring only the conductor length inside the field.','Total wire length and current, while B and I both change.','Nothing; three variables can be changed together.'],a:0,w:'To test F∝L, B and I are controls and only the active field length belongs in the equation.'},
11:{s:'Repeat the search-coil investigation at a second field frequency.',q:'What should the student do?',c:['Take a new angular data set at the second frequency while keeping coil geometry and field conditions otherwise controlled.','Rotate continuously and estimate the maximum by eye.','Change the oscilloscope scale between every point without recording it.'],a:0,w:'A fair comparison needs defined fixed angles and documented instrument settings.'},
12:{s:'In the simulation, compare the effect of doubling counting time at the same distance.',q:'What should happen to fractional statistical uncertainty?',c:['It should generally reduce because more counts are accumulated, while random count variation remains.','It becomes exactly zero.','The inverse-square relationship stops applying.'],a:0,w:'Longer counting accumulates more events and usually reduces fractional counting uncertainty; the activity remains simulation-only.'}
};
function render(root,opts={}){let id=+(opts.practicalId||state.last||1);function draw(){const p=T.practical(id),v=V[id];root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Variation</b> <select id="pvP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label></div></div><div class="tool-panel"><span class="eyebrow">UNFAMILIAR CONTEXT</span><h3>${T.esc(v.s)}</h3><p>${T.esc(v.q)}</p>${v.c.map((x,i)=>`<label class="tool-choice"><input type="radio" name="pv" value="${i}"> ${T.esc(x)}</label>`).join('')}<div id="pvOut"></div><button class="primary-btn" id="pvCheck">Check adaptation</button></div><div class="tool-panel"><h3>Write the adapted method</h3><textarea id="pvMethod" rows="7" placeholder="State what you change, what you measure, what you control, repeats, graph and how the result is obtained."></textarea><div class="tool-actions"><button class="secondary-btn" id="pvDone">Save as completed practice</button></div></div>`;root.querySelector('#pvP').onchange=e=>{id=+e.target.value;draw();};root.querySelector('#pvCheck').onclick=()=>{const x=root.querySelector('input[name=pv]:checked');if(!x)return;const ok=+x.value===v.a;root.querySelector('#pvOut').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'Good adaptation':'Reconsider which quantities the physics requires'}</b><p>${T.esc(v.w)}</p></div>`;};root.querySelector('#pvDone').onclick=()=>{if(root.querySelector('#pvMethod').value.trim().split(/\s+/).length<15){root.querySelector('#pvOut').innerHTML='<div class="tool-feedback warn">Add more detail to the adapted method before marking it complete.</div>';return;}T.mark(8,true);root.querySelector('#pvDone').textContent='Completed ✓';};}draw();}
T.register(8,{title:'Practical variations',kicker:'TRANSFER THE METHOD',description:'Adapt familiar required-practical physics to an unfamiliar variable, apparatus or analysis task.',icon:'🔀',render,decorate({addPracticalButton,open}){addPracticalButton('variations','Variation challenge',()=>open(8,{practicalId:current?.id||state.last}));}});
})();