(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const setups={
1:[['Drive end','Vibration generator / string driver','Produces the vibration in the string.'],['Measured section','String between effective end points','This is the vibrating length used in the model.'],['Tension end','Pulley + hanging mass','Provides the string tension.'],['Length reference','Metre rule','Measures the vibrating length.']],
2:[['Light path','Light source → slit/grating → screen','Defines the interference/diffraction geometry.'],['Pattern element','Double slit or diffraction grating','Produces the selected interference pattern.'],['Observation plane','Screen','Where fringe or diffraction positions are measured.'],['Distance reference','Ruler / distance scale','Defines the source-element/screen geometry used in calculations.']],
3:[['Release point','Release mechanism','Starts the fall from a consistent reference point.'],['Falling object','Metal ball','Object whose free-fall time is measured.'],['Timing end point','Impact pad / light-gate arrangement','Provides electronic timing in the selected setup.'],['Vertical reference','Metre rule + plumb alignment','Defines the measured fall distance.']],
4:[['Reference support','Fixed reference wire','Provides comparison against support movement.'],['Test sample','Test wire','Wire whose extension is measured.'],['Loading point','Mass hanger / load','Applies tensile force.'],['Small-distance measurement','Micrometer / vernier arrangement','Measures diameter and/or extension accurately.']],
5:[['Test material','Resistance wire beside a length scale','Defines the selected wire length.'],['Moveable point','Sliding contact','Selects the effective wire length.'],['Series measurement','Ammeter','Measures current through the wire.'],['Parallel measurement','Voltmeter','Measures p.d. across the selected length.']],
6:[['Source','Cell / battery','Provides emf and internal resistance.'],['Series path','Ammeter + variable resistor','Measures and changes current.'],['Cell terminals','Voltmeter across the cell','Measures terminal p.d.'],['Control','Switch','Allows readings to be taken without leaving current flowing continuously.']],
7:[['Pendulum support','Clamp + pivot + string','Defines the simple-pendulum suspension.'],['Pendulum reference','Fiducial marker / ruler','Improves length/position judgement.'],['Spring support','Clamp + spring + mass','Forms the mass–spring oscillator.'],['Timing','Stopwatch / oscilloscope where used','Measures oscillation period using the chosen method.']],
8:[['Boyle gas sample','Vertical clamped gas syringe','Contains the trapped gas volume.'],['Boyle loading','String loop + mass holder + slotted masses','Changes the force on the plunger in the AQA hanging-mass geometry.'],['Boyle scale','Syringe scale / seal diameter measurement','Provides volume and plunger-area information.'],['Charles setup','Capillary/air column in water bath + thermometer','Measures gas-volume proxy versus temperature at constant pressure.']],
9:[['Storage element','Capacitor','Stores charge.'],['Time-constant element','Resistor','Sets RC with the capacitor.'],['Switching','Charge/discharge switch arrangement','Starts the selected charge or discharge process.'],['Measurement','Voltmeter / data logger across capacitor','Records capacitor p.d. versus time.']],
10:[['Force element','Current-carrying wire in magnetic field','Experiences magnetic force.'],['Field region','Magnet / field assembly','Provides flux density B.'],['Force measurement','Top-pan balance','Measures the change associated with magnetic force.'],['Electrical control','Supply + ammeter / variable resistor','Controls and measures current.']],
11:[['Field source','Alternating magnetic-field assembly','Produces changing magnetic flux.'],['Sensor','Search coil','Links magnetic flux at a chosen angle.'],['Angle reference','Protractor / angle scale','Defines the coil orientation.'],['Signal measurement','Oscilloscope','Measures induced emf amplitude.']],
12:[['Virtual detector','Virtual GM tube','Represents the detector in the simulation.'],['Virtual source marker','Virtual source position','Defines the simulated source location only.'],['Geometry','Distance scale / alignment axis','Defines virtual separation r.'],['Counting','Virtual scaler','Displays simulated counts; no source-handling procedure is included.']]
};
function shuffle(a){return [...a].sort(()=>Math.random()-.5);}
function render(root,opts={}){let id=+(opts.practicalId||state.last||1),selected=null,placed=[];
 function draw(){const rows=setups[id],tray=shuffle(rows.map(x=>x[1]));placed=Array(rows.length).fill(null);selected=null;root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="asP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">AQA-style virtual arrangement</span></div></div><div class="tool-two"><div class="tool-panel"><span class="eyebrow">APPARATUS TRAY</span><h3>Choose a component</h3><div id="asTray" class="setup-tray">${tray.map(x=>`<button type="button" class="setup-part" data-part="${T.esc(x)}">${T.esc(x)}</button>`).join('')}</div><p class="tool-callout">Tap a component, then tap the slot where it belongs. On a real practical, follow your teacher/technician instructions and local risk assessment.</p>${id===2?'<div class="tool-feedback warn">Optics challenge: this app teaches diagram geometry and measurement only; it does not provide laser-use instructions.</div>':''}${id===12?'<div class="tool-feedback warn">Radiation challenge is simulation-only. It does not provide source handling, storage or access instructions.</div>':''}</div><div class="tool-panel"><h3>Build the setup</h3><div id="asBoard" class="setup-board">${rows.map((r,i)=>`<button type="button" class="setup-slot" data-slot="${i}"><small>${T.esc(r[0])}</small><b>${placed[i]?T.esc(placed[i]):'Place component'}</b></button>`).join('')}</div><div class="tool-actions"><button class="primary-btn" id="asCheck">Check setup</button><button class="secondary-btn" id="asReset">Reset</button></div><div id="asOut"></div></div></div>`;
 bind(tray);
 }
 function bind(tray){root.querySelector('#asP').onchange=e=>{id=+e.target.value;draw();};root.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{selected=b.dataset.part;root.querySelectorAll('[data-part]').forEach(x=>x.classList.toggle('active',x===b));});root.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{if(!selected)return;const i=+b.dataset.slot,old=placed[i];placed[i]=selected;if(old){const ob=[...root.querySelectorAll('[data-part]')].find(x=>x.dataset.part===old);if(ob)ob.disabled=false;}const pb=[...root.querySelectorAll('[data-part]')].find(x=>x.dataset.part===selected);if(pb)pb.disabled=true;b.querySelector('b').textContent=selected;selected=null;root.querySelectorAll('[data-part]').forEach(x=>x.classList.remove('active'));});root.querySelector('#asReset').onclick=draw;root.querySelector('#asCheck').onclick=()=>{const rows=setups[id],ok=rows.every((r,i)=>placed[i]===r[1]);root.querySelectorAll('[data-slot]').forEach((b,i)=>b.classList.toggle('correct',placed[i]===rows[i][1]));root.querySelector('#asOut').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'Setup correctly arranged':'Some components are in the wrong positions'}</b>${ok?`<table class="tool-table"><tbody>${rows.map(r=>`<tr><th>${T.esc(r[0])}</th><td><b>${T.esc(r[1])}</b><br>${T.esc(r[2])}</td></tr>`).join('')}</tbody></table>`:'<p>Use the measurement purpose of each slot to decide where each component belongs.</p>'}</div>`;if(ok)T.mark(22,true);};}
 draw();}
T.register(22,{title:'Apparatus Setup Challenge',kicker:'BUILD THE AQA-STYLE GEOMETRY',description:'Place the practical-specific apparatus into the correct measurement arrangement.',icon:'🧰',render,decorate({addPracticalButton,open}){addPracticalButton('setup-challenge','Setup challenge',()=>open(22,{practicalId:current?.id||state.last}));}});
})();