(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
function r(a,b){return a+Math.random()*(b-a)}
const makers={
1:()=>{const L=r(.45,.85),Tn=r(5,12),mu=r(.0012,.003),f=(1/(2*L))*Math.sqrt(Tn/mu);return{target:'mass per unit length μ',unit:'kg m⁻¹',answer:mu,prompt:`A string of vibrating length ${L.toFixed(3)} m is under ${Tn.toFixed(2)} N tension and resonates at ${f.toFixed(2)} Hz in the fundamental mode. Determine μ.`,work:'Use f=(1/2L)√(T/μ), then rearrange for μ.'}},
2:()=>{const D=r(1.2,2),s=r(.2,.5)*1e-3,lam=r(480,650)*1e-9,w=lam*D/s;return{target:'wavelength λ',unit:'m',answer:lam,prompt:`Young-slits data: screen distance D=${D.toFixed(3)} m, slit separation s=${(s*1e3).toFixed(3)} mm, fringe spacing w=${(w*1e3).toFixed(3)} mm. Determine λ.`,work:'Use w=λD/s and convert all lengths consistently.'}},
3:()=>{const h=r(.5,1.5),g=r(9.72,9.90),t=Math.sqrt(2*h/g);return{target:'gravitational field strength g',unit:'m s⁻²',answer:g,prompt:`A mean fall time of ${t.toFixed(4)} s is measured through a fall height h=${h.toFixed(3)} m. Determine g.`,work:'Use h=½gt².'}},
4:()=>{const F=r(15,35),L=r(1.5,2.5),d=r(.35,.55)*1e-3,E=r(1.7,2.1)*1e11,A=Math.PI*d*d/4,ext=F*L/(A*E);return{target:'Young modulus E',unit:'Pa',answer:E,prompt:`A wire has L=${L.toFixed(3)} m, diameter ${(d*1e3).toFixed(3)} mm. A force ${F.toFixed(2)} N produces extension ${(ext*1e3).toFixed(3)} mm. Determine E.`,work:'Find A=πd²/4, stress=F/A and strain=ΔL/L; E=stress/strain.'}},
5:()=>{const L=r(.5,1.2),d=r(.35,.6)*1e-3,rho=r(3.5,6.2)*1e-7,A=Math.PI*d*d/4,R=rho*L/A;return{target:'resistivity ρ',unit:'Ω m',answer:rho,prompt:`A wire of length ${L.toFixed(3)} m and diameter ${(d*1e3).toFixed(3)} mm has resistance ${R.toFixed(3)} Ω. Determine its resistivity.`,work:'Use ρ=RA/L with A=πd²/4.'}},
6:()=>{const e=r(1.35,1.65),ri=r(.18,.65),I1=r(.18,.35),I2=r(.65,.95),V1=e-I1*ri,V2=e-I2*ri;return{target:'internal resistance r',unit:'Ω',answer:ri,prompt:`Two points from a V–I graph are (I=${I1.toFixed(3)} A, V=${V1.toFixed(3)} V) and (I=${I2.toFixed(3)} A, V=${V2.toFixed(3)} V). Determine the magnitude of the internal resistance.`,work:'For V=ε−Ir, the gradient ΔV/ΔI=−r.'}},
7:()=>{const m=r(.25,.7),k=r(6,12),period=2*Math.PI*Math.sqrt(m/k);return{target:'spring constant k',unit:'N m⁻¹',answer:k,prompt:`A mass ${m.toFixed(3)} kg has mean period ${period.toFixed(3)} s on a spring. Determine k.`,work:'Use T=2π√(m/k) and rearrange.'}},
8:()=>{const p1=r(85,98),V1=r(22,35),p2=r(65,82),V2=p1*V1/p2;return{target:'new gas volume V₂',unit:'mL',answer:V2,prompt:`For a fixed gas sample at constant temperature, P₁=${p1.toFixed(1)} kPa and V₁=${V1.toFixed(2)} mL. The pressure changes to P₂=${p2.toFixed(1)} kPa. Determine V₂.`,work:'Use P₁V₁=P₂V₂. This is data processing for the Boyle-law model.'}},
9:()=>{const R=r(70,180)*1000,C=r(60,220)*1e-6,tau=R*C;return{target:'capacitance C',unit:'F',answer:C,prompt:`A discharge graph gives time constant τ=${tau.toFixed(3)} s. The resistor is ${(R/1000).toFixed(1)} kΩ. Determine C.`,work:'Use τ=RC and convert kΩ to Ω.'}},
10:()=>{const I=r(1.2,3),L=r(.035,.08),B=r(.18,.48),F=B*I*L;return{target:'flux density B',unit:'T',answer:B,prompt:`A wire carrying ${I.toFixed(3)} A has active length ${L.toFixed(4)} m in a field. The measured magnetic force is ${(F*1000).toFixed(3)} mN. Determine B.`,work:'Use F=BIL and convert mN to N.'}},
11:()=>{const th=r(15,65),K=r(.6,1.8),emf=K*Math.cos(th*Math.PI/180);return{target:'angular proportionality constant K',unit:'V',answer:K,prompt:`At θ=${th.toFixed(1)}°, the induced emf amplitude is ${emf.toFixed(3)} V and the model is E=K cosθ. Determine K.`,work:'Use K=E/cosθ with the calculator in degree mode.'}},
12:()=>{const k=r(3500,6000),r0=r(12,28),rate=k/(r0*r0);return{target:'virtual distance r',unit:'cm',answer:r0,prompt:`Simulation-only inverse-square model: corrected virtual count rate=${rate.toFixed(2)} min⁻¹ and model constant k=${k.toFixed(0)} min⁻¹ cm². Determine virtual distance r.`,work:'Use rate=k/r² and rearrange. This is a virtual data exercise only.'}}
};
function render(root,opts={}){let id=+(opts.practicalId||state.last||1),q=makers[id]();
 function draw(){root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="usP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Hidden target</span></div></div><div class="tool-two"><div class="tool-panel"><span class="eyebrow">UNKNOWN RESULT</span><h3>Determine ${T.esc(q.target)}</h3><p>${T.esc(q.prompt)}</p><div class="formula-box">${T.esc(q.work)}</div>${id===12?'<div class="tool-feedback warn">Simulation-only data task. No radiation-source handling is included.</div>':''}<textarea id="usWorking" rows="7" placeholder="Show rearrangement, substitution, units and intermediate working…"></textarea></div><div class="tool-panel"><h3>Your result</h3><label><input id="usAnswer" type="number" step="any" inputmode="decimal"> <b>${T.esc(q.unit)}</b></label><div class="tool-actions"><button class="primary-btn" id="usCheck">Check result</button><button class="secondary-btn" id="usNew">New unknown</button></div><div id="usOut"></div><div class="tool-callout">Keep extra figures during the calculation, then round the final result to a precision justified by the measurements.</div></div></div>`;root.querySelector('#usP').onchange=e=>{id=+e.target.value;q=makers[id]();draw();};root.querySelector('#usNew').onclick=()=>{q=makers[id]();draw();};root.querySelector('#usCheck').onclick=()=>{const a=+root.querySelector('#usAnswer').value,frac=Math.abs(a-q.answer)/(Math.abs(q.answer)||1),ok=Number.isFinite(a)&&frac<=.025;root.querySelector('#usOut').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'Result accepted':'Check the rearrangement and unit conversions'}</b><p>${ok?`Expected result ≈ ${q.answer.toPrecision(4)} ${T.esc(q.unit)}.`:'Your value should normally be within about 2.5% of the hidden result. Check SI prefixes, powers and the graph-derived quantity used.'}</p></div>`;if(ok)T.mark(24,true);};}
 draw();}
T.register(24,{title:'Unknown Sample / Target Result',kicker:'DETERMINE THE HIDDEN QUANTITY',description:'Use practical measurements to determine an unknown physical quantity without seeing the answer first.',icon:'🎯',render,decorate({addPracticalButton,open}){addPracticalButton('unknown-target','Unknown target',()=>open(24,{practicalId:current?.id||state.last}));}});
})();