(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
function entry(id){return state.labBook?.[String(id)]||{};}
function words(s){return String(s||'').trim().split(/\s+/).filter(Boolean).length;}
function inspect(id){const e=entry(id),checks=[];const add=(name,ok,msg)=>checks.push({name,ok,msg});
 add('Aim',words(e.aim)>=8,words(e.aim)>=8?'Aim is specific enough to identify the investigation.':'Write a specific aim naming the relationship or quantity being investigated.');
 add('Set-up record',words(e.setup)>=20,words(e.setup)>=20?'Set-up description has useful detail.':'Add the actual arrangement, key reference points, meter/settings/ranges and measurement geometry.');
 add('Variables',words(e.independent)>=2&&words(e.dependent)>=2&&words(e.controls)>=5,'Name independent and dependent variables and explain how important controls were kept constant.');
 add('Method',words(e.method)>=35,words(e.method)>=35?'Method has enough detail to follow.':'Expand the method: sequence, settings, repeats, how readings were taken and any changes made.');
 add('Safety',words(e.safety)>=12,words(e.safety)>=12?'Safety notes are specific.':'Link safety controls to the actual apparatus/hazards used, rather than a generic sentence.');
 const rows=Array.isArray(e.rawRows)?e.rawRows:[];const filled=rows.filter(r=>Array.isArray(r)&&r.filter(x=>String(x||'').trim()).length>=2).length;add('Raw data',filled>=4,filled>=4?`${filled} usable data rows recorded.`:'Aim for enough raw readings to reveal the relationship; four is a minimum check, not a universal target.');
 const unc=Array.isArray(e.uncRows)?e.uncRows:[];const goodUnc=unc.filter(r=>r&&words(r.q)>=1&&words(r.uncertainty)>=1).length;add('Uncertainty',goodUnc>=2,goodUnc>=2?'Multiple measurement uncertainties are documented.':'Record uncertainty/resolution for the measurements that matter most and explain how they affect the result.');
 add('Calculations',words(e.calculations)>=20,words(e.calculations)>=20?'Calculation record contains working.':'Show equations, substitutions, units and enough working for another reader to follow.');
 add('Graph processing',words(e.graph)>=18&&words(e.graphResult)>=3,'State axes with units, transformation, best-fit method, gradient/intercept and the physical quantity obtained.');
 add('Conclusion',words(e.conclusion)>=25,words(e.conclusion)>=25?'Conclusion has enough space to connect evidence and physics.':'Quote the measured result/trend, units, uncertainty where relevant and compare with the expected relationship.');
 const ev=Array.isArray(e.evalRows)?e.evalRows:[];const goodEv=ev.filter(r=>r&&words(r.limitation)>=2&&words(r.effect)>=3&&words(r.improvement)>=4).length;add('Evaluation',goodEv>=2,goodEv>=2?'At least two linked limitation → effect → improvement chains are present.':'Add at least two specific limitation → effect on data/result → targeted improvement chains.');
 add('Evidence & reflection',words(e.reflection)>=18,'Reflect on a practical skill, evidence of improvement and what you would change next time.');
 return checks;}
function render(root,opts={}){let id=+(opts.practicalId||document.querySelector('#lbSelect')?.value||state.last||1);
 function draw(){const p=T.practical(id),c=inspect(id),n=c.filter(x=>x.ok).length,pc=Math.round(n/c.length*100);root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Lab Book practical</b> <select id="lbcP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">${n}/${c.length} checks met</span></div><div class="tool-meter" style="margin-top:12px"><i style="width:${pc}%"></i></div></div><div class="tool-two"><div class="tool-panel"><h3>Record check</h3>${c.map(x=>`<div class="tool-feedback ${x.ok?'':'warn'}"><b>${x.ok?'✓':'△'} ${T.esc(x.name)}</b><p>${T.esc(x.msg)}</p></div>`).join('')}</div><div class="tool-panel"><h3>Next improvements</h3><ol>${c.filter(x=>!x.ok).slice(0,5).map(x=>`<li><b>${T.esc(x.name)}:</b> ${T.esc(x.msg)}</li>`).join('')||'<li>Your structural checks are complete. Now read the record for scientific clarity, significant figures, units and whether claims are actually supported by the data.</li>'}</ol><div class="tool-callout">This checker evaluates structure and evidence quality heuristically. It does not award the Practical Endorsement or replace teacher judgement.</div><div class="tool-actions"><button class="primary-btn" id="lbcRecheck">Re-check saved entry</button><button class="secondary-btn" id="lbcOpen">Open Lab Book</button></div></div></div>`;root.querySelector('#lbcP').onchange=e=>{id=+e.target.value;draw();};root.querySelector('#lbcRecheck').onclick=draw;root.querySelector('#lbcOpen').onclick=()=>navigate('labbook');if(pc>=80)T.mark(3,true);}
 draw();}
T.register(3,{title:'Lab Book Checker',kicker:'RECORD QUALITY',description:'Check the saved record for method, data, uncertainty, graphing, conclusion and linked evaluation.',icon:'✅',render,decorate({addLabButton,open}){addLabButton('checker','Check my record',()=>open(3,{practicalId:+document.querySelector('#lbSelect')?.value||state.last}));}});
})();