(()=>{
'use strict';
const T=window.PracticalTools;if(!T)return;
const graph={1:'Plot resonant frequency f against 1/L.',2:'Use the interference relationship for the selected mode and process fringe spacing or sinθ consistently.',3:'Plot h against t²; gradient = g/2.',4:'Plot stress against strain in the elastic region.',5:'Plot R against L; gradient = ρ/A.',6:'Plot terminal p.d. V against current I; intercept = emf and gradient = −r.',7:'Plot T² against L for the pendulum or T² against m for the spring.',8:'Boyle: plot 1/V against P. Charles: use absolute temperature in kelvin.',9:'For discharge, plot ln(V) against t so gradient = −1/RC.',10:'Plot F against the variable being changed while holding the other two in F=BIL constant.',11:'Plot induced emf amplitude against the appropriate angular factor for the defined angle.',12:'Plot corrected count rate against 1/r².'};
const repeatReason={1:'Resonance judgement has scatter, so repeat the frequency judgement.',2:'Repeat position/span measurements to reduce reading scatter.',3:'Repeat electronic fall times at each height and use a mean.',4:'Take repeated diameter measurements and repeat extension readings where practical.',5:'Repeat diameter readings and paired V/I readings while limiting heating.',6:'Take several paired I,V readings across a wide safe range.',7:'Time many oscillations and repeat the timing.',8:'Repeat settled syringe/temperature readings; note friction or thermal lag.',9:'Collect many time-voltage points and repeat a run if switching/data capture was poor.',10:'Repeat balance changes after returning to zero/reference.',11:'Repeat oscilloscope amplitude readings at selected angles.',12:'Use suitably long count times and repeats because count variation is statistical.'};
function makeQuestions(p){const app=p.apparatus.map(a=>a[0]);const decoys=['Stopwatch only','Thermometer only','Measuring cylinder','Spring balance'];const correctApp=app.slice(0,Math.min(3,app.length));return[
 {title:'Choose the essential apparatus',prompt:'Which group best represents the core apparatus for this investigation?',choices:[correctApp.join(' + '),[correctApp[0],decoys[0],decoys[1]].join(' + '),decoys.slice(0,3).join(' + ')],answer:0,why:`The AQA-style setup for Practical ${p.id} centres on ${correctApp.join(', ')}. Other equipment may support the measurement, but this group defines the core investigation.`},
 {title:'Identify the variables',prompt:'What should a strong variables plan do?',choices:['Name what is changed, what is measured, and what is controlled with how it is controlled.','List only the independent variable.','Call every fixed apparatus item a control variable.'],answer:0,why:'A useful practical record distinguishes independent, dependent and genuinely controlled quantities, and explains how important controls are kept constant.'},
 {title:'Plan the measurements',prompt:'Which measurement strategy gives the strongest evidence?',choices:['Use a useful range, sensible intervals, units in headings and enough points to reveal the relationship.','Take one reading at the default setting.','Change several variables together to save time.'],answer:0,why:'A broad, controlled data range supports graphing, identification of anomalies and a more reliable gradient/intercept.'},
 {title:'Decide on repeats',prompt:'What should you do about repeats?',choices:[repeatReason[p.id]||'Repeat measurements where scatter or judgement contributes uncertainty.','Never repeat because the apparatus is digital.','Repeat only the final point.'],answer:0,why:repeatReason[p.id]||'Repeats reveal scatter and improve the reliability of a mean.'},
 {title:'Choose the processing',prompt:'Which processing is appropriate for this practical?',choices:[graph[p.id],'Plot the two raw columns on any axes and force a straight line.','Calculate a percentage for every row instead of using the physics relationship.'],answer:0,why:graph[p.id]}
];}
function render(root,opts={}){let id=+(opts.practicalId||state.last||1),p=T.practical(id),qs=makeQuestions(p),step=0,score=0,answers=[];
 function draw(){const q=qs[step];root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="pcPractical">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Decision ${step+1} / ${qs.length}</span></div></div><div class="tool-panel"><span class="eyebrow">${T.esc(q.title.toUpperCase())}</span><h3>${T.esc(q.prompt)}</h3><div id="pcChoices">${q.choices.map((c,i)=>`<label class="tool-choice"><input type="radio" name="pc" value="${i}"> ${T.esc(c)}</label>`).join('')}</div><div id="pcFeedback"></div><div class="tool-actions"><button class="primary-btn" id="pcCheck">Check decision</button>${step?'<button class="secondary-btn" id="pcPrev">← Previous</button>':''}</div></div><div class="tool-panel"><h3>Coach principle</h3><p>${T.esc(p.short)}</p><div class="tool-callout">Do not copy a method blindly: be able to explain why each measurement or control is needed.</div></div>`;
 root.querySelector('#pcPractical').onchange=e=>{id=+e.target.value;p=T.practical(id);qs=makeQuestions(p);step=0;score=0;answers=[];draw();};
 root.querySelector('#pcPrev')?.addEventListener('click',()=>{step--;draw();});
 root.querySelector('#pcCheck').onclick=()=>{const pick=root.querySelector('input[name=pc]:checked');if(!pick)return;const n=+pick.value,ok=n===q.answer;if(answers[step]===undefined&&ok)score++;answers[step]=n;root.querySelector('#pcFeedback').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'Good decision':'Reconsider this choice'}</b><p>${T.esc(q.why)}</p></div><div class="tool-actions">${step<qs.length-1?'<button class="primary-btn" id="pcNext">Next decision →</button>':'<button class="primary-btn" id="pcFinish">Finish coach</button>'}</div>`;root.querySelector('#pcNext')?.addEventListener('click',()=>{step++;draw();});root.querySelector('#pcFinish')?.addEventListener('click',()=>{T.mark(1,true);root.innerHTML=`<div class="tool-panel"><span class="eyebrow">COACH COMPLETE</span><h3>${score} / ${qs.length} first-time decisions correct</h3><p>You worked through apparatus, variables, measurement strategy, repeats and processing for Practical ${id}.</p><div class="tool-actions"><button class="primary-btn" id="pcAgain">Try another practical</button></div></div>`;root.querySelector('#pcAgain').onclick=()=>{step=0;score=0;answers=[];draw();};});};
 }
 draw();}
T.register(1,{title:'Practical Coach',kicker:'GUIDED DECISION MODE',description:'Build the method by choosing apparatus, variables, measurements, repeats and processing.',icon:'🧭',render,decorate({addPracticalButton,open}){addPracticalButton('coach','Coach mode',()=>open(1,{practicalId:current?.id||state.last}));}});
})();