(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const cases={
1:{method:'Change the vibrating length and tension together, take one resonance reading at each setting, then plot frequency against length.',faults:['Two independent variables are changed together.','One resonance judgement per setting gives weak evidence of repeatability.','The graph choice does not match the linearised relationship for fixed tension.'],fix:'Change one quantity at a time, repeat resonance judgement and use the equation to choose a justified graph.'},
2:{method:'Measure the position of one bright fringe only and use it as the fringe spacing. Move the screen between readings without recording the new distance.',faults:['One fringe position is not the same as fringe spacing.','Measuring several fringes would reduce fractional reading uncertainty.','Screen distance is being changed without being recorded/controlled.'],fix:'Measure a multi-fringe span, define the geometry clearly and record the screen distance used.'},
3:{method:'Use only two drop heights, record one time at each, and calculate g from 2h/t.',faults:['Two heights are insufficient for a strong graph.','Timing should be repeated at each height.','The correct free-fall linearisation uses h against t², not 2h/t.'],fix:'Use several heights, repeat timings and obtain g from the h versus t² gradient.'},
4:{method:'Measure the wire diameter once, add loads beyond the elastic region and use extension/force as Young modulus.',faults:['A single diameter reading is weak because area depends on d².','Loads should remain in the elastic region for this analysis.','Young modulus is stress/strain, not extension/force directly.'],fix:'Repeat diameter measurements, stay in the elastic region and calculate stress and strain before finding the gradient.'},
5:{method:'Increase wire length and supply voltage together. Leave the current flowing continuously and use the nominal wire diameter from the packet.',faults:['Two variables are changed together.','Continuous current can heat the wire and change its resistance.','Diameter should be measured rather than assumed.'],fix:'Vary length only, limit heating and measure diameter with an appropriate small-distance instrument.'},
6:{method:'Take terminal voltage readings without measuring current, leave the switch closed between readings and estimate emf from the largest voltage seen.',faults:['Each voltage needs a matching current value.','Leaving current flowing can change cell conditions unnecessarily.','Emf should come from the V–I relationship/intercept, not simply the largest observed terminal voltage.'],fix:'Record paired I,V values, open the switch between readings and use a best-fit graph.'},
7:{method:'Time one oscillation, use a large pendulum angle and change both length and bob mass together.',faults:['Timing one cycle gives large fractional timing uncertainty.','Large pendulum amplitude weakens the simple small-angle model.','Two variables are changed together.'],fix:'Time many cycles, keep pendulum amplitude small and vary one quantity at a time.'},
8:{method:'For Boyle’s law, push the syringe plunger by hand to different positions and assume atmospheric pressure is unchanged. For Charles’s law, record immediately after changing water temperature.',faults:['The AQA hanging-mass geometry should determine the applied force/pressure change.','Pressure must be calculated for the Boyle setup rather than assumed constant.','Charles-law readings need thermal equilibrium.'],fix:'Use the syringe-and-hanging-mass pressure model and allow the gas to settle/thermalise before reading.'},
9:{method:'Record only the start and end capacitor voltages and fit a straight line to V against t.',faults:['Two points do not describe the exponential response.','Raw V against t is not the required log-linear analysis for discharge.','The time constant cannot be determined reliably from a forced straight line through raw exponential data.'],fix:'Record many time-voltage points and use ln(V) against t for the discharge analysis.'},
10:{method:'Change current and active wire length at the same time, read the absolute balance mass instead of the change, and ignore the sign/direction of the force.',faults:['Only one factor in F=BIL should be changed at a time.','The measurement is the balance change from a reference reading.','Force direction/sign contains useful information and should be treated consistently.'],fix:'Hold two variables fixed, use balance change and keep the force-direction convention clear.'},
11:{method:'Rotate the search coil continuously while reading the oscilloscope and change the field frequency at the same time.',faults:['The coil angle should be set and held for each amplitude reading.','Changing frequency introduces a second changing variable.','A stable oscilloscope amplitude should be read at defined angles.'],fix:'Set a chosen angle, hold it, keep other field conditions fixed and record the signal amplitude.'},
12:{method:'In the simulation, use one short virtual count at each distance, ignore background and judge inverse square from the nearest two points.',faults:['Short counts have large fractional statistical variation.','Background must be accounted for in the model analysis.','Two near points are insufficient to test the inverse-square relationship.'],fix:'Simulation-only: use several distances, longer/repeated virtual counts and background-corrected rates.'}
};
function render(root,opts={}){let id=+(opts.practicalId||state.last||1);
 function draw(){const c=cases[id],pool=[...c.faults,'The title is too short.','Every digital reading must automatically be exact.','The graph should always be forced through the origin.'].sort(()=>Math.random()-.5);root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="edP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Find all 3 method faults</span></div></div><div class="tool-two"><div class="tool-panel"><span class="eyebrow">FLAWED METHOD</span><h3>What is wrong with this plan?</h3><p class="method-error-case">${T.esc(c.method)}</p><div class="tool-callout">Select the three problems that would most directly weaken the practical evidence.</div></div><div class="tool-panel"><h3>Identify the faults</h3>${pool.map((x,i)=>`<label class="tool-choice"><input type="checkbox" data-ed="${i}"> ${T.esc(x)}</label>`).join('')}<div class="tool-actions"><button class="primary-btn" id="edCheck">Check faults</button></div><div id="edOut"></div></div></div>`;root.querySelector('#edP').onchange=e=>{id=+e.target.value;draw();};root.querySelector('#edCheck').onclick=()=>{const picked=[...root.querySelectorAll('[data-ed]:checked')].map(x=>pool[+x.dataset.ed]),hits=picked.filter(x=>c.faults.includes(x)),ok=hits.length===3&&picked.length===3;root.querySelector('#edOut').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'All three method problems identified':'Keep diagnosing'}</b><p>${ok?T.esc(c.fix):`You selected ${hits.length} of the 3 practical problems. Focus on variable control, measurement strategy, repeats and data processing.`}</p>${ok?`<ul>${c.faults.map(x=>`<li>${T.esc(x)}</li>`).join('')}</ul>`:''}</div>`;if(ok)T.mark(23,true);};}
 draw();}
T.register(23,{title:'Method Error Detective',kicker:'DIAGNOSE A FLAWED METHOD',description:'Find practical-specific design, measurement and processing mistakes before they reach the lab book.',icon:'🕵️',render,decorate({addPracticalButton,open}){addPracticalButton('error-detective','Method detective',()=>open(23,{practicalId:current?.id||state.last}));}});
})();