(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const G={1:['resonance','length','repeat','1/L','frequency'],2:['fringes','several','distance','sin','alignment'],3:['release','height','repeat','t²','gradient'],4:['diameter','micrometer','stress','strain','elastic'],5:['diameter','heating','R','length','gradient'],6:['switch','current','voltage','intercept','gradient'],7:['oscillations','small angle','T²','length','repeat'],8:['syringe','mass','pressure','kelvin','equilibrium'],9:['capacitor','switch','time','ln','RC'],10:['balance','active length','current','force','gradient'],11:['angle','coil','oscilloscope','amplitude','cos'],12:['background','count time','random','1/r²','uncertainty']};
const stem={1:'stationary waves',2:'interference/diffraction',3:'free fall',4:'Young modulus',5:'resistivity',6:'emf/internal resistance',7:'simple harmonic motion',8:'gas laws',9:'capacitor charge/discharge',10:'magnetic force',11:'search-coil induction',12:'inverse-square radiation simulation'};
function questions(id){const k=G[id];return[
 {m:3,q:`A student is preparing the ${stem[id]} investigation. Describe three features of a suitable measurement method that would improve the quality of the evidence.`,keys:k.slice(0,3),model:`A strong answer should identify practical-specific measurements/controls, include a sensible repeat or range strategy, and explain how readings are taken consistently.`},
 {m:4,q:'Explain how the student should process the measurements using a graph, including what the gradient or intercept would tell them where relevant.',keys:k.slice(2,5),model:`State the transformed axes used for this practical, use a best-fit line, and link the gradient/intercept to the physical quantity or relationship being tested.`},
 {m:3,q:'Identify one important limitation or uncertainty in this experiment and explain a specific improvement that would reduce its effect.',keys:[k[0],k[1],'repeat'],model:'Name a real source of uncertainty/limitation, state its effect on the data/result, and give an improvement that directly addresses that cause.'}
 ];}
function render(root,opts={}){let id=+(opts.practicalId||state.last||1),qi=0;
 function draw(){const p=T.practical(id),qs=questions(id),q=qs[qi];root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="eqP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Question ${qi+1}/${qs.length}</span><span class="tool-pill">${q.m} marks</span></div></div><div class="tool-panel"><span class="eyebrow">ORIGINAL AQA-STYLE PRACTICAL QUESTION</span><h3>${T.esc(q.q)}</h3><textarea id="eqAnswer" rows="9" placeholder="Write your answer here..."></textarea><div class="tool-actions"><button class="primary-btn" id="eqCheck">Check key ideas</button>${qi?'<button class="secondary-btn" id="eqPrev">← Previous</button>':''}${qi<qs.length-1?'<button class="secondary-btn" id="eqNext">Next →</button>':''}</div><div id="eqFeedback"></div></div>`;
 root.querySelector('#eqP').onchange=e=>{id=+e.target.value;qi=0;draw();};root.querySelector('#eqPrev')?.addEventListener('click',()=>{qi--;draw();});root.querySelector('#eqNext')?.addEventListener('click',()=>{qi++;draw();});root.querySelector('#eqCheck').onclick=()=>{const a=root.querySelector('#eqAnswer').value.toLowerCase(),hits=q.keys.filter(k=>a.includes(String(k).toLowerCase()));const approx=Math.min(q.m,Math.max(0,hits.length));let reveal=T.suite.teacher?.hideHints?'':'<button class="secondary-btn" id="eqReveal">Show marking-point guidance</button>';root.querySelector('#eqFeedback').innerHTML=`<div class="tool-feedback"><b>Key-idea check: about ${approx}/${q.m}</b><p>Detected ideas: ${hits.length?hits.map(T.esc).join(', '):'none of the practical-specific key ideas yet'}.</p><small>This is a keyword-based revision check, not official exam marking.</small></div>${reveal}`;root.querySelector('#eqReveal')?.addEventListener('click',()=>{root.querySelector('#eqFeedback').innerHTML+=`<div class="tool-callout"><b>Model guidance</b><p>${T.esc(q.model)}</p></div>`;});if(qi===qs.length-1&&approx>=1)T.mark(7,true);};}
 draw();}
T.register(7,{title:'Exam Question mode',kicker:'PRACTICAL EXAM PRACTICE',description:'Answer original practical questions on method, graph processing, uncertainty and evaluation.',icon:'📝',render,decorate({addPracticalButton,open}){addPracticalButton('exam-mode','Exam questions',()=>open(7,{practicalId:current?.id||state.last}));}});
})();