(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const H={
1:['Think about which quantities must stay fixed if you are testing length.','Start from f=(1/2L)√(T/μ). Which transformed x-variable makes a straight line?','Use 1/L on the x-axis and f on the y-axis; repeat resonance judgements because identifying the maximum introduces scatter.'],
2:['Identify whether you are using Young slits or a grating before choosing an equation.','Young slits uses fringe spacing; a grating uses diffraction order and angle.','Young: w=λD/s. Grating: d sinθ=nλ. Measure multiple fringes / symmetric orders where possible.'],
3:['The ball is released from rest, so use the constant-acceleration displacement equation.','h is proportional to t², not t.','Plot h against t²; gradient=g/2. Repeat each height and use consistent distance reference points.'],
4:['Young modulus links stress to strain in the elastic region.','You need wire area from diameter, and strain needs original length.','Plot stress against strain; gradient=E. Repeated micrometer readings matter because area depends on d².'],
5:['Start from R=ρL/A.','If wire material/diameter are fixed, R is proportional to L.','Plot R against L; gradient=ρ/A, so ρ=gradient×A. Limit heating and measure diameter carefully.'],
6:['Terminal p.d. falls as current increases because of lost volts inside the cell.','Rearrange the source equation into y=mx+c form.','V=ε−Ir: plot V against I; intercept=ε and gradient=−r. Open the switch between readings.'],
7:['Square the period equations to linearise them.','Pendulum: T²∝L. Spring: T²∝m.','Plot T² against L or m. Time many oscillations so reaction time is a smaller percentage of total time.'],
8:['Treat Boyle and Charles as different investigations with different controls.','Boyle needs pressure from hanging force/area; Charles needs absolute temperature.','Boyle AQA hanging-mass geometry: P=Patm−mg/A and test 1/V against P. Charles: convert °C to K and wait for thermal equilibrium.'],
9:['The raw V-t curve is exponential, not linear.','Take the natural log of the discharge relationship.','lnV=lnV0−t/RC, so gradient=−1/RC. Low-voltage points can have larger relative uncertainty.'],
10:['Only one of B, I and active length L should change at a time.','Convert balance change to force before graphing.','F=BIL. The active length is only the conductor inside the magnetic field; choose axes so the gradient contains the two controlled quantities.'],
11:['For each reading, the coil should be held at a defined angle.','Flux linkage depends on an angular factor and the oscilloscope shows emf amplitude.','Plot emf amplitude against the appropriate trigonometric factor for the angle convention used, keeping field/frequency and coil geometry controlled.'],
12:['Start by correcting for background and remember counts vary statistically.','Inverse-square means corrected rate should be proportional to 1/r².','Plot corrected simulated count rate against 1/r². Longer count times reduce fractional statistical uncertainty. This remains simulation-only.']};
function render(root,opts={}){let id=+(opts.practicalId||state.last||1),level=0;function draw(){const p=T.practical(id),locked=!!T.suite.teacher?.hideHints;root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="phP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Progressive hints</span></div></div><div class="tool-panel"><span class="eyebrow">TRY BEFORE REVEALING</span><h3>${T.esc(p.title)}</h3>${locked?'<div class="tool-feedback warn"><b>Hints hidden in Teacher Mode</b><p>Work from the practical, graph and Lab Book prompts instead.</p></div>':`<p>Reveal only as much help as you need. Each level becomes more specific.</p><div id="phHints">${H[id].slice(0,level).map((h,i)=>`<div class="tool-feedback"><b>Hint ${i+1}</b><p>${T.esc(h)}</p></div>`).join('')||'<div class="tool-callout">No hints revealed yet.</div>'}</div><div class="tool-actions">${level<3?'<button class="primary-btn" id="phReveal">Reveal next hint</button>':''}<button class="secondary-btn" id="phReset">Reset hints</button></div>`}</div><div class="tool-panel"><h3>Before the final hint, ask yourself</h3><ul><li>What is the equation behind this practical?</li><li>Which quantity should be changed and which must be controlled?</li><li>What transformation would create a straight-line graph?</li><li>What measurement is most likely to dominate uncertainty?</li></ul></div>`;root.querySelector('#phP').onchange=e=>{id=+e.target.value;level=0;draw();};root.querySelector('#phReveal')?.addEventListener('click',()=>{level++;if(level>=3)T.mark(14,true);draw();});root.querySelector('#phReset')?.addEventListener('click',()=>{level=0;draw();});}draw();}
T.register(14,{title:'Progressive hints',kicker:'SCAFFOLDED SUPPORT',description:'Reveal a small conceptual hint first, then stronger guidance only when you need it.',icon:'💡',render,decorate({addPracticalButton,open}){addPracticalButton('hints','Hints',()=>open(14,{practicalId:current?.id||state.last}));}});
})();