(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const labs=[
 {name:'Ruler & parallax',unit:'cm',make:()=>({v:+(2+Math.random()*15).toFixed(1),res:0.1}),prompt:'Read the marked length from the ruler. Record to the ruler resolution.',visual:o=>`<div style="padding:25px;background:linear-gradient(#f3ead0,#e7d7a9);border-radius:12px;font-family:monospace">0&nbsp;&nbsp;1&nbsp;&nbsp;2&nbsp;&nbsp;3&nbsp;&nbsp;4&nbsp;&nbsp;5&nbsp;&nbsp;... <b>pointer at ${o.v.toFixed(1)} cm</b></div>`},
 {name:'Micrometer',unit:'mm',make:()=>({v:+(0.25+Math.random()*0.7).toFixed(2),res:0.01}),prompt:'Enter the micrometer reading to 0.01 mm.',visual:o=>`<div class="tool-callout">Sleeve + thimble combine to give <b>${o.v.toFixed(2)} mm</b> in this virtual scale exercise. Hide the value with your hand/scroll and practise the precision convention.</div>`},
 {name:'Vernier scale',unit:'mm',make:()=>({v:+(4+Math.random()*16).toFixed(1),res:0.1}),prompt:'Enter the vernier reading to 0.1 mm.',visual:o=>`<div class="tool-callout">Main-scale position plus aligned vernier division corresponds to a virtual reading near ${Math.floor(o.v)} mm.</div>`},
 {name:'Analogue meter',unit:'V',make:()=>({v:+(1+Math.random()*8).toFixed(1),res:0.2}),prompt:'Read the pointer on a 0–10 V scale with 0.2 V minor divisions.',visual:o=>`<meter min="0" max="10" value="${o.v}" style="width:100%;height:45px"></meter><p>Scale: 0 to 10 V · minor division 0.2 V</p>`},
 {name:'Oscilloscope amplitude',unit:'V',make:()=>{let div=+(1+Math.random()*3).toFixed(1),scale=[0.2,0.5,1][Math.floor(Math.random()*3)];return {v:+(div*scale).toFixed(2),res:scale/5,div,scale}},prompt:'Calculate amplitude = vertical divisions × volts/div.',visual:o=>`<div class="tool-callout"><b>${o.div} vertical divisions</b> from centre line to peak<br><b>${o.scale} V/div</b></div>`},
 {name:'Balance conversion',unit:'N',make:()=>{let g=+(0.2+Math.random()*1.8).toFixed(2);return {v:+(g/1000*9.81).toFixed(4),res:.0001,g}},prompt:'Convert the balance change from grams to force using F = Δmg.',visual:o=>`<div class="tool-score">Δm = ${o.g.toFixed(2)} g</div>`},
 {name:'Uncertainty estimate',unit:'%',make:()=>{let v=+(10+Math.random()*40).toFixed(1),u=+(0.1+Math.random()*.5).toFixed(1);return {v:+(u/v*100).toFixed(2),res:.05,raw:v,u}},prompt:'Calculate percentage uncertainty = absolute uncertainty / measured value × 100.',visual:o=>`<div class="tool-callout">Measured value = ${o.raw}<br>Absolute uncertainty = ±${o.u}</div>`}
];
function render(root){let idx=0,score=0,o=labs[0].make();function draw(){const l=labs[idx];root.innerHTML=`<div class="tool-panel"><div class="tool-row"><span class="tool-pill">Mini-lab ${idx+1}/${labs.length}</span><b>${T.esc(l.name)}</b></div></div><div class="tool-two"><div class="tool-panel"><h3>${T.esc(l.prompt)}</h3>${l.visual(o)}<label><b>Your reading / calculation (${T.esc(l.unit)})</b><input id="msAnswer" type="number" step="any" inputmode="decimal"></label><div id="msOut"></div><div class="tool-actions"><button class="primary-btn" id="msCheck">Check</button><button class="secondary-btn" id="msNew">New value</button></div></div><div class="tool-panel"><h3>Measurement habits</h3><ul><li>Record units in the heading, not repeatedly in every data cell.</li><li>Match decimal places to the instrument resolution where appropriate.</li><li>State estimated uncertainty separately from the measured value.</li><li>Avoid parallax by viewing an analogue scale normally to the pointer/mark.</li><li>Do not add unjustified significant figures during later calculations.</li></ul></div></div>`;root.querySelector('#msNew').onclick=()=>{o=l.make();draw();};root.querySelector('#msCheck').onclick=()=>{const a=+root.querySelector('#msAnswer').value,tol=Math.max(l.res,Math.abs(o.v)*.01),ok=Number.isFinite(a)&&Math.abs(a-o.v)<=tol;if(ok)score++;root.querySelector('#msOut').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'Correct':'Check the scale/calculation'}</b><p>Expected about ${o.v} ${T.esc(l.unit)}. Resolution/tolerance matters more than adding extra decimal places.</p></div>${idx<labs.length-1?'<button class="primary-btn" id="msNext">Next mini-lab →</button>':'<button class="primary-btn" id="msFinish">Finish skills set</button>'}`;root.querySelector('#msNext')?.addEventListener('click',()=>{idx++;o=labs[idx].make();draw();});root.querySelector('#msFinish')?.addEventListener('click',()=>{T.mark(11,true);root.querySelector('#msFinish').textContent=`Completed ✓ (${score}/${labs.length})`;});};}draw();}
T.register(11,{title:'Measurement skills mini-labs',kicker:'READING INSTRUMENTS',description:'Practise ruler, micrometer, vernier, analogue meter, oscilloscope, balance and uncertainty readings.',icon:'📏',render});
})();