(()=>{
'use strict';
const T=window.PracticalTools;if(!T)return;
const plans={
1:{iv:'Vibrating length, tension or mass per unit length — one at a time',dv:'Resonant frequency',control:'Keep the other two wave variables and mode identification consistent',range:'Use a broad set of values that produces several measurable resonances',repeat:'Repeat resonance judgement and use several points',graph:'Use the linearised relationship for the variable changed'},
2:{iv:'Screen distance / slit geometry / diffraction order as appropriate to the selected investigation',dv:'Fringe spacing or diffraction angle/position',control:'Keep wavelength and the unused geometry fixed',range:'Use several measurable fringe spans or orders where available',repeat:'Repeat position/span measurements',graph:'Process using the relevant interference equation; define the angle/geometry clearly'},
3:{iv:'Drop height h',dv:'Fall time t',control:'Use the same ball, release method and timing reference points',range:'Use several well-spaced heights',repeat:'Repeat each electronic timing and calculate a mean',graph:'Plot h against t²; gradient = g/2'},
4:{iv:'Applied force / load',dv:'Extension',control:'Same wire, original length and cross-sectional area',range:'Remain within the elastic region and collect several loads',repeat:'Repeat diameter measurements; compare loading/unloading if used',graph:'Plot stress against strain; gradient = Young modulus'},
5:{iv:'Length of resistance wire',dv:'Resistance from V/I',control:'Same wire/material/diameter and minimise temperature change',range:'Use several well-spaced lengths',repeat:'Repeat diameter readings and check paired electrical readings',graph:'Plot R against L; gradient = ρ/A'},
6:{iv:'Current (changed via external resistance)',dv:'Terminal p.d.',control:'Same cell/battery and stable conditions',range:'Use a useful current range without unnecessary heating/drain',repeat:'Take several paired I,V readings',graph:'Plot V against I; intercept = emf, gradient = −r'},
7:{iv:'Pendulum length or oscillating mass',dv:'Period T',control:'Keep amplitude small and other system properties constant',range:'Use several lengths/masses spanning a useful range',repeat:'Time many oscillations and repeat totals',graph:'Plot T² against L or T² against m'},
8:{iv:'Boyle: hanging mass; Charles: temperature',dv:'Boyle: syringe volume; Charles: air-column length/volume',control:'Boyle: temperature; Charles: pressure and same gas sample',range:'Use several settled readings over a useful range',repeat:'Repeat settled readings and note friction/thermal lag',graph:'Boyle: relate P to 1/V; Charles: use absolute temperature'},
9:{iv:'Time after switching',dv:'Capacitor p.d.',control:'Keep R, C and supply/initial voltage fixed for a run',range:'Record enough times to capture the exponential change',repeat:'Repeat if switching/data capture was poor',graph:'For discharge, plot ln(V) against t; gradient = −1/RC'},
10:{iv:'Current, active wire length or flux density — one at a time',dv:'Force from balance change',control:'Hold the other two quantities and geometry constant',range:'Use several values including a sensible spread',repeat:'Repeat balance changes after returning to a reference reading',graph:'Plot F against the variable changed'},
11:{iv:'Angle between search coil and field direction',dv:'Induced emf amplitude',control:'Keep coil, field amplitude and frequency constant',range:'Use several angles across the useful angular range',repeat:'Repeat oscilloscope amplitude readings',graph:'Plot emf amplitude against the appropriate angular factor for the defined angle'},
12:{iv:'Distance r in the virtual inverse-square model',dv:'Background-corrected count rate',control:'Keep count time and virtual source/detector model fixed',range:'Use several distances; avoid relying on only near points',repeat:'Use long count times/repeats because counting variation is statistical',graph:'Plot corrected count rate against 1/r²'}
};
function choices(correct,wrong1,wrong2){return [correct,wrong1,wrong2].sort(()=>Math.random()-.5);}
function render(root,opts={}){
 let id=+(opts.practicalId||state.last||1),step=0,answers=[];
 function qs(){const p=plans[id];return[
  ['Independent variable',p.iv,'Change every adjustable control together','Use time as the independent variable for every practical'],
  ['Dependent variable',p.dv,'The apparatus list','The control variables'],
  ['Controls',p.control,'Nothing needs controlling if readings are repeated','Keep only the room lights constant'],
  ['Range',p.range,'Use the default setting only','Use two nearly identical values'],
  ['Repeats',p.repeat,'One reading is always enough with digital equipment','Repeat only the result closest to theory'],
  ['Graph / processing',p.graph,'Force a straight line through the raw columns regardless of theory','Choose axes after seeing which gives the highest R²']
 ];}
 function draw(){const p=T.practical(id),q=qs()[step],opts2=choices(q[1],q[2],q[3]);root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="plP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Planning decision ${step+1}/6</span></div></div><div class="tool-two"><div class="tool-panel"><span class="eyebrow">PLAN BEFORE YOU MEASURE</span><h3>${T.esc(q[0])}</h3><p>Choose the planning decision that would give the strongest evidence for this practical.</p><div id="plChoices">${opts2.map((x,i)=>`<label class="tool-choice"><input type="radio" name="pl" value="${i}"> ${T.esc(x)}</label>`).join('')}</div><div class="tool-actions"><button class="primary-btn" id="plCheck">Check plan</button>${step?'<button class="secondary-btn" id="plBack">← Previous</button>':''}</div><div id="plOut"></div></div><div class="tool-panel"><h3>Your planning record</h3><div class="planning-ledger">${qs().map((x,i)=>`<div class="planning-line ${i<answers.length?'done':''}"><span>${i+1}</span><div><b>${T.esc(x[0])}</b><small>${i<answers.length?T.esc(x[1]):'Complete this decision to reveal the recommended plan.'}</small></div></div>`).join('')}</div><div class="tool-callout">A strong plan should explain <b>why</b> the range, repeats and controls are suitable, not just name them.</div></div></div>`;
 root.querySelector('#plP').onchange=e=>{id=+e.target.value;step=0;answers=[];draw();};root.querySelector('#plBack')?.addEventListener('click',()=>{step--;draw();});
 root.querySelector('#plCheck').onclick=()=>{const pick=root.querySelector('input[name=pl]:checked');if(!pick)return;const chosen=opts2[+pick.value],ok=chosen===q[1];root.querySelector('#plOut').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'Good planning decision':'That would weaken the investigation'}</b><p>${T.esc(q[1])}</p></div><div class="tool-actions">${ok?(step<5?'<button class="primary-btn" id="plNext">Next planning decision →</button>':'<button class="primary-btn" id="plFinish">Finish plan</button>'):''}</div>`;if(ok){answers[step]=q[1];root.querySelector('#plNext')?.addEventListener('click',()=>{step++;draw();});root.querySelector('#plFinish')?.addEventListener('click',()=>{T.mark(17,true);root.innerHTML=`<div class="tool-panel"><span class="eyebrow">PLAN COMPLETE</span><h3>Practical ${id} planning framework</h3><table class="tool-table"><tbody>${qs().map(x=>`<tr><th>${T.esc(x[0])}</th><td>${T.esc(x[1])}</td></tr>`).join('')}</tbody></table><div class="tool-actions"><button class="primary-btn" id="plAgain">Plan another practical</button></div></div>`;root.querySelector('#plAgain').onclick=()=>{step=0;answers=[];draw();};});}};
 }
 draw();
}
T.register(17,{title:'Planning Challenge',kicker:'DESIGN THE INVESTIGATION',description:'Choose variables, controls, range, repeats, apparatus strategy and graph before measuring.',icon:'🗺️',render,decorate({addPracticalButton,open}){addPracticalButton('planning','Planning challenge',()=>open(17,{practicalId:current?.id||state.last}));}});
})();