(()=>{
'use strict';
const T=window.PracticalTools;if(!T)return;
const models={
1:{result:'Calculated / inferred wave quantity',rule:'For f ∝ T½ μ⁻½ L⁻¹, combine percentage contributions using the powers as multipliers.',qs:[['L','m',1],['T','N',.5],['μ','kg m⁻¹',.5]]},
2:{result:'Young-slits wavelength / spacing result',rule:'For λ = ws/D, percentage contributions from w, s and D add in a worst-case estimate.',qs:[['fringe spacing w','m',1],['slit separation s','m',1],['screen distance D','m',1]]},
3:{result:'g',rule:'For g = 2h/t², the timing percentage contribution is doubled.',qs:[['height h','m',1],['mean time t','s',2]]},
4:{result:'Young modulus E',rule:'E = FL/(AΔL) and A ∝ d², so diameter percentage uncertainty contributes twice.',qs:[['force F','N',1],['original length L','m',1],['diameter d','m',2],['extension ΔL','m',1]]},
5:{result:'resistivity ρ',rule:'ρ = RA/L and A ∝ d², so diameter is often an important uncertainty contribution.',qs:[['resistance R','Ω',1],['diameter d','m',2],['length L','m',1]]},
6:{result:'internal resistance / emf from graph',rule:'Use extreme acceptable gradients/intercepts. For r = |gradient|, the percentage uncertainty in r follows the gradient uncertainty.',qs:[['best-fit gradient magnitude','V A⁻¹',1],['gradient uncertainty','V A⁻¹',0]]},
7:{result:'g or spring constant',rule:'Pendulum: g ∝ L/T². Spring: k ∝ m/T². The period percentage contribution is doubled.',qs:[['length L or mass m','m or kg',1],['period T','s',2]]},
8:{result:'gas-law processed quantity',rule:'Use uncertainty in the directly measured pressure/volume/temperature quantities. For Boyle analysis, syringe volume and pressure calculation both matter.',qs:[['pressure P','kPa',1],['volume V','mL',1]]},
9:{result:'time constant RC',rule:'For τ = −1/gradient, the fractional uncertainty in τ is the same as the fractional uncertainty in the fitted gradient magnitude.',qs:[['gradient magnitude','s⁻¹',1],['gradient uncertainty','s⁻¹',0]]},
10:{result:'magnetic force / derived quantity',rule:'For F = BIL, percentage uncertainties in B, I and active length L add in a worst-case estimate.',qs:[['flux density B','T',1],['current I','A',1],['active length L','m',1]]},
11:{result:'angular dependence',rule:'Angle uncertainty is nonlinear: near large angles, a small angle uncertainty can cause a larger fractional uncertainty in cosθ.',qs:[['angle θ','°',0],['angle uncertainty','°',0],['emf amplitude','V',1]]},
12:{result:'corrected count rate',rule:'For random counting statistics, the standard uncertainty in N is approximately √N, so fractional counting uncertainty is approximately 1/√N.',qs:[['virtual source count N','counts',0],['virtual background count B','counts',0]]}
};
function render(root,opts={}){let id=+(opts.practicalId||state.last||1);
 function draw(){const m=models[id],p=T.practical(id);root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="ucP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Practical-specific model</span></div></div><div class="tool-two"><div class="tool-panel"><span class="eyebrow">UNCERTAINTY MODEL</span><h3>${T.esc(m.result)}</h3><p>${T.esc(m.rule)}</p><div class="tool-callout">Enter measured values and <b>absolute</b> uncertainties. The calculator shows a conservative percentage-contribution estimate for learning; a real analysis should match the method and graph actually used.</div>${id===12?'<div class="tool-feedback warn">Practical 12 remains simulation-only. This calculator covers statistical count uncertainty only.</div>':''}</div><div class="tool-panel"><h3>Measurement contributions</h3><div style="overflow:auto"><table class="tool-table"><thead><tr><th>Quantity</th><th>Value</th><th>Absolute uncertainty</th><th>Contribution</th></tr></thead><tbody>${m.qs.map((q,i)=>`<tr><td><b>${T.esc(q[0])}</b><br><small>${T.esc(q[1])}</small></td><td><input data-uv="${i}" type="number" step="any" value="${id===12?(i?100:400):''}"></td><td><input data-uu="${i}" type="number" step="any" min="0" value="${id===12?'':''}"></td><td id="ucC${i}">—</td></tr>`).join('')}</tbody></table></div><div class="tool-actions"><button class="primary-btn" id="ucCalc">Calculate uncertainty</button></div><div id="ucOut"></div></div></div>`;
 root.querySelector('#ucP').onchange=e=>{id=+e.target.value;draw();};root.querySelector('#ucCalc').onclick=()=>calc(m);
 }
 function calc(m){
  if(id===12){const N=Math.max(1,+root.querySelector('[data-uv="0"]').value||0),B=Math.max(0,+root.querySelector('[data-uv="1"]').value||0),sigN=Math.sqrt(N),sigB=Math.sqrt(B),net=Math.max(1,N-B),sig=Math.sqrt(sigN*sigN+sigB*sigB),pct=sig/net*100;root.querySelector('#ucC0').textContent=`√N = ${sigN.toFixed(2)}`;root.querySelector('#ucC1').textContent=`√B = ${sigB.toFixed(2)}`;root.querySelector('#ucOut').innerHTML=`<div class="tool-feedback"><b>Background-corrected count: ${net.toFixed(0)} ± ${sig.toFixed(1)}</b><p>Approximate fractional statistical uncertainty: <b>${pct.toFixed(1)}%</b>. Longer counting times increase N and reduce the fractional counting uncertainty.</p></div>`;T.mark(19,true);return;}
  if(id===11){const th=+root.querySelector('[data-uv="0"]').value,du=Math.abs(+root.querySelector('[data-uv="1"]').value||0),E=Math.abs(+root.querySelector('[data-uv="2"]').value||0),dE=Math.abs(+root.querySelector('[data-uu="2"]').value||0);if(!Number.isFinite(th)||!E){root.querySelector('#ucOut').innerHTML='<div class="tool-feedback warn">Enter the angle and emf amplitude.</div>';return;}const angFrac=Math.abs(Math.tan(th*Math.PI/180)*du*Math.PI/180)*100,emfFrac=dE/E*100,total=angFrac+emfFrac;root.querySelector('#ucC0').textContent=`angle effect ≈ ${angFrac.toFixed(2)}%`;root.querySelector('#ucC1').textContent='used with θ';root.querySelector('#ucC2').textContent=`${emfFrac.toFixed(2)}%`;root.querySelector('#ucOut').innerHTML=`<div class="tool-feedback"><b>Approximate combined contribution: ±${total.toFixed(2)}%</b><p>The angular contribution grows where |tanθ| is larger, so angle precision matters more for some orientations.</p></div>`;T.mark(19,true);return;}
  if(id===6||id===9){const g=Math.abs(+root.querySelector('[data-uv="0"]').value||0),dg=Math.abs(+root.querySelector('[data-uv="1"]').value||0);if(!g){root.querySelector('#ucOut').innerHTML='<div class="tool-feedback warn">Enter the fitted gradient magnitude and its uncertainty.</div>';return;}const pct=dg/g*100;root.querySelector('#ucC0').textContent='reference gradient';root.querySelector('#ucC1').textContent=`${pct.toFixed(2)}%`;root.querySelector('#ucOut').innerHTML=`<div class="tool-feedback"><b>Derived-result uncertainty ≈ ±${pct.toFixed(2)}%</b><p>Estimate the gradient uncertainty from defensible steepest and shallowest acceptable lines or equivalent fitting analysis.</p></div>`;T.mark(19,true);return;}
  let sum=0,valid=true;m.qs.forEach((q,i)=>{const v=Math.abs(+root.querySelector(`[data-uv="${i}"]`).value||0),u=Math.abs(+root.querySelector(`[data-uu="${i}"]`).value||0);if(!v){valid=false;root.querySelector(`#ucC${i}`).textContent='enter value';return;}const pct=u/v*100*Math.abs(q[2]);sum+=pct;root.querySelector(`#ucC${i}`).textContent=`${pct.toFixed(2)}%`;});if(!valid){root.querySelector('#ucOut').innerHTML='<div class="tool-feedback warn">Enter a non-zero measured value for each required quantity.</div>';return;}root.querySelector('#ucOut').innerHTML=`<div class="tool-feedback"><b>Conservative combined percentage uncertainty: ±${sum.toFixed(2)}%</b><p>Report the final result to a precision consistent with this uncertainty and identify which measurement contributes most.</p></div>`;T.mark(19,true);
 }
 draw();}
T.register(19,{title:'Practical Uncertainty Calculator',kicker:'MEASUREMENT UNCERTAINTY',description:'Propagate the measurements that matter for each required practical instead of using a generic percentage box.',icon:'±',render,decorate({addPracticalButton,open}){addPracticalButton('uncertainty-calc','Uncertainty calculator',()=>open(19,{practicalId:current?.id||state.last}));}});
})();