(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const S={
1:[['The resonance peak is broad and repeat frequency readings differ.',['Increase frequency slowly near the maximum and repeat the resonance judgement.','Record the first value only.','Change the string and tension at the same time.'],0,'A slow sweep and repeat judgement addresses uncertainty in identifying the maximum while keeping the controlled quantities fixed.'],['The measured frequency is consistently shifted for every length.',['Check how the effective vibrating length/end points were defined.','Delete the whole data set.','Average frequency and length together.'],0,'A consistent shift suggests a systematic geometry/reference issue rather than random scatter.']],
2:[['The fringes are difficult to measure precisely.',['Measure a span across several fringes and divide by the number of spacings.','Move your eye closer to the source beam.','Use only one fringe width.'],0,'A multi-fringe span reduces the percentage effect of a fixed scale-reading uncertainty.'],['The left and right diffraction angles disagree.',['Stop and check alignment/reference geometry with teacher supervision.','Choose whichever angle gives the expected wavelength.','Increase the light intensity by looking along the beam.'],0,'Asymmetry can reveal alignment error. Optical source alignment should remain safely teacher-supervised.']],
3:[['Repeated fall times at one height scatter more than the others.',['Repeat that height and check release/detector alignment.','Delete the point immediately.','Square the height instead of the time.'],0,'A repeat tests whether the scatter is random and alignment affects the release-to-detector geometry.']],
4:[['The extension does not return to zero after unloading.',['Record it and consider whether the elastic region was exceeded or the wire slipped.','Force the graph through the origin.','Ignore unloading data.'],0,'A permanent offset is evidence that must be documented, not hidden.']],
5:[['Resistance drifts upward while taking a reading.',['Open the circuit, allow the wire to cool, and reduce heating during readings.','Increase the current to make the meter steadier.','Average the first and last readings without comment.'],0,'Heating changes resistance systematically, so the method should minimise time/current rather than average away the effect.']],
6:[['The open-circuit p.d. changes during the run.',['Record the drift and minimise discharge/heating by opening the switch between readings.','Short-circuit the cell between readings.','Force the V-I line through the origin.'],0,'Source condition can drift; opening the switch reduces unnecessary current draw.']],
7:[['Pendulum periods depend noticeably on starting amplitude.',['Use a smaller, consistent angle and release without pushing.','Increase amplitude further.','Measure length to the bottom of the bob.'],0,'The small-angle model is more appropriate at small amplitudes and length should be pivot to bob centre.']],
8:[['Boyle syringe readings differ depending on whether load was just increased or decreased.',['Record the hysteresis and approach readings consistently; plunger friction may be important.','Average all readings without noting direction.','Use pressure = Patm + mg/A for this hanging-mass geometry.'],0,'Plunger friction can produce hysteresis. The AQA hanging-mass geometry uses Patm − mg/A.'],['Charles-law points taken immediately after changing bath temperature do not lie on a line.',['Allow thermal equilibrium before reading temperature and air-column length.','Convert temperature to Fahrenheit.','Heat faster.'],0,'The gas must be at the measured bath temperature before the point represents the intended state.']],
9:[['Late discharge points scatter strongly after taking ln(V).',['Discuss low-voltage resolution and justify any excluded point explicitly.','Force a straight line through all raw V-t points.','Replace low readings with zero.'],0,'Log processing magnifies relative noise at low voltage; exclusions need scientific justification.']],
10:[['The balance does not return to its previous zero after current is removed.',['Check for drift/vibration/heating and repeat after the reading stabilises.','Subtract an arbitrary constant from every point.','Increase current until the change is much larger.'],0,'A changing baseline is evidence of a systematic problem and should be investigated within safe apparatus limits.']],
11:[['The oscilloscope amplitude changes while the selected angle is supposedly fixed.',['Check that the coil is held at the chosen angle and the alternating field conditions remain stable.','Rotate the coil continuously while reading.','Change the angle scale after collecting data.'],0,'The investigation needs a defined fixed angle for each amplitude reading.']],
12:[['Two equal-duration simulated counts at the same distance differ.',['Treat this as expected statistical variation and use longer counts/repeats where appropriate.','Alter the virtual source position until the counts match.','Infer a handling fault.'],0,'Counting variation is statistical. This activity remains simulation-only and does not diagnose or teach source handling.']]
};
function render(root,opts={}){let id=+(opts.practicalId||state.last||1),idx=0,score=0;
 function draw(){const p=T.practical(id),list=S[id]||S[1],s=list[idx%list.length];root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="tsP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Scenario ${idx+1} / ${list.length}</span></div></div><div class="tool-panel"><span class="eyebrow">DIAGNOSE THE PROBLEM</span><h3>${T.esc(s[0])}</h3>${s[1].map((c,i)=>`<label class="tool-choice"><input type="radio" name="ts" value="${i}"> ${T.esc(c)}</label>`).join('')}<div id="tsOut"></div><div class="tool-actions"><button class="primary-btn" id="tsCheck">Check diagnosis</button></div></div>`;root.querySelector('#tsP').onchange=e=>{id=+e.target.value;idx=0;score=0;draw();};root.querySelector('#tsCheck').onclick=()=>{const x=root.querySelector('input[name=ts]:checked');if(!x)return;const ok=+x.value===s[2];if(ok)score++;root.querySelector('#tsOut').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'Correct diagnosis':'Try to identify the underlying measurement problem'}</b><p>${T.esc(s[3])}</p></div>${idx<list.length-1?'<button class="primary-btn" id="tsNext">Next scenario →</button>':'<button class="primary-btn" id="tsFinish">Finish troubleshooting</button>'}`;root.querySelector('#tsNext')?.addEventListener('click',()=>{idx++;draw();});root.querySelector('#tsFinish')?.addEventListener('click',()=>{T.mark(4,true);root.querySelector('#tsFinish').textContent=`Completed ✓ (${score}/${list.length})`;});};}
 draw();}
T.register(4,{title:'Troubleshooting scenarios',kicker:'DIAGNOSE PRACTICAL PROBLEMS',description:'Find the cause of poor data, drift, alignment problems and unreliable measurements.',icon:'🛠️',render,decorate({addPracticalButton,open}){addPracticalButton('troubleshoot','Troubleshoot',()=>open(4,{practicalId:current?.id||state.last}));}});
})();