(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const scenarios={
1:[['Increase vibrating length L while T and μ stay fixed','decrease','Because f ∝ 1/L.'],['Increase tension T while L and μ stay fixed','increase','Because f ∝ √T.']],
2:[['Increase screen distance D in Young slits while λ and slit separation stay fixed','increase','Fringe spacing w=λD/s increases.'],['Use a grating with larger line spacing d for the same λ and order','decrease','Since d sinθ=nλ, a larger d gives a smaller sinθ.']],
3:[['Increase drop height h','increase','Fall time increases because t=√(2h/g).'],['Keep h fixed but add a positive timing offset','increase','The measured time is systematically longer.']],
4:[['Increase applied force while staying in the elastic region','increase','Extension increases because stress and strain increase proportionally.'],['Increase wire diameter for the same force and length','decrease','Larger area reduces stress and therefore strain/extension.']],
5:[['Increase wire length for the same material and diameter','increase','R=ρL/A, so resistance increases with length.'],['Increase wire diameter for the same length and material','decrease','Larger cross-sectional area reduces resistance.']],
6:[['Increase current drawn from the cell','decrease','Terminal p.d. V=ε−Ir decreases.'],['Increase external resistance','decrease','Current I=ε/(R+r) decreases.']],
7:[['Increase pendulum length','increase','T=2π√(L/g), so period increases.'],['Increase the oscillating mass on the same spring','increase','T=2π√(m/k), so period increases.']],
8:[['Add more hanging mass in the AQA Boyle syringe geometry','increase','The trapped-gas volume increases in this hanging-mass arrangement because the applied downward pull reduces gas pressure.'],['Increase absolute temperature at constant pressure in Charles’s law','increase','Gas volume/air-column length is proportional to kelvin temperature.']],
9:[['Increase resistance R with the same capacitance C','increase','The time constant τ=RC increases.'],['Wait longer during capacitor discharge','decrease','V=V₀e^(−t/RC) decreases with time.']],
10:[['Increase current I while B and active length L stay fixed','increase','F=BIL, so force increases linearly.'],['Reverse current direction while keeping magnitude fixed','reverse','The force direction reverses while the magnitude is unchanged.']],
11:[['Move the search coil angle toward the orientation that gives a larger |cosθ| for the app’s defined angle','increase','The modeled emf amplitude follows the angular factor.'],['Increase the alternating-field frequency while other factors stay fixed','increase','Faster flux change gives a larger induced emf.']],
12:[['Increase virtual source–detector distance r','decrease','The simulated corrected count rate follows 1/r².'],['Increase virtual counting time','same','The expected count rate stays the same, but fractional statistical uncertainty decreases.']]
};
function render(root,opts={}){let id=+(opts.practicalId||state.last||1),idx=0,streak=0;
 function draw(){const p=T.practical(id),s=scenarios[id][idx%scenarios[id].length];root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="pbP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label><span class="tool-pill">Prediction ${idx+1}</span></div></div><div class="tool-two"><div class="tool-panel"><span class="eyebrow">PREDICT BEFORE CHANGING</span><h3>${T.esc(s[0])}</h3><p>What happens to the dependent quantity?</p><div class="predict-buttons"><button data-pred="increase">↑ Increase</button><button data-pred="decrease">↓ Decrease</button><button data-pred="same">→ Stay the same</button><button data-pred="reverse">↔ Reverse direction</button></div><div id="pbOut"></div></div><div class="tool-panel"><h3>Why this helps in the real practical</h3><p>Make a prediction before moving a control. If the observed trend disagrees, first check the setup, units, controlled variables and whether the measurement has reached a stable value.</p><textarea id="pbWhy" rows="6" placeholder="Write the equation or proportionality that supports your prediction…"></textarea><div class="tool-callout">Prediction is not about guessing the final numerical result; it is about using the model to anticipate the direction and shape of the response.</div></div></div>`;
 root.querySelector('#pbP').onchange=e=>{id=+e.target.value;idx=0;streak=0;draw();};root.querySelectorAll('[data-pred]').forEach(b=>b.onclick=()=>{const ok=b.dataset.pred===s[1];root.querySelector('#pbOut').innerHTML=`<div class="tool-feedback ${ok?'':'warn'}"><b>${ok?'Prediction matches the model':'Recheck the relationship'}</b><p>${T.esc(s[2])}</p></div>${ok?'<div class="tool-actions"><button class="primary-btn" id="pbNext">Next prediction →</button></div>':''}`;if(ok){streak++;T.mark(21,true);root.querySelector('#pbNext').onclick=()=>{idx++;draw();};}});
 }
 draw();}
T.register(21,{title:'Predict Before You Change It',kicker:'LINK THEORY TO OBSERVATION',description:'Predict increase, decrease, no change or reversal before changing a practical control.',icon:'🔮',render,decorate({addPracticalButton,open}){addPracticalButton('predict','Predict first',()=>open(21,{practicalId:current?.id||state.last}));}});
})();