(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;
const axes={1:['1/L / m⁻¹','f / Hz'],2:['processed independent quantity','pattern measurement'],3:['t² / s²','h / m'],4:['strain','stress / Pa'],5:['L / m','R / Ω'],6:['I / A','V / V'],7:['L or m','T² / s²'],8:['P / kPa or T / K','1/V or air-column length'],9:['t / s','ln(V)'],10:['I, L or B','F / N'],11:['angular factor','emf amplitude / V'],12:['1/r²','corrected count rate']};
function reg(d){if(d.length<2)return null;let n=d.length,sx=0,sy=0,sxx=0,sxy=0;d.forEach(p=>{sx+=p.x;sy+=p.y;sxx+=p.x*p.x;sxy+=p.x*p.y});let den=n*sxx-sx*sx;if(Math.abs(den)<1e-12)return null;let m=(n*sxy-sx*sy)/den,c=(sy-m*sx)/n,mean=sy/n,ssT=0,ssR=0;d.forEach(p=>{ssT+=(p.y-mean)**2;ssR+=(p.y-(m*p.x+c))**2});return{m,c,r2:ssT?1-ssR/ssT:1};}
function sample(id){const p=T.practical(id),out=[];for(let i=0;i<6;i++){const x=i+1;out.push({x,y:1.7*x+(id%3)*.18+(i===4?.12:0)});}return out;}
function render(root,opts={}){let id=+(opts.practicalId||state.last||1),mode=0,use='recorded';
 function source(){let d=T.data(id,mode).map(r=>({x:+r.x,y:+r.y})).filter(r=>Number.isFinite(r.x)&&Number.isFinite(r.y));return d.length>=2?d:sample(id);}
 function draw(){const p=T.practical(id),d=source(),fit=reg(d),a=axes[id]||[p.x,p.y];root.innerHTML=`<div class="tool-panel"><div class="tool-row"><label><b>Practical</b> <select id="guP">${practicals.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.id}. ${T.esc(x.title)}</option>`).join('')}</select></label>${p.modes.length>1?`<label><b>Mode</b> <select id="guM">${p.modes.map((m,i)=>`<option value="${i}" ${i===mode?'selected':''}>${T.esc(m)}</option>`).join('')}</select></label>`:''}<span class="tool-pill">${T.data(id,mode).length>=2?'using recorded data':'using practice data'}</span></div></div><div class="tool-two"><div class="tool-panel"><h3>1. Choose and justify axes</h3><p><b>Recommended x:</b> ${T.esc(a[0])}</p><p><b>Recommended y:</b> ${T.esc(a[1])}</p><textarea id="guWhy" rows="4" placeholder="Why does this transformation produce a useful straight line?"></textarea><div class="tool-feedback">A strong answer states the rearranged equation and explains what the gradient and intercept mean physically.</div></div><div class="tool-panel"><h3>2. Best-fit analysis</h3>${fit?`<div class="tool-three"><div><small>Gradient</small><div class="tool-score">${fit.m.toPrecision(4)}</div></div><div><small>Intercept</small><div class="tool-score">${fit.c.toPrecision(4)}</div></div><div><small>R²</small><div class="tool-score">${fit.r2.toFixed(4)}</div></div></div>`:'<p>Record at least two valid points.</p>'}<p>Do not treat a high R² by itself as proof that the method is accurate; systematic effects can preserve linearity.</p></div></div><div class="tool-panel"><h3>3. Data table</h3><div style="overflow:auto"><table class="tool-table"><thead><tr><th>#</th><th>x</th><th>y</th><th>Residual from best fit</th></tr></thead><tbody>${d.map((r,i)=>`<tr><td>${i+1}</td><td>${r.x.toPrecision(5)}</td><td>${r.y.toPrecision(5)}</td><td>${fit?(r.y-(fit.m*r.x+fit.c)).toPrecision(3):'—'}</td></tr>`).join('')}</tbody></table></div></div><div class="tool-two"><div class="tool-panel"><h3>4. Measurement uncertainty</h3><label>x uncertainty <input id="guDx" type="number" min="0" step="any" value="0.01"></label><br><label>y uncertainty <input id="guDy" type="number" min="0" step="any" value="0.01"></label><div id="guUncOut" class="tool-feedback">Enter absolute uncertainties to estimate extreme gradients.</div><button class="primary-btn" id="guCalc">Calculate gradient range</button></div><div class="tool-panel"><h3>5. Interpret the graph</h3><textarea id="guInterpret" rows="6" placeholder="State the trend, gradient meaning, uncertainty evidence, any anomaly and the physical conclusion."></textarea><div class="tool-actions"><button class="primary-btn" id="guDone">Mark workshop complete</button></div></div></div>`;
 root.querySelector('#guP').onchange=e=>{id=+e.target.value;mode=0;draw();};root.querySelector('#guM')?.addEventListener('change',e=>{mode=+e.target.value;draw();});root.querySelector('#guCalc').onclick=()=>{if(!fit)return;let dx=Math.abs(+root.querySelector('#guDx').value||0),dy=Math.abs(+root.querySelector('#guDy').value||0),sorted=[...d].sort((a,b)=>a.x-b.x),lo=sorted[0],hi=sorted.at(-1),span=(hi.x-lo.x);if(span<=2*dx){root.querySelector('#guUncOut').textContent='The x-range is too small compared with the entered uncertainty. Increase the data range.';return;}let max=((hi.y+dy)-(lo.y-dy))/((hi.x-dx)-(lo.x+dx)),min=((hi.y-dy)-(lo.y+dy))/((hi.x+dx)-(lo.x-dx)),frac=Math.abs(max-min)/(2*Math.abs(fit.m)||1)*100;root.querySelector('#guUncOut').innerHTML=`Approx. steepest gradient: <b>${max.toPrecision(4)}</b><br>Approx. shallowest gradient: <b>${min.toPrecision(4)}</b><br>Gradient uncertainty estimate: <b>±${frac.toFixed(1)}%</b><br><small>This endpoint method is a learning approximation; in a real graph use uncertainty bars and defensible extreme acceptable lines.</small>`;};root.querySelector('#guDone').onclick=()=>{T.mark(2,true);root.querySelector('#guDone').textContent='Completed ✓';};}
 draw();}
T.register(2,{title:'Graph & uncertainty workshop',kicker:'DATA PROCESSING',description:'Build the right graph, inspect residuals and estimate gradient uncertainty from your readings.',icon:'📈',render,decorate({open}){const h=document.querySelector('#view-practical .graph-head');if(h&&!h.querySelector('[data-suite-graph]')){const b=document.createElement('button');b.className='secondary-btn';b.dataset.suiteGraph='1';b.textContent='Graph workshop';b.onclick=()=>open(2,{practicalId:current?.id||state.last});h.appendChild(b);}}});
})();