(()=>{
'use strict';const T=window.PracticalTools;if(!T)return;const cfg=T.suite.teacher;cfg.locked=cfg.locked||[];cfg.required=cfg.required||[];cfg.task=cfg.task||'';cfg.hideExamples=!!cfg.hideExamples;cfg.hideHints=!!cfg.hideHints;
function persist(){save();apply();}
function apply(){
 document.documentElement.classList.toggle('teacher-hide-examples',!!cfg.hideExamples);
 const ex=document.querySelector('#lbModeExample');if(ex)ex.classList.toggle('tool-hidden',!!cfg.hideExamples);
 document.querySelectorAll('[data-open]').forEach(b=>{const id=+b.dataset.open,locked=cfg.locked.includes(id);b.disabled=locked;b.title=locked?'Locked in Teacher Mode':'';b.closest('.practical-card')?.classList.toggle('tool-lock',locked);});
 let banner=document.querySelector('#teacherTaskBanner');
 if(cfg.task||cfg.required.length){
   if(!banner){banner=document.createElement('section');banner.id='teacherTaskBanner';banner.className='study-card';document.querySelector('#view-home .lab-intro')?.after(banner);}
   const sig=JSON.stringify([cfg.task,cfg.required]);
   if(banner.dataset.sig!==sig){banner.dataset.sig=sig;banner.innerHTML=`<span class="eyebrow">CLASS TASK</span><h3>${T.esc(cfg.task||'Required practical work')}</h3><p>${cfg.required.length?'Required practicals: '+cfg.required.join(', '):'Follow the task instructions set on this device.'}</p>`;}
 }else banner?.remove();
}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-open]');if(b&&cfg.locked.includes(+b.dataset.open)){e.preventDefault();e.stopImmediatePropagation();}},true);
function render(root){root.innerHTML=`<div class="tool-panel"><span class="eyebrow">LOCAL CLASSROOM CONTROLS</span><h3>Teacher Mode</h3><div class="tool-callout">These controls change this browser/device only. They are not password protection, an LMS, or a secure assessment system.</div></div><div class="tool-two"><div class="tool-panel"><h3>Student-facing options</h3><label class="tool-choice"><input id="tmExamples" type="checkbox" ${cfg.hideExamples?'checked':''}> Hide Completed example Lab Book button</label><label class="tool-choice"><input id="tmHints" type="checkbox" ${cfg.hideHints?'checked':''}> Hide progressive model-answer reveals where supported</label><label><b>Assignment message</b><textarea id="tmTask" rows="5" placeholder="e.g. Complete P5, collect six readings and finish uncertainty/evaluation sections.">${T.esc(cfg.task)}</textarea></label></div><div class="tool-panel"><h3>Required practicals</h3><p>Select practicals to highlight in the class task banner.</p>${practicals.map(p=>`<label class="tool-choice"><input type="checkbox" data-tm-required="${p.id}" ${cfg.required.includes(p.id)?'checked':''}> P${p.id} · ${T.esc(p.title)}</label>`).join('')}</div></div><div class="tool-panel"><h3>Lock practicals on this device</h3><p>Useful when a lesson should focus on a smaller set. This is a navigation aid, not security.</p><div class="tool-three">${practicals.map(p=>`<label class="tool-choice"><input type="checkbox" data-tm-lock="${p.id}" ${cfg.locked.includes(p.id)?'checked':''}> Lock P${p.id}</label>`).join('')}</div><div class="tool-actions"><button class="primary-btn" id="tmSave">Apply classroom controls</button><button class="secondary-btn" id="tmClear">Clear controls</button><button class="secondary-btn" id="tmPrint">Print progress summary</button></div></div>`;
 root.querySelector('#tmSave').onclick=()=>{cfg.hideExamples=root.querySelector('#tmExamples').checked;cfg.hideHints=root.querySelector('#tmHints').checked;cfg.task=root.querySelector('#tmTask').value.trim();cfg.required=[...root.querySelectorAll('[data-tm-required]:checked')].map(x=>+x.dataset.tmRequired);cfg.locked=[...root.querySelectorAll('[data-tm-lock]:checked')].map(x=>+x.dataset.tmLock);persist();T.mark(6,true);root.querySelector('#tmSave').textContent='Applied ✓';};root.querySelector('#tmClear').onclick=()=>{cfg.hideExamples=false;cfg.hideHints=false;cfg.task='';cfg.required=[];cfg.locked=[];persist();render(root);};root.querySelector('#tmPrint').onclick=()=>window.print();}
const obs=new MutationObserver(apply);obs.observe(document.body,{childList:true,subtree:true});setTimeout(apply,0);
T.register(6,{title:'Teacher Mode',kicker:'LOCAL CLASSROOM CONTROLS',description:'Set a lesson task, choose required practicals, hide examples and lock selected practicals on this device.',icon:'🧑‍🏫',render});
})();