(()=>{
'use strict';
state.labBook=state.labBook&&typeof state.labBook==='object'&&!Array.isArray(state.labBook)?state.labBook:{};
let lbSelected=state.last||1,lbStep=0,saveTimer=0;
const stepNames=['Identity','Set-up','Variables & method','Safety','Raw data','Uncertainty & maths','Graph','Conclusion & evaluation','Evidence & reflection'];
const schemas={
1:['Vibrating length / m','Tension / N','Frequency reading 1 / Hz','Frequency reading 2 / Hz'],
2:['Screen distance D / m or order n','Measured fringe span / mm or spot position','Number of fringe intervals','Second span / position'],
3:['Fall distance h / m','Time 1 / s','Time 2 / s','Time 3 / s'],
4:['Force / N','Wire diameter / mm','Extension loading / mm','Extension unloading / mm'],
5:['Wire length / m','p.d. / V','Current / A','Repeat p.d. / V'],
6:['External resistance / Ω','Current / A','Terminal p.d. / V','Notes'],
7:['Length / m or mass / kg','Number of cycles','Total time 1 / s','Total time 2 / s'],
8:['Hanging mass / g or bath T / °C','Volume / mL or air length / cm','Atmospheric pressure / kPa or repeat T / °C','Repeat volume / length'],
9:['Time / s','Capacitor p.d. reading 1 / V','Reading 2 / V','Charge or discharge'],
10:['Current / A','Active length / m','Balance before / g','Balance after / g'],
11:['Angle / °','Emf amplitude 1 / V','Emf amplitude 2 / V','AC frequency / Hz'],
12:['Distance / cm','Count time / s','Source + background counts','Background counts / time']
};
const focus={
1:['Measure the vibrating length between effective end points.','Keep tension and linear density fixed when investigating length.','State how resonance was identified and repeated.'],
2:['Measure several fringes rather than one where possible.','Define D from the slit/grating plane to the screen.','For the grating, record order n and the angle convention.'],
3:['Measure the vertical fall distance from consistent reference points.','Repeat electronic timings and calculate a mean.','Use h against t²; gradient = g/2.'],
4:['Take several diameter readings in different positions/orientations.','Record loading and unloading where appropriate.','Calculate stress and strain before finding Young modulus.'],
5:['Record L, V and I for each point and calculate R=V/I.','Avoid heating changing the resistance.','Use R against L and relate gradient to ρ/A.'],
6:['Record paired I and V values only while the switch is closed.','Open the switch between readings.','V against I gives emf from intercept and r from gradient magnitude.'],
7:['Time many oscillations and divide by the number of cycles.','Keep pendulum amplitude small.','Use T² against L or T² against m.'],
8:['Boyle: record total hanging mass, seal diameter, syringe volume and calculated pressure.','Use P = Patm − mg/A for the AQA hanging-mass geometry.','Charles: allow thermal equilibrium and use kelvin.'],
9:['Start timing consistently with switching.','Record enough points to show the exponential change.','For discharge use ln(V) against t.'],
10:['Use only the wire length inside the magnetic field as active length.','Convert balance change to force using Δmg.','Change one variable at a time in F=BIL.'],
11:['Keep the search coil centred while changing angle.','Hold the selected angle while reading the alternating signal.','Record the angle convention and oscilloscope amplitude.'],
12:['Simulation-only: record background separately and correct the count rate.','Use long enough count times to reduce fractional uncertainty.','Do not record or practise source-handling procedures in this app.']
};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function rowsTableV3(id,e){
 const raw=rowsTable(id,e);
 const simulated=e.simRows.length?`<details class="lb-sim-practice"><summary>${e.simRows.length} imported simulation readings (practice only)</summary><div class="lb-table-wrap"><table class="lb-table"><thead><tr><th>Mode</th><th>Model x</th><th>Simulated y</th></tr></thead><tbody>${e.simRows.map(r=>`<tr><td>${esc(r.mode)}</td><td>${esc(r.x)}</td><td>${esc(r.y)}</td></tr>`).join('')}</tbody></table></div></details>`:'';
 const history=e.corrections.length?`<details class="lb-correction-history"><summary>Corrections and removed readings (${e.corrections.length})</summary><ol>${e.corrections.slice().reverse().map(c=>`<li><time>${esc(c.at)}</time> · ${esc(c.kind)}: ${esc(c.detail)}</li>`).join('')}</ol></details>`:'';
 return raw+`<p class="lb-help">Raw measurements stay here. Put means, transforms and derived values in the processing section. Changes to recorded cells are logged in correction history.</p>`+simulated+history;
}
function backupLabBook(){const blob=new Blob([JSON.stringify({version:3,exported:new Date().toISOString(),labBook:state.labBook},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AQA-Physics-Lab-Book-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function printRecordHtml(id){
 const p=pById(id),e=entry(id),head=schemas[id],value=k=>esc(e[k]||'').replace(/\n/g,'<br>');
 const section=(title,body)=>`<section><h2>${title}</h2>${body}</section>`;
 const para=(label,key)=>`<p><b>${label}:</b> ${value(key)||'<em>Not recorded</em>'}</p>`;
 const raw=`<table><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${e.rawRows.map(r=>`<tr>${head.map((_,i)=>`<td>${esc(r[i]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const unc=`<table><thead><tr><th>Quantity</th><th>Instrument</th><th>Resolution</th><th>Uncertainty</th><th>How used</th></tr></thead><tbody>${e.uncRows.map(r=>`<tr>${['q','instrument','resolution','uncertainty','note'].map(k=>`<td>${esc(r[k]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const evals=`<table><thead><tr><th>Limitation</th><th>Effect</th><th>Improvement</th></tr></thead><tbody>${e.evalRows.map(r=>`<tr>${['limitation','effect','improvement'].map(k=>`<td>${esc(r[k]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const corrections=e.corrections.map(c=>`<li>${esc(c.at)} — ${esc(c.kind)}: ${esc(c.detail)}</li>`).join('');
 const sim=e.simRows.length?section('Simulation practice (separate from real observations)',`<p>${e.simRows.length} imported readings. These are not laboratory evidence.</p><table><tr><th>Mode</th><th>x</th><th>y</th></tr>${e.simRows.map(r=>`<tr><td>${esc(r.mode)}</td><td>${esc(r.x)}</td><td>${esc(r.y)}</td></tr>`).join('')}</table>`):'';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Practical ${id} lab record</title><style>body{font:15px/1.55 Arial,sans-serif;max-width:850px;margin:30px auto;color:#182d25}h1{font-size:27px}h2{font-size:17px;border-bottom:2px solid #567b6a;padding-bottom:5px}section{break-inside:avoid;margin:27px 0}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #aaa;padding:6px;text-align:left;vertical-align:top}th{background:#e9f2ec}p{white-space:normal}.note{background:#eff5e8;padding:12px}a{color:#245c45}@media print{body{margin:0}}</style></head><body><h1>Practical ${id}: ${esc(p.title)}</h1><p><b>Date:</b> ${esc(e.date||'')} · <b>Class / reference:</b> ${esc(e.studentRef||'')}</p><p class="note">Personal student record. Section ticks indicate writing progress only; teacher observation determines endorsement. Imported simulation readings are separate.</p>${section('Aim and AQA links',para('Aim', 'aim')+`<p>AQA techniques: ${esc(p.at.join(', '))}</p><p><a href="https://filestore.aqa.org.uk/resources/physics/AQA-7407-7408-SUG-P${id}.PDF">AQA apparatus guide</a> · <a href="https://www.aqa.org.uk/subjects/physics/a-level/physics-7408/specification/practical-assessment">AQA specification</a></p>`)}${section('Set-up',para('Apparatus and geometry','setup'))}${section('Variables and method',para('Independent variable','independent')+para('Dependent variable','dependent')+para('Controls','controls')+para('Method used','method'))}${section('Safety',para('Risk controls','safety'))}${section('Raw data and observations',raw+para('Observations and anomalies','observations'))}${section('Uncertainty and processing',unc+para('Processed table / values','processedTable')+para('Calculations','calculations'))}${section('Graph and result',para('Graph record','graph')+para('Result','graphResult'))}${section('Conclusion and evaluation',para('Conclusion','conclusion')+evals)}${section('Changes and references',para('Changes','changes')+para('References','references')+para('Reflection','reflection')+(corrections?`<h3>Correction history</h3><ol>${corrections}</ol>`:''))}${sim}</body></html>`;
}
function downloadRecord(id){const blob=new Blob([printRecordHtml(id)],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`AQA-Physics-Practical-${id}-lab-record.html`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function sanitiseEntry(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))return null;const out={};for(const [k,v] of Object.entries(raw)){if(k==='__proto__'||k==='constructor'||k==='prototype')continue;if(['completed','setupChecks'].includes(k)&&v&&typeof v==='object'&&!Array.isArray(v)){out[k]=Object.fromEntries(Object.entries(v).filter(([a,b])=>/^\d+$/.test(a)&&typeof b==='boolean'));continue;}if(['rawRows'].includes(k)&&Array.isArray(v)){out[k]=v.slice(0,500).filter(Array.isArray).map(r=>r.slice(0,4).map(x=>String(x??'').slice(0,1000)));continue;}if(['uncRows','evalRows','simRows','corrections'].includes(k)&&Array.isArray(v)){out[k]=v.slice(-500).filter(x=>x&&typeof x==='object'&&!Array.isArray(x)).map(x=>Object.fromEntries(Object.entries(x).filter(([a])=>!['__proto__','constructor','prototype'].includes(a)).map(([a,b])=>[a.slice(0,60),String(b??'').slice(0,2000)])));continue;}if(typeof v==='string')out[k]=v.slice(0,30000);}return out;}
async function restoreLabBook(file){if(!file||file.size>4_000_000)throw new Error('Choose a JSON backup under 4 MB.');let data=JSON.parse(await file.text());const source=data?.labBook||data?.state?.labBook;if(!source||typeof source!=='object'||Array.isArray(source))throw new Error('This file has no labBook records.');const clean={};for(const [id,raw] of Object.entries(source)){if(!/^(?:[1-9]|1[0-2])$/.test(id))continue;const e=sanitiseEntry(raw);if(e)clean[id]=e;}const n=Object.keys(clean).length;if(!n)throw new Error('No valid practical records were found.');if(!window.confirm(`Restore ${n} practical record(s)? Existing entries for those practicals will be replaced. A pre-restore backup will download first.`))return 0;backupLabBook();Object.assign(state.labBook,clean);save();renderLabBookV2();return n;}
function pById(id){return practicals.find(p=>p.id===+id)||practicals[0];}
function entry(id){const k=String(id);const e=state.labBook[k]||(state.labBook[k]={});e.date=e.date||new Date().toISOString().slice(0,10);e.completed=e.completed||{};e.rawRows=Array.isArray(e.rawRows)?e.rawRows:[];e.uncRows=Array.isArray(e.uncRows)?e.uncRows:[];e.evalRows=Array.isArray(e.evalRows)?e.evalRows:[];e.simRows=Array.isArray(e.simRows)?e.simRows:[];e.corrections=Array.isArray(e.corrections)?e.corrections:[];e.setupChecks=e.setupChecks||{};return e;}
function logCorrection(e,kind,detail){e.corrections.push({at:new Date().toISOString(),kind,detail});if(e.corrections.length>200)e.corrections.shift();}
function sourceLinks(id){return `<div class="lb-source-links"><a href="https://www.aqa.org.uk/subjects/physics/a-level/physics-7408/specification/practical-assessment" target="_blank" rel="noopener">AQA 7408 required practicals ↗</a><a href="https://filestore.aqa.org.uk/resources/physics/AQA-7407-7408-SUG-P${id}.PDF" target="_blank" rel="noopener">AQA Practical ${id} apparatus guide ↗</a><a href="https://filestore.aqa.org.uk/resources/physics/AQA-7407-7408-PHBK.PDF" target="_blank" rel="noopener">AQA practical handbook ↗</a></div>`;}
function saveNow(){save();updateQuality();let stored=false;try{stored=localStorage.getItem(KEY)===JSON.stringify(state);}catch{}const s=document.querySelector('#lbSaveStatus');if(s){s.innerHTML=stored?'<i></i>Saved on this device':'<i></i>Not saved on this device — export a backup';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(s&&stored)s.innerHTML='<i></i>Autosave on';},900);}}
function progress(id){const e=entry(id);let n=0;for(let i=0;i<9;i++)if(e.completed[i])n++;return {n,pct:Math.round(n/9*100)};}
function draftPrompts(e,step){
 const present=k=>typeof e[k]==='string'&&e[k].trim().length>0;
 const checks=[
  [['date','Date the entry'],['aim','State a measurable aim']],
  [['setup','Describe or sketch your actual apparatus and measurement geometry']],
  [['independent','Name the independent variable'],['dependent','Name the measured response'],['controls','Explain the controls'],['method','Record the method actually used']],
  [['safety','Link risk controls to your apparatus']],
  [['raw','Enter raw readings with units in headings and note anomalies']],
  [['unc','Record instrument and repeat uncertainty'],['processedTable','Show processed values separately'],['calculations','Show a substituted calculation with units']],
  [['graph','State axes, gradient and fit method'],['graphResult','Record the physical result with units']],
  [['conclusion','Connect evidence to the aim'],['evaluation','Name a limitation, its effect and a specific improvement']],
  [['references','Cross-reference the instructions/data used'],['reflection','Reflect on a practical skill']]
 ];
 return checks[step].filter(([k])=>k==='raw'?e.rawRows.filter(r=>r.some(x=>String(x||'').trim())).length<3:k==='unc'?!e.uncRows.some(r=>r.q&&r.uncertainty):k==='evaluation'?!e.evalRows.some(r=>r.limitation&&r.improvement):!present(k)).map(([,label])=>label);
}
function qualityHtml(e,step){const missing=draftPrompts(e,step);return `<div class="lb-quality" id="lbQuality"><b>${missing.length?'Next evidence to add':'This section has the key evidence prompts filled'}</b>${missing.length?`<ul>${missing.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<small>These prompts help you review a draft. They do not grade scientific quality or award a practical-endorsement pass.</small></div>`;}
function updateQuality(){const q=document.querySelector('#lbQuality');if(q)q.outerHTML=qualityHtml(entry(lbSelected),lbStep);}
function totalProgress(){let done=0;practicals.forEach(p=>done+=progress(p.id).n);return {done,total:108,pct:Math.round(done/108*100)};}
function recordedData(id){const sets=[];Object.entries(state.data||{}).forEach(([k,rows])=>{if(!k.startsWith(id+'_')||!Array.isArray(rows)||!rows.length)return;const mode=+k.split('_')[1]||0;sets.push({mode,rows});});return sets;}
function dataPreview(id){const p=pById(id),sets=recordedData(id);if(!sets.length)return 'No simulation readings recorded yet.';return sets.map(s=>`${p.modes[s.mode]||'Mode '+(s.mode+1)}\n${p.x}\t${p.y}\n${s.rows.map(r=>`${fmt(r.x)}\t${fmt(r.y)}`).join('\n')}`).join('\n\n');}
function field(e,key,label,hint,rows=5){return `<label class="lb-field"><span>${label}</span><small>${hint}</small><textarea rows="${rows}" data-lbf="${key}">${esc(e[key]||'')}</textarea></label>`;}
function textInput(e,key,label,hint,type='text'){return `<label class="lb-field"><span>${label}</span><small>${hint}</small><input type="${type}" data-lbf="${key}" value="${esc(e[key]||'')}"></label>`;}
function setupPanel(id,e){const g=window.AQA_SETUP_GUIDE?.[id],checks=g?.checks||[];return `<div class="lb-panel"><div class="lb-section-title"><h3>AQA set-up check</h3><span class="lb-required">check before writing</span></div><p class="lb-help">${esc(g?.summary||'Record the arrangement actually used in your lesson.')}</p><div class="lb-checklist">${checks.map((x,i)=>`<label class="lb-check"><input type="checkbox" data-setup-check="${i}" ${e.setupChecks[i]?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div></div>`;}
function rowsTable(id,e){const heads=schemas[id]||['Independent variable','Dependent variable','Processed value','Notes'];if(!e.rawRows.length)e.rawRows.push(['','','','']);return `<div class="lb-table-wrap"><table class="lb-table"><thead><tr><th>#</th>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}<th></th></tr></thead><tbody>${e.rawRows.map((r,ri)=>`<tr><td>${ri+1}</td>${heads.map((_,ci)=>`<td><input data-raw-row="${ri}" data-raw-col="${ci}" value="${esc(r[ci]||'')}"></td>`).join('')}<td><button class="tiny-btn" data-del-raw="${ri}" aria-label="Remove row">×</button></td></tr>`).join('')}</tbody></table></div><div class="lb-row-actions"><button class="secondary-btn" id="lbAddRaw">+ Add row</button><button class="secondary-btn" id="lbImportSim">Import simulation readings</button></div>`;}
function uncTable(e){if(!e.uncRows.length)e.uncRows.push({q:'',instrument:'',resolution:'',uncertainty:'',note:''});return `<div class="lb-table-wrap"><table class="lb-table"><thead><tr><th>Quantity</th><th>Instrument</th><th>Resolution</th><th>Uncertainty</th><th>How used</th><th></th></tr></thead><tbody>${e.uncRows.map((r,i)=>`<tr>${['q','instrument','resolution','uncertainty','note'].map(k=>`<td><input data-unc-row="${i}" data-unc-key="${k}" value="${esc(r[k]||'')}"></td>`).join('')}<td><button class="tiny-btn" data-del-unc="${i}">×</button></td></tr>`).join('')}</tbody></table></div><div class="lb-row-actions"><button class="secondary-btn" id="lbAddUnc">+ Add uncertainty</button></div>`;}
function evalTable(e){if(!e.evalRows.length)e.evalRows.push({limitation:'',effect:'',improvement:''});return `<div class="lb-table-wrap"><table class="lb-table"><thead><tr><th>Limitation / issue</th><th>Effect on data/result</th><th>Specific improvement</th><th></th></tr></thead><tbody>${e.evalRows.map((r,i)=>`<tr>${['limitation','effect','improvement'].map(k=>`<td><textarea data-eval-row="${i}" data-eval-key="${k}">${esc(r[k]||'')}</textarea></td>`).join('')}<td><button class="tiny-btn" data-del-eval="${i}">×</button></td></tr>`).join('')}</tbody></table></div><div class="lb-row-actions"><button class="secondary-btn" id="lbAddEval">+ Add evaluation point</button></div>`;}
function stepHtml(id,step){const p=pById(id),e=entry(id),f=focus[id]||[];let main='',side='';
 if(step===0){main=`<div class="lb-panel"><div class="lb-two">${textInput(e,'date','Date','Date the practical record.','date')}${textInput(e,'studentRef','Class / page / file reference','Optional cross-reference used by your school or college.')}</div>${field(e,'aim','Aim / objective','State the relationship or quantity being investigated; do not just write the practical title.',4)}</div>`;side=`<div class="lb-panel"><h3>What a strong opening contains</h3><div class="lb-checklist"><span>• A clear practical title and date.</span><span>• A specific aim linked to measurable quantities.</span><span>• Relevant AQA apparatus/technique codes: <b>${p.at.join(' · ')}</b>.</span></div></div>`;}
 if(step===1){main=setupPanel(id,e)+`<div class="lb-panel">${field(e,'setup','Your apparatus / labelled set-up record','Describe or sketch the arrangement actually used. Include meter ranges, key distances, reference points and settings where relevant.',7)}</div>`;side=`<div class="lb-panel"><h3>Student check</h3><p class="lb-help">A set-up drawing should make the measurement geometry obvious. Label the parts that define the quantities you calculate later.</p><div class="lb-callout">${esc(f[0]||'Record the measurement geometry clearly.')}</div></div>`;}
 if(step===2){main=`<div class="lb-panel"><div class="lb-three">${field(e,'independent','Independent variable','What you deliberately change.',3)}${field(e,'dependent','Dependent variable','What you measure as the response.',3)}${field(e,'controls','Control variables','What must stay constant and how.',3)}</div>${field(e,'method','Method as actually carried out','Write the sequence, settings and changes actually used. Include repeats and how readings were taken.',8)}</div>`;side=`<div class="lb-panel"><h3>Method focus</h3><div class="lb-callout">${esc(f[1]||'Keep important control variables constant.')}</div><p class="lb-help">A lab book is a live record. If the method changed, record the change later rather than rewriting history.</p></div>`;}
 if(step===3){main=`<div class="lb-panel">${field(e,'safety','Safety / risk controls','Record the controls your teacher/technician required and the precautions relevant to the apparatus actually used.',7)}</div>`;side=`<div class="lb-panel"><h3>Keep this specific</h3><p class="lb-help">Avoid a generic list. Link each control to the equipment or hazard in the real practical. Your school/college risk assessment and staff instructions take priority.</p>${id===12?'<div class="lb-callout warn">This app keeps Practical 12 simulation-only and does not provide source-handling instructions.</div>':''}</div>`;}
 if(step===4){main=`<div class="lb-panel"><div class="lb-section-title"><h3>Raw data table</h3><span class="lb-required">record during practical</span></div><p class="lb-help">Use units in headings. Keep raw readings distinct from later processed quantities.</p>${rowsTableV3(id,e)}</div><div class="lb-panel">${field(e,'observations','Observations / anomalies','Record useful qualitative observations, unexpected behaviour, anomalous points and what happened during the run.',5)}</div>`;side=`<div class="lb-panel"><h3>Simulation data available</h3><pre class="lb-data-preview">${esc(dataPreview(id))}</pre><p class="lb-help">Importing simulation data is for revision/practice. Your real lab book should contain the readings you actually obtained in class.</p></div>`;}
 if(step===5){main=`<div class="lb-panel"><h3>Measurement uncertainty</h3><p class="lb-help">Record instrument resolution, estimated uncertainty and where repeat spread matters.</p>${uncTable(e)}</div><div class="lb-panel">${field(e,'processedTable','Processed results table','Show means and transformed quantities with units. Keep these separate from raw readings.',6)}${field(e,'calculations','Calculations / processing','Show equations, substitutions, units and processed values. Keep enough working that another reader can follow your reasoning.',8)}</div>`;side=`<div class="lb-panel"><h3>Uncertainty focus</h3><div class="lb-callout">${esc(f[2]||'Link uncertainty to the measurements that dominate the final result.')}</div><p class="lb-help">Where a calculation uses powers or products, explain how measurement uncertainty affects the processed quantity.</p></div>`;}
 if(step===6){main=`<div class="lb-panel">${field(e,'graph','Graph / data-processing record','Write the axes and units, transformation, best-fit method, gradient/intercept and what physical quantity the graph gives.',8)}${field(e,'graphResult','Gradient / intercept / result from graph','Record the numerical quantity extracted from the graph with units and sensible precision.',4)}</div>`;side=`<div class="lb-panel"><h3>For this practical</h3><div class="lb-callout">${esc(({
1:'Use the linearised relationship appropriate to the variable being changed.',2:'Young slits: use fringe spacing carefully. Grating: use nλ = d sinθ.',3:'Plot h against t²; gradient = g/2.',4:'Plot stress against strain in the elastic region.',5:'Plot R against L; gradient = ρ/A.',6:'Plot V against I; intercept = emf and gradient = −r.',7:'Plot T² against L or m.',8:'Boyle: plot 1/V against P. Charles: use absolute temperature.',9:'For discharge, plot ln(V) against t.',10:'Test F against I, L or B one variable at a time.',11:'Plot emf amplitude against the chosen trigonometric function.',12:'Plot corrected count rate against 1/r².'}[id])||'State why your graph tests the physics model.')}</div></div>`;}
 if(step===7){main=`<div class="lb-panel">${field(e,'conclusion','Conclusion','Answer the aim using your evidence. Quote the measured relationship/result with units where appropriate and connect it to the expected physics.',6)}</div><div class="lb-panel"><h3>Evaluation table</h3><p class="lb-help">Make each improvement solve a specific limitation rather than writing vague phrases such as “be more careful”.</p>${evalTable(e)}</div>`;side=`<div class="lb-panel"><h3>Evaluation quality check</h3><div class="lb-checklist"><span>• Identify whether effects are random or systematic where possible.</span><span>• Refer to scatter, anomalies or uncertainty evidence.</span><span>• Explain the direction/effect on the result when you can.</span><span>• Link every improvement to a named limitation.</span></div></div>`;}
 if(step===8){main=`<div class="lb-panel">${field(e,'changes','Changes made during the practical','Record method changes, repeated runs, rejected readings and the reason for them.',5)}${field(e,'references','References / cross-references','Record worksheets, data files, page references or other sources used.',4)}${field(e,'reflection','Practical-skills reflection','What skill improved? What would you do differently next time? What evidence could your teacher use when judging practical competence?',6)}</div>`;side=`<div class="lb-panel"><h3>Evidence record</h3><div class="lb-evidence"><div><span>Followed procedures</span><b>${e.completed[2]?'✓':'—'}</b></div><div><span>Used apparatus / measurements</span><b>${e.completed[1]&&e.completed[4]?'✓':'—'}</b></div><div><span>Recorded data with units</span><b>${e.completed[4]?'✓':'—'}</b></div><div><span>Processed data / uncertainty</span><b>${e.completed[5]&&e.completed[6]?'✓':'—'}</b></div><div><span>Evaluated evidence</span><b>${e.completed[7]?'✓':'—'}</b></div></div><p class="lb-help">This is a student organisation aid only. Practical Endorsement assessment/sign-off remains with your school or college.</p></div>`;}
 return `<div class="lb-step-content"><div class="lb-main">${main}</div><aside class="lb-side">${side}</aside></div>`;
}
function dashboard(){const overall=totalProgress();return `<div class="lb-dashboard"><section class="lb-hero"><span class="eyebrow">AQA PRACTICAL RECORD WORKSPACE</span><h2>Your Physics Lab Book</h2><p>Build a clear record of what you actually did, measured, calculated and concluded. This nine-section layout is suggested by the AQA practical handbook. Record what actually happened as you work. Teacher observation and your school’s procedures determine the practical endorsement.</p></section><section class="lb-summary"><small>Overall recording progress</small><strong>${overall.pct}%</strong><div class="lb-progressbar"><i style="width:${overall.pct}%"></i></div><span>${overall.done} of ${overall.total} recording steps marked complete</span></section></div><div class="lb-practical-grid">${practicals.map(p=>{const pr=progress(p.id);return `<article class="lb-card" data-lb-open="${p.id}" tabindex="0" role="button" aria-label="Open Practical ${p.id} lab book"><div class="lb-card-top"><span class="lb-badge">Practical ${p.id}</span><span class="lb-mini-progress">${pr.pct}%</span></div><h3>${esc(p.title)}</h3><small>${esc(p.topic)} · ${pr.n}/9 sections complete</small><div class="lb-progressbar"><i style="width:${pr.pct}%"></i></div></article>`}).join('')}</div>`;}
function renderLabBookV2(){const root=document.querySelector('#labBookRoot');if(!root)return;const p=pById(lbSelected),e=entry(lbSelected),pr=progress(lbSelected);root.innerHTML=`<div class="labbook-v2">${dashboard()}<section class="lb-entry"><div class="lb-entry-head"><div><span class="eyebrow">CURRENT ENTRY</span><h2>Practical ${p.id}: ${esc(p.title)}</h2><div class="lb-save-status" id="lbSaveStatus"><i></i>Autosave on</div></div><div class="lb-toolbar"><select id="lbSelect">${practicals.map(x=>`<option value="${x.id}" ${x.id===lbSelected?'selected':''}>${x.id}. ${esc(x.title)}</option>`).join('')}</select><button class="secondary-btn" id="lbOpenSim">Open simulation</button><button class="secondary-btn" id="lbPrint">Print / Save PDF</button><button class="secondary-btn" id="lbBackup">Export backup</button><button class="secondary-btn" id="lbRestore">Restore backup</button><input type="file" id="lbRestoreFile" accept="application/json,.json" hidden><button class="secondary-btn" id="lbRecord">Download full record</button></div></div>${sourceLinks(p.id)}<div class="lb-progressbar"><i style="width:${pr.pct}%"></i></div><div class="lb-stepper">${stepNames.map((n,i)=>`<button data-lb-step="${i}" class="${lbStep===i?'active':''} ${e.completed[i]?'done':''}"><span>${i+1}</span>${n}</button>`).join('')}</div>${stepHtml(lbSelected,lbStep)}${qualityHtml(e,lbStep)}<div class="lb-nav"><button class="secondary-btn" id="lbPrev" ${lbStep===0?'disabled':''}>← Previous</button><label class="lb-check"><input id="lbDone" type="checkbox" ${e.completed[lbStep]?'checked':''}><span>Mark this section drafted</span></label><button class="primary-btn" id="lbNext">${lbStep===8?'Back to section 1':'Next →'}</button></div></section></div>`;bind();}
function bind(){const e=entry(lbSelected);
 document.querySelectorAll('[data-lb-open]').forEach(x=>{x.onclick=()=>{lbSelected=+x.dataset.lbOpen;lbStep=0;renderLabBookV2();};x.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();x.click();}};});
 const sel=document.querySelector('#lbSelect');if(sel)sel.onchange=()=>{lbSelected=+sel.value;lbStep=0;renderLabBookV2();};
 document.querySelectorAll('[data-lb-step]').forEach(x=>x.onclick=()=>{lbStep=+x.dataset.lbStep;renderLabBookV2();});
 document.querySelectorAll('[data-lbf]').forEach(x=>x.oninput=()=>{e[x.dataset.lbf]=x.value;saveNow();});
 document.querySelectorAll('[data-setup-check]').forEach(x=>x.onchange=()=>{e.setupChecks[x.dataset.setupCheck]=x.checked;saveNow();});
 document.querySelectorAll('[data-raw-row]').forEach(x=>{x.onfocus=()=>{x.dataset.before=x.value;};x.onchange=()=>{const before=x.dataset.before||'';if(before&&before!==x.value){logCorrection(e,'Edited raw reading',`Row ${+x.dataset.rawRow+1}, column ${+x.dataset.rawCol+1}: ${before} → ${x.value}`);saveNow();}x.dataset.before=x.value;};x.oninput=()=>{const r=+x.dataset.rawRow,c=+x.dataset.rawCol;e.rawRows[r]=e.rawRows[r]||['','','',''];e.rawRows[r][c]=x.value;saveNow();};});
 document.querySelectorAll('[data-unc-row]').forEach(x=>x.oninput=()=>{const r=+x.dataset.uncRow,k=x.dataset.uncKey;e.uncRows[r]=e.uncRows[r]||{};e.uncRows[r][k]=x.value;saveNow();});
 document.querySelectorAll('[data-eval-row]').forEach(x=>x.oninput=()=>{const r=+x.dataset.evalRow,k=x.dataset.evalKey;e.evalRows[r]=e.evalRows[r]||{};e.evalRows[r][k]=x.value;saveNow();});
 document.querySelectorAll('[data-del-raw]').forEach(x=>x.onclick=()=>{const row=e.rawRows.splice(+x.dataset.delRaw,1)[0];logCorrection(e,'Removed raw row',`Row ${+x.dataset.delRaw+1}: ${JSON.stringify(row)}. Enter a corrected reading in a new row.`);saveNow();renderLabBookV2();});
 document.querySelectorAll('[data-del-unc]').forEach(x=>x.onclick=()=>{e.uncRows.splice(+x.dataset.delUnc,1);saveNow();renderLabBookV2();});
 document.querySelectorAll('[data-del-eval]').forEach(x=>x.onclick=()=>{e.evalRows.splice(+x.dataset.delEval,1);saveNow();renderLabBookV2();});
 const addRaw=document.querySelector('#lbAddRaw');if(addRaw)addRaw.onclick=()=>{e.rawRows.push(['','','','']);saveNow();renderLabBookV2();};
 const addUnc=document.querySelector('#lbAddUnc');if(addUnc)addUnc.onclick=()=>{e.uncRows.push({q:'',instrument:'',resolution:'',uncertainty:'',note:''});saveNow();renderLabBookV2();};
 const addEval=document.querySelector('#lbAddEval');if(addEval)addEval.onclick=()=>{e.evalRows.push({limitation:'',effect:'',improvement:''});saveNow();renderLabBookV2();};
 const imp=document.querySelector('#lbImportSim');if(imp)imp.onclick=()=>{const sets=recordedData(lbSelected);sets.forEach(s=>s.rows.forEach(r=>e.simRows.push({mode:pById(lbSelected).modes[s.mode]||String(s.mode),x:fmt(r.x),y:fmt(r.y)})));e.simRows=e.simRows.slice(-500);saveNow();renderLabBookV2();};
 const done=document.querySelector('#lbDone');if(done)done.onchange=()=>{e.completed[lbStep]=done.checked;saveNow();renderLabBookV2();};
 const prev=document.querySelector('#lbPrev');if(prev)prev.onclick=()=>{if(lbStep>0){lbStep--;renderLabBookV2();}};
 const next=document.querySelector('#lbNext');if(next)next.onclick=()=>{lbStep=lbStep===8?0:lbStep+1;renderLabBookV2();};
 const sim=document.querySelector('#lbOpenSim');if(sim)sim.onclick=()=>navigate('practical',lbSelected);
 const print=document.querySelector('#lbPrint');if(print)print.onclick=()=>{const w=window.open('','_blank');if(!w)return;w.document.open();w.document.write(printRecordHtml(lbSelected));w.document.close();setTimeout(()=>{w.focus();w.print();},100);};
 const backup=document.querySelector('#lbBackup');if(backup)backup.onclick=backupLabBook;
 const record=document.querySelector('#lbRecord');if(record)record.onclick=()=>downloadRecord(lbSelected);
 const restore=document.querySelector('#lbRestore'),file=document.querySelector('#lbRestoreFile');if(restore&&file){restore.onclick=()=>file.click();file.onchange=async()=>{try{const n=await restoreLabBook(file.files?.[0]);if(n)window.alert(`${n} practical record(s) restored.`);}catch(err){window.alert(`Restore failed: ${err.message}`);}file.value='';};}
}
window.renderLabBook=renderLabBookV2;
const priorNavigateV2=navigate;navigate=function(view,id){const out=priorNavigateV2(view,id);if(view==='labbook'){if(id)lbSelected=+id;setTimeout(renderLabBookV2,0);}return out;};
window.__labBookV2={render:renderLabBookV2,select:id=>{lbSelected=+id;lbStep=0;renderLabBookV2();},progress};
})();
