(()=>{
state.labBook=state.labBook||{};
const fields=['aim','setup','variables','method','safety','rawData','observations','uncertainty','calculations','graph','conclusion','evaluation','changes','references','reflection'];
const labFocus={
1:{measure:'Record vibrating length, tension/attached mass, string linear density and resonant frequency.',graph:'State which relationship you tested, for example resonant frequency against 1/L when T and μ are controlled.',unc:'Record ruler resolution, frequency resolution and how consistently resonance was judged.'},
2:{measure:'Record wavelength/source information, screen distance and either multi-fringe span or diffraction positions/angles.',graph:'Young slits: process fringe spacing carefully. Grating: state order n and the angle convention used.',unc:'Explain why measuring across several fringes/orders reduces percentage uncertainty.'},
3:{measure:'Record vertical fall distance and repeat electronic fall times, then calculate a mean.',graph:'For release from rest, a plot of h against t² has gradient g/2.',unc:'Record distance resolution, timing resolution and any scatter between repeated fall times.'},
4:{measure:'Record wire diameter readings, original wire length, applied force and extension readings during loading/unloading.',graph:'Calculate stress and strain; the gradient of stress against strain gives Young modulus in the elastic region.',unc:'Include diameter uncertainty carefully because cross-sectional area depends on d².'},
5:{measure:'Record wire diameter, selected wire length, potential difference and current for each reading; calculate R=V/I.',graph:'Plot R against L; gradient = ρ/A.',unc:'Discuss micrometer uncertainty, contact resistance and heating of the test wire.'},
6:{measure:'Record paired current I and terminal p.d. V values for several external resistances.',graph:'Plot V against I. Intercept gives emf and gradient is −r.',unc:'Record meter resolutions and note why the switch is open between readings.'},
7:{measure:'Pendulum: length and total time for many oscillations. Spring: oscillating mass and total time for many oscillations.',graph:'Plot T² against L for the pendulum or T² against m for the spring system.',unc:'Include ruler uncertainty and timing uncertainty; explain the advantage of timing multiple cycles.'},
8:{measure:'Boyle: total hanging mass, seal diameter, syringe volume and calculated gas pressure. Charles: temperature and trapped-air column length.',graph:'AQA Boyle processing: plot 1/V against P. Charles: plot air-column length (∝ volume) against absolute temperature.',unc:'Boyle: include seal-diameter and volume-scale uncertainty. Charles: include temperature and length uncertainties.'},
9:{measure:'Record capacitor voltage and corresponding time values through charge/discharge.',graph:'For discharge, calculate ln(V) and plot ln(V) against t; gradient = −1/RC.',unc:'Record voltage/time resolution and component tolerances where known.'},
10:{measure:'Record current, active wire length in the magnetic field, magnetic flux density where relevant, and balance change.',graph:'Convert apparent mass change to force and test F against I, L or B while the others are controlled.',unc:'Include balance resolution, current resolution and uncertainty in the active wire length.'},
11:{measure:'Record the search-coil angle and corresponding induced-emf amplitude while drive conditions remain fixed.',graph:'Plot induced-emf amplitude against the appropriate trigonometric function for the defined angle.',unc:'Record angle resolution and oscilloscope amplitude-reading uncertainty.'},
12:{measure:'Simulation-only: record distance, count time, background rate and simulated count result.',graph:'Plot background-corrected count rate against 1/r² and comment on statistical scatter.',unc:'Use counting statistics and explain how longer count times reduce fractional uncertainty. Do not record source-handling instructions.'}
};
function entry(id){const k=String(id);if(!state.labBook[k])state.labBook[k]={date:new Date().toISOString().slice(0,10),completed:{}};return state.labBook[k];}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function practical(id){return practicals.find(p=>p.id===+id)||practicals[0];}
function completion(e){let n=0,total=9;for(let i=0;i<total;i++)if(e.completed?.[i])n++;return {n,total,pct:Math.round(n/total*100)};}
function recordedData(id){const out=[];Object.entries(state.data||{}).forEach(([k,rows])=>{if(!k.startsWith(id+'_')||!Array.isArray(rows)||!rows.length)return;const mode=+k.split('_')[1]||0,p=practical(id),name=p.modes?.[mode]||`Mode ${mode+1}`;out.push({name,rows});});return out;}
function dataText(id){const p=practical(id),sets=recordedData(id);if(!sets.length)return 'No simulation readings have been recorded yet.';return sets.map(s=>`${s.name}\n${p.x}\t${p.y}\n`+s.rows.map(r=>`${r.x}\t${r.y}`).join('\n')).join('\n\n');}
function stepTitle(i){return ['1. Identify the practical','2. Record the apparatus and set-up','3. Record the method and variables','4. Record safety and risk controls','5. Enter raw data and observations','6. Show uncertainty and calculations','7. Process data and record the graph','8. Write the conclusion and evaluation','9. References, changes and reflection'][i];}
function textArea(field,label,hint,e,rows=5){return `<label class="lab-field"><span>${label}</span><small>${hint}</small><textarea rows="${rows}" data-lab-field="${field}">${esc(e[field]||'')}</textarea></label>`;}
function renderStep(id,i){const p=practical(id),e=entry(id),f=labFocus[id],setup=window.AQA_SETUP_GUIDE?.[id];let html='';
 if(i===0)html=`<div class="lab-two"> <label class="lab-field"><span>Date</span><small>Date each practical record.</small><input type="date" data-lab-field="date" value="${esc(e.date||'')}"></label><label class="lab-field"><span>Practical title</span><small>Use a clear title that identifies the investigation.</small><input value="Practical ${p.id}: ${esc(p.title)}" readonly></label></div>${textArea('aim','Aim / objective','State what relationship or quantity is being investigated. Include the relevant apparatus/technique focus where useful.',e,4)}<div class="lab-prompt"><b>AQA apparatus/techniques:</b> ${p.at.join(' · ')}</div>`;
 if(i===1)html=`<div class="setup-reference"><span class="eyebrow">AQA SET-UP REFERENCE</span><h4>${esc(setup?.title||p.title)}</h4><p>${esc(setup?.summary||'Record the arrangement actually used in your lesson.')}</p>${(setup?.checks||[]).map(x=>`<div class="setup-check">✓ ${esc(x)}</div>`).join('')}</div>${textArea('setup','Your labelled set-up record','Draw a labelled sketch in your paper lab book or describe the actual arrangement used. Record relevant instrument ranges/resolutions and any settings.',e,6)}`;
 if(i===2)html=`${textArea('variables','Variables','Identify the independent, dependent and important control variables. State how each control variable was kept constant.',e,5)}${textArea('method','Method as actually carried out','Record enough detail, including settings and changes, for a competent student to understand or repeat what you did. Do not simply copy a pre-written method after the lesson.',e,7)}<div class="lab-prompt"><b>What to measure:</b> ${esc(f.measure)}</div>`;
 if(i===3)html=`${textArea('safety','Safety / risk controls','Record the controls your teacher or technician required and the precautions relevant to the apparatus you actually used. Do not invent a generic list.',e,6)}<div class="lab-prompt"><b>App note:</b> this simulation supports revision; real practical work follows your school/college risk assessment and staff instructions.</div>`;
 if(i===4)html=`<div class="lab-actions"><button class="secondary-btn" id="importLabData">Use recorded simulation data</button></div>${textArea('rawData','Raw data table / readings','Enter readings while the experiment is taking place, with headings and units. Keep raw readings separate from processed values.',e,8)}${textArea('observations','Observations / what happened','Record useful qualitative observations, anomalies, equipment behaviour and anything that affected the run.',e,5)}<div class="lab-prompt"><b>Measurement focus:</b> ${esc(f.measure)}</div>`;
 if(i===5)html=`${textArea('uncertainty','Measurement uncertainty','Estimate the uncertainty of relevant measurements and explain where repeat spread or instrument resolution was used.',e,6)}${textArea('calculations','Calculations','Show equations, substitutions, units and processed values clearly enough that your reasoning can be followed.',e,7)}<div class="lab-prompt"><b>Uncertainty focus:</b> ${esc(f.unc)}</div>`;
 if(i===6)html=`${textArea('graph','Graph / data processing record','State the plotted axes with units, any transformation used, best-fit method, gradient/intercept and the physical meaning extracted from the graph.',e,7)}<div class="lab-prompt"><b>For this practical:</b> ${esc(f.graph)}</div>`;
 if(i===7)html=`${textArea('conclusion','Conclusion','Answer the aim using your evidence. Quote a result/relationship with units where appropriate and say whether the evidence supports the expected physics.',e,6)}${textArea('evaluation','Evaluation','Identify specific limitations supported by your results, distinguish random/systematic effects where possible, and propose realistic improvements.',e,7)}`;
 if(i===8)html=`${textArea('changes','Changes made during the practical','Record any method changes, repeated runs, rejected readings (with a reason) or problems that occurred. A lab book is a live record, not a rewritten perfect version.',e,5)}${textArea('references','References / cross-references','Record sources used, worksheet/page references, data-file names, graph pages or links to earlier related work.',e,4)}${textArea('reflection','CPAC / skills reflection','Briefly note which practical skills you demonstrated and what you would improve next time. Teacher assessment/sign-off remains with your school or college.',e,5)}`;
 return `<div class="lab-step-card"><div class="lab-step-head"><div><span class="eyebrow">LAB BOOK STEP ${i+1} OF 9</span><h3>${stepTitle(i)}</h3></div><label class="lab-complete"><input type="checkbox" id="labStepDone" ${e.completed?.[i]?'checked':''}> Step complete</label></div>${html}<div class="lab-step-nav"><button class="secondary-btn" id="labPrev" ${i===0?'disabled':''}>← Previous</button><button class="primary-btn" id="labNext">${i===8?'Back to overview':'Next step →'}</button></div></div>`;
}
let selected=1,step=0;
function renderLabBook(){const root=document.querySelector('#labBookRoot');if(!root)return;selected=+document.querySelector('#labPracticalSelect')?.value||selected||1;const p=practical(selected),e=entry(selected),c=completion(e);root.innerHTML=`<section class="labbook-intro"><div><span class="eyebrow">AQA-ALIGNED RECORDING WORKFLOW</span><h2>Practical ${p.id}: ${esc(p.title)}</h2><p>AQA says a dedicated lab book is not itself a requirement, but A-level students must keep an appropriate record of practical work. The handbook describes a lab book as a live record that can include methods, raw data, uncertainty, calculations, graphs, conclusions and references.</p></div><div class="labbook-progress"><strong>${c.pct}%</strong><span>${c.n} of ${c.total} steps complete</span><div><i style="width:${c.pct}%"></i></div></div></section><div class="labbook-toolbar"><label>Practical <select id="labPracticalSelect">${practicals.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${x.id}. ${esc(x.title)}</option>`).join('')}</select></label><button class="secondary-btn" id="labPrint">Print / save record</button><button class="secondary-btn" id="labCopy">Copy entry summary</button><button class="secondary-btn" id="labOpenPractical">Open simulation</button></div><div class="aqa-lab-guidance"><b>How AQA describes good lab-book practice</b><div class="guidance-grid"><span>Date each page/entry.</span><span>Record notes as the practical happens rather than rewriting a perfect copy later.</span><span>Keep raw data, observations and changes visible.</span><span>Include method details/settings and measurement uncertainties.</span><span>Show annotated calculations, graphs, discussion and conclusions.</span><span>Cross-reference sources and related work.</span></div><small>Paper-lab-book conventions vary by school/college. Follow your teacher’s rules for ink, corrections, diagrams and attached printouts.</small></div><div class="lab-stepper">${Array.from({length:9},(_,i)=>`<button data-lab-step="${i}" class="${i===step?'active':''} ${e.completed?.[i]?'done':''}"><span>${i+1}</span>${['Identify','Set-up','Method','Safety','Raw data','Maths','Graph','Evaluate','Reflect'][i]}</button>`).join('')}</div>${renderStep(selected,step)}`;
 bindLabBook();}
function bindLabBook(){
 const sel=document.querySelector('#labPracticalSelect');if(sel)sel.onchange=e=>{selected=+e.target.value;step=0;renderLabBook();};
 document.querySelectorAll('[data-lab-step]').forEach(b=>b.onclick=()=>{step=+b.dataset.labStep;renderLabBook();});
 document.querySelectorAll('[data-lab-field]').forEach(el=>el.oninput=()=>{const e=entry(selected);e[el.dataset.labField]=el.value;save();});
 const done=document.querySelector('#labStepDone');if(done)done.onchange=e=>{entry(selected).completed[step]=e.target.checked;save();renderLabBook();};
 const prev=document.querySelector('#labPrev');if(prev)prev.onclick=()=>{if(step>0){step--;renderLabBook();}};
 const next=document.querySelector('#labNext');if(next)next.onclick=()=>{step=step===8?0:step+1;renderLabBook();};
 const imp=document.querySelector('#importLabData');if(imp)imp.onclick=()=>{const e=entry(selected),txt=dataText(selected);e.rawData=(e.rawData?e.rawData+'\n\n':'')+txt;save();renderLabBook();};
 const op=document.querySelector('#labOpenPractical');if(op)op.onclick=()=>navigate('practical',selected);
 const pr=document.querySelector('#labPrint');if(pr)pr.onclick=()=>window.print();
 const cp=document.querySelector('#labCopy');if(cp)cp.onclick=async()=>{const p=practical(selected),e=entry(selected);let txt=`Practical ${p.id}: ${p.title}\nDate: ${e.date||''}\n\nAim\n${e.aim||''}\n\nSet-up\n${e.setup||''}\n\nVariables\n${e.variables||''}\n\nMethod\n${e.method||''}\n\nSafety\n${e.safety||''}\n\nRaw data\n${e.rawData||''}\n\nObservations\n${e.observations||''}\n\nUncertainty\n${e.uncertainty||''}\n\nCalculations\n${e.calculations||''}\n\nGraph\n${e.graph||''}\n\nConclusion\n${e.conclusion||''}\n\nEvaluation\n${e.evaluation||''}\n\nChanges\n${e.changes||''}\n\nReferences\n${e.references||''}\n\nReflection\n${e.reflection||''}`;try{await navigator.clipboard.writeText(txt);cp.textContent='Copied ✓';setTimeout(()=>cp.textContent='Copy entry summary',1200);}catch(err){alert('Copy was not available in this browser.');}};
}
const priorNavigate=navigate;navigate=function(view,id){const out=priorNavigate(view,id);if(view==='labbook'){if(id)selected=+id;setTimeout(renderLabBook,0);}return out;};
const priorOpen=openPractical;openPractical=function(id){priorOpen(id);setTimeout(()=>{const strip=document.querySelector('.action-strip');if(strip&&!strip.querySelector('#openLabBookBtn')){const b=document.createElement('button');b.id='openLabBookBtn';b.className='secondary-btn';b.textContent='Lab book entry';b.onclick=()=>{selected=current.id;step=0;navigate('labbook');};strip.appendChild(b);}},0);};
window.renderLabBook=renderLabBook;
})();