(() => {
 'use strict';
 const $=id=>document.getElementById(id),core=RevisionQuestionBank,key='revision-source-bank-v1';
 let bank,sets=[],active,mode=new URLSearchParams(location.search).get('mode')==='mark'?'mark':'answer',store={drafts:{},games:{}},examples=[],gameChecked=false;
 const node=(tag,content,cls)=>{const e=document.createElement(tag);if(content!==undefined)e.textContent=content;if(cls)e.className=cls;return e;};
 try{const value=JSON.parse(localStorage.getItem(key));if(value&&typeof value==='object'&&!Array.isArray(value))store={drafts:value.drafts&&typeof value.drafts==='object'?value.drafts:{},games:value.games&&typeof value.games==='object'?value.games:{}};}catch{}
 function save(){try{localStorage.setItem(key,JSON.stringify(store));$('bank-storage').textContent='Drafts and progress saved on this device.';}catch{$('bank-storage').textContent='Device storage is full or unavailable. You can continue this session; copy any answers you want to keep.';}}
 function draft(){return store.drafts[active.id]||(store.drafts[active.id]=core.safeDraft(active,null));}
 function html(host,value){host.innerHTML=value;}
 function content(value,cls='source-content'){const e=node('div',undefined,cls);html(e,value);return e;}
 function button(label,fn){const b=node('button',label);b.type='button';b.onclick=fn;return b;}
 function choices(max,name){const s=node('select');s.setAttribute('aria-label',name);s.append(new Option('Choose marks…',''));for(let i=0;i<=max;i++)s.append(new Option(`${i} / ${max}`,String(i)));return s;}
 function updateURL(){const u=new URL(location.href);u.searchParams.set('mode',mode);for(const [key,value]of [['subject',$('bank-subject').value],['pathway',$('bank-pathway').value],['topic',$('bank-topic').value]])u.searchParams.set(key,value);if(active)u.searchParams.set('set',active.id);else u.searchParams.delete('set');if($('bank-search').value)u.searchParams.set('search',$('bank-search').value);else u.searchParams.delete('search');history.replaceState({},'',u);}
 function filtered(){return bank.sets.filter(s=>s.subject===$('bank-subject').value&&($('bank-pathway').value==='all'||s.scope===$('bank-pathway').value)&&(mode!=='mark'||core.canMark(s)));}
 function topics(){const previous=$('bank-topic').value,values=[...new Set(filtered().map(s=>s.topic))];$('bank-topic').replaceChildren(new Option('All topics','all'),...values.map(v=>new Option(v,v)));if(values.includes(previous))$('bank-topic').value=previous;}
 function refresh(preferred){const q=$('bank-search').value.trim().toLowerCase();sets=filtered().filter(s=>($('bank-topic').value==='all'||s.topic===$('bank-topic').value)&&(!q||(s.title+' '+s.sourceHeading+' '+s.parts.map(p=>p.html.replace(/<[^>]+>/g,' ')).join(' ')).toLowerCase().includes(q)));active=sets.find(s=>s.id===preferred)||sets[0];$('bank-set').replaceChildren(...sets.map(s=>new Option(`${s.title} · ${s.marks} marks`,s.id)));$('bank-set').disabled=!active;$('bank-workspace').hidden=!active;$('bank-empty').hidden=!!active;$('bank-count').textContent=`${sets.length} sets match · 106 supplied sets · 143 question parts · ${mode==='mark'?'compare the supplied student answers':'complete a set to reveal its answers'}`;['bank-previous','bank-next','bank-random'].forEach(id=>$(id).disabled=!active);if(active){$('bank-set').value=active.id;render();}updateURL();}
 function render(){gameChecked=false;$('bank-feedback').textContent='';$('bank-review').hidden=true;$('bank-review').replaceChildren();$('bank-questions').replaceChildren();$('bank-actions').replaceChildren();$('bank-meta').textContent=`GCSE · ${active.subject} · ${active.scope==='combined'?'Combined Science':'Separate Science'} · ${active.topic}`;$('bank-title').textContent=active.title;$('bank-description').textContent=active.details;$('bank-previous').disabled=sets.indexOf(active)===0;$('bank-next').disabled=sets.indexOf(active)===sets.length-1;
  if(mode==='mark')renderMarking();else renderAnswers();
 }
 function unlock(){const d=draft();d.completed=false;d.selfMarks={};$('bank-review').hidden=true;$('bank-review').replaceChildren();$('bank-feedback').textContent='Answer changed. Complete the set again to reveal feedback.';save();}
 function sketch(part,d,card){const details=node('details');details.append(node('summary','Optional sketch or diagram'));details.append(node('p','Use a mouse, pen or touch to sketch. You can also describe your diagram in the answer box.','bank-note'));const canvas=node('canvas');canvas.width=800;canvas.height=400;canvas.setAttribute('aria-label',`Sketch for question ${part.label}`);canvas.className='bank-sketch';const ctx=canvas.getContext('2d');ctx.strokeStyle='#172738';ctx.lineWidth=3;ctx.lineCap='round';let drawing=false,changed=false;const xy=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*800/r.width,(e.clientY-r.top)*400/r.height];};if(d.sketches[part.label]){const image=new Image();image.onload=()=>ctx.drawImage(image,0,0);image.src=d.sketches[part.label];}
  canvas.onpointerdown=e=>{if(e.button!==0)return;drawing=true;changed=false;canvas.setPointerCapture(e.pointerId);const [x,y]=xy(e);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+.1,y+.1);ctx.stroke();changed=true;};canvas.onpointermove=e=>{if(!drawing)return;ctx.lineTo(...xy(e));ctx.stroke();changed=true;};const finish=()=>{if(!drawing)return;drawing=false;if(changed){d.sketches[part.label]=canvas.toDataURL('image/png');unlock();}};canvas.onpointerup=finish;canvas.onpointercancel=finish;details.append(canvas,button('Clear sketch',()=>{ctx.clearRect(0,0,800,400);delete d.sketches[part.label];unlock();}));card.append(details);
 }
 function renderAnswers(){const d=store.drafts[active.id]=core.safeDraft(active,store.drafts[active.id]);html($('bank-context'),active.contextHtml);$('bank-context').hidden=!active.contextHtml;active.parts.forEach(part=>{const card=node('article',undefined,'bank-card');card.append(node('h3',`Question ${part.label} · ${part.marks} ${part.marks===1?'mark':'marks'}`),content(part.html));const label=node('label','Your answer'),answer=node('textarea');answer.rows=5;answer.maxLength=40000;answer.value=d.answers[part.label]||'';answer.setAttribute('aria-label',`Your answer to ${part.label}`);answer.placeholder='Write your answer and working here…';answer.oninput=()=>{d.answers[part.label]=answer.value;unlock();};label.append(answer);card.append(label);sketch(part,d,card);$('bank-questions').append(card);});$('bank-actions').append(button('Complete set & reveal answers',()=>{if(!core.complete(active,d)){$('bank-feedback').textContent='Answer every part before revealing the mark scheme. You can write an answer or add a sketch.';return;}d.completed=true;save();review();$('bank-feedback').textContent='Set completed. Compare your answers with the supplied mark scheme and examples, then record your self-assessed marks.';}));if(d.completed)review();}
 function details(title,value){const d=node('details');d.append(node('summary',title),content(value));return d;}
 function review(){const host=$('bank-review');host.hidden=false;host.replaceChildren(node('h2','Review your answer'));host.append(details('Supplied mark scheme',active.schemeHtml));if(active.modelHtml)host.append(details('Supplied full-marks / model answer',active.modelHtml));if(active.partialHtml)host.append(details(active.modelHtml?'Supplied partial answer and marking commentary':'Supplied example answer and marking commentary',active.partialHtml));const card=node('div',undefined,'bank-card');card.append(node('h3','Record your self-assessed marks'),node('p','Use the mark scheme above. These written answers are self-assessed.','bank-note'));const selects=new Map();for(const part of active.parts){const label=node('label',`Question ${part.label}`),select=choices(part.marks,`Self-assessed marks for ${part.label}`);if(draft().selfMarks?.[part.label]!==undefined)select.value=String(draft().selfMarks[part.label]);selects.set(part.label,select);label.append(select);card.append(label);}const feedback=node('p');feedback.setAttribute('role','status');card.append(button('Save self-assessment',()=>{const marks=Object.fromEntries([...selects].map(([id,s])=>[id,s.value===''?null:Number(s.value)])),result=core.selfScore(active,marks);if(!result){feedback.textContent='Choose marks for every part.';return;}draft().selfMarks=marks;save();feedback.textContent=`Self-assessed score: ${result.score} / ${result.max}. Choose another set to keep practising.`;}),feedback);host.append(card);}
 function renderMarking(){html($('bank-context'),active.questionHtml);$('bank-context').hidden=false;const note=node('p','Award marks to each supplied answer. The answer labels are shuffled so you need to judge the science. Original marking commentary appears after you choose all scores.','bank-note');$('bank-questions').append(note);examples=active.markingExamples.map(e=>({e,order:crypto.getRandomValues(new Uint32Array(1))[0]})).sort((a,b)=>a.order-b.order).map(x=>x.e);examples.forEach((e,i)=>{const card=node('article',undefined,'bank-card');card.append(node('h3',`Student answer ${String.fromCharCode(65+i)} · question ${e.label}`),content(e.answerHtml));const label=node('label',`How many marks out of ${e.max}?`),s=choices(e.max,`Marks for student answer ${String.fromCharCode(65+i)}`);s.id='student-marks-'+i;label.append(s);card.append(label);$('bank-questions').append(card);});const check=button('Check my marking',()=>{if(gameChecked)return;const picks=examples.map((_,i)=>$('student-marks-'+i).value===''?null:Number($('student-marks-'+i).value)),result=core.award(examples,picks);if(!result){$('bank-feedback').textContent='Choose a mark for every student answer first.';return;}gameChecked=true;check.disabled=true;examples.forEach((e,i)=>{const s=$('student-marks-'+i);s.disabled=true;const feedback=node('p',`${picks[i]===e.score?'Correct.':'Compare your judgement.'} The supplied marking awards ${e.score} / ${e.max}.`,'mark-result');s.closest('article').append(feedback);});store.games[active.id]={correct:result.correct,total:result.total};save();$('bank-feedback').textContent=`You matched ${result.correct} of ${result.total} supplied scores. Read the mark scheme and original commentary to understand why.`;const host=$('bank-review');host.hidden=false;host.replaceChildren(node('h2','Marking feedback'),details('Supplied mark scheme',active.schemeHtml),details('Original marked example and commentary',active.partialHtml));if(active.modelHtml)host.append(details('Supplied full-marks answer',active.modelHtml));});$('bank-actions').append(check);}
 function move(delta){const s=sets[sets.indexOf(active)+delta];if(s){active=s;$('bank-set').value=s.id;render();updateURL();$('bank-title').scrollIntoView({block:'start'});}}
 async function init(){try{const response=await fetch('bank.json');if(!response.ok)throw Error('Question bank could not be loaded.');bank=await response.json();const params=new URLSearchParams(location.search);for(const s of bank.sets)store.drafts[s.id]=core.safeDraft(s,store.drafts[s.id]);$('mode-answer').removeAttribute('aria-current');$('mode-mark').removeAttribute('aria-current');$(mode==='mark'?'mode-mark':'mode-answer').setAttribute('aria-current','page');$('bank-subject').value=['biology','chemistry','physics'].includes(params.get('subject'))?params.get('subject'):'physics';$('bank-pathway').value=['combined','triple'].includes(params.get('pathway'))?params.get('pathway'):'all';$('bank-search').value=params.get('search')||'';topics();if([...$('bank-topic').options].some(o=>o.value===params.get('topic')))$('bank-topic').value=params.get('topic');refresh(params.get('set'));}catch(e){$('bank-count').textContent='Unable to load the question banks. Reload the page to try again.';$('bank-feedback').textContent=e.message;}}
 const filters=['bank-subject','bank-pathway','bank-topic','bank-search'];
 for(const id of [...filters,'bank-set','bank-previous','bank-next','bank-random'])$(id).disabled=true;
 for(const id of ['bank-subject','bank-pathway'])$(id).onchange=()=>{topics();refresh();};$('bank-topic').onchange=()=>refresh();$('bank-search').oninput=()=>refresh(active?.id);$('bank-set').onchange=()=>{active=sets.find(s=>s.id===$('bank-set').value);render();updateURL();};$('bank-previous').onclick=()=>move(-1);$('bank-next').onclick=()=>move(1);$('bank-random').onclick=()=>{if(!sets.length)return;active=sets[crypto.getRandomValues(new Uint32Array(1))[0]%sets.length];$('bank-set').value=active.id;render();updateURL();};$('bank-clear').onclick=()=>{$('bank-search').value='';$('bank-topic').value='all';refresh();};init().then(()=>{if(bank)for(const id of filters)$(id).disabled=false;});
})();
