'use strict';
(()=>{
if(window.__meV7Loaded)return;window.__meV7Loaded=true;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const set=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const S={profile:get('meV7Profile',{name:'Student',level:'A-level',lang:'English'}),skills:get('meV7Skills',{}),review:get('meV7Review',[]),notebook:get('meV7Notebook',[]),teacher:get('meV7TeacherContent',[]),confidence:get('meV7Confidence',{}),classroom:get('meV7Classroom',[]),difficulty:get('meV7Difficulty',3)};
const skills=['Instrument reading','Uncertainty','Propagation','Graphing','Evaluation','Experimental design','Data analysis','Significant figures'];
const skillKey=s=>s.toLowerCase().replace(/\s+/g,'_');
function save(){set('meV7Profile',S.profile);set('meV7Skills',S.skills);set('meV7Review',S.review);set('meV7Notebook',S.notebook);set('meV7TeacherContent',S.teacher);set('meV7Confidence',S.confidence);set('meV7Classroom',S.classroom);set('meV7Difficulty',S.difficulty)}
function bump(skill,n=1){const k=skillKey(skill);S.skills[k]=Math.max(0,Math.min(100,(S.skills[k]||0)+n));save();renderPassport();renderAdaptive()}
function addNav(view,label,before='spec'){const nav=q('.main-nav');if(!nav||q(`[data-view="${view}"]`))return;const b=document.createElement('button');b.className='nav-button';b.dataset.view=view;b.textContent=label;const r=nav.querySelector(`[data-view="${before}"]`);r?nav.insertBefore(b,r):nav.appendChild(b);b.onclick=()=>{showView(view);if(view==='v7lab')renderBench();if(view==='learning')renderLearning();if(view==='assessment')renderAssessment();if(view==='teacher')renderTeacherExtensions()}}
addNav('v7lab','Advanced Lab','formula');addNav('learning','Learning Hub','mastery');addNav('assessment','Assessment Lab','teacher');
const spec=q('#view-spec');
const insert=html=>spec?.insertAdjacentHTML('beforebegin',html);
insert(`<section class="view" id="view-v7lab"><div class="section-head"><div><span class="eyebrow">Build, measure, diagnose</span><h2>Advanced Virtual Laboratory</h2></div><p class="muted">Construct investigations, import real data, use camera overlays, explore blind practicals and connect compatible browser sensors.</p></div><div class="v7-tabs"><button class="button primary" data-v7lab="bench">Lab Bench</button><button class="button" data-v7lab="gltf">GLTF Apparatus</button><button class="button" data-v7lab="camera">Camera / AR</button><button class="button" data-v7lab="data">Real Data</button><button class="button" data-v7lab="sensor">Sensors</button><button class="button" data-v7lab="blind">Blind Practical</button><button class="button" data-v7lab="linear">Linearisation</button><button class="button" data-v7lab="optimiser">Uncertainty Optimiser</button><button class="button" data-v7lab="methods">Compare Methods</button></div><div id="v7LabContent"></div></section>`);
insert(`<section class="view" id="view-learning"><div class="section-head"><div><span class="eyebrow">Personal learning</span><h2>Adaptive Learning Hub</h2></div><p class="muted">Profiles, spaced retrieval, confidence tracking, practical portfolio, challenge mode, accessibility and cross-topic links.</p></div><div class="v7-tabs"><button class="button primary" data-learn="profile">Profile</button><button class="button" data-learn="retrieval">Spaced Retrieval</button><button class="button" data-learn="mastery">Mastery Map</button><button class="button" data-learn="notebook">Lab Notebook</button><button class="button" data-learn="challenge">Challenge Mode</button><button class="button" data-learn="access">Accessibility / EAL</button><button class="button" data-learn="links">Physics Links</button></div><div id="learningContent"></div></section>`);
insert(`<section class="view" id="view-assessment"><div class="section-head"><div><span class="eyebrow">Generate, mark, improve</span><h2>Assessment Laboratory</h2></div><p class="muted">Build papers, generate Paper 3 practice, act as examiner, track confidence and create targeted questions from mistakes.</p></div><div class="v7-tabs"><button class="button primary" data-assess="builder">Paper Builder</button><button class="button" data-assess="paper3">Full Paper 3</button><button class="button" data-assess="examiner">Examiner Commentary</button><button class="button" data-assess="personal">Personal Generator</button><button class="button" data-assess="escape">Escape Room</button><button class="button" data-assess="video">Interactive Practical</button></div><div id="assessmentContent"></div></section>`);

const benchTools=[['Ruler','resolution 1 mm'],['Vernier','resolution 0.1 mm'],['Micrometer','resolution 0.01 mm'],['Stopwatch','manual timing'],['Light gate','electronic timing'],['Balance','mass / g'],['Thermometer','temperature'],['Multimeter','electrical measurement']];
let benchItems=[];
function renderBench(){showLab('bench')}
function showLab(mode){qa('[data-v7lab]').forEach(b=>b.classList.toggle('primary',b.dataset.v7lab===mode));const c=q('#v7LabContent');if(!c)return;if(mode==='bench'){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card v7-wide"><h3>Full Virtual Lab Bench</h3><p class="muted">Drag apparatus onto the bench, position it, then build a method.</p><div class="apparatus-tray">${benchTools.map((x,i)=>`<button class="apparatus-chip" data-tool="${i}">${x[0]}</button>`).join('')}</div><div class="lab-bench" id="labBench"></div><div class="button-row"><button class="button primary" id="benchMission">Generate mission</button><button class="button" id="clearBench">Clear bench</button></div><div id="benchFeedback" class="feedback hidden"></div></article></div>`;qa('[data-tool]').forEach(b=>b.onclick=()=>addBench(+b.dataset.tool));q('#clearBench').onclick=()=>{benchItems=[];drawBench()};q('#benchMission').onclick=mission;drawBench()}else if(mode==='gltf')gltfUI(c);else if(mode==='camera')cameraUI(c);else if(mode==='data')dataUI(c);else if(mode==='sensor')sensorUI(c);else if(mode==='blind')blindUI(c);else if(mode==='linear')linearUI(c);else if(mode==='optimiser')optimiserUI(c);else methodsUI(c)}
qa('[data-v7lab]').forEach(b=>b.onclick=()=>showLab(b.dataset.v7lab));
function addBench(i){benchItems.push({i,x:40+benchItems.length*120,y:160+(benchItems.length%2)*80});drawBench()}
function drawBench(){const b=q('#labBench');if(!b)return;b.innerHTML=benchItems.map((o,j)=>`<div class="bench-item" data-bi="${j}" style="left:${o.x}px;top:${o.y}px">${benchTools[o.i][0]}<small>${benchTools[o.i][1]}</small></div>`).join('');qa('.bench-item',b).forEach(el=>{let ox=0,oy=0,down=false;const start=e=>{down=true;const p=e.touches?e.touches[0]:e;ox=p.clientX-el.offsetLeft;oy=p.clientY-el.offsetTop;e.preventDefault()};const move=e=>{if(!down)return;const p=e.touches?e.touches[0]:e;const r=b.getBoundingClientRect(),idx=+el.dataset.bi;benchItems[idx].x=Math.max(0,Math.min(r.width-el.offsetWidth,p.clientX-r.left-ox+r.left));benchItems[idx].y=Math.max(0,Math.min(r.height-el.offsetHeight,p.clientY-r.top-oy+r.top));el.style.left=benchItems[idx].x+'px';el.style.top=benchItems[idx].y+'px';e.preventDefault()};const end=()=>down=false;el.addEventListener('mousedown',start);window.addEventListener('mousemove',move);window.addEventListener('mouseup',end);el.addEventListener('touchstart',start,{passive:false});window.addEventListener('touchmove',move,{passive:false});window.addEventListener('touchend',end)})}
function mission(){const missions=[['Determine the density of a metal cylinder with the lowest practical percentage uncertainty.',['Balance','Vernier']],['Measure a pendulum period while minimising reaction-time uncertainty.',['Stopwatch']],['Measure a thin wire diameter accurately.',['Micrometer']],['Investigate a short transit time.',['Light gate']]];const m=missions[Math.floor(Math.random()*missions.length)],names=benchItems.map(x=>benchTools[x.i][0]),ok=m[1].every(x=>names.includes(x));const f=q('#benchFeedback');f.className='feedback '+(ok?'good':'partial');f.innerHTML=`<strong>Mission:</strong> ${m[0]}<br>${ok?'Your apparatus can support this investigation. Now justify range, resolution, repeats and uncertainty.':'Consider adding: '+m[1].filter(x=>!names.includes(x)).join(', ')+'.'}`;f.classList.remove('hidden');bump('Experimental design',ok?5:1)}

function gltfUI(c){
 c.innerHTML=`<div class="v7-grid"><article class="panel v7-card v7-wide"><h3>Photoreal-ready GLTF Apparatus Library</h3><p class="muted">These are real glTF model assets rendered with Three.js. Rotate/zoom the apparatus and swap models.</p><div id="gltfStage" class="camera-box" style="height:480px"></div><div class="button-row"><button class="button primary" data-model="micrometer">Micrometer</button><button class="button" data-model="caliper">Vernier</button><button class="button" data-model="meter">Analogue meter</button></div><div id="gltfInfo" class="equation"></div></article></div>`;
 if(!window.THREE||!THREE.GLTFLoader){q('#gltfStage').innerHTML='<div style="padding:30px">3D model loader unavailable. The procedural v6 3D lab remains available.</div>';return}
 const host=q('#gltfStage'),scene=new THREE.Scene();scene.background=new THREE.Color(0x07111f);const camera=new THREE.PerspectiveCamera(42,host.clientWidth/480,.1,100);camera.position.set(7,5,8);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(host.clientWidth,480);renderer.setPixelRatio(Math.min(2,devicePixelRatio||1));renderer.shadowMap.enabled=true;host.innerHTML='';host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x223344,2.0));const dl=new THREE.DirectionalLight(0xffffff,2.8);dl.position.set(5,8,5);dl.castShadow=true;scene.add(dl);const ground=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x263545,roughness:.8}));ground.rotation.x=-Math.PI/2;ground.position.y=-2;ground.receiveShadow=true;scene.add(ground);let model=null,drag=false,last={x:0,y:0},yaw=.2,pitch=.15,dist=10;
 function load(name){if(model)scene.remove(model);const loader=new THREE.GLTFLoader();loader.load(MeasurementsGLTFLibrary.models[name],g=>{model=g.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.material.roughness=.3;o.material.metalness=.65}});scene.add(model);q('#gltfInfo').innerHTML='<strong>'+name+'</strong> loaded from a local glTF asset. Drag to rotate · wheel to zoom.'},undefined,e=>q('#gltfInfo').textContent='Could not load model: '+e.message)}
 renderer.domElement.onpointerdown=e=>{drag=true;last={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId)};renderer.domElement.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-last.x)*.01;pitch=Math.max(-1.1,Math.min(1.1,pitch+(e.clientY-last.y)*.01));last={x:e.clientX,y:e.clientY}};renderer.domElement.onpointerup=()=>drag=false;renderer.domElement.onwheel=e=>{dist=Math.max(4,Math.min(18,dist+e.deltaY*.01));e.preventDefault()};qa('[data-model]').forEach(b=>b.onclick=()=>load(b.dataset.model));
 function anim(){if(!host.isConnected){renderer.dispose();return}requestAnimationFrame(anim);camera.position.set(Math.sin(yaw)*Math.cos(pitch)*dist,Math.sin(-pitch)*dist+1,Math.cos(yaw)*Math.cos(pitch)*dist);camera.lookAt(0,0,0);renderer.render(scene,camera)}load('micrometer');anim();
}

function cameraUI(c){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card"><h3>Camera Measurement / AR Overlay</h3><div class="camera-box"><video id="cam" autoplay playsinline></video><div class="ar-overlay"></div></div><div class="button-row"><button class="button primary" id="camStart">Start camera</button><button class="button" id="camStop">Stop</button></div><p class="muted small">Use the crosshair to align a scale or apparatus. Camera access depends on browser permission.</p></article><article class="panel v7-card"><h3>Reading check</h3><label class="field"><span>Apparatus</span><select id="camType"><option>Ruler</option><option>Micrometer</option><option>Vernier</option><option>Analogue meter</option></select></label><label class="field"><span>Your reading</span><input id="camRead" type="number" step="any"></label><button class="button primary" id="camMark">Record reading</button><div id="camFeed" class="feedback hidden"></div></article></div>`;let stream=null;q('#camStart').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});q('#cam').srcObject=stream}catch(e){alert('Camera unavailable or permission denied.') }};q('#camStop').onclick=()=>{stream?.getTracks().forEach(t=>t.stop());stream=null};q('#camMark').onclick=()=>{const f=q('#camFeed');f.className='feedback good';f.innerHTML='Reading recorded. Explain the instrument resolution and realistic uncertainty before accepting the result.';f.classList.remove('hidden');bump('Instrument reading',3)}}
function dataUI(c){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card"><h3>Real Data Import</h3><input type="file" id="csvFile" accept=".csv,text/csv"><textarea id="csvPaste" rows="8" placeholder="Or paste two-column CSV data here"></textarea><button class="button primary" id="analyseCSV">Analyse data</button></article><article class="panel v7-card"><h3>Analysis</h3><div id="csvResult" class="worked">Import data to calculate mean, range, regression and flag possible anomalies.</div></article></div>`;q('#csvFile').onchange=async e=>{q('#csvPaste').value=await e.target.files[0].text()};q('#analyseCSV').onclick=()=>analyseCSV(q('#csvPaste').value)}
function analyseCSV(txt){const rows=txt.trim().split(/\r?\n/).map(r=>r.split(',').map(Number)).filter(r=>r.length>=2&&r.every(Number.isFinite));if(rows.length<2){q('#csvResult').textContent='Need at least two numeric rows.';return}const xs=rows.map(r=>r[0]),ys=rows.map(r=>r[1]),mean=ys.reduce((a,b)=>a+b,0)/ys.length,range=Math.max(...ys)-Math.min(...ys),sx=xs.reduce((a,b)=>a+b,0),sy=ys.reduce((a,b)=>a+b,0),sxx=xs.reduce((a,b)=>a+b*b,0),sxy=rows.reduce((a,r)=>a+r[0]*r[1],0),n=rows.length,m=(n*sxy-sx*sy)/(n*sxx-sx*sx),inter=(sy-m*sx)/n,res=rows.map(r=>Math.abs(r[1]-(m*r[0]+inter))),lim=(res.reduce((a,b)=>a+b,0)/n)*2.5,anoms=rows.filter((r,i)=>res[i]>lim);q('#csvResult').innerHTML=`Rows: <strong>${n}</strong><br>Mean y: <strong>${mean.toPrecision(4)}</strong><br>Range: <strong>${range.toPrecision(4)}</strong><br>Best-fit: <strong>y = ${m.toPrecision(4)}x + ${inter.toPrecision(4)}</strong><br>Possible anomalies: <strong>${anoms.length}</strong>`;bump('Data analysis',5);addNotebook('Imported data',`Analysed ${n} rows; gradient ${m.toPrecision(4)}.`)}
function sensorUI(c){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card"><h3>Live Sensor Support</h3><p>Use Web Serial with compatible Arduino/microcontroller sensors. Incoming lines can be captured as experimental data.</p><button class="button primary" id="serialConnect">Connect serial device</button><button class="button" id="serialStop">Stop</button><div class="sensor-box"><pre id="serialLog"></pre></div></article><article class="panel v7-card"><h3>Sensor notes</h3><p class="muted">This uses the browser's Web Serial API where available. It does not install drivers or bypass device permissions.</p></article></div>`;let reader=null;q('#serialConnect').onclick=async()=>{if(!('serial'in navigator)){alert('Web Serial is not supported in this browser.');return}try{const port=await navigator.serial.requestPort();await port.open({baudRate:9600});reader=port.readable.getReader();while(true){const {value,done}=await reader.read();if(done)break;q('#serialLog').textContent+=new TextDecoder().decode(value);}}catch(e){q('#serialLog').textContent+='\nConnection ended.'}};q('#serialStop').onclick=()=>reader?.cancel()}
function blindUI(c){const rels=[['A pendulum experiment gives T as length changes.','Plot T² against L','gradient should be approximately 4π²/g'],['A wire experiment measures extension for different forces.','Plot extension against force','gradient relates to stiffness/compliance'],['A light experiment varies distance and intensity.','Plot intensity against 1/r²','a straight line supports inverse-square behaviour']];const r=rels[Math.floor(Math.random()*rels.length)];c.innerHTML=`<article class="panel v7-card"><h3>Blind Practical</h3><p>${r[0]}</p><p class="muted">The expected relationship is hidden. Decide how to transform the data.</p><label class="field"><span>Your proposed graph</span><input id="blindAnswer"></label><button class="button primary" id="blindCheck">Check reasoning</button><div id="blindFeed" class="feedback hidden"></div></article>`;q('#blindCheck').onclick=()=>{const t=q('#blindAnswer').value.toLowerCase(),ok=r[1].toLowerCase().split(' ').filter(x=>x.length>2).some(x=>t.includes(x));const f=q('#blindFeed');f.className='feedback '+(ok?'good':'partial');f.innerHTML=`Suggested approach: <strong>${r[1]}</strong>; ${r[2]}.`;f.classList.remove('hidden');bump('Experimental design',ok?5:2)}}
function linearUI(c){c.innerHTML=`<article class="panel v7-card"><h3>Graph Linearisation Trainer</h3><label class="field"><span>Relationship</span><select id="linRel"><option value="square">y ∝ x²</option><option value="inverse">y ∝ 1/x</option><option value="root">y ∝ √x</option><option value="exp">y = Ae^(kx)</option></select></label><div class="choice-list" id="linChoices"></div><div id="linFeed" class="feedback hidden"></div></article>`;const opts=['plot y against x','plot y against x²','plot y against 1/x','plot y² against x','plot ln(y) against x'];const render=()=>{q('#linChoices').innerHTML=opts.map(o=>`<button class="choice">${o}</button>`).join('');qa('.choice',q('#linChoices')).forEach(b=>b.onclick=()=>{const ans={square:'plot y against x²',inverse:'plot y against 1/x',root:'plot y² against x',exp:'plot ln(y) against x'}[q('#linRel').value],ok=b.textContent===ans;const f=q('#linFeed');f.className='feedback '+(ok?'good':'bad');f.textContent=ok?'Correct linearisation.':'Not linear. Correct choice: '+ans;f.classList.remove('hidden');bump('Graphing',ok?5:0)})};q('#linRel').onchange=render;render()}
function optimiserUI(c){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card"><h3>Uncertainty Optimiser</h3><label class="field"><span>Resolution</span><input type="range" id="optRes" min="0.01" max="1" step="0.01" value="0.2"></label><label class="field"><span>Measured interval</span><input type="range" id="optVal" min="1" max="100" step="1" value="20"></label><label class="field"><span>Repeats</span><input type="range" id="optRep" min="1" max="50" step="1" value="5"></label></article><article class="panel v7-card"><h3>Live impact</h3><div id="optResult" class="equation"></div><p class="muted">Increasing the measured interval and repeating random measurements can improve the relative quality, but neither automatically fixes systematic error.</p></article></div>`;const run=()=>{const r=+q('#optRes').value,x=+q('#optVal').value,n=+q('#optRep').value,p=r/x*100/Math.sqrt(n);q('#optResult').innerHTML=`Estimated relative random contribution ≈ <strong>${p.toFixed(3)}%</strong><br>resolution/value = ${(r/x*100).toFixed(3)}% · repeats = ${n}`};qa('#optRes,#optVal,#optRep').forEach(x=>x.oninput=run);run()}
function methodsUI(c){const methods=[['Ruler only',1,'cheap/simple but high % uncertainty'],['Vernier calipers',4,'better resolution and suitable range'],['Micrometer',5,'best for small wire diameter but limited range']];c.innerHTML=`<article class="panel v7-card"><h3>Compare Experimental Methods</h3><div class="v7-grid">${methods.map((m,i)=>`<div class="method-card ${i===2?'best':''}"><h3>${m[0]}</h3><p>Relative quality score: ${m[1]}/5</p><p>${m[2]}</p></div>`).join('')}</div><p class="callout">Best method depends on the quantity, required range and resolution—not simply on choosing the most expensive instrument.</p></article>`}

qa('[data-learn]').forEach(b=>b.onclick=()=>showLearn(b.dataset.learn));
function renderLearning(){showLearn('profile')}
function showLearn(mode){qa('[data-learn]').forEach(b=>b.classList.toggle('primary',b.dataset.learn===mode));const c=q('#learningContent');if(!c)return;if(mode==='profile')profileUI(c);else if(mode==='retrieval')retrievalUI(c);else if(mode==='mastery')masteryUI(c);else if(mode==='notebook')notebookUI(c);else if(mode==='challenge')challengeUI(c);else if(mode==='access')accessUI(c);else linksUI(c)}
function profileUI(c){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card"><h3>Local Student Profile</h3><label class="field"><span>Name</span><input id="profName" value="${S.profile.name||''}"></label><label class="field"><span>Level</span><select id="profLevel"><option>A-level</option><option>AS</option></select></label><label class="field"><span>Language support</span><select id="profLang"><option>English</option><option>English + Mandarin glossary</option><option>English + Spanish glossary</option></select></label><button class="button primary" id="saveProfile">Save locally</button></article><article class="panel v7-card"><h3>Progress follows this browser</h3><p class="muted">No cloud account is required. Progress is stored locally. A backend can be added later for cross-device syncing.</p><div class="profile-chip"><strong>${S.profile.name}</strong><span>${S.profile.level}</span></div></article></div>`;q('#saveProfile').onclick=()=>{S.profile={name:q('#profName').value||'Student',level:q('#profLevel').value,lang:q('#profLang').value};save();profileUI(c)}}
const retrievalBank=[['Why does averaging reduce random error but not systematic error?','repeats reduce random scatter; systematic offset remains','Evaluation'],['State the percentage uncertainty equation.','Δx/x × 100%','Uncertainty'],['How do percentage uncertainties combine for Q = ab²/c?','%a + 2%b + %c','Propagation'],['Why use a large triangle for gradient?','reduces percentage reading uncertainty','Graphing'],['What is resolution?','smallest detectable change','Instrument reading']];
function retrievalUI(c){const now=Date.now();const due=S.review.filter(x=>x.due<=now);const item=(due[0]||{idx:Math.floor(Math.random()*retrievalBank.length)}),r=retrievalBank[item.idx];c.innerHTML=`<article class="panel v7-card"><h3>Spaced Retrieval</h3><p>${r[0]}</p><textarea id="retrievalAnswer" rows="4"></textarea><div class="confidence-row"><button class="button" data-conf="1">Guessing</button><button class="button" data-conf="2">Unsure</button><button class="button" data-conf="3">Confident</button><button class="button" data-conf="4">Very confident</button></div><div class="button-row"><button class="button primary" id="retrievalShow">Check / reveal</button></div><div id="retrievalFeed" class="feedback hidden"></div></article>`;let conf=2;qa('[data-conf]').forEach(b=>b.onclick=()=>{conf=+b.dataset.conf;qa('[data-conf]').forEach(x=>x.classList.toggle('active',x===b))});q('#retrievalShow').onclick=()=>{const ans=q('#retrievalAnswer').value.toLowerCase(),keywords=r[1].toLowerCase().split(/[^a-z%]+/).filter(x=>x.length>4),hits=keywords.filter(k=>ans.includes(k)).length,ok=hits>=Math.max(1,Math.floor(keywords.length/3));const days=ok?(conf>=3?7:3):1;S.review=S.review.filter(x=>x.idx!==item.idx);S.review.push({idx:item.idx,due:Date.now()+days*86400000});S.confidence[item.idx]=conf;bump(r[2],ok?4:0);save();const f=q('#retrievalFeed');f.className='feedback '+(ok?'good':'partial');f.innerHTML=`Model focus: ${r[1]}. Next review in ${days} day${days>1?'s':''}.`;f.classList.remove('hidden')}}
function renderPassport(){const el=q('#passportBars');if(!el)return;el.innerHTML=skills.map(s=>{const v=S.skills[skillKey(s)]||0;return `<div class="skill-row"><span>${s}</span><div class="skill-track"><div class="skill-fill" style="width:${v}%"></div></div><strong>${v}%</strong></div>`}).join('')}
function masteryUI(c){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card"><h3>Practical Skills Passport</h3><div id="passportBars" class="skill-bars"></div></article><article class="panel v7-card"><h3>Mastery Map</h3><div class="cross-topic">${skills.map(s=>`<div class="topic-link"><strong>${s}</strong><p class="muted small">${(S.skills[skillKey(s)]||0)>=70?'Secure':'Keep practising'}</p></div>`).join('')}</div></article></div>`;renderPassport()}
function addNotebook(title,text){S.notebook.unshift({title,text,date:new Date().toLocaleString()});S.notebook=S.notebook.slice(0,50);save()}
function notebookUI(c){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card"><h3>Digital Practical Notebook</h3><label class="field"><span>Title</span><input id="noteTitle"></label><textarea id="noteText" rows="8" placeholder="Method, data, uncertainty, evaluation..."></textarea><div class="button-row"><button class="button primary" id="saveNote">Save entry</button><button class="button" id="exportPortfolio">Export portfolio</button></div></article><article class="panel v7-card"><h3>Entries</h3><div id="noteList">${S.notebook.map(n=>`<div class="notebook-entry"><strong>${n.title}</strong><div class="small muted">${n.date}</div><p>${n.text}</p></div>`).join('')||'<p class="muted">No entries yet.</p>'}</div></article></div>`;q('#saveNote').onclick=()=>{addNotebook(q('#noteTitle').value||'Practical entry',q('#noteText').value);notebookUI(c)};q('#exportPortfolio').onclick=()=>{const html=`<html><body><h1>${S.profile.name} – Measurements & Errors Practical Portfolio</h1>${S.notebook.map(n=>`<h2>${n.title}</h2><p>${n.date}</p><p>${n.text}</p>`).join('')}</body></html>`;const blob=new Blob([html],{type:'text/html'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='practical-portfolio.html';a.click()}}
function challengeUI(c){const d=S.difficulty;const qs=[['Foundation','A reading is 20.0 ± 0.5 cm. Find % uncertainty.',2.5],['Secure','A = xy, uncertainties 2% and 3%. Find % uncertainty.',5],['A-level','A = x²/y; uncertainties 2% and 4%. Find % uncertainty.',8],['Stretch','A best gradient is 3.20 and worst acceptable gradient is 3.44. Find % gradient uncertainty.',7.5],['A/A*','A cylinder has d uncertainty 1% and length uncertainty 2%. Estimate % uncertainty in volume.',4]][d-1];c.innerHTML=`<article class="panel v7-card"><h3>Adaptive Challenge Mode</h3><span class="difficulty-pill">${qs[0]}</span><p>${qs[1]}</p><input id="challengeAns" type="number" step="any"><div class="button-row"><button class="button primary" id="challengeCheck">Check</button><button class="button" id="challengeHarder">Harder</button><button class="button" id="challengeEasier">Easier</button></div><div id="challengeFeed" class="feedback hidden"></div></article>`;q('#challengeCheck').onclick=()=>{const ok=Math.abs(+q('#challengeAns').value-qs[2])<0.15;const f=q('#challengeFeed');f.className='feedback '+(ok?'good':'bad');f.textContent=ok?'Correct. Difficulty can increase.':'Recheck which uncertainty rule applies.';f.classList.remove('hidden');if(ok)S.difficulty=Math.min(5,S.difficulty+1);save();bump('Uncertainty',ok?5:0)};q('#challengeHarder').onclick=()=>{S.difficulty=Math.min(5,S.difficulty+1);save();challengeUI(c)};q('#challengeEasier').onclick=()=>{S.difficulty=Math.max(1,S.difficulty-1);save();challengeUI(c)}}
function accessUI(c){c.innerHTML=`<article class="panel v7-card"><h3>Accessibility & EAL</h3><div class="accessibility-grid"><label class="choice"><input type="checkbox" id="accLarge"> Larger text</label><label class="choice"><input type="checkbox" id="accContrast"> High contrast</label><label class="choice"><input type="checkbox" id="accDys"> Dyslexia-friendly spacing</label><label class="choice"><input type="checkbox" id="accMotion"> Reduced motion</label></div><label class="field"><span>Physics glossary support</span><select id="accLang"><option>English</option><option>Mandarin glossary</option><option>Spanish glossary</option></select></label><div id="glossary" class="callout">uncertainty = quantified doubt in a measurement · precision = closeness of repeated readings</div></article>`;const body=document.body;const apply=()=>{body.classList.toggle('large-text',q('#accLarge').checked);body.classList.toggle('high-contrast',q('#accContrast').checked);body.classList.toggle('dyslexia-friendly',q('#accDys').checked);body.classList.toggle('reduced-motion',q('#accMotion').checked)};qa('#accLarge,#accContrast,#accDys,#accMotion').forEach(x=>x.onchange=apply);q('#accLang').onchange=()=>{q('#glossary').textContent=q('#accLang').value==='Mandarin glossary'?'uncertainty 不确定度 · precision 精密度 · accuracy 准确度 · resolution 分辨率':q('#accLang').value==='Spanish glossary'?'uncertainty incertidumbre · precision precisión · accuracy exactitud · resolution resolución':'uncertainty = quantified doubt in a measurement · precision = closeness of repeated readings'}}
function linksUI(c){const topics=[['Electricity','resistivity: length, diameter, V and I uncertainties'],['Mechanics','g from pendulum/projectile data and gradient uncertainty'],['Materials','Young modulus: diameter dominates area uncertainty'],['Waves','diffraction measurements and angular uncertainty'],['Nuclear','count-rate statistics, background subtraction and uncertainty'],['Fields','graph linearisation and gradient interpretation']];c.innerHTML=`<article class="panel v7-card"><h3>Cross-topic Practical Links</h3><div class="cross-topic">${topics.map(t=>`<div class="topic-link"><strong>${t[0]}</strong><p>${t[1]}</p></div>`).join('')}</div><p class="callout">The same measurement engine can be reused across your other A-level Physics apps.</p></article>`}
function renderAdaptive(){const el=q('#teacherWeaknessV7')||q('#adaptiveV7');if(!el)return;const weak=skills.map(s=>[s,S.skills[skillKey(s)]||0]).sort((a,b)=>a[1]-b[1]).slice(0,3);el.innerHTML=weak.map(x=>`<div class="adaptive-card"><strong>${x[0]}</strong><span class="muted small">Current mastery ${x[1]}% · target this next.</span></div>`).join('')}

qa('[data-assess]').forEach(b=>b.onclick=()=>showAssess(b.dataset.assess));
function renderAssessment(){showAssess('builder')}
function showAssess(mode){qa('[data-assess]').forEach(b=>b.classList.toggle('primary',b.dataset.assess===mode));const c=q('#assessmentContent');if(!c)return;if(mode==='builder')paperBuilder(c);else if(mode==='paper3')paper3(c);else if(mode==='examiner')examinerUI(c);else if(mode==='personal')personalUI(c);else if(mode==='escape')escapeUI(c);else videoUI(c)}
const bank=[{topic:'Uncertainty',m:2,q:'A length is 0.840 ± 0.002 m. Calculate the percentage uncertainty.',a:'0.24%'},{topic:'Propagation',m:3,q:'Q = ab²/c. Uncertainties are 2%, 3%, 4%. Find % uncertainty in Q.',a:'12%'},{topic:'Graphing',m:3,q:'Explain how to estimate uncertainty in the gradient of a straight-line graph.',a:'Draw best and worst acceptable lines and compare gradients.'},{topic:'Evaluation',m:4,q:'Explain how to improve measurement of a pendulum period.',a:'Time many oscillations, repeat, average, use fiducial marker/electronic timing.'},{topic:'Instrument reading',m:2,q:'Why is a micrometer more suitable than a ruler for a 0.4 mm wire?',a:'Suitable range and much finer resolution.'},{topic:'Significant figures',m:2,q:'Report 12.347 cm with uncertainty ±0.6 cm appropriately.',a:'12.3 ± 0.6 cm'}];
function paperBuilder(c){c.innerHTML=`<div class="v7-grid"><article class="panel v7-card"><h3>Exam Paper Builder</h3><label class="field"><span>Total marks target</span><input id="paperMarks" type="number" value="20" min="5" max="60"></label><label class="field"><span>Difficulty</span><select id="paperDiff"><option>Mixed</option><option>Foundation</option><option>Standard</option><option>Stretch</option></select></label><button class="button primary" id="makePaper">Generate paper</button></article><article class="panel v7-card"><h3>Generated paper</h3><div id="paperOut"></div></article></div>`;q('#makePaper').onclick=()=>{let total=0,out=[],i=0,target=+q('#paperMarks').value;while(total<target&&i<30){const z=bank[i%bank.length];out.push(z);total+=z.m;i++}q('#paperOut').innerHTML=out.map((z,i)=>`<div class="paper-question"><span class="eyebrow">${z.topic} · ${z.m} marks</span><p>${i+1}. ${z.q}</p><details><summary>Mark scheme</summary>${z.a}</details></div>`).join('');bump('Data analysis',2)}}
function paper3(c){const scenario='A student investigates how the period of a pendulum depends on its length. They measure several lengths, time repeated oscillations, calculate T and plot T² against L.';c.innerHTML=`<article class="panel v7-card"><h3>Full Paper 3 Simulation</h3><p>${scenario}</p>${bank.slice(0,5).map((z,i)=>`<div class="paper-question"><span class="paper-mark">[${z.m}]</span> ${i+1}. ${z.q}<textarea rows="3" data-p3="${i}"></textarea></div>`).join('')}<button class="button primary" id="markP3">Mark paper</button><div id="p3Feed" class="feedback hidden"></div></article>`;q('#markP3').onclick=()=>{const filled=qa('[data-p3]').filter(x=>x.value.trim().length>8).length,score=Math.round(filled/5*14);const f=q('#p3Feed');f.className='feedback '+(score>=10?'good':'partial');f.innerHTML=`Completion-based practice score: <strong>${score}/14</strong>. Use Examiner Mode for detailed mark-point comparison.`;f.classList.remove('hidden');bump('Evaluation',filled)}}
function examinerUI(c){const z=bank[Math.floor(Math.random()*bank.length)];c.innerHTML=`<article class="panel v7-card"><h3>Examiner Commentary</h3><p><strong>Question:</strong> ${z.q}</p><textarea id="examinerAns" rows="6"></textarea><button class="button primary" id="examinerMark">Analyse response</button><div id="examinerFeed" class="feedback hidden"></div></article>`;q('#examinerMark').onclick=()=>{const txt=q('#examinerAns').value.toLowerCase(),keys=z.a.toLowerCase().split(/[^a-z]+/).filter(x=>x.length>5),hits=keys.filter(k=>txt.includes(k));const f=q('#examinerFeed');f.className='feedback '+(hits.length?'partial':'bad');f.innerHTML=`Likely evidence present: <strong>${hits.slice(0,5).join(', ')||'limited'}</strong>.<br><strong>Model mark points:</strong> ${z.a}<br><strong>Improve:</strong> use precise measurement language and link each improvement to how it reduces uncertainty or corrects bias.`;f.classList.remove('hidden')}}
function personalUI(c){const weak=skills.map(s=>[s,S.skills[skillKey(s)]||0]).sort((a,b)=>a[1]-b[1])[0][0],matches=bank.filter(x=>x.topic===weak||weak.includes(x.topic));const z=matches[0]||bank[0];c.innerHTML=`<article class="panel v7-card"><h3>Personal Question Generator</h3><p>Your weakest tracked skill is <strong>${weak}</strong>.</p><div class="paper-question">${z.q}</div><textarea id="personalAns" rows="4"></textarea><button class="button primary" id="personalMark">Check</button><div id="personalFeed" class="feedback hidden"></div></article>`;q('#personalMark').onclick=()=>{const f=q('#personalFeed');f.className='feedback partial';f.innerHTML=`Model focus: ${z.a}`;f.classList.remove('hidden');bump(weak,3)}}
function escapeUI(c){const stages=[['Convert 250 μm to metres.','0.00025'],['A value is 10.0 ± 0.2. Find % uncertainty.','2'],['x has 3% uncertainty. What is % uncertainty in x²?','6']];let i=0;c.innerHTML=`<article class="panel v7-card"><h3>Measurement Escape Room</h3><div id="escQ"></div><input id="escA"><button class="button primary" id="escGo">Unlock</button><div id="escF" class="feedback hidden"></div></article>`;const show=()=>q('#escQ').innerHTML=`Stage ${i+1}/${stages.length}: <strong>${stages[i][0]}</strong>`;q('#escGo').onclick=()=>{const ok=q('#escA').value.replace(/\s/g,'').includes(stages[i][1]);if(ok&&i<stages.length-1){i++;q('#escA').value='';show()}else{const f=q('#escF');f.className='feedback '+(ok?'good':'bad');f.textContent=ok?'Lab unlocked — all stages complete.':'Not yet. Recheck units or uncertainty rule.';f.classList.remove('hidden')}};show()}
function videoUI(c){const steps=[['A student times one swing of a pendulum.','Time many oscillations instead.'],['The eye views a ruler scale from an angle.','Move the eye perpendicular to the scale to reduce parallax.'],['A micrometer is used without checking zero.','Close it first and check/correct zero error.']];let i=0;c.innerHTML=`<article class="panel v7-card"><h3>Interactive Practical Decisions</h3><div class="camera-box" style="display:grid;place-items:center;min-height:300px"><div id="vidScene" style="font-size:1.2rem;padding:30px;text-align:center"></div></div><label class="field"><span>What should happen next?</span><input id="vidAns"></label><button class="button primary" id="vidCheck">Check decision</button><div id="vidFeed" class="feedback hidden"></div></article>`;const show=()=>q('#vidScene').textContent=steps[i][0];q('#vidCheck').onclick=()=>{const f=q('#vidFeed');f.className='feedback good';f.textContent=steps[i][1];f.classList.remove('hidden');i=(i+1)%steps.length;setTimeout(()=>{show();f.classList.add('hidden')},1600);bump('Evaluation',2)};show()}

function renderTeacherExtensions(){const view=q('#view-teacher');if(!view||q('#v7TeacherExt'))return;view.insertAdjacentHTML('beforeend',`<div id="v7TeacherExt" class="v7-grid" style="margin-top:16px"><article class="panel v7-card"><h3>Teacher-created Content</h3><label class="field"><span>Question / challenge</span><input id="teacherCustomQ"></label><label class="field"><span>Answer / guidance</span><input id="teacherCustomA"></label><button class="button primary" id="saveTeacherQ">Save activity</button><div id="teacherCustomList"></div></article><article class="panel v7-card"><h3>Local Classroom Dashboard</h3><div class="heatmap" id="classHeat"></div><div class="live-room"><strong>Live classroom mode</strong><p class="muted small">Uses BroadcastChannel between tabs/windows on this device/browser profile; a real multi-device classroom needs a backend.</p><button class="button" id="broadcastQ">Broadcast current challenge</button></div></article><article class="panel v7-card v7-wide"><h3>Adaptive Class Focus</h3><div id="teacherWeaknessV7"></div></article></div>`);const list=()=>q('#teacherCustomList').innerHTML=S.teacher.map((x,i)=>`<div class="notebook-entry"><strong>${x.q}</strong><p>${x.a}</p></div>`).join('')||'<p class="muted">No custom activities yet.</p>';q('#saveTeacherQ').onclick=()=>{S.teacher.unshift({q:q('#teacherCustomQ').value,a:q('#teacherCustomA').value});save();list()};list();q('#classHeat').innerHTML=skills.slice(0,8).map(s=>`<div class="heat-cell"><strong>${S.skills[skillKey(s)]||0}%</strong>${s}</div>`).join('');q('#broadcastQ').onclick=()=>{if('BroadcastChannel'in window){const bc=new BroadcastChannel('measurements-class');bc.postMessage({type:'challenge',text:S.teacher[0]?.q||retrievalBank[0][0]});alert('Challenge broadcast to other open app tabs on this browser profile.')}else alert('BroadcastChannel unsupported.')};renderAdaptive()}

// Voice viva: add shortcut into learning hub profile
function addVoiceButton(){const nav=q('.pills');if(!nav||q('#voiceViva'))return;const b=document.createElement('button');b.className='pill';b.id='voiceViva';b.textContent='Voice Viva';b.style.cursor='pointer';b.onclick=startViva;nav.appendChild(b)}
function startViva(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Speech recognition is not supported in this browser.');return}const prompts=['Why are repeated measurements useful?','Explain the difference between precision and accuracy.','How would you reduce percentage uncertainty in a timing experiment?'];const p=prompts[Math.floor(Math.random()*prompts.length)];if(!confirm('Voice viva question:\n\n'+p+'\n\nPress OK and answer aloud.'))return;const r=new SR();r.lang='en-GB';r.onresult=e=>{const t=e.results[0][0].transcript;alert('You said: '+t+'\n\nNow compare your reasoning with the relevant lesson and examiner language.');bump('Evaluation',2)};r.start()}
addVoiceButton();

// GLTF apparatus library hook: integrates with existing Three.js lab if loader available.
window.MeasurementsGLTFLibrary={models:{micrometer:'models/micrometer.gltf',caliper:'models/vernier.gltf',meter:'models/analogue-meter.gltf'},load(name,scene){if(!window.THREE||!THREE.GLTFLoader)return Promise.reject(new Error('GLTF loader unavailable'));return new Promise((res,rej)=>new THREE.GLTFLoader().load(this.models[name],g=>{scene.add(g.scene);res(g.scene)},undefined,rej))}};

// Offline/PWA registration
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').then(()=>{const p=q('.pills');if(p&&!q('#offlineReady')){const s=document.createElement('span');s.id='offlineReady';s.className='pill offline-badge';s.innerHTML='<i class="offline-dot ready"></i> Offline ready';p.appendChild(s)}}).catch(()=>{}))}

// initialize first tabs and expose functions
window.v7={showLab,showLearn,showAssess,bump,addNotebook};
})();
