'use strict';(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
if(q('#view-exam'))return;
const nav=q('.main-nav'),spec=q('#view-spec');
function insertBefore(el,html){el.insertAdjacentHTML('beforebegin',html)}
function storageGet(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function storageSet(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
let EX=storageGet('meV4Exam',{attempts:0,best:0,last:0}),timer=null,seconds=20*60,started=false;
const paper=[
  {t:'calc',topic:'Uncertainty',m:2,q:'A length is 0.840 ± 0.002 m. Calculate the percentage uncertainty.',answer:0.238095,tol:.01,unit:'%'},
  {t:'calc',topic:'Propagation',m:2,q:'Q = ab²/c. The percentage uncertainties in a, b and c are 2%, 3% and 4%. Calculate the percentage uncertainty in Q.',answer:12,tol:.01,unit:'%'},
  {t:'mc',topic:'Errors',m:1,q:'Which action most directly reduces random uncertainty?',choices:['Calibrate the instrument','Repeat and average','Apply a zero correction','Change the SI unit'],answer:1},
  {t:'mc',topic:'Resolution',m:1,q:'Resolution is best defined as:',choices:['closeness to the true value','smallest detectable change','spread of repeat readings','largest readable value'],answer:1},
  {t:'calc',topic:'Graph skills',m:3,q:'A best-fit gradient is 2.40 and a worst acceptable gradient is 2.55. Calculate the percentage uncertainty in the gradient.',answer:6.25,tol:.02,unit:'%'},
  {t:'text',topic:'Practical skills',m:4,q:'Explain how to obtain a reliable diameter of a thin wire using a micrometer.',keys:['zero','repeat','position','mean'],model:'Check/correct zero error, take repeat readings at different positions/orientations, use consistent pressure and calculate a mean with a realistic uncertainty.'},
  {t:'calc',topic:'Units',m:2,q:'Convert 2.50 eV to joules. Use 1 eV = 1.602 × 10⁻¹⁹ J.',answer:4.005e-19,tol:5e-22,unit:'J'},
  {t:'text',topic:'Evaluation',m:3,q:'Repeated readings are tightly clustered but all disagree with an accepted value. Explain what this suggests.',keys:['precis','systematic','inaccur'],model:'The readings are precise but inaccurate, suggesting a systematic error such as calibration or zero offset.'}
];
if(nav){const b=document.createElement('button');b.className='nav-button';b.dataset.view='exam';b.textContent='Exam Mode';nav.insertBefore(b,nav.querySelector('[data-view="spec"]'));b.onclick=()=>{showView('exam');renderExamSummary()}}
if(spec)insertBefore(spec,`<section class="view" id="view-exam"><div class="section-head"><div><span class="eyebrow">Paper 3-style practice</span><h2>Timed Measurements & Errors mini assessment</h2></div><p class="muted">Mixed calculation, data-analysis and practical-skills practice with marking after submission.</p></div><div class="exam-grid"><article class="panel pad"><div class="progress-head"><div><span class="eyebrow">20 marks</span><h3>Mini assessment</h3></div><div class="exam-timer" id="examTimer">20:00</div></div><div id="examQuestions"></div><div class="button-row"><button class="button primary" id="startExam">Start / reset paper</button><button class="button" id="submitExam">Submit & mark</button></div><div id="examFeedback" class="feedback hidden"></div></article><aside class="panel pad"><h3>Adaptive revision</h3><div class="v4-kpi"><div><strong id="examBest">0</strong><span class="muted small">best / 20</span></div><div><strong id="examAttempts">0</strong><span class="muted small">attempts</span></div><div><strong id="coursePercentV4">0%</strong><span class="muted small">course</span></div></div><div id="adaptiveRevision" style="margin-top:14px"></div><div class="button-row"><button class="button" id="exportProgress">Export progress CSV</button></div></aside></div></section>`);
const plannerBtn=document.createElement('button');plannerBtn.className='button';plannerBtn.dataset.practical='planner';plannerBtn.textContent='Method planner';const ps=q('#practicalSwitch');if(ps)ps.appendChild(plannerBtn);
const pv=q('#view-practical');if(pv)pv.insertAdjacentHTML('beforeend',`<div class="practical-panel hidden" id="practical-planner"><div class="planner-grid"><article class="panel pad"><span class="eyebrow">Practical planning</span><h3>Method & uncertainty planner</h3><label class="field"><span>Measurement scenario</span><select id="planScenario"><option value="wire">Wire diameter</option><option value="pendulum">Pendulum period</option><option value="gradient">Linear graph investigation</option><option value="temperature">Temperature change</option></select></label><label class="field"><span>Primary limitation</span><select id="planLimitation"><option value="resolution">Instrument resolution</option><option value="random">Random scatter</option><option value="systematic">Systematic offset</option><option value="reaction">Reaction time</option></select></label><button class="button primary" id="buildPlan">Build method</button></article><article class="panel pad"><h3>Suggested method</h3><div id="planOutput"></div></article></div></div>`);
plannerBtn.onclick=()=>{practicalSwitch('planner');buildPlan()};
function renderPaper(){q('#examQuestions').innerHTML=paper.map((z,i)=>`<section class="exam-question" data-eq="${i}"><span class="eyebrow">${z.topic} · ${z.m} mark${z.m>1?'s':''}</span><h3>${i+1}. ${z.q}</h3>${z.t==='mc'?`<div class="choice-list">${z.choices.map((c,j)=>`<label class="choice"><input type="radio" name="ex${i}" value="${j}"> ${c}</label>`).join('')}</div>`:z.t==='calc'?`<input type="text" inputmode="decimal" data-answer="${i}" placeholder="Enter numerical answer${z.unit?' in '+z.unit:''}">`:`<textarea data-answer="${i}" placeholder="Write a concise exam-style answer..."></textarea>`}<div class="small muted" data-mark="${i}"></div></section>`).join('')}
function tick(){if(!started)return;seconds=Math.max(0,seconds-1);paintTime();if(!seconds){started=false;clearInterval(timer)}}
function paintTime(){const m=Math.floor(seconds/60),s=seconds%60;q('#examTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function start(){clearInterval(timer);seconds=20*60;started=true;renderPaper();paintTime();timer=setInterval(tick,1000);q('#examFeedback').classList.add('hidden')}
function parseNumber(raw){return Number(String(raw).trim().replace(/\s/g,'').replace(/×10\^?(-?\d+)/i,'e$1'))}
function mark(){started=false;clearInterval(timer);let score=0,weak={};paper.forEach((z,i)=>{let got=0;if(z.t==='mc'){const r=q(`input[name="ex${i}"]:checked`);got=r&&+r.value===z.answer?z.m:0}else if(z.t==='calc'){const v=parseNumber(q(`[data-answer="${i}"]`).value);got=Number.isFinite(v)&&Math.abs(v-z.answer)<=z.tol?z.m:0}else{const txt=(q(`[data-answer="${i}"]`).value||'').toLowerCase();got=Math.min(z.m,z.keys.filter(k=>txt.includes(k)).length)}score+=got;if(got<z.m)weak[z.topic]=(weak[z.topic]||0)+(z.m-got);const box=q(`[data-mark="${i}"]`),parent=box.parentElement;box.innerHTML=`<strong>${got}/${z.m}</strong>${z.model?` · Model focus: ${z.model}`:''}`;parent.classList.remove('good','partial','bad');parent.classList.add('exam-result',got===z.m?'good':got?'partial':'bad')});EX.attempts++;EX.last=score;EX.best=Math.max(EX.best,score);EX.weak=weak;storageSet('meV4Exam',EX);const f=q('#examFeedback');f.className='feedback '+(score>=16?'good':score>=10?'partial':'bad');f.innerHTML=`<div class="exam-score">${score} / 20</div><p>${score>=16?'Strong performance.':'Use the adaptive revision panel to target the weakest areas.'}</p>`;renderExamSummary()}
function renderExamSummary(){if(!q('#examBest'))return;q('#examBest').textContent=EX.best||0;q('#examAttempts').textContent=EX.attempts||0;const cp=typeof state!=='undefined'?Math.round(state.completed.size/lessons.length*100):0;q('#coursePercentV4').textContent=cp+'%';let items=[];const weak=Object.entries(EX.weak||{}).sort((a,b)=>b[1]-a[1]);if(weak.length)items.push(...weak.slice(0,3).map(([k,v])=>`<div class="adaptive-card"><strong>${k}</strong><span class="muted small">Lost ${v} mark${v>1?'s':''} on the latest paper. Revisit the linked lesson/formula tool, then retry.</span></div>`));if(typeof state!=='undefined'&&state.completed.size<lessons.length){const l=lessons.find(x=>!state.completed.has(x.id));if(l)items.push(`<div class="adaptive-card"><strong>Next lesson: ${l.title}</strong><span class="muted small">Complete the guided lesson before another timed attempt.</span></div>`)}if(!items.length)items.push('<div class="adaptive-card"><strong>Ready for mixed practice</strong><span class="muted small">Use the data workspace, uncertainty challenge and timed paper to maintain fluency.</span></div>');q('#adaptiveRevision').innerHTML=items.join('')}
function exportProgress(){const v3=storageGet('meV3Stats',{}),rows=[['metric','value'],['completed_lessons',typeof state!=='undefined'?state.completed.size:0],['total_lessons',typeof lessons!=='undefined'?lessons.length:8],['exam_attempts',EX.attempts||0],['exam_best',EX.best||0],['exam_last',EX.last||0],['mastery_attempts',v3.quizAttempts||0],['mastery_correct',v3.quizCorrect||0],['sigfig_attempts',v3.sigAttempts||0],['sigfig_correct',v3.sigCorrect||0],['uncertainty_challenge_attempts',v3.chAttempts||0],['uncertainty_challenge_correct',v3.chCorrect||0]];const csv=rows.map(r=>r.join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='measurements-errors-progress.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const plans={wire:['Check the micrometer zero before measuring.','Use the ratchet/consistent pressure.','Measure at several positions and rotate the wire between readings.','Calculate a mean diameter.','Use repeat spread and instrument resolution to justify uncertainty.'],pendulum:['Measure length from pivot to centre of bob.','Use a fiducial marker at the equilibrium position.','Time many oscillations rather than one.','Repeat the total-time measurement and calculate mean period.','State how timing more oscillations reduces percentage timing uncertainty.'],gradient:['Choose an appropriate range of the independent variable.','Take repeated dependent-variable readings where practical.','Plot points with uncertainty/error bars.','Draw a best-fit line using the full range.','Draw one worst acceptable line and compare gradient/intercept with the best line.'],temperature:['Choose a thermometer/probe with suitable range and resolution.','Allow time for thermal equilibrium.','Keep geometry/immersion depth consistent.','Repeat runs where possible.','Discuss calibration, heat loss and resolution separately as systematic/random limitations.']};
function buildPlan(){const sc=q('#planScenario')?.value||'wire',lim=q('#planLimitation')?.value||'resolution',extra={resolution:'Record readings to a precision justified by the instrument resolution.',random:'Use repeats and averaging to reduce the influence of random scatter.',systematic:'Perform a zero/calibration check and apply a correction or redesign if necessary.',reaction:'Increase the timed interval or use electronic timing to reduce reaction-time percentage uncertainty.'}[lim];q('#planOutput').innerHTML=plans[sc].map((x,i)=>`<div class="planner-step"><b>${i+1}</b><div>${x}</div></div>`).join('')+`<div class="callout" style="margin-top:12px"><strong>Targeted improvement:</strong> ${extra}</div>`}
q('#startExam').onclick=start;q('#submitExam').onclick=mark;q('#exportProgress').onclick=exportProgress;q('#buildPlan').onclick=buildPlan;q('#planScenario').onchange=buildPlan;q('#planLimitation').onchange=buildPlan;renderPaper();paintTime();renderExamSummary();buildPlan();
})();
