(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SUBJECT_ANSWERS=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';const clean=s=>String(s).toLowerCase().replace(/−/g,'-').replace(/\s+/g,'').trim();
 function polynomial(input){const s=clean(input).replace(/²/g,'^2').replace(/³/g,'^3');if(s.length>160)throw Error('Expression too long');const tokens=s.match(/(?:\d+(?:\.\d+)?|\.\d+)|[x()+*/^\-]/g)||[];if(tokens.join('')!==s||!tokens.length)throw Error('Use numbers, x, brackets and arithmetic symbols.');let i=0;
 const trim=a=>{while(a.length>1&&Math.abs(a.at(-1))<1e-12)a.pop();if(a.length>7||a.some(v=>!Number.isFinite(v)||Math.abs(v)>1e12))throw Error('Expression exceeds the supported range');return a;};const add=(a,b,k=1)=>trim(Array.from({length:Math.max(a.length,b.length)},(_,j)=>(a[j]||0)+k*(b[j]||0)));const mul=(a,b)=>{const c=Array(a.length+b.length-1).fill(0);for(let j=0;j<a.length;j++)for(let k=0;k<b.length;k++)c[j+k]+=a[j]*b[k];return trim(c);};
 function atom(){let a;if(tokens[i]==='+'){i++;return atom();}if(tokens[i]==='-'){i++;return atom().map(v=>-v);}if(tokens[i]==='('){i++;a=sum();if(tokens[i++]!==')')throw Error('Close the bracket');}else if(tokens[i]==='x'){i++;a=[0,1];}else if(/^(?:\d|\.)/.test(tokens[i]||'')){a=[Number(tokens[i++])];}else throw Error('Invalid expression');if(tokens[i]==='^'){i++;const n=Number(tokens[i++]);if(!Number.isInteger(n)||n<0||n>6)throw Error('Use whole powers from 0 to 6');let c=[1];for(let j=0;j<n;j++)c=mul(c,a);a=c;}return a;}
 function product(){let a=atom();while(tokens[i]==='*'||tokens[i]==='/'||tokens[i]==='x'||tokens[i]==='('){const op=tokens[i]==='/'?tokens[i++]:tokens[i]==='*'?tokens[i++]:'*';const b=atom();if(op==='/'){if(b.length!==1||b[0]===0)throw Error('Divide only by a non-zero constant');a=a.map(v=>v/b[0]);}else a=mul(a,b);}return a;}
 function sum(){let a=product();while(tokens[i]==='+'||tokens[i]==='-'){const op=tokens[i++];a=add(a,product(),op==='+'?1:-1);}return a;}const result=trim(sum());if(i!==tokens.length)throw Error('Check the expression');return result;
 }
 function check(q,value){if(q.type==='written')return null;try{if(q.type==='number'||q.type==='expression'){const a=polynomial(value),b=polynomial(q.answer);return a.length===b.length&&a.every((v,i)=>Math.abs(v-b[i])<=(q.tolerance??1e-9)*Math.max(1,Math.abs(b[i])));}return [q.answer,...(q.accept||[])].some(a=>clean(a)===clean(value));}catch{return false;}}
 return {clean,polynomial,check};
});
