(() => {
 'use strict';const $=id=>document.getElementById(id),registry=window.REVISION_SUBJECT_COURSES,params=new URLSearchParams(location.search);let course,subject=params.get('subject'),view=params.get('view')||'course',tier=params.get('tier')||'foundation',option=params.get('option')||'all',query='',saved={};
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};const key=()=>`subject-course-progress:${subject}`;
 function loadSaved(){try{const s=JSON.parse(localStorage.getItem(key())||'{}');saved=s&&typeof s==='object'&&!Array.isArray(s)?s:{};}catch{saved={};}for(const k of ['lessons','notes'])if(!saved[k]||typeof saved[k]!=='object'||Array.isArray(saved[k]))saved[k]={};if(!Array.isArray(saved.bookmarks))saved.bookmarks=[];}
 function save(){try{localStorage.setItem(key(),JSON.stringify(saved));}catch{$('course-status').textContent='Storage is unavailable. Your work is still visible until you leave this page.';}}
 function route(next,lesson='',topic=''){const u=new URL(location.href);u.searchParams.set('subject',subject);u.searchParams.set('view',next);u.searchParams.set('tier',tier);if(option!=='all')u.searchParams.set('option',option);else u.searchParams.delete('option');for(const [k,v]of [['lesson',lesson],['topic',topic]])v?u.searchParams.set(k,v):u.searchParams.delete(k);return u.href;}
 function link(text,next,lesson='',topic=''){const a=el('a',text,'course-link');a.href=route(next,lesson,topic);return a;}
 const topics=()=>course.topics.filter(t=>option==='all'||t.option===option||!t.option);const lessons=t=>t.lessons.filter(l=>tier==='higher'||l.tier!=='higher');const allLessons=()=>topics().flatMap(t=>lessons(t).map(l=>({...l,topicId:t.id,topicTitle:t.title})));
 function header(){const meta=registry.find(c=>c.id===subject);document.title=`GCSE ${meta.title} · Spark`;$('course-title').textContent=`GCSE ${meta.title}`;$('course-description').textContent=course.introduction;$('course-controls').replaceChildren();const choose=el('select');choose.setAttribute('aria-label','Subject');choose.append(new Option('Choose a subject',''),...registry.map(c=>new Option(c.title,c.id)));choose.value=subject;choose.onchange=()=>location.assign('index.html?subject='+encodeURIComponent(choose.value));$('course-controls').append(choose);
 if(meta.tiers){const s=el('select');s.setAttribute('aria-label','Maths tier');s.append(new Option('Foundation','foundation'),new Option('Higher','higher'));s.value=tier;s.onchange=()=>{tier=s.value;location.assign(route(view));};$('course-controls').append(s);}
 if(course.options?.length){const s=el('select');s.setAttribute('aria-label','Course option');s.append(new Option('All supported options','all'),...course.options.map(o=>new Option(o.title,o.id)));s.value=option;s.onchange=()=>{option=s.value;location.assign(route('course'));};$('course-controls').append(s);}
 const spec=el('a',meta.spec);spec.href=meta.specUrl;spec.target='_blank';spec.rel='noopener';$('course-controls').append(spec);
 $('course-nav').replaceChildren(...[['course','Course'],['textbook','Textbook'],['practice','Practice'],['exam','Exam preparation'],['tools','Study tools'],['saved','Notes & bookmarks']].map(([v,title])=>{const a=link(title,v);if(v===view)a.setAttribute('aria-current','page');return a;}));const list=allLessons();$('course-progress').textContent=`${list.filter(l=>saved.lessons[l.id]).length} / ${list.length} lessons studied · ${topics().length} topics`;try{localStorage.setItem('revision-last-study-v1',JSON.stringify({path:'courses/subjects/index.html'+location.search}));}catch{}
 }
 function search(){const l=el('label','Find a topic or lesson'),input=el('input');input.type='search';input.placeholder='Search the textbook and lessons';input.value=query;input.oninput=()=>{query=input.value.toLowerCase();renderList();};l.append(input);$('course-content').append(l,el('div',undefined,'grid'));$('course-content').lastChild.id='course-list';renderList();}
 function renderList(){const box=$('course-list');box.replaceChildren();for(const t of topics()){const matches=lessons(t).filter(l=>!query||[t.title,l.title,...l.sections.map(s=>s.text)].join(' ').toLowerCase().includes(query));if(!matches.length)continue;const card=el('article',undefined,'card');card.append(el('span',t.code||'TOPIC','eyebrow'),el('h2',t.title),el('p',t.summary),el('small',`${matches.filter(l=>saved.lessons[l.id]).length} / ${matches.length} lessons studied`));for(const l of matches){const p=el('p');p.append(link((saved.lessons[l.id]?'✓ ':'')+l.title,'lesson',l.id,t.id));card.append(p);}card.append(link('Read textbook chapter','textbook','',t.id));box.append(card);}if(!box.children.length)box.append(el('p','No lessons match your search.'));}
 function content(l){const block=el('div');block.append(el('h2',l.title));if(l.tier==='higher')block.append(el('span','Higher tier','tag'));if(l.objectives?.length){block.append(el('h3','What you will learn'));const ul=el('ul');l.objectives.forEach(o=>ul.append(el('li',o)));block.append(ul);}for(const s of l.sections){block.append(el('h3',s.heading),el(s.kind==='code'?'pre':'p',s.text,s.kind==='extract'?'reading-passage':''));}const example=el('section',undefined,'worked');example.append(el('h3','Worked example'),el('p',l.worked.prompt));const ol=el('ol');l.worked.steps.forEach(s=>ol.append(el('li',s)));example.append(ol);block.append(example,el('p',l.misconception,'misconception'));return block;}
 function question(q,i){const card=el('article',undefined,'question');card.append(el('h3',`${i+1}. ${q.prompt}`));const label=el('label',q.type==='written'?'Write your response':'Your answer'),input=el(q.type==='written'?'textarea':'input');if(q.type!=='written')input.type='text';input.maxLength=5000;label.append(input);card.append(label);const feedback=el('div',undefined,'answer-feedback');feedback.setAttribute('aria-live','polite');const b=el('button',q.type==='written'?'Compare with the model':'Check answer');b.type='button';b.onclick=()=>{if(!input.value.trim()){feedback.textContent='Enter your answer first.';return;}const correct=window.SUBJECT_ANSWERS.check(q,input.value);feedback.textContent=correct===null?'Teacher / self review: compare your reasoning with the model below.':correct?'Correct. Check your working as well.':'Try again, or compare your method with the solution.';if(correct===null||correct===true){const detail=el('details');detail.append(el('summary',correct===null?'Model response and marking guidance':'Worked solution'),el('p',q.model||String(q.answer)));feedback.append(detail);}};const solution=el('details');solution.append(el('summary','Reveal solution'),el('p',q.model||String(q.answer)));card.append(b,feedback,solution);return card;}
 function notes(l){const aside=el('aside',undefined,'card');aside.append(el('h3','Your study notebook'));const label=el('label','Notes for this lesson'),ta=el('textarea');ta.value=saved.notes[l.id]||'';ta.maxLength=20000;ta.oninput=()=>{saved.notes[l.id]=ta.value;save();};label.append(ta);aside.append(label);const bookmark=el('button',saved.bookmarks.includes(l.id)?'Remove bookmark':'Bookmark lesson');bookmark.onclick=()=>{saved.bookmarks=saved.bookmarks.includes(l.id)?saved.bookmarks.filter(id=>id!==l.id):[...saved.bookmarks,l.id];save();bookmark.textContent=saved.bookmarks.includes(l.id)?'Remove bookmark':'Bookmark lesson';};const done=el('button',saved.lessons[l.id]?'Mark as not studied':'Mark lesson studied');done.onclick=()=>{saved.lessons[l.id]=!saved.lessons[l.id];for(const t of course.topics)saved[t.id]=t.lessons.every(x=>saved.lessons[x.id]);save();done.textContent=saved.lessons[l.id]?'Mark as not studied':'Mark lesson studied';header();};aside.append(bookmark,done,el('p','Studied progress records your choice; it is not an exam grade.','muted'));return aside;}
 function render(){header();const box=$('course-content');box.replaceChildren();const activeTopic=params.get('topic');if(view==='course')search();else if(view==='lesson'){const l=allLessons().find(l=>l.id===params.get('lesson'));if(!l){box.append(el('p','This lesson is unavailable for the chosen course option or tier.'),link('Return to course','course'));return;}const layout=el('div',undefined,'lesson-layout'),main=content(l);main.append(el('h3','Practice and recall'));l.questions.forEach((q,i)=>main.append(question(q,i)));main.append(el('h3','Exam application'),question({...l.exam,type:'written'},l.questions.length),link('Back to topic','course','',l.topicId));layout.append(main,notes(l));box.append(layout);}
 else if(view==='textbook'){const searchLabel=el('label','Search textbook chapters'),input=el('input');input.type='search';searchLabel.append(input);box.append(searchLabel);const chapters=el('div');box.append(chapters);const show=()=>{chapters.replaceChildren();for(const t of topics().filter(t=>!activeTopic||t.id===activeTopic)){const matches=lessons(t).filter(l=>[l.title,...l.sections.map(s=>s.text)].join(' ').toLowerCase().includes(input.value.toLowerCase()));if(!matches.length)continue;const chapter=el('article',undefined,'chapter');chapter.append(el('h2',t.title),el('p',t.summary));for(const l of matches){const detail=el('details');detail.append(el('summary',l.title),content(l),link('Open lesson and practice','lesson',l.id,t.id));chapter.append(detail);}chapters.append(chapter);}if(!chapters.children.length)chapters.append(el('p','No chapters match.'));};input.oninput=show;show();}
 else if(view==='practice'){const select=el('select');select.setAttribute('aria-label','Practice topic');select.append(new Option('All topics',''),...topics().map(t=>new Option(t.title,t.id)));const target=el('div'),b=el('button','Build practice set');b.onclick=()=>{target.replaceChildren();const bank=allLessons().filter(l=>!select.value||l.topicId===select.value).flatMap(l=>l.questions);const set=[...bank].sort(()=>Math.random()-.5).slice(0,10);set.forEach((q,i)=>target.append(question(q,i)));};box.append(el('h2','Practice what you have learned'),el('p','Numerical and supported algebra answers are checked automatically. Extended answers use model responses and teacher / self review.'),select,b,target);b.click();}
 else if(view==='exam'){box.append(el('h2','Exam preparation'),el('p',course.examGuide));for(const t of topics()){const d=el('details');d.append(el('summary',t.title));lessons(t).forEach((l,i)=>d.append(question({...l.exam,type:'written'},i)));box.append(d);}}
 else if(view==='tools')window.SUBJECT_TOOLS.render(box,subject,course);
 else if(view==='saved'){box.append(el('h2','Notes and bookmarks'));const stored=allLessons().filter(l=>saved.bookmarks.includes(l.id)||saved.notes[l.id]);for(const l of stored){const c=el('article',undefined,'card');c.append(link(l.title,'lesson',l.id,l.topicId),el('p',saved.notes[l.id]||'Bookmarked lesson'));box.append(c);}if(!stored.length)box.append(el('p','Open a lesson to save notes or a bookmark.'));}
 else{box.append(el('p','Choose a course view from the navigation.'));}}
 async function init(){if(!registry.some(c=>c.id===subject)){const box=$('course-content');box.className='grid';registry.forEach(c=>{const card=el('article',undefined,'card');card.append(el('h2',c.title),el('p',c.description));const a=el('a','Open course','course-link');a.href='index.html?subject='+c.id;card.append(a);box.append(card);});return;}try{const r=await fetch(subject+'.json');if(!r.ok)throw Error('Course content could not be loaded.');course=await r.json();loadSaved();render();}catch(e){$('course-content').textContent=e.message;}}
 init();
})();
