(() => {
  'use strict';
  const E=RevisionEquations,U=RevisionCalculationUI,$=id=>document.getElementById(id);
  let selected,question,answerForm,seed=freshSeed(),stats={attempted:0,independent:0},checked=false,revealed=false;
  function freshSeed(){return crypto.getRandomValues(new Uint32Array(1))[0];}
  try{const old=JSON.parse(localStorage.getItem('revision-equation-progress-v1'));if(old&&Number.isInteger(old.attempted)&&Number.isInteger(old.independent))stats=old;}catch{}
  function tab(name,focus=false){['learn','worked','try'].forEach(k=>{$(k+'-panel').hidden=k!==name;$(k+'-tab').setAttribute('aria-selected',String(k===name));$(k+'-tab').tabIndex=k===name?0:-1;});if(focus)$(name+'-tab').focus();}
  const tabs=['learn','worked','try'];tabs.forEach((k,i)=>{$(k+'-tab').addEventListener('click',()=>tab(k));$(k+'-tab').addEventListener('keydown',e=>{let index;if(e.key==='ArrowRight')index=(i+1)%3;else if(e.key==='ArrowLeft')index=(i+2)%3;else if(e.key==='Home')index=0;else if(e.key==='End')index=2;else return;e.preventDefault();tab(tabs[index],true);});});
  function list(){const items=E.available({level:$('eq-level').value,subject:$('eq-subject').value,pathway:$('eq-pathway').value});const search=$('eq-search').value.trim().toLowerCase();const visible=items.filter(d=>(d.name+' '+d.formula).toLowerCase().includes(search));$('eq-pathway').disabled=$('eq-level').value!=='gcse';$('eq-count').textContent=`${visible.length} equations`;const host=$('eq-library');host.replaceChildren();visible.forEach(d=>{const b=U.node('button',d.name);b.type='button';b.setAttribute('aria-pressed',String(selected?.id===d.id));b.addEventListener('click',()=>choose(d));host.append(b);});if(!items.some(d=>d.id===selected?.id)&&items[0])choose(items[0]);if(!visible.length)host.append(U.node('p','No matching equations. Try another search.'));}
  function choose(d){selected=d;list();$('eq-title').textContent=d.name;$('eq-subtitle').textContent=`${$('eq-level').value==='gcse'?'GCSE':'A-level'} · ${d.subject}`;$('eq-formula').textContent=d.formula;const tbody=$('eq-symbols');tbody.replaceChildren();[d.result,...d.inputs].forEach(v=>{const tr=U.node('tr');[v.symbol,v.name,v.unit].forEach(text=>tr.append(U.node('td',text)));tbody.append(tr);});if(d.constant){const tr=U.node('tr');tr.append(U.node('td','Constant'),U.node('td',d.constant),U.node('td','Use the value provided'));tbody.append(tr);}$('eq-note').textContent=d.note||'Match the quantities to their symbols and use the required units before substituting.';$('eq-rearrangements').replaceChildren(...Object.values(d.forms).map(f=>U.node('li',f)));$('eq-target').replaceChildren(new Option('Any unknown','any'),...[d.result,...d.inputs].map(v=>new Option(`${v.symbol} · ${v.name}`,v.symbol)));newQuestion();tab('learn');}
  function newQuestion(){seed=freshSeed();checked=false;revealed=false;question=E.build(selected.id,seed,$('eq-demand').value,$('eq-demand').value==='support'?selected.result.symbol:$('eq-target').value);$('eq-target').disabled=$('eq-demand').value==='support';$('eq-question').textContent=question.prompt;answerForm=U.form(question,()=>{$('eq-feedback').hidden=true;});$('eq-answer-form').replaceChildren(answerForm);$('eq-feedback').hidden=true;$('eq-solution').hidden=true;$('eq-solution').replaceChildren(U.solution(question));const worked=E.build(selected.id,12345,'stretch',question.target.symbol);$('eq-worked-question').textContent=worked.prompt;$('eq-worked-solution').replaceChildren(U.solution(worked));progress();}
  function progress(){$('eq-progress').textContent=`On this device: ${stats.attempted} questions checked · ${stats.independent} complete first checks without viewing the solution. Written working is for your review.`;}
  $('eq-check').addEventListener('click',()=>{const answer=answerForm.read(),a=E.assess(question,answer);$('eq-feedback').replaceChildren(U.feedback(question,answer));$('eq-feedback').hidden=false;if(!checked){stats.attempted++;if(!revealed&&a.formula&&a.conversions.every(Boolean)&&a.value&&a.unit&&a.working)stats.independent++;checked=true;try{localStorage.setItem('revision-equation-progress-v1',JSON.stringify(stats));}catch{}progress();}});
  $('eq-reveal').addEventListener('click',()=>{revealed=true;$('eq-solution').hidden=false;});$('eq-next').addEventListener('click',newQuestion);$('eq-demand').addEventListener('change',newQuestion);$('eq-target').addEventListener('change',newQuestion);['eq-level','eq-subject','eq-pathway'].forEach(id=>$(id).addEventListener('change',list));$('eq-search').addEventListener('input',list);$('eq-see-example').addEventListener('click',()=>tab('worked'));$('eq-start').addEventListener('click',()=>tab('try'));list();
})();
