/* Shared, deterministic calculation engine for practice and teacher question sets. */
(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.RevisionEquations = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  const units = {
    m: [['cm', .01], ['mm', .001], ['km', 1000]], s: [['ms', .001], ['min', 60]],
    kg: [['g', .001]], g: [['mg', .001], ['kg', 1000]], mm: [['μm', .001], ['cm', 10]],
    'm²': [['cm²', .0001]], 'm³': [['cm³', .000001], ['dm³', .001]],
    'dm³': [['cm³', .001]], J: [['kJ', 1000]], W: [['kW', 1000]],
    A: [['mA', .001]], C: [['mC', .001]], F: [['μF', .000001]],
    Hz: [['kHz', 1000]], Pa: [['kPa', 1000]], N: [['kN', 1000]]
  };
  const variable = (symbol, name, unit, low, high, power = 1) => ({symbol, name, unit, low, high, power});
  const definitions = [];
  function expression(d,target,values) {
    const token=x=>values?`(${format(values[x.symbol])})`:x.symbol;
    const term=x=>{const p=Math.abs(x.power);return p===1?token(x):p===2?token(x)+'²':p===3?token(x)+'³':`(${token(x)})^${p}`;};
    const positives=d.inputs.filter(x=>x.power>0&&x.symbol!==target),negatives=d.inputs.filter(x=>x.power<0&&x.symbol!==target);
    const unknown=d.inputs.find(x=>x.symbol===target);
    const coefficient=values?String(d.coefficient):d.constant?d.constant.split(' (')[0]:d.coefficient===.5?'½':String(d.coefficient);
    let numerator,denominator;
    if(!unknown){numerator=[...(d.coefficient!==1?[coefficient]:[]),...positives.map(term)];denominator=negatives.map(term);}
    else if(unknown.power>0){numerator=[...(d.coefficient===.5?['2']:[]),token(d.result),...negatives.map(term)];denominator=[...(d.coefficient!==1&&d.coefficient!==.5?[coefficient]:[]),...positives.map(term)];}
    else {numerator=[...(d.coefficient!==1?[coefficient]:[]),...positives.map(term)];denominator=[token(d.result),...negatives.map(term)];}
    const top=numerator.join(' × ')||'1',bottom=denominator.join(' × '),ratio=bottom?`${numerator.length>1?'('+top+')':top} / ${denominator.length>1?'('+bottom+')':bottom}`:top;
    return unknown&&Math.abs(unknown.power)!==1 ? Math.abs(unknown.power)===2?`√(${ratio})`:`(${ratio})^${1/Math.abs(unknown.power)}` : ratio;
  }
  function add(id, subject, levels, topic, name, formula, result, inputs, coefficient = 1, note = '', constant = '') {
    const powers = inputs.map(v => v.power);
    const d={id,subject,levels,topic,name,formula,result,inputs,powers,coefficient,note,constant};
    const forms = {[result.symbol]: formula};
    inputs.forEach(v=>forms[v.symbol]=`${v.symbol} = ${expression(d,v.symbol)}`);
    definitions.push({...d,forms});
  }
  const v = variable;
  const both = ['gcse', 'alevel'], advanced = ['alevel'];
  add('speed','physics',both,'p5','Speed','v = d / t',v('v','speed','m/s'),[v('d','distance','m',12,750),v('t','time','s',2,90, -1)],1,'Use total distance and time for average speed.');
  add('force','physics',both,'p5','Newton’s second law','F = m × a',v('F','resultant force','N'),[v('m','mass','kg',.3,80),v('a','acceleration','m/s²',.2,12)]);
  add('weight','physics',both,'p5','Weight','W = m × g',v('W','weight','N'),[v('m','mass','kg',.1,90)],9.8,'Weight is a force. Mass is measured in kg.','g (9.8 N/kg)');
  add('density','physics',both,'p3','Density','ρ = m / V',v('ρ','density','kg/m³'),[v('m','mass','kg',.2,12),v('V','volume','m³',.0002,.01,-1)]);
  add('work','physics',both,'p1','Work done','E = F × d',v('E','work done','J'),[v('F','force','N',5,600),v('d','distance in the force direction','m',.2,30)]);
  add('kinetic','physics',both,'p1','Kinetic energy','E = ½ × m × v²',v('E','kinetic energy','J'),[v('m','mass','kg',.2,60),v('v','speed','m/s',1,35,2)],.5,'Square the speed before multiplying.','½');
  add('potential','physics',both,'p1','Gravitational potential energy','E = m × g × h',v('E','change in gravitational potential energy','J'),[v('m','mass','kg',.2,30),v('h','vertical height change','m',.3,40)],9.8,'Use the change in vertical height. Assume g = 9.8 N/kg.','g (9.8 N/kg)');
  add('elastic','physics',both,'p1','Elastic potential energy','E = ½ × k × x²',v('E','elastic energy','J'),[v('k','spring constant','N/m',20,600),v('x','extension','m',.01,.3,2)],.5,'Only valid within the limit of proportionality. Extension must be in metres.','½');
  add('hooke','physics',both,'p5','Hooke’s law','F = k × x',v('F','spring force','N'),[v('k','spring constant','N/m',20,800),v('x','extension','m',.01,.25)],1,'Only valid within the limit of proportionality.');
  add('power','physics',both,'p1','Power','P = E / t',v('P','power','W'),[v('E','energy transferred','J',50,20000),v('t','time','s',2,200,-1)]);
  add('efficiency','physics',both,'p1','Efficiency','η = 100 × U / I',v('η','efficiency','%'),[v('U','useful energy output','J',10,90),v('I','total energy input','J',100,200,-1)],100,'Efficiency cannot exceed 100%. Both energies must use the same units.','100');
  add('charge','physics',both,'p2','Charge flow','Q = I × t',v('Q','charge','C'),[v('I','current','A',.05,8),v('t','time','s',5,300)]);
  add('resistance','physics',both,'p2','Potential difference','V = I × R',v('V','potential difference','V'),[v('I','current','A',.05,3),v('R','resistance','Ω',2,80)]);
  add('electrical-power','physics',both,'p2','Electrical power','P = V × I',v('P','power','W'),[v('V','potential difference','V',2,240),v('I','current','A',.02,5)]);
  add('resistor-power','physics',both,'p2','Resistor power','P = I² × R',v('P','power','W'),[v('I','current','A',.05,4,2),v('R','resistance','Ω',2,100)]);
  add('electrical-energy','physics',both,'p2','Electrical energy','E = Q × V',v('E','energy','J'),[v('Q','charge','C',.1,120),v('V','potential difference','V',2,230)]);
  add('wave','physics',both,'p6','Wave speed','v = f × λ',v('v','wave speed','m/s'),[v('f','frequency','Hz',20,3000),v('λ','wavelength','m',.02,4)]);
  add('period','physics',both,'p6','Period and frequency','T = 1 / f',v('T','period','s'),[v('f','frequency','Hz',2,800,-1)]);
  add('pressure','physics',both,'p5','Pressure','p = F / A',v('p','pressure','Pa'),[v('F','normal force','N',10,1500),v('A','area','m²',.002,.4,-1)],1,'Force acts perpendicular to the surface. This GCSE calculation is Separate Science.');
  add('thermal','physics',both,'p1','Specific heat capacity','E = m × c × ΔT',v('E','thermal energy change','J'),[v('m','mass','kg',.1,5),v('c','specific heat capacity','J/(kg °C)',200,4200),v('ΔT','temperature change','°C',2,60)],1,'ΔT is the temperature change, not the final temperature.');
  add('latent','physics',both,'p3','Specific latent heat','E = m × L',v('E','energy transferred','J'),[v('m','mass','kg',.01,3),v('L','specific latent heat','J/kg',20000,2300000)],1,'During a change of state the temperature remains constant.');
  add('momentum','physics',both,'p5','Momentum','p = m × v',v('p','momentum','kg m/s'),[v('m','mass','kg',.1,100),v('v','velocity','m/s',.5,35)],1,'Momentum is a vector. This calculation uses magnitudes in one direction; GCSE Separate Science.');
  add('moment','physics',both,'p5','Moment of a force','M = F × d',v('M','moment','N m'),[v('F','force','N',5,400),v('d','perpendicular distance from pivot','m',.05,2)],1,'Use the perpendicular distance. GCSE Separate Science.');
  add('capacitance','physics',advanced,'electricity','Capacitance','Q = C × V',v('Q','charge','C'),[v('C','capacitance','F',.000001,.002),v('V','potential difference','V',2,100)]);
  add('capacitor-energy','physics',advanced,'electricity','Capacitor energy','E = ½ × C × V²',v('E','stored energy','J'),[v('C','capacitance','F',.000001,.001),v('V','potential difference','V',2,100,2)],.5,'Square the potential difference.','½');
  add('photon','physics',advanced,'particles','Photon energy','E = h × f',v('E','photon energy','J'),[v('f','frequency','Hz',1e14,9e14)],6.63e-34,'Use h = 6.63 × 10⁻³⁴ J s. Scientific notation is accepted.','h (6.63 × 10⁻³⁴ J s)');
  add('centripetal','physics',advanced,'further-mechanics','Centripetal force','F = m × v² / r',v('F','centripetal force','N'),[v('m','mass','kg',.1,5),v('v','speed','m/s',1,20,2),v('r','radius','m',.2,5,-1)],1,'Resultant force points towards the centre.');
  add('ideal-gas','chemistry',advanced,'chem-physical','Ideal gas equation','p = n × R × T / V',v('p','pressure','Pa'),[v('n','amount','mol',.01,.5),v('T','absolute temperature','K',273,500),v('V','volume','m³',.001,.03,-1)],8.31,'Temperature must be in kelvin and volume in m³. Assume ideal gas behaviour.','R (8.31 J/(mol K))');
  add('moles','chemistry',both,'c3','Amount of substance','n = m / M',v('n','amount','mol'),[v('m','mass','g',.1,30),v('M','molar mass','g/mol',18,200,-1)],1,'Use mass in grams when molar mass is in g/mol.');
  add('molarity','chemistry',both,'c3','Amount concentration','c = n / V',v('c','concentration','mol/dm³'),[v('n','amount','mol',.005,.5),v('V','solution volume','dm³',.025,2,-1)],1,'Convert cm³ to dm³ by dividing by 1000. GCSE Separate Science.');
  add('mass-concentration','chemistry',both,'c3','Mass concentration','c = m / V',v('c','mass concentration','g/dm³'),[v('m','solute mass','g',.1,20),v('V','solution volume','dm³',.05,2,-1)]);
  add('gas-volume','chemistry',both,'c3','Gas volume at RTP','V = n × 24',v('V','gas volume','dm³'),[v('n','amount','mol',.005,2)],24,'Use 24 dm³/mol at room temperature and pressure. GCSE Separate Science.','24 dm³/mol');
  add('yield','chemistry',both,'c3','Percentage yield','Y = 100 × A / T',v('Y','percentage yield','%'),[v('A','actual mass of product','g',1,9),v('T','theoretical mass of product','g',10,25,-1)],100,'Use the same mass units. Pure, dry actual yield should not exceed theoretical yield. GCSE Separate Science.','100');
  add('atom-economy','chemistry',both,'c3','Atom economy','A = 100 × D / R',v('A','atom economy','%'),[v('D','stoichiometric mass of desired product','g',10,90),v('R','total stoichiometric mass of reactants','g',100,250,-1)],100,'Include balanced-equation coefficients in these masses. GCSE Separate Science.','100');
  add('rate','chemistry',both,'c6','Mean reaction rate','r = V / t',v('r','mean rate','cm³/s'),[v('V','gas produced','cm³',10,250),v('t','time','s',5,200,-1)],1,'Use change in gas volume over the specified time interval.');
  add('calorimetry','chemistry',advanced,'chem-physical','Calorimetry','q = m × c × ΔT',v('q','heat absorbed by solution','J'),[v('m','solution mass','g',25,250),v('c','specific heat capacity','J/(g °C)',4.18,4.18),v('ΔT','temperature rise','°C',2,30)],1,'Assume no heat loss. Reaction heat has the opposite sign; ΔH = −q/n for an exothermic reaction.');
  add('magnification','biology',both,'b1','Microscope magnification','M = I / A',v('M','magnification','×'),[v('I','image size','mm',10,90),v('A','actual size','mm',.01,.3,-1)],1,'Image and actual size must use the same units. 1000 μm = 1 mm. Magnification is dimensionless.');
  add('growth-rate','biology',both,'b2','Mean growth rate','r = L / t',v('r','mean growth rate','mm/s'),[v('L','change in length','mm',1,30),v('t','time interval','s',10,300,-1)]);
  add('population','biology',both,'b7','Quadrat population estimate','N = D × A',v('N','estimated population','organisms'),[v('D','mean population density','organisms/m²',2,80),v('A','habitat area','m²',10,800)],1,'Assume random, representative samples and a reasonably uniform distribution. Estimates need not be whole numbers before rounding.');
  add('transfer','biology',both,'b7','Biomass transfer efficiency','E = 100 × B / A',v('E','transfer efficiency','%'),[v('B','biomass at next trophic level','g',1,9),v('A','biomass at preceding trophic level','g',10,100,-1)],100,'Compare the same area and time interval. GCSE Separate Science.','100');
  add('surface-volume','biology',advanced,'bio-molecules','Cube surface area to volume ratio','R = 6 / l',v('R','surface area to volume ratio','mm⁻¹'),[v('l','cube side length','mm',.5,10,-1)],6,'For a cube, surface area = 6l² and volume = l³. The ratio decreases as size increases.','6');
  add('dilution','biology',advanced,'bio-molecules','Dilution','c₂ = c₁ × V₁ / V₂',v('c₂','final concentration','g/dm³'),[v('c₁','stock concentration','g/dm³',10,100),v('V₁','stock volume used','dm³',.001,.01),v('V₂','final total volume','dm³',.02,.1,-1)],1,'V₂ is the final total volume after adding solvent. Both volumes use the same units.');
  definitions.push({id:'acceleration',subject:'physics',levels:both,topic:'p5',name:'Acceleration',formula:'a = (v − u) / t',result:v('a','acceleration','m/s²'),inputs:[v('u','initial velocity','m/s',1,10),v('v','final velocity','m/s',15,40),v('t','time','s',2,30)],coefficient:1,kind:'acceleration',note:'Use the change in velocity. These questions consider motion along one direction.',forms:{a:'a = (v − u) / t',u:'u = v − a × t',v:'v = u + a × t',t:'t = (v − u) / a'}});
  definitions.push({id:'percentage-change',subject:'biology',levels:both,topic:'b1',name:'Percentage change',formula:'P = 100 × (F − I) / I',result:v('P','percentage change','%'),inputs:[v('F','final sample mass','g',1,40),v('I','initial sample mass','g',3,40)],coefficient:100,kind:'percentage-change',note:'A negative percentage means a decrease. Divide by the initial mass, not the final mass.',constant:'100',forms:{P:'P = 100 × (F − I) / I',F:'F = I × (1 + P / 100)',I:'I = F / (1 + P / 100)'}});
  definitions.push({id:'net-production',subject:'biology',levels:advanced,topic:'bio-energy',name:'Net primary production',formula:'N = G − R',result:v('N','net primary production','kJ/(m² year)'),inputs:[v('G','gross primary production','kJ/(m² year)',50,200),v('R','respiratory losses','kJ/(m² year)',5,40)],coefficient:1,kind:'net-production',note:'Compare energy transfers over the same area and time period.',forms:{N:'N = G − R',G:'G = N + R',R:'R = G − N'}});
  // AQA numerical relationships: core science, mathematical skills and all five Physics options.
  // Independent practice data and explanations; source map is in docs/aqa-equation-coverage.md.
  function mono(id, subject, levels, topic, name, result, inputs, coefficient=1, constant='', note='', scope='combined') {
    const d={id,subject,levels,topic,name,result,inputs,coefficient,constant,note,scope};
    d.formula=`${result.symbol} = ${expression(d,result.symbol)}`;
    d.forms=Object.fromEntries([result,...inputs].map(x=>[x.symbol,`${x.symbol} = ${expression(d,x.symbol)}`]));
    definitions.push(d);
  }
  function custom(id,subject,levels,topic,name,result,inputs,formula,calculate,forms={},note='',scope='combined') {
    definitions.push({id,subject,levels,topic,name,result,inputs,formula,calculate,forms:{[result.symbol]:formula,...forms},coefficient:1,kind:'custom',note,scope});
  }
  const P=(id,topic,name,result,inputs,k=1,c='',note='',levels=advanced,scope='combined')=>mono(id,'physics',levels,topic,name,result,inputs,k,c,note,scope);
  const C=(id,name,result,inputs,k=1,c='',note='',levels=advanced,scope='combined')=>mono(id,'chemistry',levels,'chem-physical',name,result,inputs,k,c,note,scope);
  const B=(id,topic,name,result,inputs,k=1,c='',note='',levels=advanced,scope='combined')=>mono(id,'biology',levels,topic,name,result,inputs,k,c,note,scope);
  const pc=(id,topic,name,result,inputs,formula,calculate,forms={},note='',levels=advanced,scope='combined')=>custom(id,'physics',levels,topic,name,result,inputs,formula,calculate,forms,note,scope);
  const cc=(id,name,result,inputs,formula,calculate,forms={},note='',levels=advanced)=>custom(id,'chemistry',levels,'chem-physical',name,result,inputs,formula,calculate,forms,note);
  const bc=(id,topic,name,result,inputs,formula,calculate,forms={},note='',levels=advanced)=>custom(id,'biology',levels,topic,name,result,inputs,formula,calculate,forms,note);
  const G=6.67e-11,h=6.63e-34,c=3e8,e=1.6e-19,kB=1.38e-23;
  // Remaining GCSE Physics equations and equivalent electrical/energy forms.
  P('power-work','p1','Power from work done',v('P','power','W'),[v('W','work done','J',100,10000),v('t','time','s',2,200,-1)],1,'','Work and energy transfer have the same unit.',both);
  P('efficiency-power','p1','Efficiency from power',v('η','efficiency','%'),[v('U','useful output power','W',5,90),v('I','input power','W',100,500,-1)],100,'100','Use powers measured over the same interval.',both);
  P('electrical-energy-time','p2','Energy from electrical power',v('E','energy transferred','J'),[v('P','power','W',5,1500),v('t','time','s',5,600)],1,'','Equivalent to E = VIt when P = VI.',both);
  P('electrical-energy-vit','p2','Energy from voltage, current and time',v('E','energy transferred','J'),[v('V','potential difference','V',2,240),v('I','current','A',.05,5),v('t','time','s',5,600)],1,'','For constant voltage and current.',both);
  P('resistor-power-voltage','p2','Power from voltage and resistance',v('P','power','W'),[v('V','potential difference','V',2,240,2),v('R','resistance','Ω',10,1000,-1)],1,'','Combine P = VI with V = IR.',both);
  P('liquid-pressure','p5','Pressure due to a liquid column',v('p','pressure difference','Pa'),[v('h','depth','m',.1,25),v('ρ','liquid density','kg/m³',700,1400)],9.8,'g (9.8 N/kg)','Pressure increase below the surface, excluding atmospheric pressure.',both,'triple');
  P('gas-pressure-volume','p3','Boyle’s law',v('p₂','final pressure','Pa'),[v('p₁','initial pressure','Pa',50000,200000),v('V₁','initial volume','m³',.001,.01),v('V₂','final volume','m³',.015,.025,-1)],1,'','Fixed mass of gas at constant temperature: p₁V₁ = p₂V₂.',both,'triple');
  P('transformer-voltage','p7','Transformer voltage ratio',v('Vₛ','secondary potential difference','V'),[v('Vₚ','primary potential difference','V',12,240),v('Nₛ','secondary turns','turns',100,800),v('Nₚ','primary turns','turns',900,2000,-1)],1,'','For an ideal transformer: Vₚ/Vₛ = Nₚ/Nₛ.',both,'triple');
  P('transformer-current','p7','Ideal transformer power',v('Iₛ','secondary current','A'),[v('Vₚ','primary voltage','V',12,240),v('Iₚ','primary current','A',.05,5),v('Vₛ','secondary voltage','V',5,100,-1)],1,'','An ideal transformer conserves power: VₚIₚ = VₛIₛ.',both,'triple');
  P('motor-force','p7','Force on a current-carrying conductor',v('F','magnetic force','N'),[v('B','magnetic flux density','T',.05,1),v('I','current','A',.1,10),v('l','length in field','m',.05,1)],1,'','Conductor perpendicular to the field. GCSE Higher Separate Science.',both,'triple');
  P('force-momentum','p5','Force from change in momentum',v('F','mean resultant force','N'),[v('Δp','momentum change','kg m/s',1,300),v('Δt','time interval','s',.01,2,-1)],1,'','Use signed momentum changes for direction. These questions use magnitudes.',both,'triple');
  pc('suvat-speed','p5','Uniform acceleration without time',v('v','final speed','m/s'),[v('u','initial speed','m/s',1,8),v('a','acceleration','m/s²',1,6),v('s','displacement','m',10,80)],'v = √(u² + 2 × a × s)',{v:x=>Math.sqrt(x.u*x.u+2*x.a*x.s),u:x=>Math.sqrt(x.v*x.v-2*x.a*x.s),a:x=>(x.v*x.v-x.u*x.u)/(2*x.s),s:x=>(x.v*x.v-x.u*x.u)/(2*x.a)},{u:'u = √(v² − 2 × a × s)',a:'a = (v² − u²) / (2 × s)',s:'s = (v² − u²) / (2 × a)'},'Constant acceleration; v² − u² = 2as. Positive speed branch used.',both);
  // A-level particles, waves and mechanics.
  P('specific-charge','particles','Specific charge',v('q/m','specific charge','C/kg'),[v('q','charge magnitude','C',e,4*e),v('m','particle mass','kg',1.67e-27,8e-27,-1)]);
  P('photon-wavelength','particles','Photon energy from wavelength',v('E','photon energy','J'),[v('λ','wavelength','m',2e-7,9e-7,-1)],h*c,'hc (1.989e-25 J m)','E = hf = hc/λ.');
  P('electronvolt','particles','Electronvolts to joules',v('E','energy','J'),[v('Eₑ','energy in electronvolts','eV',1,10000)],e,'e (1.60e-19 J/eV)');
  P('de-broglie','particles','de Broglie wavelength',v('λ','matter wavelength','m'),[v('p','momentum','kg m/s',1e-25,1e-22,-1)],h,'h (6.63e-34 J s)');
  pc('photoelectric','particles','Photoelectric equation',v('K','maximum kinetic energy','J'),[v('f','photon frequency','Hz',8e14,1.2e15),v('φ','work function','J',1e-19,3e-19)],'K = h × f − φ',{K:x=>h*x.f-x.φ,f:x=>(x.K+x.φ)/h,φ:x=>h*x.f-x.K},{f:'f = (K + φ) / h',φ:'φ = h × f − K'},'h = 6.63e-34 J s. Emission requires hf ≥ φ.');
  P('threshold-frequency','particles','Threshold frequency',v('f₀','threshold frequency','Hz'),[v('φ','work function','J',1e-19,6e-19)],1/h,'1/h (h = 6.63e-34 J s)');
  P('stopping-potential','particles','Stopping potential',v('V','stopping potential','V'),[v('K','maximum electron kinetic energy','J',1e-20,4e-19)],1/e,'1/e (e = 1.60e-19 C)');
  P('refractive-index','waves','Absolute refractive index',v('n','refractive index','dimensionless'),[v('v','light speed in medium','m/s',1.2e8,2.5e8,-1)],c,'c (3.00e8 m/s)');
  pc('snell','waves','Snell’s law',v('θ₂','refracted angle','rad'),[v('n₁','first refractive index','dimensionless',1,1.2),v('n₂','second refractive index','dimensionless',1.4,1.8),v('θ₁','incident angle','rad',.1,.8)],'θ₂ = asin(n₁ × sin(θ₁) / n₂)',{"θ₂":x=>Math.asin(x["n₁"]*Math.sin(x["θ₁"])/x["n₂"]),"n₁":x=>x["n₂"]*Math.sin(x["θ₂"])/Math.sin(x["θ₁"]),"n₂":x=>x["n₁"]*Math.sin(x["θ₁"])/Math.sin(x["θ₂"]),"θ₁":x=>Math.asin(x["n₂"]*Math.sin(x["θ₂"])/x["n₁"])},{"n₁":'n₁ = n₂ × sin(θ₂) / sin(θ₁)',"n₂":'n₂ = n₁ × sin(θ₁) / sin(θ₂)',"θ₁":'θ₁ = asin(n₂ × sin(θ₂) / n₁)'},'Angles from the normal. Calculator in radians for these questions.');
  pc('critical-angle','waves','Critical angle',v('θc','critical angle','rad'),[v('n','refractive index relative to air','dimensionless',1.3,2)],'θc = asin(1 / n)',{θc:x=>Math.asin(1/x.n),n:x=>1/Math.sin(x.θc)},{n:'n = 1 / sin(θc)'},'From material into air; use radians.');
  P('young-fringes','waves','Young’s double-slit fringes',v('w','fringe spacing','m'),[v('λ','wavelength','m',4e-7,7e-7),v('D','screen distance','m',.5,3),v('s','slit separation','m',.0001,.001,-1)]);
  pc('diffraction-grating','waves','Diffraction grating',v('θ','diffraction angle','rad'),[v('n','order','dimensionless',1,1),v('λ','wavelength','m',4e-7,7e-7),v('d','grating spacing','m',1e-6,3e-6)],'θ = asin(n × λ / d)',{θ:x=>Math.asin(x.n*x.λ/x.d),λ:x=>x.d*Math.sin(x.θ)/x.n,d:x=>x.n*x.λ/Math.sin(x.θ)},{λ:'λ = d × sin(θ) / n',d:'d = n × λ / sin(θ)'},'d sin θ = nλ. Integer order fixed at n = 1; use radians.');
  P('string-frequency','waves','Fundamental frequency of a stretched string',v('f','fundamental frequency','Hz'),[v('L','vibrating length','m',.3,1.2,-1),v('T','tension','N',10,200,.5),v('μ','mass per unit length','kg/m',.0005,.005,-.5)],.5,'½','f = (1/2L)√(T/μ). Both ends fixed.');
  P('intensity','waves','Intensity',v('I','intensity','W/m²'),[v('P','power','W',1,100),v('A','area','m²',.1,10,-1)]);
  P('inverse-square-intensity','waves','Point-source intensity',v('I','intensity','W/m²'),[v('P','source power','W',1,100),v('r','distance','m',.2,5,-2)],1/(4*Math.PI),'1/(4π)','Uniform emission; negligible absorption.');
  pc('suvat-average','mechanics-materials','Uniform acceleration: average velocity',v('s','displacement','m'),[v('u','initial velocity','m/s',1,10),v('v','final velocity','m/s',15,40),v('t','time','s',1,20)],'s = (u + v) × t / 2',{s:x=>(x.u+x.v)*x.t/2,u:x=>2*x.s/x.t-x.v,v:x=>2*x.s/x.t-x.u,t:x=>2*x.s/(x.u+x.v)},{u:'u = 2 × s / t − v',v:'v = 2 × s / t − u',t:'t = 2 × s / (u + v)'},'Constant acceleration.');
  pc('suvat-displacement','mechanics-materials','Uniform acceleration: displacement',v('s','displacement','m'),[v('u','initial velocity','m/s',2,12),v('a','acceleration','m/s²',.5,4),v('t','time','s',2,15)],'s = u × t + a × t² / 2',{s:x=>x.u*x.t+x.a*x.t*x.t/2,u:x=>(x.s-x.a*x.t*x.t/2)/x.t,a:x=>2*(x.s-x.u*x.t)/(x.t*x.t),t:x=>(-x.u+Math.sqrt(x.u*x.u+2*x.a*x.s))/x.a},{u:'u = (s − a × t² / 2) / t',a:'a = 2 × (s − u × t) / t²',t:'t = (−u + √(u² + 2 × a × s)) / a'},'Constant acceleration; positive time branch.');
  pc('force-component','mechanics-materials','Resolve a force',v('Fₓ','component along x','N'),[v('F','force magnitude','N',10,500),v('θ','angle to x','rad',.1,1.2)],'Fₓ = F × cos(θ)',{Fₓ:x=>x.F*Math.cos(x.θ),F:x=>x.Fₓ/Math.cos(x.θ),θ:x=>Math.acos(x.Fₓ/x.F)},{F:'F = Fₓ / cos(θ)',θ:'θ = acos(Fₓ / F)'},'Complementary component is F sin θ. Angles in radians.');
  pc('angled-work','mechanics-materials','Work by an angled force',v('W','work done','J'),[v('F','force','N',5,500),v('s','displacement','m',.5,30),v('θ','angle between force and motion','rad',.1,1)],'W = F × s × cos(θ)',{W:x=>x.F*x.s*Math.cos(x.θ),F:x=>x.W/(x.s*Math.cos(x.θ)),s:x=>x.W/(x.F*Math.cos(x.θ))},{F:'F = W / (s × cos(θ))',s:'s = W / (F × cos(θ))'},'Angle measured in radians; force constant.');
  P('power-speed','mechanics-materials','Power at constant speed',v('P','power','W'),[v('F','force parallel to motion','N',5,600),v('v','speed','m/s',.5,30)]);
  P('impulse','mechanics-materials','Impulse',v('J','impulse','N s'),[v('F','constant force','N',10,2000),v('Δt','contact duration','s',.01,1)],1,'','J = FΔt = Δp.');
  P('stress','mechanics-materials','Tensile stress',v('σ','tensile stress','Pa'),[v('F','tensile force','N',10,1000),v('A','cross-sectional area','m²',1e-7,1e-5,-1)]);
  P('strain','mechanics-materials','Tensile strain',v('ε','tensile strain','dimensionless'),[v('ΔL','extension','m',.0001,.005),v('L','original length','m',.5,3,-1)]);
  P('young-modulus','mechanics-materials','Young modulus',v('E','Young modulus','Pa'),[v('σ','tensile stress','Pa',1e6,1e8),v('ε','tensile strain','dimensionless',.0001,.01,-1)],1,'','Within the linear elastic region.');
  P('young-wire','mechanics-materials','Young modulus from wire measurements',v('E','Young modulus','Pa'),[v('F','force','N',10,200),v('L','original length','m',.5,3),v('A','cross-sectional area','m²',1e-7,1e-6,-1),v('ΔL','extension','m',.0002,.002,-1)]);
  P('elastic-work','mechanics-materials','Work stretching a wire',v('W','elastic work','J'),[v('F','final force','N',10,500),v('ΔL','extension','m',.001,.05)],.5,'½','Force increases linearly from zero; area under force–extension graph.');
  // Electricity and thermal/circular motion.
  P('resistivity','electricity','Resistance and resistivity',v('R','resistance','Ω'),[v('ρ','resistivity','Ω m',1e-8,8e-7),v('L','wire length','m',.5,20),v('A','cross-sectional area','m²',1e-7,2e-6,-1)]);
  pc('series-resistance','electricity','Series resistors',v('R','total resistance','Ω'),[v('R₁','first resistance','Ω',5,100),v('R₂','second resistance','Ω',5,100)],'R = R₁ + R₂',{R:x=>x["R₁"]+x["R₂"],"R₁":x=>x.R-x["R₂"],"R₂":x=>x.R-x["R₁"]},{"R₁":'R₁ = R − R₂',"R₂":'R₂ = R − R₁'},'For more resistors add every resistance.',both);
  pc('parallel-resistance','electricity','Two parallel resistors',v('R','total resistance','Ω'),[v('R₁','first resistance','Ω',10,100),v('R₂','second resistance','Ω',10,100)],'R = R₁ × R₂ / (R₁ + R₂)',{R:x=>x["R₁"]*x["R₂"]/(x["R₁"]+x["R₂"]),"R₁":x=>x.R*x["R₂"]/(x["R₂"]-x.R),"R₂":x=>x.R*x["R₁"]/(x["R₁"]-x.R)},{"R₁":'R₁ = R × R₂ / (R₂ − R)',"R₂":'R₂ = R × R₁ / (R₁ − R)'},'Equivalent to 1/R = 1/R₁ + 1/R₂.');
  P('drift','electricity','Electron drift velocity',v('v','drift speed','m/s'),[v('I','current','A',.1,5),v('n','carrier number density','m⁻³',1e28,9e28,-1),v('A','cross-sectional area','m²',1e-7,1e-5,-1)],1/e,'1/e (e = 1.60e-19 C)','I = nAev.');
  pc('emf','electricity','EMF and internal resistance',v('ε','electromotive force','V'),[v('I','current','A',.1,5),v('R','external resistance','Ω',2,20),v('r','internal resistance','Ω',.1,2)],'ε = I × (R + r)',{ε:x=>x.I*(x.R+x.r),I:x=>x.ε/(x.R+x.r),R:x=>x.ε/x.I-x.r,r:x=>x.ε/x.I-x.R},{I:'I = ε / (R + r)',R:'R = ε / I − r',r:'r = ε / I − R'},'Terminal voltage V = ε − Ir.');
  pc('terminal-voltage','electricity','Terminal potential difference',v('V','terminal voltage','V'),[v('ε','electromotive force','V',10,24),v('I','current','A',.1,2),v('r','internal resistance','Ω',.1,2)],'V = ε − I × r',{V:x=>x.ε-x.I*x.r,ε:x=>x.V+x.I*x.r,I:x=>(x.ε-x.V)/x.r,r:x=>(x.ε-x.V)/x.I},{ε:'ε = V + I × r',I:'I = (ε − V) / r',r:'r = (ε − V) / I'});
  pc('potential-divider','electricity','Potential divider',v('V₂','output voltage','V'),[v('V','supply voltage','V',5,24),v('R₁','first resistor','Ω',100,1000),v('R₂','output resistor','Ω',100,1000)],'V₂ = V × R₂ / (R₁ + R₂)',{"V₂":x=>x.V*x["R₂"]/(x["R₁"]+x["R₂"]),V:x=>x["V₂"]*(x["R₁"]+x["R₂"])/x["R₂"],"R₁":x=>x["R₂"]*(x.V/x["V₂"]-1),"R₂":x=>x["V₂"]*x["R₁"]/(x.V-x["V₂"])},{V:'V = V₂ × (R₁ + R₂) / R₂',"R₁":'R₁ = R₂ × (V / V₂ − 1)',"R₂":'R₂ = V₂ × R₁ / (V − V₂)'},'Output measured across R₂; negligible load.');
  P('capacitor-energy-qv','electricity','Capacitor energy from Q and V',v('E','stored energy','J'),[v('Q','charge','C',.00001,.005),v('V','voltage','V',2,100)],.5,'½');
  P('capacitor-energy-qc','electricity','Capacitor energy from Q and C',v('E','stored energy','J'),[v('Q','charge','C',.00001,.005,2),v('C','capacitance','F',1e-6,.001,-1)],.5,'½');
  P('rc-time','electricity','RC time constant',v('τ','time constant','s'),[v('R','resistance','Ω',1000,100000),v('C','capacitance','F',1e-6,.001)]);
  pc('capacitor-discharge','electricity','Capacitor discharge',v('Q','remaining charge','C'),[v('Q₀','initial charge','C',.0001,.01),v('t','time','s',1,10),v('τ','RC time constant','s',3,20)],'Q = Q₀ × exp(−t / τ)',{Q:x=>x["Q₀"]*Math.exp(-x.t/x.τ),"Q₀":x=>x.Q*Math.exp(x.t/x.τ),t:x=>-x.τ*Math.log(x.Q/x["Q₀"]),τ:x=>-x.t/Math.log(x.Q/x["Q₀"])},{"Q₀":'Q₀ = Q × exp(t / τ)',t:'t = −τ × ln(Q / Q₀)',τ:'τ = −t / ln(Q / Q₀)'},'Same exponential applies to voltage and current magnitude. τ = RC.');
  pc('capacitor-charge','electricity','Capacitor charging',v('V','capacitor voltage','V'),[v('V₀','supply voltage','V',5,24),v('t','elapsed time','s',1,10),v('τ','time constant','s',3,20)],'V = V₀ × (1 − exp(−t / τ))',{V:x=>x["V₀"]*(1-Math.exp(-x.t/x.τ)),"V₀":x=>x.V/(1-Math.exp(-x.t/x.τ)),t:x=>-x.τ*Math.log(1-x.V/x["V₀"])},{"V₀":'V₀ = V / (1 − exp(−t / τ))',t:'t = −τ × ln(1 − V / V₀)'},'Initially uncharged capacitor; charging through a resistor.');
  P('angular-speed','further-mechanics','Angular speed',v('ω','angular speed','rad/s'),[v('f','frequency','Hz',.2,20)],2*Math.PI,'2π');
  P('angular-period','further-mechanics','Angular speed from period',v('ω','angular speed','rad/s'),[v('T','period','s',.1,10,-1)],2*Math.PI,'2π');
  P('circular-speed','further-mechanics','Circular speed',v('v','linear speed','m/s'),[v('ω','angular speed','rad/s',.5,30),v('r','radius','m',.1,5)]);
  P('centripetal-acceleration','further-mechanics','Centripetal acceleration',v('a','centripetal acceleration','m/s²'),[v('v','speed','m/s',1,20,2),v('r','radius','m',.2,5,-1)]);
  P('centripetal-angular','further-mechanics','Centripetal force from angular speed',v('F','centripetal force','N'),[v('m','mass','kg',.1,5),v('ω','angular speed','rad/s',.5,20,2),v('r','radius','m',.2,5)]);
  P('shm-acceleration','further-mechanics','SHM acceleration',v('a','acceleration','m/s²'),[v('ω','angular frequency','rad/s',1,10,2),v('x','displacement from equilibrium','m',.01,.2)],-1,'−1','Acceleration is opposite to displacement: a = −ω²x.');
  P('shm-period-spring','further-mechanics','Mass–spring period',v('T','period','s'),[v('m','oscillating mass','kg',.1,2,.5),v('k','spring constant','N/m',10,200,-.5)],2*Math.PI,'2π','T = 2π√(m/k); negligible spring mass.');
  P('shm-period-pendulum','further-mechanics','Simple pendulum period',v('T','period','s'),[v('L','pendulum length','m',.2,2,.5)],2*Math.PI/Math.sqrt(9.8),'2π/√g (g = 9.8 m/s²)','T = 2π√(L/g); small angular displacement.');
  pc('shm-displacement','further-mechanics','SHM displacement',v('x','displacement','m'),[v('A','amplitude','m',.02,.3),v('ω','angular frequency','rad/s',1,5),v('t','time from maximum displacement','s',.02,.2)],'x = A × cos(ω × t)',{x:z=>z.A*Math.cos(z.ω*z.t),A:z=>z.x/Math.cos(z.ω*z.t)},{A:'A = x / cos(ω × t)'},'Cosine phase: starts at maximum positive displacement. Radians.');
  pc('shm-velocity','further-mechanics','SHM speed at displacement',v('v','speed magnitude','m/s'),[v('ω','angular frequency','rad/s',1,10),v('A','amplitude','m',.1,.5),v('x','displacement','m',.01,.05)],'v = ω × √(A² − x²)',{v:z=>z.ω*Math.sqrt(z.A*z.A-z.x*z.x),ω:z=>z.v/Math.sqrt(z.A*z.A-z.x*z.x),A:z=>Math.sqrt(z.v*z.v/(z.ω*z.ω)+z.x*z.x)},{ω:'ω = v / √(A² − x²)',A:'A = √(v² / ω² + x²)'},'Velocity has two possible directions; this question asks for magnitude.');
  P('shm-energy','further-mechanics','Total SHM energy',v('E','total oscillation energy','J'),[v('m','mass','kg',.1,2),v('ω','angular frequency','rad/s',1,10,2),v('A','amplitude','m',.02,.3,2)],.5,'½');
  P('ideal-gas-physics','further-mechanics','Ideal gas (moles)',v('p','pressure','Pa'),[v('n','amount','mol',.01,.5),v('T','temperature','K',273,500),v('V','volume','m³',.001,.03,-1)],8.31,'R (8.31 J/(mol K))');
  P('ideal-gas-particles','further-mechanics','Ideal gas (particles)',v('p','pressure','Pa'),[v('N','number of molecules','particles',1e20,1e23),v('T','temperature','K',273,500),v('V','volume','m³',.001,.03,-1)],kB,'k (1.38e-23 J/K)');
  P('gas-kinetic','further-mechanics','Kinetic theory pressure',v('p','pressure','Pa'),[v('ρ','gas density','kg/m³',.2,2),v('cᵣ','rms molecular speed','m/s',300,700,2)],1/3,'⅓','pV = ⅓ Nm⟨c²⟩; p = ⅓ρ cᵣ².');
  P('molecular-energy','further-mechanics','Mean molecular kinetic energy',v('E','mean kinetic energy','J'),[v('T','absolute temperature','K',200,600)],1.5*kB,'3k/2 (k = 1.38e-23 J/K)');
  P('rms-speed','further-mechanics','RMS molecular speed',v('cᵣ','rms speed','m/s'),[v('T','temperature','K',200,600,.5),v('m','mass of one molecule','kg',2e-27,8e-26,-.5)],Math.sqrt(3*kB),'√(3k) (k = 1.38e-23 J/K)','cᵣ = √(3kT/m).');
  // Fields and nuclear physics.
  P('gravity-force','fields','Newton’s gravitational force',v('F','force magnitude','N'),[v('m₁','first mass','kg',1e3,1e7),v('m₂','second mass','kg',1e3,1e7),v('r','centre separation','m',10,100,-2)],G,'G (6.67e-11 N m²/kg²)');
  P('gravity-strength','fields','Radial gravitational field strength',v('g','field strength','N/kg'),[v('M','source mass','kg',1e23,1e25),v('r','distance from centre','m',1e7,5e7,-2)],G,'G (6.67e-11 N m²/kg²)');
  P('gravity-potential','fields','Gravitational potential',v('V','gravitational potential','J/kg'),[v('M','source mass','kg',1e23,1e25),v('r','distance from centre','m',1e7,5e7,-1)],-G,'−G (G = 6.67e-11 N m²/kg²)','Zero potential at infinity.');
  P('potential-work','fields','Work through a potential difference',v('W','work done','J'),[v('m','mass','kg',1,500),v('ΔV','gravitational potential difference','J/kg',1e4,1e7)]);
  P('escape-speed','fields','Escape speed',v('v','escape speed','m/s'),[v('M','source mass','kg',1e23,1e25,.5),v('r','starting radius','m',1e7,5e7,-.5)],Math.sqrt(2*G),'√(2G) (G = 6.67e-11 N m²/kg²)','v = √(2GM/r); ignore atmosphere and rotation.');
  P('orbital-speed','fields','Circular orbital speed',v('v','orbital speed','m/s'),[v('M','central mass','kg',1e23,1e25,.5),v('r','orbital radius','m',1e7,5e7,-.5)],Math.sqrt(G),'√G (G = 6.67e-11 N m²/kg²)');
  P('orbital-period','fields','Kepler’s circular orbital period',v('T','orbital period','s'),[v('r','orbital radius','m',1e7,5e7,1.5),v('M','central mass','kg',1e23,1e25,-.5)],2*Math.PI/Math.sqrt(G),'2π/√G (G = 6.67e-11 N m²/kg²)','T² = 4π²r³/(GM).');
  P('orbital-energy','fields','Total circular orbital energy',v('E','total orbital energy','J'),[v('M','central mass','kg',1e23,1e25),v('m','satellite mass','kg',100,2000),v('r','orbital radius','m',1e7,5e7,-1)],-G/2,'−G/2 (G = 6.67e-11 N m²/kg²)','Potential zero at infinity; bound orbit has negative total energy.');
  P('electric-field','fields','Electric field strength',v('E','field strength','N/C'),[v('F','force magnitude','N',.001,1),v('Q','test charge','C',1e-8,1e-5,-1)]);
  P('coulomb','fields','Coulomb’s law',v('F','electric force magnitude','N'),[v('Q₁','charge magnitude','C',1e-8,1e-5),v('Q₂','charge magnitude','C',1e-8,1e-5),v('r','separation','m',.1,2,-2)],8.99e9,'1/(4πε₀) (8.99e9 N m²/C²)','Use signs of charges to determine attraction or repulsion separately.');
  P('radial-electric','fields','Radial electric field strength',v('E','field strength magnitude','N/C'),[v('Q','source charge magnitude','C',1e-8,1e-5),v('r','distance','m',.1,2,-2)],8.99e9,'1/(4πε₀) (8.99e9 N m²/C²)');
  P('electric-potential','fields','Radial electric potential',v('V','electric potential','V'),[v('Q','positive source charge','C',1e-8,1e-5),v('r','distance','m',.1,2,-1)],8.99e9,'1/(4πε₀) (8.99e9 N m²/C²)','Potential zero at infinity; negative charge gives negative potential.');
  P('uniform-electric','fields','Uniform electric field',v('E','field strength','V/m'),[v('V','potential difference','V',10,1000),v('d','plate separation','m',.005,.05,-1)]);
  P('electric-work','fields','Electric potential energy transfer',v('W','energy transfer magnitude','J'),[v('Q','charge magnitude','C',1e-8,1e-4),v('ΔV','potential difference magnitude','V',10,10000)]);
  P('parallel-capacitor','fields','Parallel plate capacitance',v('C','capacitance','F'),[v('εᵣ','relative permittivity','dimensionless',1,5),v('A','plate area','m²',.001,.1),v('d','plate separation','m',.0001,.005,-1)],8.85e-12,'ε₀ (8.85e-12 F/m)','Fringing neglected.');
  P('magnetic-particle','fields','Magnetic force on a moving charge',v('F','force magnitude','N'),[v('B','flux density','T',.05,1),v('Q','charge magnitude','C',e,4*e),v('v','speed','m/s',1e5,1e7)],1,'','Velocity perpendicular to magnetic field.');
  P('magnetic-radius','fields','Charged particle orbit radius',v('r','radius','m'),[v('m','particle mass','kg',1e-27,1e-26),v('v','speed','m/s',1e5,1e7),v('B','flux density','T',.05,1,-1),v('Q','charge magnitude','C',e,4*e,-1)]);
  pc('flux','fields','Magnetic flux',v('Φ','flux','Wb'),[v('B','flux density','T',.05,1),v('A','area','m²',.001,.1),v('θ','angle between field and area normal','rad',.1,1.2)],'Φ = B × A × cos(θ)',{Φ:x=>x.B*x.A*Math.cos(x.θ),B:x=>x.Φ/(x.A*Math.cos(x.θ)),A:x=>x.Φ/(x.B*Math.cos(x.θ))},{B:'B = Φ / (A × cos(θ))',A:'A = Φ / (B × cos(θ))'},'Angle from the normal; radians. Flux linkage is NΦ.');
  P('flux-linkage','fields','Flux linkage',v('Λ','flux linkage','Wb turns'),[v('N','number of turns','turns',20,1000),v('Φ','flux per turn','Wb',.0001,.02)]);
  P('faraday','fields','Faraday’s law: induced EMF magnitude',v('ε','mean induced EMF magnitude','V'),[v('N','turns','turns',20,1000),v('ΔΦ','flux change magnitude','Wb',.0001,.02),v('Δt','time interval','s',.01,2,-1)],1,'','Direction opposes the change by Lenz’s law: ε = −N ΔΦ/Δt.');
  pc('alternator','fields','Alternator EMF',v('ε','instantaneous EMF','V'),[v('N','turns','turns',20,1000),v('B','flux density','T',.05,.5),v('A','coil area','m²',.001,.05),v('ω','angular speed','rad/s',10,100),v('t','time','s',.001,.01)],'ε = N × B × A × ω × sin(ω × t)',{ε:x=>x.N*x.B*x.A*x.ω*Math.sin(x.ω*x.t)}, {},'Uniform rotation; phase chosen for zero EMF at t = 0. Radians.');
  P('rms-voltage','fields','RMS alternating voltage',v('Vᵣ','rms voltage','V'),[v('V₀','peak voltage','V',5,400)],1/Math.sqrt(2),'1/√2','Sinusoidal AC; identical relation for rms current.');
  P('rms-current','fields','RMS alternating current',v('Iᵣ','rms current','A'),[v('I₀','peak current','A',.1,20)],1/Math.sqrt(2),'1/√2');
  P('nuclear-radius','nuclear','Nuclear radius',v('R','nuclear radius','m'),[v('A','nucleon number','dimensionless',10,240,1/3)],1.2e-15,'r₀ (1.2e-15 m)','R = r₀ A^(1/3).');
  P('mass-energy','nuclear','Mass–energy equivalence',v('E','rest energy / binding energy','J'),[v('Δm','mass / mass defect','kg',1e-30,1e-26)],c*c,'c² (c = 3.00e8 m/s)');
  P('activity','nuclear','Radioactive activity',v('A','activity','Bq'),[v('λ','decay constant','s⁻¹',.00001,.01),v('N','undecayed nuclei','nuclei',1e6,1e12)]);
  P('half-life','nuclear','Half-life and decay constant',v('T','half-life','s'),[v('λ','decay constant','s⁻¹',.00001,.01,-1)],Math.log(2),'ln 2','T = ln 2 / λ.');
  pc('decay','nuclear','Exponential radioactive decay',v('N','remaining nuclei','nuclei'),[v('N₀','initial nuclei','nuclei',1e6,1e10),v('λ','decay constant','s⁻¹',.001,.01),v('t','elapsed time','s',10,100)],'N = N₀ × exp(−λ × t)',{N:x=>x["N₀"]*Math.exp(-x.λ*x.t),"N₀":x=>x.N*Math.exp(x.λ*x.t),λ:x=>-Math.log(x.N/x["N₀"])/x.t,t:x=>-Math.log(x.N/x["N₀"])/x.λ},{"N₀":'N₀ = N × exp(λ × t)',λ:'λ = −ln(N / N₀) / t',t:'t = −ln(N / N₀) / λ'},'The same law holds for activity A and count rate after subtracting background.');
  P('binding-per-nucleon','nuclear','Binding energy per nucleon',v('Eₙ','binding energy per nucleon','MeV'),[v('E','total binding energy','MeV',100,1000),v('A','nucleon number','dimensionless',20,200,-1)]);
  // Chemistry quantitative relationships.
  C('avogadro','Particle number',v('N','number of particles','particles'),[v('n','amount','mol',.001,2)],6.02e23,'Nₐ (6.02e23 mol⁻¹)','N = nNₐ.',both);
  C('mass-percentage','Percentage by mass',v('P','mass percentage','%'),[v('m','mass of constituent','g',1,20),v('M','total sample mass','g',30,100,-1)],100,'100','Both masses use the same units.',both);
  C('rf','Chromatography Rf value',v('Rf','Rf value','dimensionless'),[v('d','distance moved by spot','cm',1,4),v('D','distance moved by solvent front','cm',5,10,-1)],1,'','Measure both distances from the baseline.',both);
  C('stoichiometry','Stoichiometric mole ratio',v('nB','amount of product B','mol'),[v('nA','amount of reactant A','mol',.01,1),v('b','coefficient of B','dimensionless',2,2),v('a','coefficient of A','dimensionless',1,1,-1)],1,'','Coefficients supplied by the balanced equation.',both);
  C('titre','Titration mole ratio',v('cB','unknown concentration','mol/dm³'),[v('cA','known concentration','mol/dm³',.05,.3),v('VA','known solution volume','dm³',.01,.03),v('b','coefficient of B','dimensionless',1,1),v('VB','unknown solution volume','dm³',.01,.03,-1),v('a','coefficient of A','dimensionless',1,1,-1)],1,'','cAVA/a = cBVB/b. Coefficients fixed at 1:1 for these examples; convert cm³ to dm³.',both,'triple');
  cc('isotope-mean','Relative atomic mass (two isotopes)',v('Ar','relative atomic mass','dimensionless'),[v('m₁','first isotope relative mass','dimensionless',10,10),v('m₂','second isotope relative mass','dimensionless',11,11),v('p','first isotope abundance','%',10,90)],'Ar = (m₁ × p + m₂ × (100 − p)) / 100',{Ar:x=>(x["m₁"]*x.p+x["m₂"]*(100-x.p))/100,p:x=>100*(x.Ar-x["m₂"])/(x["m₁"]-x["m₂"])},{p:'p = 100 × (Ar − m₂) / (m₁ − m₂)'},'Weighted mean. Abundances add to 100%.',both);
  cc('bond-enthalpy','Reaction enthalpy from mean bond enthalpies',v('ΔH','reaction enthalpy','kJ/mol'),[v('B','total energy to break bonds','kJ/mol',1500,2000),v('F','total energy released making bonds','kJ/mol',2200,3000)],'ΔH = B − F',{ΔH:x=>x.B-x.F,B:x=>x.ΔH+x.F,F:x=>x.B-x.ΔH},{B:'B = ΔH + F',F:'F = B − ΔH'},'Count bonds using the balanced equation. Negative ΔH is exothermic.',both);
  C('enthalpy-calorimetry','Molar reaction enthalpy',v('ΔH','molar reaction enthalpy','kJ/mol'),[v('q','heat absorbed by solution','J',100,10000),v('n','amount reacted','mol',.005,.1,-1)],-.001,'−1/1000','ΔH = −q/(1000n). Exothermic solution temperature rise gives negative ΔH.');
  cc('hess','Hess’s law using formation enthalpies',v('ΔH','reaction enthalpy','kJ/mol'),[v('P','sum of product formation enthalpies','kJ/mol',-1000,-600),v('R','sum of reactant formation enthalpies','kJ/mol',-500,-100)],'ΔH = P − R',{ΔH:x=>x.P-x.R,P:x=>x.ΔH+x.R,R:x=>x.P-x.ΔH},{P:'P = ΔH + R',R:'R = P − ΔH'},'Each sum includes stoichiometric coefficients. For combustion enthalpies reverse the subtraction.');
  cc('gibbs','Gibbs free energy',v('ΔG','Gibbs energy change','kJ/mol'),[v('ΔH','enthalpy change','kJ/mol',10,50),v('T','temperature','K',280,500),v('ΔS','entropy change','J/(mol K)',50,150)],'ΔG = ΔH − T × ΔS / 1000',{ΔG:x=>x.ΔH-x.T*x.ΔS/1000,ΔH:x=>x.ΔG+x.T*x.ΔS/1000,T:x=>1000*(x.ΔH-x.ΔG)/x.ΔS,ΔS:x=>1000*(x.ΔH-x.ΔG)/x.T},{ΔH:'ΔH = ΔG + T × ΔS / 1000',T:'T = 1000 × (ΔH − ΔG) / ΔS',ΔS:'ΔS = 1000 × (ΔH − ΔG) / T'},'Convert entropy J to kJ. Thermodynamic feasibility when ΔG < 0; says nothing about reaction rate.');
  C('feasible-temperature','Temperature at ΔG = 0',v('T','boundary temperature','K'),[v('ΔH','enthalpy change','kJ/mol',10,50),v('ΔS','entropy change','J/(mol K)',50,150,-1)],1000,'1000','T = ΔH/ΔS with matching energy units. Interpret signs separately.');
  cc('entropy','Entropy change',v('ΔS','entropy change','J/(mol K)'),[v('P','sum of product entropies','J/(mol K)',300,500),v('R','sum of reactant entropies','J/(mol K)',100,250)],'ΔS = P − R',{ΔS:x=>x.P-x.R,P:x=>x.ΔS+x.R,R:x=>x.P-x.ΔS},{P:'P = ΔS + R',R:'R = P − ΔS'},'Multiply each entropy by its balanced-equation coefficient.');
  C('rate-first','First-order rate equation',v('r','reaction rate','mol/(dm³ s)'),[v('k','rate constant','s⁻¹',.001,.1),v('A','reactant concentration','mol/dm³',.01,.3)],1,'','r = k[A]. Zero order: r = k; second order: r = k[A]².');
  C('rate-second','Second-order rate equation',v('r','reaction rate','mol/(dm³ s)'),[v('k','rate constant','dm³/(mol s)',.01,2),v('A','reactant concentration','mol/dm³',.01,.3,2)]);
  C('rate-two','Rate equation with two reactants',v('r','reaction rate','mol/(dm³ s)'),[v('k','rate constant','dm³/(mol s)',.01,2),v('A','first concentration','mol/dm³',.01,.3),v('B','second concentration','mol/dm³',.01,.3)],1,'','First order in A and B; total order two. General rate = k[A]^m[B]^n.');
  C('first-half-life','First-order half-life',v('T','half-life','s'),[v('k','rate constant','s⁻¹',.001,.1,-1)],Math.log(2),'ln 2','First order only; half-life independent of initial concentration.');
  cc('arrhenius','Arrhenius equation',v('k','rate constant (first-order example)','s⁻¹'),[v('A','pre-exponential factor','s⁻¹',1e8,1e10),v('Ea','activation energy','J/mol',40000,60000),v('T','temperature','K',290,400)],'k = A × exp(−Ea / (R × T))',{k:x=>x.A*Math.exp(-x.Ea/(8.31*x.T)),A:x=>x.k*Math.exp(x.Ea/(8.31*x.T)),Ea:x=>-8.31*x.T*Math.log(x.k/x.A),T:x=>-x.Ea/(8.31*Math.log(x.k/x.A))},{A:'A = k × exp(Ea / (R × T))',Ea:'Ea = −R × T × ln(k / A)',T:'T = −Ea / (R × ln(k / A))'},'R = 8.31 J/(mol K). Ea in J/mol; ln k = −Ea/(RT) + ln A. Units of k depend on total order.');
  C('kc','Kc for A + B ⇌ C',v('Kc','equilibrium constant','dm³/mol'),[v('C','equilibrium product concentration','mol/dm³',.05,.3),v('A','equilibrium A concentration','mol/dm³',.01,.1,-1),v('B','equilibrium B concentration','mol/dm³',.01,.1,-1)],1,'','Use equilibrium concentrations; coefficients become powers. Pure solids/liquids excluded.');
  C('kc-square','Kc for A ⇌ 2B',v('Kc','equilibrium constant','mol/dm³'),[v('B','equilibrium B concentration','mol/dm³',.05,.3,2),v('A','equilibrium A concentration','mol/dm³',.01,.1,-1)],1,'','For any reaction: Kc = product concentration powers / reactant concentration powers.');
  C('partial-pressure','Partial pressure',v('p','partial pressure','Pa'),[v('x','mole fraction','dimensionless',.05,.9),v('P','total pressure','Pa',1e5,5e5)]);
  C('mole-fraction','Mole fraction',v('x','mole fraction','dimensionless'),[v('n','amount of gas component','mol',.01,.1),v('N','total gas amount','mol',.2,1,-1)]);
  C('kp','Kp for A ⇌ 2B',v('Kp','equilibrium constant','Pa'),[v('pB','equilibrium B partial pressure','Pa',1e4,1e5,2),v('pA','equilibrium A partial pressure','Pa',1e4,1e5,-1)],1,'','Use the pressure unit specified; stoichiometric coefficients are powers.');
  cc('ph','pH and hydrogen ion concentration',v('pH','pH','dimensionless'),[v('H','hydrogen ion concentration','mol/dm³',1e-5,.01)],'pH = −log₁₀(H)',{pH:x=>-Math.log10(x.H),H:x=>10**(-x.pH)},{H:'H = 10^(−pH)'},'Strong monoprotic acid: [H⁺] ≈ acid concentration.');
  C('kw','Ionic product of water',v('H','hydrogen ion concentration','mol/dm³'),[v('OH','hydroxide ion concentration','mol/dm³',1e-5,.01,-1)],1e-14,'Kw (1.00e-14 mol²/dm⁶ at 298 K)','Kw = [H⁺][OH⁻]; Kw changes with temperature.');
  C('ka','Acid dissociation constant',v('Ka','acid dissociation constant','mol/dm³'),[v('H','hydrogen ion concentration','mol/dm³',.0001,.001),v('A','conjugate base concentration','mol/dm³',.0001,.001),v('HA','undissociated acid concentration','mol/dm³',.01,.1,-1)],1,'','Ka = [H⁺][A⁻]/[HA]. Equilibrium concentrations.');
  C('weak-acid','Weak acid hydrogen ion approximation',v('H','hydrogen ion concentration','mol/dm³'),[v('Ka','acid dissociation constant','mol/dm³',1e-6,1e-4,.5),v('c','initial acid concentration','mol/dm³',.1,1,.5)],1,'','[H⁺] ≈ √(Ka c); small dissociation, negligible water contribution.');
  C('buffer','Buffer hydrogen ion concentration',v('H','hydrogen ion concentration','mol/dm³'),[v('Ka','acid dissociation constant','mol/dm³',1e-6,1e-4),v('HA','acid concentration','mol/dm³',.05,.3),v('A','conjugate base concentration','mol/dm³',.05,.3,-1)],1,'','Approximation assumes acid and salt concentrations change negligibly at equilibrium.');
  cc('pka','pKa',v('pKa','pKa','dimensionless'),[v('Ka','acid dissociation constant','mol/dm³',1e-6,1e-3)],'pKa = −log₁₀(Ka)',{pKa:x=>-Math.log10(x.Ka),Ka:x=>10**(-x.pKa)},{Ka:'Ka = 10^(−pKa)'});
  cc('buffer-ph','Buffer pH',v('pH','buffer pH','dimensionless'),[v('pKa','pKa','dimensionless',3,6),v('A','conjugate base concentration','mol/dm³',.05,.3),v('HA','acid concentration','mol/dm³',.05,.3)],'pH = pKa + log₁₀(A / HA)',{pH:x=>x.pKa+Math.log10(x.A/x.HA),pKa:x=>x.pH-Math.log10(x.A/x.HA),A:x=>x.HA*10**(x.pH-x.pKa),HA:x=>x.A/10**(x.pH-x.pKa)},{pKa:'pKa = pH − log₁₀(A / HA)',A:'A = HA × 10^(pH − pKa)',HA:'HA = A / 10^(pH − pKa)'},'Equivalent to [H⁺] = Ka[HA]/[A⁻] under buffer approximations.');
  cc('cell-emf','Standard cell potential',v('E','standard cell EMF','V'),[v('E₊','positive electrode reduction potential','V',.2,1.5),v('E₋','negative electrode reduction potential','V',-1.5,-.2)],'E = E₊ − E₋',{E:x=>x["E₊"]-x["E₋"],"E₊":x=>x.E+x["E₋"],"E₋":x=>x["E₊"]-x.E},{"E₊":'E₊ = E + E₋',"E₋":'E₋ = E₊ − E'},'Both tabulated values are reduction potentials under standard conditions.');
  // Biology, ecology, genetics and statistical mathematical skills.
  B('cardiac','3.3','Cardiac output',v('Q','cardiac output','cm³/min'),[v('f','heart rate','beats/min',50,150),v('V','stroke volume','cm³/beat',50,100)]);
  B('ventilation','3.3','Minute ventilation',v('Q','minute ventilation','dm³/min'),[v('f','breathing frequency','breaths/min',10,30),v('V','tidal volume','dm³/breath',.3,.8)]);
  B('respiratory-quotient','3.5','Respiratory quotient',v('RQ','respiratory quotient','dimensionless'),[v('C','carbon dioxide volume','cm³',10,30),v('O','oxygen volume','cm³',35,50,-1)],1,'','Volumes compared at the same temperature and pressure.');
  B('water-uptake','b2','Potometer water uptake rate',v('r','water uptake rate','mm³/s'),[v('A','capillary cross-sectional area','mm²',.1,1),v('d','bubble distance','mm',5,50),v('t','time','s',30,300,-1)],1,'','Estimates water uptake, not a direct measure of transpiration.',both);
  bc('bacterial-growth','b1','Bacterial exponential growth',v('N','final population','cells'),[v('N₀','initial cells','cells',100,1000),v('t','elapsed time','min',20,80),v('g','generation time','min',20,40)],'N = N₀ × 2^(t / g)',{N:x=>x["N₀"]*2**(x.t/x.g),"N₀":x=>x.N/2**(x.t/x.g),t:x=>x.g*Math.log2(x.N/x["N₀"]),g:x=>x.t/Math.log2(x.N/x["N₀"])},{"N₀":'N₀ = N / 2^(t / g)',t:'t = g × log₂(N / N₀)',g:'g = t / log₂(N / N₀)'},'Ideal growth: nutrients and space not limiting. GCSE Separate Science; fractional model population is rounded at the end.',both);
  definitions.at(-1).scope='triple';
  B('mitotic-index','3.2','Mitotic index',v('I','mitotic index','%'),[v('m','cells undergoing mitosis','cells',10,80),v('N','total observed cells','cells',100,300,-1)],100,'100','As a fraction omit ×100.');
  B('cell-cycle','3.2','Cell cycle phase duration',v('t','estimated phase duration','min'),[v('n','cells in phase','cells',10,80),v('N','total observed cells','cells',100,300,-1),v('T','total cell cycle duration','min',600,1800)],1,'','Assumes representative sample and equal cycle lengths.');
  B('mark-recapture','3.7','Mark–release–recapture estimate',v('N','population estimate','organisms'),[v('M','marked in first sample','organisms',20,100),v('C','total second sample','organisms',20,100),v('R','marked recaptures','organisms',5,15,-1)],1,'','Closed population; marks retained; equal capture probability; marked individuals mix.');
  B('frequency','b7','Species frequency',v('F','frequency','%'),[v('q','quadrats with species present','quadrats',5,15),v('N','total quadrats','quadrats',20,40,-1)],100,'100','Presence per quadrat, not individual abundance.',both);
  bc('secondary-production','3.5','Net secondary production',v('N','net secondary production','kJ/(m² year)'),[v('I','ingested energy','kJ/(m² year)',200,400),v('F','faecal energy loss','kJ/(m² year)',20,60),v('R','respiratory loss','kJ/(m² year)',30,80)],'N = I − F − R',{N:x=>x.I-x.F-x.R,I:x=>x.N+x.F+x.R,F:x=>x.I-x.R-x.N,R:x=>x.I-x.F-x.N},{I:'I = N + F + R',F:'F = I − R − N',R:'R = I − F − N'},'Energy quantities refer to the same area and time.');
  bc('hardy-frequency','3.7','Hardy–Weinberg allele frequencies',v('p','dominant allele frequency','dimensionless'),[v('q','recessive allele frequency','dimensionless',.1,.8)],'p = 1 − q',{p:x=>1-x.q,q:x=>1-x.p},{q:'q = 1 − p'},'p + q = 1. Assumes large randomly mating population, no selection, mutation or migration.');
  B('hardy-recessive','3.7','Hardy–Weinberg recessive genotype',v('q²','recessive homozygote frequency','dimensionless'),[v('q','recessive allele frequency','dimensionless',.1,.8,2)],1,'','p² + 2pq + q² = 1. Square-root q² to find q.');
  B('hardy-dominant','3.7','Hardy–Weinberg dominant genotype',v('p²','dominant homozygote frequency','dimensionless'),[v('p','dominant allele frequency','dimensionless',.1,.8,2)]);
  bc('hardy-heterozygote','3.7','Hardy–Weinberg heterozygotes',v('H','heterozygote frequency','dimensionless'),[v('p','dominant allele frequency','dimensionless',.1,.45)],'H = 2 × p × (1 − p)',{H:x=>2*x.p*(1-x.p),p:x=>(1-Math.sqrt(1-2*x.H))/2},{p:'p = (1 − √(1 − 2 × H)) / 2'},'Uses q = 1 − p. This inverse takes the p ≤ 0.5 branch.');
  bc('simpson','3.7','Simpson’s diversity index',v('D','diversity index','dimensionless'),[v('n₁','first species count','organisms',10,30),v('n₂','second species count','organisms',10,30),v('n₃','third species count','organisms',10,30)],'D = 1 − (n₁² + n₂² + n₃²) / (n₁ + n₂ + n₃)²',{D:x=>1-(x["n₁"]*x["n₁"]+x["n₂"]*x["n₂"]+x["n₃"]*x["n₃"])/(x["n₁"]+x["n₂"]+x["n₃"])**2},{},'AQA form: D = 1 − Σ(n/N)². Here N is the sum of the three species counts; greater D means greater diversity.');
  bc('chi-squared','3.7','Chi-squared statistic (two categories)',v('χ²','chi-squared statistic','dimensionless'),[v('O₁','first observed count','organisms',20,40),v('O₂','second observed count','organisms',20,40),v('E₁','first expected count','organisms',30,30),v('E₂','second expected count','organisms',30,30)],'χ² = (O₁ − E₁)² / E₁ + (O₂ − E₂)² / E₂',{"χ²":x=>(x["O₁"]-x["E₁"])**2/x["E₁"]+(x["O₂"]-x["E₂"])**2/x["E₂"]},{},'Sum (O−E)²/E over all categories. Compare with a supplied critical value and valid degrees of freedom; expected counts should be ≥5.');
  B('mean','3.1','Arithmetic mean',v('x̄','mean','mm'),[v('Σx','sum of measurements','mm',100,1000),v('n','sample size','dimensionless',10,10,-1)]);
  B('sample-sd','3.1','Sample standard deviation',v('s','sample standard deviation','mm'),[v('SS','sum of squared deviations','mm²',20,200,.5),v('df','sample size minus one','dimensionless',9,9,-.5)],1,'','s = √(Σ(x−x̄)²/(n−1)); df = n−1.');
  B('standard-error','3.1','Standard error of the mean',v('SE','standard error','mm'),[v('s','sample standard deviation','mm',1,10),v('n','sample size','dimensionless',10,100,-.5)]);
  bc('t-test','3.1','Two-sample t statistic',v('t','t statistic','dimensionless'),[v('x₁','first mean','mm',30,50),v('x₂','second mean','mm',10,20),v('s₁','first standard deviation','mm',1,5),v('s₂','second standard deviation','mm',1,5),v('n₁','first sample size','dimensionless',10,10),v('n₂','second sample size','dimensionless',10,10)],'t = (x₁ − x₂) / √(s₁² / n₁ + s₂² / n₂)',{t:x=>(x["x₁"]-x["x₂"])/Math.sqrt(x["s₁"]*x["s₁"]/x["n₁"]+x["s₂"]*x["s₂"]/x["n₂"])},{},'Use the statistical-test formula and critical-value table supplied in the question; this is an independent two-sample form.');
  B('correlation','3.1','Pearson correlation coefficient',v('r','correlation coefficient','dimensionless'),[v('Sxy','sum of paired deviation products','mm²',5,15),v('Sxx','sum of squared x deviations','mm²',30,100,-.5),v('Syy','sum of squared y deviations','mm²',30,100,-.5)],1,'','r = Σ((x−x̄)(y−ȳ))/√(Σ(x−x̄)² Σ(y−ȳ)²). Critical values and assumptions matter; correlation does not prove causation.');
  // Cross-science uncertainty and geometry skills.
  for(const subject of ['physics','chemistry','biology']) mono('uncertainty-'+subject,subject,both,subject==='physics'?'measurements':subject==='chemistry'?'chem-physical':'3.1','Percentage uncertainty',v('U','percentage uncertainty','%'),[v('Δx','absolute uncertainty','mm',.01,.1),v('x','measured value','mm',10,50,-1)],100,'100','For a difference of two readings add their absolute uncertainties. For products/quotients add percentage uncertainties.');
  P('circle-area','measurements','Circular cross-sectional area',v('A','cross-sectional area','m²'),[v('d','diameter','m',.0001,.01,2)],Math.PI/4,'π/4','A = π(d/2)².');
  // Five AQA optional Physics routes. These are explicitly labelled, never mixed into core homework topics.
  P('telescope-magnification','astrophysics','Astronomical telescope magnification',v('M','angular magnification magnitude','×'),[v('fₒ','objective focal length','m',.5,2),v('fₑ','eyepiece focal length','m',.01,.1,-1)]);
  P('wien','astrophysics','Wien displacement law',v('λ','peak wavelength','m'),[v('T','surface temperature','K',3000,15000,-1)],2.9e-3,'b (2.90e-3 m K)');
  P('stefan','astrophysics','Stefan–Boltzmann luminosity',v('L','luminosity','W'),[v('r','stellar radius','m',1e8,1e10,2),v('T','surface temperature','K',3000,15000,4)],4*Math.PI*5.67e-8,'4πσ (σ = 5.67e-8 W/(m² K⁴))','Treat the star as a black body.');
  P('stellar-flux','astrophysics','Stellar flux at Earth',v('F','received flux','W/m²'),[v('L','stellar luminosity','W',1e25,1e29),v('d','distance','m',1e16,1e18,-2)],1/(4*Math.PI),'1/(4π)');
  P('hubble','astrophysics','Hubble’s law',v('v','recession speed','m/s'),[v('H','Hubble constant','s⁻¹',2e-18,2.4e-18),v('d','distance','m',1e22,1e24)]);
  P('hubble-age','astrophysics','Hubble time',v('T','approximate universe age','s'),[v('H','Hubble constant','s⁻¹',2e-18,2.4e-18,-1)],1,'','Simple constant-expansion estimate, not a full cosmological age model.');
  P('schwarzschild','astrophysics','Schwarzschild radius',v('R','event horizon radius','m'),[v('M','black-hole mass','kg',1e30,1e32)],2*G/(c*c),'2G/c² (G = 6.67e-11; c = 3.00e8 m/s)');
  P('parallax','astrophysics','Parallax distance',v('d','distance','pc'),[v('p','parallax angle','arcsec',.01,.5,-1)]);
  pc('absolute-magnitude','astrophysics','Apparent and absolute magnitude',v('M','absolute magnitude','mag'),[v('m','apparent magnitude','mag',5,15),v('d','distance','pc',20,1000)],'M = m − 5 × log₁₀(d / 10)',{M:x=>x.m-5*Math.log10(x.d/10),m:x=>x.M+5*Math.log10(x.d/10),d:x=>10*10**((x.m-x.M)/5)},{m:'m = M + 5 × log₁₀(d / 10)',d:'d = 10 × 10^((m − M) / 5)'},'Distance in parsecs; ignore interstellar extinction.');
  P('rayleigh','astrophysics','Rayleigh angular resolution',v('θ','minimum resolvable angle','rad'),[v('λ','wavelength','m',4e-7,7e-7),v('D','aperture diameter','m',.1,5,-1)],1.22,'1.22');
  pc('redshift','astrophysics','Wavelength redshift',v('z','redshift','dimensionless'),[v('λo','observed wavelength','nm',700,900),v('λe','emitted wavelength','nm',400,600)],'z = (λo − λe) / λe',{z:x=>(x.λo-x.λe)/x.λe,λo:x=>x.λe*(1+x.z),λe:x=>x.λo/(1+x.z)},{λo:'λo = λe × (1 + z)',λe:'λe = λo / (1 + z)'},'Small-speed limit recession speed v ≈ cz; do not use for large z.');
  P('lens-power','medical','Lens power',v('P','lens power','D'),[v('f','focal length','m',.05,.5,-1)]);
  pc('lens','medical','Thin lens equation',v('v','image distance','m'),[v('u','object distance','m',.5,2),v('f','focal length','m',.05,.2)],'v = f × u / (u − f)',{v:x=>x.f*x.u/(x.u-x.f),u:x=>x.f*x.v/(x.v-x.f),f:x=>x.u*x.v/(x.u+x.v)},{u:'u = f × v / (v − f)',f:'f = u × v / (u + v)'},'1/f = 1/u + 1/v. Real-is-positive convention; converging lens, object beyond focus.');
  P('lens-magnification','medical','Linear lens magnification',v('M','magnification magnitude','×'),[v('v','image distance magnitude','m',.1,2),v('u','object distance magnitude','m',.1,2,-1)],1,'','Magnitude v/u; image orientation handled separately.');
  pc('decibels','medical','Sound intensity level',v('L','intensity level','dB'),[v('I','sound intensity','W/m²',1e-8,.001)],'L = 10 × log₁₀(I / I₀)',{L:x=>10*Math.log10(x.I/1e-12),I:x=>1e-12*10**(x.L/10)},{I:'I = I₀ × 10^(L / 10)'},'I₀ = 1e-12 W/m².');
  P('acoustic-impedance','medical','Acoustic impedance',v('Z','acoustic impedance','kg/(m² s)'),[v('ρ','density','kg/m³',800,2000),v('c','sound speed','m/s',1000,3000)]);
  pc('ultrasound-reflection','medical','Ultrasound reflected intensity fraction',v('R','reflected intensity fraction','dimensionless'),[v('Z₁','first impedance','kg/(m² s)',1e6,1.5e6),v('Z₂','second impedance','kg/(m² s)',2e6,4e6)],'R = ((Z₂ − Z₁) / (Z₂ + Z₁))²',{R:x=>((x["Z₂"]-x["Z₁"])/(x["Z₂"]+x["Z₁"]))**2},{},'Normal incidence; R = Iᵣ/Iᵢ.');
  P('echo-depth','medical','Ultrasound echo depth',v('d','reflector depth','m'),[v('c','sound speed','m/s',1400,1600),v('t','echo round-trip time','s',.00001,.0002)],.5,'½');
  pc('attenuation','medical','X-ray attenuation',v('I','transmitted intensity','W/m²'),[v('I₀','incident intensity','W/m²',1,10),v('μ','linear attenuation coefficient','m⁻¹',1,10),v('x','thickness','m',.01,.2)],'I = I₀ × exp(−μ × x)',{I:z=>z["I₀"]*Math.exp(-z.μ*z.x),"I₀":z=>z.I*Math.exp(z.μ*z.x),μ:z=>-Math.log(z.I/z["I₀"])/z.x,x:z=>-Math.log(z.I/z["I₀"])/z.μ},{"I₀":'I₀ = I × exp(μ × x)',μ:'μ = −ln(I / I₀) / x',x:'x = −ln(I / I₀) / μ'});
  P('half-value','medical','Half-value thickness',v('x','half-value thickness','m'),[v('μ','attenuation coefficient','m⁻¹',1,10,-1)],Math.log(2),'ln 2');
  P('dose','medical','Absorbed radiation dose',v('D','absorbed dose','Gy'),[v('E','absorbed energy','J',.001,.1),v('m','irradiated mass','kg',.1,5,-1)]);
  P('equivalent-dose','medical','Equivalent radiation dose',v('H','equivalent dose','Sv'),[v('w','radiation weighting factor','dimensionless',1,1),v('D','absorbed dose','Gy',.001,.1)],1,'','Weighting factor supplied; here photons with w = 1.');
  P('rotational-force','engineering','Torque and angular acceleration',v('τ','torque','N m'),[v('I','moment of inertia','kg m²',.01,2),v('α','angular acceleration','rad/s²',.5,20)]);
  P('angular-momentum','engineering','Angular momentum',v('L','angular momentum','kg m²/s'),[v('I','moment of inertia','kg m²',.01,2),v('ω','angular speed','rad/s',1,50)]);
  P('rotational-energy','engineering','Rotational kinetic energy',v('E','rotational kinetic energy','J'),[v('I','moment of inertia','kg m²',.01,2),v('ω','angular speed','rad/s',1,50,2)],.5,'½');
  P('rotational-work','engineering','Rotational work',v('W','work done','J'),[v('τ','constant torque','N m',1,100),v('θ','angle turned','rad',.5,20)]);
  P('rotational-power','engineering','Rotational power',v('P','power','W'),[v('τ','torque','N m',1,100),v('ω','angular speed','rad/s',1,50)]);
  P('flywheel-period','engineering','Rotating system frequency',v('f','frequency','Hz'),[v('ω','angular speed','rad/s',1,50)],1/(2*Math.PI),'1/(2π)');
  P('inertia-ring','engineering','Moment of inertia of a thin ring',v('I','moment of inertia','kg m²'),[v('m','mass','kg',.1,5),v('r','radius','m',.1,.8,2)],1,'','About central symmetry axis.');
  P('inertia-disc','engineering','Moment of inertia of a uniform disc',v('I','moment of inertia','kg m²'),[v('m','mass','kg',.1,5),v('r','radius','m',.1,.8,2)],.5,'½','About central symmetry axis.');
  P('inertia-rod','engineering','Moment of inertia of a uniform rod',v('I','moment of inertia','kg m²'),[v('m','mass','kg',.1,5),v('L','length','m',.2,2,2)],1/12,'1/12','Axis through centre, perpendicular to rod.');
  pc('parallel-axis','engineering','Parallel axis theorem',v('I','moment of inertia','kg m²'),[v('I₀','centre-of-mass moment of inertia','kg m²',.1,1),v('m','mass','kg',.1,5),v('d','axis separation','m',.1,.8)],'I = I₀ + m × d²',{I:x=>x["I₀"]+x.m*x.d*x.d,"I₀":x=>x.I-x.m*x.d*x.d,m:x=>(x.I-x["I₀"])/(x.d*x.d),d:x=>Math.sqrt((x.I-x["I₀"])/x.m)},{"I₀":'I₀ = I − m × d²',m:'m = (I − I₀) / d²',d:'d = √((I − I₀) / m)'});
  pc('first-law','engineering','First law of thermodynamics',v('ΔU','internal energy change','J'),[v('Q','heat supplied to system','J',500,1000),v('W','work done by system','J',100,400)],'ΔU = Q − W',{ΔU:x=>x.Q-x.W,Q:x=>x.ΔU+x.W,W:x=>x.Q-x.ΔU},{Q:'Q = ΔU + W',W:'W = Q − ΔU'},'Sign convention: W is work done by the gas; equivalent ΔU = Q + work done on gas.');
  P('gas-work','engineering','Work by expanding gas',v('W','work done','J'),[v('p','constant pressure','Pa',1e5,3e5),v('ΔV','volume increase','m³',.001,.01)]);
  pc('heat-engine','engineering','Heat engine efficiency',v('η','efficiency','%'),[v('Qh','heat received','J',1000,2000),v('Qc','heat rejected','J',200,800)],'η = 100 × (Qh − Qc) / Qh',{η:x=>100*(x.Qh-x.Qc)/x.Qh,Qh:x=>x.Qc/(1-x.η/100),Qc:x=>x.Qh*(1-x.η/100)},{Qh:'Qh = Qc / (1 − η / 100)',Qc:'Qc = Qh × (1 − η / 100)'},'Work output Qh − Qc per cycle.');
  pc('carnot','engineering','Maximum heat engine efficiency',v('η','maximum efficiency','%'),[v('Tc','cold reservoir temperature','K',250,300),v('Th','hot reservoir temperature','K',400,800)],'η = 100 × (1 − Tc / Th)',{η:x=>100*(1-x.Tc/x.Th),Tc:x=>x.Th*(1-x.η/100),Th:x=>x.Tc/(1-x.η/100)},{Tc:'Tc = Th × (1 − η / 100)',Th:'Th = Tc / (1 − η / 100)'},'Reversible Carnot limit; absolute temperatures.');
  P('electron-acceleration','turning-points','Electron speed through a potential difference',v('v','electron speed','m/s'),[v('V','accelerating voltage','V',10,1000,.5)],Math.sqrt(2*e/9.11e-31),'√(2e/mₑ) (e = 1.60e-19 C; mₑ = 9.11e-31 kg)','Non-relativistic electron initially at rest.');
  P('charge-mass-orbit','turning-points','Electron charge-to-mass ratio',v('e/m','charge-to-mass ratio','C/kg'),[v('V','accelerating voltage','V',100,1000),v('B','magnetic flux density','T',.001,.003,-2),v('r','orbit radius','m',.03,.1,-2)],2,'2','e/m = 2V/(B²r²), non-relativistic electrons perpendicular to field.');
  pc('lorentz','turning-points','Lorentz factor',v('γ','Lorentz factor','dimensionless'),[v('v','relative speed','m/s',.1*c,.8*c)],'γ = 1 / √(1 − v² / c²)',{γ:x=>1/Math.sqrt(1-x.v*x.v/(c*c)),v:x=>c*Math.sqrt(1-1/(x.γ*x.γ))},{v:'v = c × √(1 − 1 / γ²)'},'c = 3.00e8 m/s; v < c.');
  P('time-dilation','turning-points','Time dilation',v('t','dilated time','s'),[v('γ','Lorentz factor','dimensionless',1.1,3),v('t₀','proper time','s',.001,10)]);
  P('length-contraction','turning-points','Length contraction',v('L','contracted length','m'),[v('L₀','proper length','m',1,100),v('γ','Lorentz factor','dimensionless',1.1,3,-1)]);
  P('relativistic-energy','turning-points','Relativistic total energy',v('E','total energy','J'),[v('γ','Lorentz factor','dimensionless',1.1,3),v('m₀','rest mass','kg',9.11e-31,1.67e-27)],c*c,'c² (c = 3.00e8 m/s)');
  pc('relativistic-kinetic','turning-points','Relativistic kinetic energy',v('K','kinetic energy','J'),[v('γ','Lorentz factor','dimensionless',1.1,3),v('m₀','rest mass','kg',9.11e-31,1.67e-27)],'K = (γ − 1) × m₀ × c²',{K:x=>(x.γ-1)*x["m₀"]*c*c,γ:x=>1+x.K/(x["m₀"]*c*c),"m₀":x=>x.K/((x.γ-1)*c*c)},{γ:'γ = 1 + K / (m₀ × c²)',"m₀":'m₀ = K / ((γ − 1) × c²)'},'c = 3.00e8 m/s.');
  P('inverting-gain','electronics','Inverting operational amplifier gain',v('G','voltage gain','dimensionless'),[v('Rf','feedback resistance','Ω',10000,100000),v('Ri','input resistance','Ω',1000,5000,-1)],-1,'−1','Output inverted; ideal op amp with negative feedback, below saturation.');
  pc('noninverting-gain','electronics','Non-inverting operational amplifier gain',v('G','voltage gain','dimensionless'),[v('Rf','feedback resistance','Ω',10000,100000),v('R₁','resistance to ground','Ω',1000,5000)],'G = 1 + Rf / R₁',{G:x=>1+x.Rf/x["R₁"],Rf:x=>(x.G-1)*x["R₁"],"R₁":x=>x.Rf/(x.G-1)},{Rf:'Rf = (G − 1) × R₁',"R₁":'R₁ = Rf / (G − 1)'},'Ideal op amp, negative feedback, unsaturated output.');
  P('amplifier-output','electronics','Amplifier output voltage',v('Vo','output voltage','V'),[v('G','gain','dimensionless',2,10),v('Vi','input voltage','V',.01,.5)],1,'','Output cannot exceed supply rails.');
  P('bandwidth','electronics','Gain–bandwidth product',v('f','bandwidth','Hz'),[v('GB','gain–bandwidth product','Hz',1e5,1e7),v('G','gain magnitude','dimensionless',10,100,-1)]);
  P('adc-step','electronics','ADC quantisation step',v('ΔV','voltage step','V'),[v('V','full-scale span','V',1,10),v('L','number of quantisation levels','dimensionless',256,256,-1)],1,'','L = 2^n for n bits. Uses span/2^n convention; if endpoint codes include both rails follow the stated convention.');
  P('bit-rate','electronics','Serial bit rate',v('B','bit rate','bit/s'),[v('n','bits per sample','bit',8,8),v('f','sample frequency','Hz',1000,100000)]);
  P('sampling','electronics','Nyquist minimum sampling frequency',v('fs','minimum sampling frequency','Hz'),[v('f','highest signal frequency','Hz',100,10000)],2,'2','Sample above twice the maximum signal frequency; practical filtering needs a margin.');
  P('attenuation-db','electronics','Power attenuation ratio',v('A','attenuation ratio','dimensionless'),[v('Pi','input power','W',1,10),v('Po','output power','W',.001,.1,-1)],1,'','Attenuation in dB = 10 log₁₀(Pi/Po); voltage ratios use 20 log₁₀ for equal impedances.');

  P('optical-magnification','p6','Image height magnification',v('M','magnification','×'),[v('hi','image height','mm',10,100),v('ho','object height','mm',2,10,-1)],1,'','Use image height / object height in matching units.',both,'triple');
  B('inverse-time-rate','b2','Rate from completion time',v('r','relative rate','s⁻¹'),[v('t','time to a fixed endpoint','s',10,300,-1)],1,'','For a fixed amount of change, relative rate is proportional to 1/time.',both);
  C('tof-time','Time-of-flight drift time',v('t','drift time','s'),[v('d','drift distance','m',.5,2),v('v','ion speed','m/s',1e4,1e5,-1)],1,'','Drift region has no accelerating field: t = d/v.');
  C('tof-mass','Time-of-flight ion mass',v('m','ion mass','kg'),[v('E','ion kinetic energy','J',1e-17,1e-16),v('t','drift time','s',1e-6,1e-5,2),v('d','drift distance','m',.5,2,-2)],2,'2','Combine E = ½mv² and v = d/t.');
  C('molecular-multiplier','Empirical to molecular formula multiplier',v('k','formula multiplier','dimensionless'),[v('Mr','molecular relative mass','dimensionless',180,180),v('Er','empirical formula relative mass','dimensionless',30,30,-1)],1,'','Multiply all empirical subscripts by Mr/Er; the multiplier should be a whole number for consistent data.',both);
  bc('spearman','3.1','Spearman rank correlation',v('r','rank correlation coefficient','dimensionless'),[v('SS','sum of squared rank differences','dimensionless',10,100),v('n','number of paired ranks','dimensionless',10,10)],'r = 1 − 6 × SS / (n × (n² − 1))',{r:x=>1-6*x.SS/(x.n*(x.n*x.n-1))},{},'No tied ranks in this form. Follow the supplied test formula, ranking method and critical values.');
  P('grating-spacing','waves','Diffraction grating line density',v('d','line spacing','m'),[v('N','lines per metre','m⁻¹',1e5,8e5,-1)]);
  P('charge-carriers','electricity','Number of electrons transferred',v('N','electron count','electrons'),[v('Q','charge magnitude','C',.001,2)],1/e,'1/e (e = 1.60e-19 C)');
  P('uniform-gravity','fields','Gravitational field from force',v('g','field strength','N/kg'),[v('F','force','N',1,100),v('m','test mass','kg',.1,10,-1)]);
  P('field-potential-gradient','fields','Field from potential gradient magnitude',v('E','electric field magnitude','V/m'),[v('ΔV','potential change magnitude','V',10,1000),v('Δx','distance interval','m',.01,.5,-1)],1,'','Signed relation E = −dV/dx; these questions use magnitudes over a uniform region.');
  P('attenuation-electronics-db','electronics','Signal attenuation in decibels',v('D','attenuation','dB'),[v('logR','log₁₀(input power/output power)','dimensionless',.5,3)],10,'10','D = 10 log₁₀(Pin/Pout). For equal impedance voltage ratios, use 20 log₁₀(Vin/Vout).');
  pc('astable','electronics','555 astable frequency',v('f','frequency','Hz'),[v('R₁','first timing resistance','Ω',1000,10000),v('R₂','second timing resistance','Ω',10000,100000),v('C','timing capacitance','F',1e-7,1e-5)],'f = 1.44 / ((R₁ + 2 × R₂) × C)',{f:x=>1.44/((x['R₁']+2*x['R₂'])*x.C),C:x=>1.44/((x['R₁']+2*x['R₂'])*x.f)},{C:'C = 1.44 / ((R₁ + 2 × R₂) × f)'},'Standard 555 astable circuit; component tolerances affect actual frequency.');
  P('monostable','electronics','555 monostable pulse duration',v('t','pulse duration','s'),[v('R','timing resistance','Ω',1000,100000),v('C','timing capacitance','F',1e-7,1e-5)],1.1,'1.1','Standard 555 monostable circuit.');
  pc('summing-amplifier','electronics','Inverting summing amplifier',v('Vo','output voltage','V'),[v('V₁','first input voltage','V',.1,.5),v('V₂','second input voltage','V',.1,.5),v('Rf','feedback resistance','Ω',10000,20000),v('R','equal input resistance','Ω',5000,10000)],'Vo = −Rf × (V₁ + V₂) / R',{Vo:x=>-x.Rf*(x['V₁']+x['V₂'])/x.R},{},'Equal input resistors, ideal op amp, output within supply rails.');
  P('xray-cutoff','medical','Minimum X-ray wavelength',v('λ','minimum wavelength','m'),[v('V','accelerating voltage','V',10000,100000,-1)],h*c/e,'hc/e (h = 6.63e-34 J s; c = 3.00e8 m/s; e = 1.60e-19 C)','Maximum photon energy equals electron energy eV.');
  P('doppler-ultrasound','medical','Doppler ultrasound frequency shift',v('Δf','frequency shift magnitude','Hz'),[v('f','incident ultrasound frequency','Hz',1e6,5e6),v('v','flow speed along beam','m/s',.05,.5),v('c','sound speed','m/s',1540,1540,-1)],2,'2','Two-way reflection; speed along beam. For an angle θ multiply by cos θ.');
  P('isotope-dose-rate','medical','Absorbed dose rate',v('r','dose rate','Gy/s'),[v('D','absorbed dose','Gy',.001,.1),v('t','exposure duration','s',1,100,-1)]);
  P('redshift-speed','astrophysics','Low-speed redshift recession speed',v('v','recession speed','m/s'),[v('z','redshift','dimensionless',.001,.03)],c,'c (3.00e8 m/s)','v ≈ cz only when recession speed is small compared with c.');
  pc('magnitude-difference','astrophysics','Magnitude and intensity ratio',v('Δm','magnitude difference','mag'),[v('I₁','first observed intensity','W/m²',1e-9,5e-9),v('I₂','second observed intensity','W/m²',1e-11,1e-10)],'Δm = −2.5 × log₁₀(I₁ / I₂)',{Δm:x=>-2.5*Math.log10(x['I₁']/x['I₂'])},{},'Δm = m₁−m₂; brighter sources have smaller magnitude.');
  P('selector','turning-points','Crossed-field velocity selector',v('v','selected particle speed','m/s'),[v('E','electric field','V/m',1e3,1e5),v('B','magnetic flux density','T',.001,.1,-1)],1,'','Electric and magnetic forces balance; velocity perpendicular to both fields.');
  P('millikan','turning-points','Stationary oil-drop charge',v('q','charge magnitude','C'),[v('m','drop mass','kg',1e-15,1e-14),v('E','electric field','V/m',1e4,1e5,-1)],9.8,'g (9.8 m/s²)','Electric force balances weight. Buoyancy neglected in this simplified calculation.');
  pc('angular-suvat','engineering','Uniform angular acceleration',v('θ','angular displacement','rad'),[v('ω₀','initial angular speed','rad/s',1,10),v('α','angular acceleration','rad/s²',.5,5),v('t','time','s',1,10)],'θ = ω₀ × t + α × t² / 2',{θ:x=>x['ω₀']*x.t+x.α*x.t*x.t/2,α:x=>2*(x.θ-x['ω₀']*x.t)/(x.t*x.t)},{α:'α = 2 × (θ − ω₀ × t) / t²'},'Constant angular acceleration; equivalent linear kinematic equations apply with s,u,v,a replaced by θ,ω₀,ω,α.');
  pc('angular-speed-change','engineering','Angular speed with constant acceleration',v('ω','final angular speed','rad/s'),[v('ω₀','initial angular speed','rad/s',1,10),v('α','angular acceleration','rad/s²',.5,5),v('t','time','s',1,10)],'ω = ω₀ + α × t',{ω:x=>x['ω₀']+x.α*x.t,"ω₀":x=>x.ω-x.α*x.t,α:x=>(x.ω-x['ω₀'])/x.t,t:x=>(x.ω-x['ω₀'])/x.α},{"ω₀":'ω₀ = ω − α × t',α:'α = (ω − ω₀) / t',t:'t = (ω − ω₀) / α'});
  P('monatomic-internal','engineering','Monatomic ideal-gas internal energy',v('U','internal energy','J'),[v('n','amount','mol',.01,1),v('T','temperature','K',200,600)],1.5*8.31,'3R/2 (R = 8.31 J/(mol K))','Translational kinetic energy only; monatomic ideal gas.');
  P('isothermal-gas','engineering','Isothermal gas pressure change',v('p₂','final pressure','Pa'),[v('p₁','initial pressure','Pa',1e5,3e5),v('V₁','initial volume','m³',.001,.005),v('V₂','final volume','m³',.006,.01,-1)],1,'','Fixed gas amount and constant temperature.');
  P('adiabatic-gas','engineering','Adiabatic gas pressure change',v('p₂','final pressure','Pa'),[v('p₁','initial pressure','Pa',1e5,3e5),v('V₁','initial volume','m³',.001,.005,1.4),v('V₂','final volume','m³',.006,.01,-1.4)],1,'','p₁V₁^γ = p₂V₂^γ; ideal diatomic gas with γ = 1.4, reversible adiabatic process.');

  const separate = new Set(['pressure','momentum','moment','molarity','gas-volume','yield','atom-economy','transfer']);
  const physicsTopics = {p1:'mechanics-materials',p2:'electricity',p3:'further-mechanics',p5:'mechanics-materials',p6:'waves',p7:'fields',measurements:'measurements'};
  const biologyTopics = {b1:'bio-cells',b2:'bio-exchange',b7:'bio-energy','3.1':'bio-molecules','3.2':'bio-cells','3.3':'bio-exchange','3.5':'bio-energy','3.7':'bio-populations'};
  definitions.forEach(d => {d.scope = separate.has(d.id) ? 'triple' : d.scope || 'combined'; d.topics = {gcse:d.subject==='chemistry'&&d.topic==='chem-physical'?({'avogadro':'c3','mass-percentage':'c3','rf':'c8','stoichiometry':'c3','titre':'c3','isotope-mean':'c1','bond-enthalpy':'c5','molecular-multiplier':'c3'}[d.id]||'c3'):d.topic,alevel:d.subject === 'physics' ? physicsTopics[d.topic] || d.topic : d.subject === 'chemistry' ? 'chem-physical' : biologyTopics[d.topic] || d.topic};});
  definitions.filter(d=>d.subject==='physics').forEach(d=>{d.topics.gcse=({electricity:'p2',waves:'p6','mechanics-materials':'p5',fields:'p7','further-mechanics':'p3',nuclear:'p4'}[d.topic]||d.topics.gcse);});
  function rng(seed) {let a = Number(seed) >>> 0; return () => {a += 0x6D2B79F5;let t = a;t = Math.imul(t ^ t >>> 15,t | 1);t ^= t + Math.imul(t ^ t >>> 7,t | 61);return ((t ^ t >>> 14) >>> 0) / 4294967296;};}
  function rounded(n) {return Number(n.toPrecision(3));}
  function format(n) {return Number(n).toPrecision(3).replace(/\.0+(?=e|$)/,'').replace(/(\.\d*?)0+(?=e|$)/,'$1');}
  function parse(value) {const t = String(value ?? '').trim().replace(/−/g,'-');if (!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(t)) return null;const n=Number(t);return Number.isFinite(n)?n:null;}
  function close(value, expected) {const n = parse(value),tolerance=expected===0?1e-12:0.51*10**(Math.floor(Math.log10(Math.abs(expected)))-2);return n !== null && Math.abs(n-expected) <= tolerance;}
  function normalUnit(unit) {return String(unit).trim().toLowerCase().replace(/micro/g,'μ').replace(/µ/g,'μ').replace(/ohms?/g,'ω').replace(/degrees?\s*c(?:elsius)?/g,'°c').replace(/\^?2/g,'²').replace(/\^?3/g,'³').replace(/\*|·/g,' ').replace(/\s+/g,'');}
  function unitCorrect(input, expected) {const aliases = {'×':['','x','times','dimensionless'], '%':['percent'], 'N m':['nm','n*m'], 'organisms':['organism'], 'mm⁻¹':['1/mm','mm^-1'],'kg m/s':['kgm/s','kgms^-1']};return normalUnit(input)===normalUnit(expected) || (aliases[expected] || []).some(a=>normalUnit(input)===normalUnit(a));}
  function available({level='gcse',subject='physics',pathway='combined',topic='all'}={}) {return definitions.filter(d=>d.levels.includes(level) && (subject==='all'||d.subject===subject) && (level!=='gcse'||pathway==='triple'||d.scope!=='triple') && (topic==='all'||d.topics[level]===topic));}
  function solve(d, target, values) {
    if(d.kind==='custom')return d.calculate[target](values);
    if(d.kind==='acceleration'){const {a,u,v,t}=values;return target==='a'?(v-u)/t:target==='u'?v-a*t:target==='v'?u+a*t:(v-u)/a;}
    if(d.kind==='percentage-change'){const {P,F,I}=values;return target==='P'?100*(F-I)/I:target==='F'?I*(1+P/100):F/(1+P/100);}
    if(d.kind==='net-production'){const {N,G,R}=values;return target==='N'?G-R:target==='G'?N+R:G-N;}
    if(target===d.result.symbol) return d.inputs.reduce((n,v)=>n*Math.pow(values[v.symbol],v.power),d.coefficient);
    const v=d.inputs.find(x=>x.symbol===target);
    const factor=d.inputs.filter(x=>x!==v).reduce((n,x)=>n*Math.pow(values[x.symbol],x.power),d.coefficient);
    return Math.pow(values[d.result.symbol]/factor,1/v.power);
  }
  function build(id,seed=1,demand='standard',targetSymbol,retry=0) {
    const d = definitions.find(x=>x.id===id);if (!d) throw new Error('Unknown equation.');
    const random=rng(seed), all=[d.result,...d.inputs];
    const targets=all.filter(x=>d.forms[x.symbol]);
    const target=targets.find(x=>x.symbol===targetSymbol) || (demand==='support'?d.result:targets[Math.floor(random()*targets.length)]);
    const values={};d.inputs.forEach(x=>{const n=x.low+(x.high-x.low)*random();values[x.symbol]=['organisms','cells','quadrats','turns','nuclei','electrons'].includes(x.unit)?Math.round(n):rounded(n);});
    if(d.id==='chi-squared')values['O₂']=60-values['O₁'];
    values[d.result.symbol]=rounded(solve(d,d.result.symbol,values));
    const givens=all.filter(x=>x!==target).map(x=>{
      const alternatives=units[x.unit];
      const alternate=demand==='stretch' && alternatives?.length ? alternatives[Math.floor(random()*alternatives.length)] : null;
      const unit=alternate?alternate[0]:x.unit, scale=alternate?alternate[1]:1;
      const displayed=rounded(values[x.symbol]/scale);
      values[x.symbol]=displayed*scale;
      return {...x,value:displayed,unit,baseUnit:x.unit,scale,baseValue:values[x.symbol]};
    });
    const expected=solve(d,target.symbol,values);
    if(!Number.isFinite(expected)||!Number.isFinite(values[d.result.symbol])){if(retry>=50)throw Error('Could not generate valid values for '+id);return build(id,(seed+7919)>>>0,demand,target.symbol,retry+1);}
    const conversions=givens.map(x=>`${x.symbol}: ${format(x.value)} ${x.unit}${x.scale!==1?` × ${x.scale} = ${format(x.baseValue)} ${x.baseUnit}`:' (already in the required units)'}`);
    const substitutions=givens.map(x=>`${x.symbol} = ${format(x.baseValue)}`).join(', ');
    const numerical=d.kind?substitute(d.forms[target.symbol].split(' = ')[1],values):expression(d,target.symbol,values);
    const steps=[`Select and rearrange: ${d.forms[target.symbol]}`, ...conversions, `Substitute ${substitutions}${d.constant?`; constant: ${d.constant}`:''}.`,`${target.symbol} = ${numerical}`, `Calculate ${target.symbol} = ${format(expected)} ${target.unit} (3 significant figures).`];
    return {id:`${id}:${seed}:${demand}:${target.symbol}`,equationId:id,seed,demand,definition:d,target,givens,expected,unit:target.unit,formula:d.forms[target.symbol],prompt:`Calculate the ${target.name} in ${target.unit}. ${givens.map(x=>`${x.name} ${x.symbol} = ${format(x.value)} ${x.unit}`).join('; ')}.${d.constant?` Use ${d.constant}.`:''}`,steps,values};
  }
  function substitute(formula,values) {
    const constants={h:6.63e-34,c:3e8,R:8.31,'I₀':1e-12};
    const data={...constants,...values};
    const names=Object.keys(data).sort((a,b)=>b.length-a.length).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
    const re=new RegExp('(?<![\\p{L}\\p{N}₀₁₂₃₊₋])('+names.join('|')+')(?![\\p{L}\\p{N}₀₁₂₃₊₋])','gu');
    return formula.replace(re,s=>'('+format(data[s])+')');
  }
  function assess(q,answer={}) {return {formula:answer.formula===q.formula, conversions:q.givens.map(x=>close(answer.conversions?.[x.symbol],x.baseValue)),value:close(answer.value,q.expected),unit:unitCorrect(answer.unit,q.unit),working:!!String(answer.working||'').trim()};}
  return {definitions,available,build,solve,rng,format,parse,close,unitCorrect,assess};
});
