/* Original data challenges. Every result is calculated from the displayed data. */
(() => {
 'use strict';
 const entries={};
 const f=x=>Number(x.toPrecision(3)).toString();
 const add=(key,title,build)=>entries[key]={title,build};
 const problem=(question,result,unit,steps)=>({question,result,unit,steps:[...steps,`Answer: ${f(result)}${unit?' '+unit:''}.`]});
 const factor=s=>1+(s%5)*0.2;
 function percent(key,title,from,to,context){add(key,title,s=>{const a=from*factor(s),b=to*factor(s),r=(a-b)/a*100;return problem(`${context} falls from ${f(a)} to ${f(b)}. Calculate the percentage decrease.`,r,'%',[`Decrease = ${f(a)} − ${f(b)} = ${f(a-b)}.`,`Percentage decrease = decrease ÷ original × 100 = ${f(a-b)} ÷ ${f(a)} × 100.`]);});}
 add('gcse:b1','Microscopy',s=>{const image=36*factor(s),real=.12;return problem(`A cell image is ${f(image)} mm long and the real cell is ${real} mm long. Calculate magnification (a ratio without units).`,image/real,'',[`Magnification = image size ÷ real size; both lengths are in mm.`,`${f(image)} ÷ ${real} = ${f(image/real)}.`]);});
 add('gcse:b2','Mean enzyme rate',s=>{const v=24*factor(s),t=3;return problem(`An enzyme reaction makes ${f(v)} cm³ of product in ${t} minutes. Calculate mean rate in cm³ min⁻¹.`,v/t,'cm³ min⁻¹',[`Mean rate = product volume ÷ time.`,`${f(v)} ÷ ${t} = ${f(v/t)}.`]);});
 percent('gcse:b3','Disease data',800,200,'The number of reported cases in equal observation periods');
 add('gcse:b4','Photosynthesis data',s=>{const v=9*factor(s),t=3;return problem(`An aquatic plant produces ${f(v)} cm³ of oxygen in ${t} minutes. Find mean oxygen-production rate in cm³ min⁻¹.`,v/t,'cm³ min⁻¹',[`Mean rate = gas volume ÷ time.`,`${f(v)} ÷ ${t} = ${f(v/t)}.`,`Gas volume is preferable to bubble count because bubble sizes can vary.`]);});
 add('gcse:b5','Reaction-time mean',s=>{const v=[.23,.25,.22,.24,.31].map(x=>x+.01*(s%5)),r=v.reduce((a,b)=>a+b,0)/v.length;return problem(`Reaction times are ${v.map(f).join(', ')} s. Calculate the mean of all five readings in seconds; no exclusion has been justified.`,r,'s',[`Add every reading: sum = ${f(v.reduce((a,b)=>a+b,0))} s.`,`Mean = sum ÷ 5 = ${f(r)} s.`,`Investigate a possible anomaly before excluding it and report any justified exclusion.`]);});
 add('gcse:b6','Genetic probability',()=>problem('For Aa × Aa with complete dominance, what percentage of offspring is expected to have genotype aa?',25,'%',['Each parent can supply A or a with equal probability.','The four equally likely combinations are AA, Aa, Aa and aa.','aa occurs in 1 of 4 combinations: 1/4 × 100 = 25%.','This is a probability, not a guaranteed ratio in a small family.']));
 add('gcse:b7','Population estimate',s=>{const count=6+s%5;return problem(`Random 0.50 m² quadrats have a mean of ${count} plants. Estimate the population in a comparable 50 m² field.`,100*count,'plants',['Estimated density = mean count ÷ quadrat area.',`Density = ${count} ÷ 0.50 = ${count*2} plants m⁻².`,`Population estimate = density × field area = ${count*2} × 50.`,`Assume the sample is representative; the estimate has sampling uncertainty.`]);});
 add('gcse:c1','Isotope abundance',s=>{const p=60+s%5*5,r=(35*p+37*(100-p))/100;return problem(`An element has ${p}% isotope-35 and ${100-p}% isotope-37. Calculate relative atomic mass, without units.`,r,'',[`Use the abundance-weighted mean.`,`Ar = (35 × ${p} + 37 × ${100-p}) ÷ 100.`]);});
 add('gcse:c2','Particle counts in a formula',s=>{const n=4+s%5;return problem(`Count the oxygen atoms represented by ${n} formula units of Mg(NO₃)₂.`,n*6,'oxygen atoms',['Each nitrate group has 3 oxygen atoms; the subscript outside the brackets gives 2 nitrate groups.','Each formula unit contains 2 × 3 = 6 oxygen atoms.',`${n} formula units contain ${n} × 6 oxygen atoms.`]);});
 add('gcse:c3','Mass concentration',s=>{const mass=12*factor(s),vol=300;return problem(`A solution contains ${f(mass)} g of solute in ${vol} cm³. Find concentration in g dm⁻³.`,mass/.3,'g dm⁻³',['Convert 300 cm³ to 0.300 dm³.',`Concentration = mass ÷ volume = ${f(mass)} ÷ 0.300.`]);});
 add('gcse:c4','Balancing electrolysis charge',s=>{const n=2+s%5;return problem(`For ${n} ions of Al³⁺ to become neutral aluminium atoms, how many electrons must they gain in total?`,n*3,'electrons',['Reduction involves electron gain.','Each Al³⁺ gains 3 electrons: Al³⁺ + 3e⁻ → Al.',`${n} ions need ${n} × 3 electrons.`]);});
 add('gcse:c5','Reaction energy',s=>{const b=720*factor(s),m=850*factor(s);return problem(`For the stated reaction amount, bond breaking needs ${f(b)} kJ and bond formation releases ${f(m)} kJ. Calculate the overall energy change in kJ.`,b-m,'kJ',['Overall energy change = energy needed to break bonds − energy released forming bonds.',`${f(b)} − ${f(m)} = ${f(b-m)} kJ.`,'The negative result means energy is transferred to the surroundings: exothermic.']);});
 add('gcse:c6','Mean reaction rate',s=>{const v=60*factor(s),t=30;return problem(`A reaction produces ${f(v)} cm³ of gas in ${t} s. Find the mean rate in cm³ s⁻¹.`,v/t,'cm³ s⁻¹',[`Mean rate = gas volume ÷ elapsed time = ${f(v)} ÷ ${t}.`,'A mean rate does not imply that the instantaneous rate stays constant.']);});
 add('gcse:c7','Alkane formula',s=>{const n=5+s%5;return problem(`An acyclic alkane contains ${n} carbon atoms per molecule. How many hydrogen atoms are in its molecular formula?`,2*n+2,'hydrogen atoms',['The alkane general formula is CₙH₂ₙ₊₂.',`For n = ${n}, hydrogen count = 2 × ${n} + 2.`]);});
 add('gcse:c8','Chromatography',s=>{const spot=3.6*factor(s),front=6*factor(s);return problem(`A spot travels ${f(spot)} cm and the solvent front ${f(front)} cm from the baseline. Find Rf (without units).`,spot/front,'',[`Rf = spot distance ÷ solvent-front distance.`,`${f(spot)} ÷ ${f(front)} = ${f(spot/front)}.`,'Compare substances only under matching solvent and stationary-phase conditions.']);});
 percent('gcse:c9','Carbon-footprint comparison',500,350,'A product carbon footprint, measured in kg CO₂-equivalent per identical functional unit,');
 add('gcse:c10','Dissolved-solids concentration',s=>{const mass=.20*factor(s),vol=.10;return problem(`Evaporating 100 cm³ of a water sample leaves ${f(mass)} g of dissolved solids. Find the original concentration in g dm⁻³.`,mass/vol,'g dm⁻³',['100 cm³ = 0.100 dm³.',`Concentration = ${f(mass)} ÷ 0.100.`,'This measurement alone does not establish whether the water is potable.']);});
 add('gcse:p1','Useful power',s=>{const e=600*factor(s),t=20;return problem(`A motor transfers ${f(e)} J usefully in ${t} s. Find its useful power in W.`,e/t,'W',[`P = E/t = ${f(e)} ÷ ${t}.`,'One watt is one joule per second.']);});
 add('gcse:p2','Circuit current',s=>{const v=12*factor(s),r=6;return problem(`A 6.0 Ω resistor has ${f(v)} V across it. Find current in A.`,v/r,'A',[`I = V/R = ${f(v)} ÷ ${r}.`]);});
 add('gcse:p3','Density',s=>{const mass=.54*factor(s),vol=2e-4;return problem(`A block has mass ${f(mass)} kg and volume 2.00 × 10⁻⁴ m³. Find density in kg m⁻³.`,mass/vol,'kg m⁻³',[`ρ = m/V = ${f(mass)} ÷ (2.00 × 10⁻⁴).`]);});
 add('gcse:p4','Half-life',s=>{const initial=800*factor(s);return problem(`A sample has initial activity ${f(initial)} Bq and half-life 2.00 h. Find activity after 6.00 h in Bq.`,initial/8,'Bq',['Number of half-lives = 6.00/2.00 = 3.',`A = A₀ × (1/2)³ = ${f(initial)} ÷ 8.`,'Activity is decays per second; detected count rate can be smaller.']);});
 add('gcse:p5','Resultant force',s=>{const mass=900*factor(s),a=2.5;return problem(`A car of mass ${f(mass)} kg accelerates at 2.50 m s⁻². Find its resultant force in N.`,mass*a,'N',[`F = ma = ${f(mass)} × ${a}.`,'This is the resultant force, after resistive forces are included.']);});
 add('gcse:p6','Wave speed',s=>{const freq=50*factor(s),wave=.8;return problem(`A wave has frequency ${f(freq)} Hz and wavelength 0.800 m. Find speed in m s⁻¹.`,freq*wave,'m s⁻¹',[`v = fλ = ${f(freq)} × 0.800.`]);});
 add('gcse:p7','Solenoid data',s=>{const a=2+s%5,b=2*a;return problem(`For the same long air-core solenoid, assume field strength is proportional to current. Current increases from ${a} A to ${b} A. By what factor does field strength change?`,b/a,'',[`Field-strength ratio = current ratio = ${b}/${a}.`,'This proportional model holds geometry constant and avoids iron-core saturation effects.']);});
 add('gcse:p8','Light travel',s=>{const years=2+s%5;return problem(`A source is ${years} million light-years away. In the stated simple model, how many million years has its light travelled?`,years,'million years',['A light-year is the distance light travels in one year, not a time unit.',`At the stated distance, travel time is ${years} million years.`,'This is the simplified nearby-source model; cosmological expansion complicates large-distance interpretations.']);});
 add('alevel:biology:3.1','Peptide hydrolysis',s=>{const n=4+s%5;return problem(`A linear peptide contains ${n} amino-acid residues. How many water molecules are used in complete hydrolysis of its peptide bonds?`,n-1,'water molecules',[`A linear chain of ${n} residues has ${n} − 1 peptide bonds.`,'Hydrolysis uses one water molecule per bond broken.']);});
 add('alevel:biology:3.2','Actual cell size',s=>{const image=45*factor(s),mag=1500;return problem(`A cell image is ${f(image)} mm long at ×${mag}. Find the actual length in μm.`,image*1000/mag,'μm',[`Image size = ${f(image*1000)} μm.`,`Actual size = image size ÷ magnification = ${f(image*1000)} ÷ ${mag}.`]);});
 add('alevel:biology:3.3','Surface area to volume',s=>{const side=3+s%5;return problem(`A cube has side length ${side} cm. Find its surface-area-to-volume ratio in cm⁻¹.`,6/side,'cm⁻¹',[`Area = 6s² = ${6*side*side} cm²; volume = s³ = ${side**3} cm³.`,`SA/V = 6/s = 6/${side}.`]);});
 add('alevel:biology:3.4','Diversity index',s=>{const n=[20+s%5,10,10],N=n.reduce((a,b)=>a+b,0),sum=n.reduce((a,b)=>a+b*(b-1),0);return problem(`Species counts are ${n.join(', ')}. Calculate D = N(N−1)/Σn(n−1), without units.`,N*(N-1)/sum,'',[`Total N = ${N}; Σn(n−1) = ${sum}.`,`D = ${N} × ${N-1} ÷ ${sum}.`,'For this specified index, a larger value indicates greater diversity.']);});
 add('alevel:biology:3.5','Net primary productivity',s=>{const gpp=24000*factor(s),resp=9000*factor(s);return problem(`GPP is ${f(gpp)} and producer respiration is ${f(resp)} kJ m⁻² year⁻¹. Calculate NPP in the same units.`,gpp-resp,'kJ m⁻² year⁻¹',[`NPP = GPP − producer respiratory losses = ${f(gpp)} − ${f(resp)}.`,'NPP describes chemical energy available for producer growth and reproduction.']);});
 percent('alevel:biology:3.6','Urine-volume data',120,30,'Urine output, measured in mL per equal time interval,');
 add('alevel:biology:3.7','Hardy–Weinberg',s=>{const q=.1*(1+s%5),recessive=q*q,p=1-q;return problem(`Under Hardy–Weinberg assumptions, ${f(recessive*100)}% show an autosomal recessive phenotype. Find the percentage expected to be heterozygous.`,2*p*q*100,'%',[`q² = ${f(recessive)}; q = √q² = ${f(q)}.`,`p = 1 − q = ${f(p)}.`,`Heterozygote percentage = 2pq × 100 = 2 × ${f(p)} × ${f(q)} × 100.`,'Assume random mating, negligible mutation/migration/drift and no selection at this locus.']);});
 add('alevel:biology:3.8','Ideal PCR amplification',s=>{const cycles=5+s%5,start=2;return problem(`Start with ${start} double-stranded target DNA molecules. Under ideal doubling, how many are present after ${cycles} PCR cycles?`,start*2**cycles,'molecules',[`Ideal total = initial molecules × 2^(number of cycles) = ${start} × 2^${cycles}.`,'Real amplification can be less efficient and does not double indefinitely.']);});
 add('alevel:chemistry:3.1','Ideal-gas amount',s=>{const vol=250*factor(s),p=100000,T=298,R=8.31;return problem(`An ideal gas occupies ${f(vol)} cm³ at 100 kPa and 298 K. Use R = 8.31 J mol⁻¹ K⁻¹ to find amount in mol.`,p*vol*1e-6/(R*T),'mol',[`V = ${f(vol*1e-6)} m³; p = 100000 Pa.`,`n = pV/(RT) = 100000 × ${f(vol*1e-6)} ÷ (8.31 × 298).`]);});
 add('alevel:chemistry:3.2','Oxidation state',()=>problem('Find the oxidation state of manganese in MnO₄⁻, taking each oxygen as −2.',7,'',['Let manganese have oxidation state x.','x + 4(−2) = −1, so x = +7.','The sum equals the overall ionic charge, not zero.']));
 add('alevel:chemistry:3.3','TLC analysis',s=>{const spot=4.2*factor(s),front=7*factor(s);return problem(`A TLC spot moves ${f(spot)} cm and the solvent front ${f(front)} cm from the baseline. Find Rf (without units).`,spot/front,'',[`Rf = ${f(spot)} ÷ ${f(front)}.`,'Use matching solvent and stationary phase when comparing a reference; Rf alone does not prove identity.']);});
 add('alevel:physics:measurements','Uncertainty',s=>{const x=20*factor(s),dx=.2;return problem(`A length is (${f(x)} ± ${dx}) cm. Find its percentage uncertainty.`,dx/x*100,'%',[`Percentage uncertainty = absolute uncertainty ÷ measurement × 100 = ${dx} ÷ ${f(x)} × 100.`]);});
 add('alevel:physics:particles','Photoelectric effect',s=>{const photon=3+s%5,work=2;return problem(`Photon energy is ${photon}.00 eV and work function is ${work}.00 eV. Find maximum photoelectron kinetic energy in eV.`,photon-work,'eV',[`Ek,max = hf − φ = ${photon} − ${work}.`,'Increasing intensity at fixed frequency changes photon number, not energy per photon.']);});
 add('alevel:physics:waves','Double-slit fringes',s=>{const D=2*factor(s),lambda=600e-9,sep=.5e-3;return problem(`λ = 600 nm, screen distance = ${f(D)} m and slit separation = 0.500 mm. In the small-angle model, find fringe spacing in mm.`,lambda*D/sep*1000,'mm',['Convert λ = 6.00 × 10⁻⁷ m and slit separation = 5.00 × 10⁻⁴ m.',`w = λD/s = (6.00 × 10⁻⁷ × ${f(D)}) ÷ (5.00 × 10⁻⁴) m.`,'Convert metres to millimetres by multiplying by 1000.']);});
 add('alevel:physics:mechanics-materials','Elastic energy',s=>{const k=200*factor(s),x=.03;return problem(`A spring obeys Hooke’s law with k = ${f(k)} N m⁻¹ and extension 0.0300 m. Find stored elastic energy in J.`,.5*k*x*x,'J',[`E = ½kx² = ½ × ${f(k)} × 0.0300².`,'This model assumes loading within the proportional elastic region.']);});
 add('alevel:physics:electricity','Internal resistance',s=>{const emf=1.5,I=.5+.1*(s%5),r=.2;return problem(`A cell has emf 1.50 V and internal resistance 0.200 Ω. Find terminal p.d. when current is ${f(I)} A.`,emf-I*r,'V',[`Lost volts = Ir = ${f(I)} × 0.200 = ${f(I*r)} V.`,`Terminal p.d. = ε − Ir = 1.50 − ${f(I*r)}.`]);});
 add('alevel:physics:further-mechanics','Thermal energy',s=>{const m=.2*factor(s),c=4200,dT=10;return problem(`Heat ${f(m)} kg of water by 10.0 K. Use c = 4200 J kg⁻¹ K⁻¹ and assume no losses. Find required energy in J.`,m*c*dT,'J',[`Q = mcΔT = ${f(m)} × 4200 × 10.0.`]);});
 add('alevel:physics:fields','Uniform electric field',s=>{const V=100*factor(s),d=.02,q=2e-6;return problem(`Parallel plates have p.d. ${f(V)} V and separation 0.0200 m. Ignoring edge effects, find force magnitude on a +2.00 μC charge in N.`,q*V/d,'N',[`E = V/d = ${f(V)} ÷ 0.0200 V m⁻¹.`,`F = qE = (2.00 × 10⁻⁶) × ${f(V/d)}.`,'The force on the positive charge is toward the negative plate.']);});
 add('alevel:physics:nuclear','Radioactive activity',s=>{const a=800*factor(s);return problem(`Initial activity is ${f(a)} Bq and half-life is 2.00 h. Calculate activity after 6.00 h in Bq.`,a/8,'Bq',['Three half-lives have passed.',`A = A₀(1/2)³ = ${f(a)} ÷ 8.`]);});
 function build(key,seed=0){if(!Number.isInteger(seed)||seed<0)throw Error('Invalid activity seed');const entry=entries[key];if(!entry)return null;return {key,title:entry.title,seed,...entry.build(seed)};}
 function parseNumber(value){const text=String(value).trim().replace(/−/g,'-');return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(text)?Number(text):NaN;}
 function correct(value,expected){const n=parseNumber(value),tolerance=expected===0?1e-12:0.51*10**(Math.floor(Math.log10(Math.abs(expected)))-2);return Number.isFinite(n)&&Math.abs(n-expected)<=tolerance;}
 window.REVISION_SKILLS={entries,build,parseNumber,correct,format:f};
})();
