const fs=require('node:fs'),path=require('node:path');
const {loadCourses,root}=require('./course-content.cjs');
function generatePractice(){
 const w=loadCourses(),lessons=[];
 for(const topic of w.GCSE_COURSE_DATA.topics)for(const [index,[title,scope]] of topic.lessons.entries()){
  const p=w.GCSE_RICH_CONTENT.getLesson(topic,title,index),query=new URLSearchParams({subject:topic.subject,topic:topic.id,mode:scope==='triple'||topic.scope==='triple'?'triple':'combined',tab:'lessons',lesson:title});
  lessons.push({id:`gcse:${topic.id}:${index}`,level:'gcse',subject:topic.subject,topic:topic.id,topicTitle:topic.title,title,scope:scope==='triple'||topic.scope==='triple'?'triple':'combined',href:`courses/gcse/index.html?${query}`,core:p.reviewPractice[0].answer.join(' '),accuracy:p.depth.misconception,questions:p.reviewPractice,skillKey:`gcse:${topic.id}`});
 }
 for(const l of w.ALEVEL_LESSONS){
  const m=w.ALEVEL_SLIDE_DESIGN.modelFor(l);if(!m)throw Error('No reviewed physics model: '+l.id);
  lessons.push({id:`alevel:physics:${l.id}`,level:'alevel',subject:'physics',topic:l.topicId,topicTitle:l.topicTitle,title:l.title,ref:l.ref,scope:'alevel',href:`courses/alevel/index.html?subject=physics#lesson=${l.id}`,core:m.facts.join(' '),accuracy:m.use,questions:[{question:m.check,answer:[m.answer]},{question:m.q,answer:m.steps},{question:`Explain how to use ${m.eq}. Include its conditions or an important check.`,answer:[m.use,...m.facts]}],skillKey:`alevel:physics:${l.topicId}`});
 }
 for(const subject of ['biology','chemistry']){
  const source=subject==='biology'?w.ALEVEL_BIOLOGY_CONTENT:w.ALEVEL_CHEMISTRY_CONTENT;
  const refs=new Set([...source.refs,...(subject==='chemistry'?w.ALEVEL_CHEMISTRY_DETAIL.rows.map(r=>r.ref):[])]);
  const topics=w.ALEVEL_COURSE_REGISTRY[subject].topics;
  for(const ref of refs){
   const p=source.get(ref),topic=topics.find(t=>t.modules.some(m=>ref===m.ref||ref.startsWith(m.ref+'.')));
   if(!p||!topic)throw Error('No lesson or topic: '+subject+' '+ref);
   const module=topic.modules.find(m=>ref===m.ref||ref.startsWith(m.ref+'.'));
   const detail=subject==='chemistry'?w.ALEVEL_CHEMISTRY_DETAIL.rows.find(r=>r.ref===ref):null;
   const query=new URLSearchParams({subject,topic:topic.id,section:module.ref});if(ref!==module.ref)query.set('lesson',ref);
   lessons.push({id:`alevel:${subject}:${ref}`,level:'alevel',subject,topic:topic.id,topicTitle:topic.title,title:detail?.title||module.title,ref,scope:'alevel',href:`courses/alevel/subjects/topic-shell.html?${query}`,core:p.core.join(' '),accuracy:p.mis,questions:p.exam.map((question,i)=>({question,answer:p.examAnswers?.[i]||[]})),skillKey:`alevel:${subject}:${ref.split('.').slice(0,2).join('.')}`});
  }
 }
 return JSON.parse(JSON.stringify({version:1,lessons}));
}
function writePractice(){const data=generatePractice();fs.writeFileSync(path.join(root,'practice-data.js'),`// Generated by scripts/practice-catalog.cjs. Edit the source lessons, then regenerate.\nwindow.REVISION_PRACTICE = ${JSON.stringify(data)};\n`);console.log(`Indexed ${data.lessons.length} lessons with answers for practice.`);return data;}
if(require.main===module)writePractice();
module.exports={generatePractice,writePractice};
