(() => {
  'use strict';
  const CDN='https://cdn.jsdelivr.net/npm/three@0.186.0/build/three.module.js';
  let THREE,renderer,scene,camera,root,mode='micrometer',reading=.5,thimble=0,fractureStrain=.02,anim=0;
  const $=s=>document.querySelector(s);
  async function init(){const host=$('#micrometer3DV8');if(!host)return;try{THREE=await import(CDN);build(host);}catch(e){host.innerHTML='<div class="feedback partial">3D instrument unavailable on this connection. The numerical micrometer tools still work.</div>';}}
  function mat(c,m=.1,r=.4){return new THREE.MeshPhysicalMaterial({color:c,metalness:m,roughness:r,clearcoat:.35});}
  function mesh(g,m,p=[0,0,0]){const o=new THREE.Mesh(g,m);o.position.set(...p);o.castShadow=o.receiveShadow=true;return o;}
  function box(s,p,m){return mesh(new THREE.BoxGeometry(...s),m,p)}
  function cyl(r,l,p,m,axis='x'){const o=mesh(new THREE.CylinderGeometry(r,r,l,36),m,p);if(axis==='x')o.rotation.z=Math.PI/2;return o;}
  function build(host){scene=new THREE.Scene();scene.background=new THREE.Color(0x06111a);camera=new THREE.PerspectiveCamera(38,1,.05,50);camera.position.set(5,3.2,6);camera.lookAt(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.innerHTML='';host.appendChild(renderer.domElement);const controls=document.createElement('div');controls.className='mic3-controls-v8';controls.innerHTML='<button class="button active" data-mic3="micrometer">Micrometer</button><button class="button" data-mic3="fracture">Fracture close-up</button><button class="button" id="mic3RotateV8">Rotate thimble</button><input id="mic3StrainV8" type="range" min="0" max="0.12" step="0.001" value="0.02">';host.appendChild(controls);controls.querySelectorAll('[data-mic3]').forEach(b=>b.onclick=()=>{mode=b.dataset.mic3;controls.querySelectorAll('[data-mic3]').forEach(x=>x.classList.toggle('active',x===b));renderMode();});$('#mic3RotateV8').onclick=()=>{thimble=(thimble+0.12)%1;reading=.45+thimble*.1;renderMode();};$('#mic3StrainV8').oninput=e=>{fractureStrain=+e.target.value;renderMode();};scene.add(new THREE.HemisphereLight(0xcfeaff,0x1a0f08,1.6));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(4,6,5);key.castShadow=true;scene.add(key);renderMode();resize();window.addEventListener('resize',resize);renderer.domElement.addEventListener('pointermove',e=>{if(e.buttons!==1)return;root.rotation.y+=e.movementX*.008;root.rotation.x=clamp(root.rotation.x+e.movementY*.004,-.4,.4)});loop();}
  function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
  function clear(){if(root)scene.remove(root);root=new THREE.Group();scene.add(root);}
  function renderMode(){if(!THREE)return;clear();mode==='micrometer'?buildMicrometer():buildFracture();}
  function buildMicrometer(){const steel=mat(0xaebac2,.85,.22),dark=mat(0x24343d,.7,.32),wire=mat(0xb66b45,.75,.28),white=mat(0xe8eef1,.15,.55);root.add(box([4.2,.35,.35],[-.8,0,0],steel));root.add(box([.4,2.7,.45],[-2.7,.1,0],dark));root.add(cyl(.42,2.0,[1.35,0,0],steel));const th=cyl(.62,1.1,[2.55,0,0],dark);th.rotation.x=thimble*Math.PI*2;root.add(th);root.add(cyl(.22,2.0,[.1,0,0],steel));root.add(cyl(.06,1.8,[.55,0,0],wire,'y'));for(let i=0;i<21;i++){const tick=box([.025,i%5===0?.28:.16,.03],[.55+i*.075,-.27,0.24],dark);root.add(tick);}const plate=box([1.8,.8,.08],[.2,-1.2,.2],white);root.add(plate);const label=sprite(`reading ≈ ${reading.toFixed(3)} mm`);label.position.set(.5,1.2,0);root.add(label);}
  function buildFracture(){const steel=mat(0xaab7c0,.8,.25),glass=new THREE.MeshPhysicalMaterial({color:0xbcecff,transmission:.8,transparent:true,opacity:.62,roughness:.08}),m=fractureStrain>.065?glass:steel;root.add(box([4.8,.35,1.6],[0,2.1,0],mat(0x2c3c46,.7,.3)));root.add(box([4.8,.35,1.6],[0,-2.1,0],mat(0x2c3c46,.7,.3)));const fractured=fractureStrain>.085,len=3.7*(1+Math.min(fractureStrain,.085)),rad=Math.max(.08,.28*(1-fractureStrain*3));if(!fractured){root.add(cyl(rad,len,[0,0,0],m,'y'));if(fractureStrain>.045){const neck=cyl(rad*.65,.7,[0,-.6,0],m,'y');root.add(neck);}}else{const a=cyl(rad,len*.46,[0,.95,0],m,'y'),b=cyl(rad,len*.46,[0,-.95,0],m,'y');a.rotation.z=.08;b.rotation.z=-.08;root.add(a,b);}const lbl=sprite(fractured?'fracture':fractureStrain>.045?'necking / plastic deformation':'elastic deformation');lbl.position.set(0,1.2,1);root.add(lbl);}
  function sprite(text){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(5,15,22,.78)';x.fillRect(0,18,512,90);x.fillStyle='#e9fbff';x.font='600 34px system-ui';x.textAlign='center';x.fillText(text,256,74);const t=new THREE.CanvasTexture(c),s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));s.scale.set(3.8,.95,1);return s;}
  function resize(){const host=$('#micrometer3DV8');if(!host||!renderer)return;const w=host.clientWidth,h=Math.max(260,host.clientHeight-48);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
  function loop(){anim=requestAnimationFrame(loop);renderer?.render(scene,camera);}
  window.addEventListener('materials-v8-micrometer-host-ready',()=>setTimeout(init,50));if(document.readyState!=='loading')setTimeout(init,120);
})();