(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const CDN='https://cdn.jsdelivr.net/npm/three@0.186.0/build/three.module.js';
  const SCENES=[['hooke','Hooke spring'],['deformation','Elastic/plastic test'],['stress','Stress–strain specimen'],['young','Young modulus / RP4'],['density','Density bench'],['energy','Elastic energy']];
  const state={scene:'hooke',force:8,k:220,propLimit:14,elasticLimit:17,strain:.012,material:'Steel',young:200,length:2,diameter:.5,mass:2,densityMass:1.8,densityVolume:250,energyX:.08,energyK:250,plasticSet:0,drag:null,yaw:.52,pitch:.24,zoom:7.8};
  let THREE,renderer,scene,camera,root,raycaster,pointer,dragStartY=0,dragStartValue=0,anim=0,materials={},objects={};

  function installShell(){
    const lab=$('#view-lab');if(!lab||$('#threeLabV5'))return;
    const sec=document.createElement('section');sec.id='threeLabV5';sec.className='three-lab-v5';sec.innerHTML=`<div class="section-head"><div><span class="eyebrow">v5 · WebGL Materials Laboratory</span><h2>Interactive 3D materials lab</h2></div><p class="muted">Rotate the camera, zoom, drag apparatus and alter measurements. The 2D analysis tools below remain available for graph work.</p></div><div class="three-shell-v5"><div class="scene-nav-v5">${SCENES.map(([id,n])=>`<button data-three-scene="${id}" class="${id===state.scene?'active':''}">${n}</button>`).join('')}</div><div class="three-stage-v5" id="threeStageV5"><div class="three-fallback-v5"><div><strong>Loading 3D laboratory…</strong><p>WebGL model will appear here. The normal simulations remain usable if 3D is unavailable.</p></div></div></div><div class="three-overlay-v5"><div class="three-badge-v5" id="threeBadgeV5">3D · physically based materials</div><div class="three-readout-v5"><strong id="threeReadoutTitleV5">Hooke spring</strong><span id="threeReadoutV5">Loading…</span></div><div class="three-hint-v5">drag apparatus · drag background to orbit · wheel/pinch to zoom</div></div><div class="three-control-deck-v5"><div class="three-control-grid-v5" id="threeControlsV5"></div><div><div class="three-actions-v5"><button class="button primary" id="threeResetV5">Reset scene</button><button class="button" id="threeFrontV5">Front view</button><button class="button" id="threeIsoV5">Isometric view</button><button class="button" id="threeAnimateV5">Animate loading</button></div><div class="three-data-v5" id="threeDataV5">Direct manipulation is enabled on highlighted apparatus.</div></div></div><div class="photoreal-note-v5">The v5 renderer uses physically based metal/glass/polymer shaders, procedural surface texture, dynamic shadows and depth lighting. It is a teaching model rather than a photograph of one manufacturer’s apparatus.</div></div>`;
    const anchor=$('#view-lab .lab-layout');anchor?.insertAdjacentElement('beforebegin',sec);
    $$('[data-three-scene]',sec).forEach(b=>b.onclick=()=>switchScene(b.dataset.threeScene));
    $('#threeResetV5').onclick=resetScene;$('#threeFrontV5').onclick=()=>setCamera(0,.12,7.2);$('#threeIsoV5').onclick=()=>setCamera(.55,.3,7.8);$('#threeAnimateV5').onclick=animateLoading;
  }

  function woodTexture(){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d');const g=x.createLinearGradient(0,0,512,0);g.addColorStop(0,'#5a331f');g.addColorStop(.5,'#8a5a36');g.addColorStop(1,'#492a1b');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);for(let i=0;i<90;i++){x.strokeStyle=`rgba(30,12,5,${.06+Math.random()*.09})`;x.lineWidth=1+Math.random()*2;x.beginPath();let y=Math.random()*256;x.moveTo(0,y);for(let px=0;px<=512;px+=32)x.lineTo(px,y+Math.sin(px*.03+i)*3+Math.random()*2);x.stroke();}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2.5,1);return t;}
  function brushedTexture(){const c=document.createElement('canvas');c.width=256;c.height=256;const x=c.getContext('2d');x.fillStyle='#aeb8bf';x.fillRect(0,0,256,256);for(let i=0;i<500;i++){x.strokeStyle=`rgba(255,255,255,${Math.random()*.12})`;x.beginPath();const y=Math.random()*256;x.moveTo(0,y);x.lineTo(256,y+(Math.random()-.5)*2);x.stroke();}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2,4);return t;}
  function makeMaterials(){const wood=woodTexture(),brush=brushedTexture();materials={wood:new THREE.MeshStandardMaterial({map:wood,roughness:.72,metalness:.05}),steel:new THREE.MeshPhysicalMaterial({color:0xaab7c0,metalness:.86,roughness:.24,map:brush,clearcoat:.25}),darkSteel:new THREE.MeshStandardMaterial({color:0x334653,metalness:.75,roughness:.3}),copper:new THREE.MeshPhysicalMaterial({color:0xb96c43,metalness:.78,roughness:.3,clearcoat:.18}),glass:new THREE.MeshPhysicalMaterial({color:0xb9eaff,roughness:.08,transmission:.82,transparent:true,opacity:.58,thickness:.45,ior:1.45}),polymer:new THREE.MeshPhysicalMaterial({color:0x397bb6,roughness:.28,metalness:.02,clearcoat:.72,clearcoatRoughness:.15}),rubber:new THREE.MeshStandardMaterial({color:0x161c20,roughness:.9}),white:new THREE.MeshStandardMaterial({color:0xe6edf2,roughness:.55}),green:new THREE.MeshStandardMaterial({color:0x59dcae,roughness:.35,emissive:0x08271e}),yellow:new THREE.MeshStandardMaterial({color:0xffc961,roughness:.38,emissive:0x251600}),red:new THREE.MeshStandardMaterial({color:0xe86c69,roughness:.4,emissive:0x260908})};}
  function mesh(g,m,pos=[0,0,0],cast=true){const o=new THREE.Mesh(g,m);o.position.set(...pos);o.castShadow=cast;o.receiveShadow=true;return o;}
  function box(s,pos,m=materials.steel,r=0){const o=mesh(new THREE.BoxGeometry(...s),m,pos);o.rotation.y=r;return o;}
  function cyl(rad,len,pos,m=materials.steel,axis='y'){const o=mesh(new THREE.CylinderGeometry(rad,rad,len,24),m,pos);if(axis==='x')o.rotation.z=Math.PI/2;if(axis==='z')o.rotation.x=Math.PI/2;return o;}
  function textSprite(text,color='#eaf7ff',scale=1){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.font='600 42px system-ui';x.fillStyle='rgba(4,12,18,.72)';x.roundRect?.(2,15,508,96,20);x.fill();x.fillStyle=color;x.textAlign='center';x.fillText(text,256,77);const t=new THREE.CanvasTexture(c),mat=new THREE.SpriteMaterial({map:t,transparent:true}),s=new THREE.Sprite(mat);s.scale.set(3.6*scale,.9*scale,1);return s;}
  function springMesh(length=2.5,r=.34,turns=15){const pts=[];for(let i=0;i<=220;i++){const t=i/220;pts.push(new THREE.Vector3(Math.sin(t*Math.PI*2*turns)*r,-t*length,Math.cos(t*Math.PI*2*turns)*r));}const curve=new THREE.CatmullRomCurve3(pts),geo=new THREE.TubeGeometry(curve,220,.045,10,false);const o=mesh(geo,materials.steel,[0,0,0]);return o;}
  function labBase(){const g=new THREE.Group();g.add(box([7.4,.36,4.6],[0,-2.35,0],materials.wood));g.add(box([7.2,.12,4.4],[0,-2.13,0],materials.darkSteel));for(const x of [-3.2,3.2])for(const z of [-1.75,1.75])g.add(box([.22,2.3,.22],[x,-3.55,z],materials.darkSteel));return g;}
  function clamp(pos=[0,0,0],rot=0){const g=new THREE.Group();g.position.set(...pos);g.rotation.y=rot;g.add(box([1.1,.28,.7],[0,0,0],materials.darkSteel));g.add(box([.18,.9,.65],[-.43,.5,0],materials.steel));g.add(box([.18,.9,.65],[.43,.5,0],materials.steel));g.add(cyl(.12,.9,[0,.82,0],materials.steel,'x'));return g;}
  function setupScene(){scene=new THREE.Scene();scene.background=new THREE.Color(0x061018);scene.fog=new THREE.Fog(0x061018,12,24);camera=new THREE.PerspectiveCamera(42,1,.05,80);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.domElement.setAttribute('aria-label','Interactive 3D A-level materials laboratory');const stage=$('#threeStageV5');stage.innerHTML='';stage.appendChild(renderer.domElement);const hemi=new THREE.HemisphereLight(0xc9e8ff,0x1c1009,1.55);scene.add(hemi);const key=new THREE.DirectionalLight(0xffffff,3.4);key.position.set(4,7,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-8;key.shadow.camera.right=8;key.shadow.camera.top=8;key.shadow.camera.bottom=-8;scene.add(key);const rim=new THREE.PointLight(0x6ba9ff,70,12,2);rim.position.set(-4,2,-4);scene.add(rim);const warm=new THREE.PointLight(0xffbd7d,45,10,2);warm.position.set(4,1,3);scene.add(warm);raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();wirePointer();setCamera(.52,.25,7.8);switchScene(state.scene);resize();window.addEventListener('resize',resize);loop();}
  function setCamera(yaw,pitch,zoom){state.yaw=yaw;state.pitch=pitch;state.zoom=zoom;updateCamera();}
  function updateCamera(){const r=state.zoom,cp=Math.cos(state.pitch);camera.position.set(Math.sin(state.yaw)*r*cp,Math.sin(state.pitch)*r+1.1,Math.cos(state.yaw)*r*cp);camera.lookAt(0,-.4,0);}
  function resize(){const stage=$('#threeStageV5');if(!stage||!renderer)return;const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
  function clearRoot(){if(root)scene.remove(root);root=new THREE.Group();scene.add(root);objects={};root.add(labBase());}
  function tagged(o,drag,cursor='grab'){o.userData.drag=drag;o.userData.cursor=cursor;objects[drag]=o;return o;}

  function buildHooke(){clearRoot();const frame=new THREE.Group();frame.add(box([4.6,.25,.65],[0,2.35,0],materials.darkSteel));frame.add(box([.32,4.55,.65],[-2.05,.05,0],materials.darkSteel));frame.add(box([.32,4.55,.65],[2.05,.05,0],materials.darkSteel));root.add(frame);const ext=hookeExtension();const spring=springMesh(2.35+ext*8);spring.position.set(0,2.18,0);root.add(spring);objects.spring=spring;const hanger=tagged(box([1.15,.34,.85],[0,-.35-ext*8,0],materials.darkSteel),'force');root.add(hanger);root.add(cyl(.12,.8,[0,-.72-ext*8,0],materials.steel));for(let i=0;i<Math.max(1,Math.round(state.force/2));i++)root.add(cyl(.42,.11,[0,-1.12-ext*8-i*.13,0],materials.steel));const label=textSprite('drag mass hanger to change force','#dff7ff',.7);label.position.set(2.05,-.45,0);root.add(label);root.add(forceArrow(new THREE.Vector3(0,-.4-ext*8,0),Math.max(.7,state.force/8),0xffc961));}
  function hookeExtension(){return state.force<=state.propLimit?state.force/state.k:(state.propLimit/state.k)+(state.force-state.propLimit)/state.k*1.85;}
  function forceArrow(pos,len,color){const dir=new THREE.Vector3(0,-1,0),a=new THREE.ArrowHelper(dir,pos,len,color,.24,.13);return a;}
  function buildDeformation(){clearRoot();root.add(box([4.7,.35,1.4],[0,2.2,0],materials.darkSteel));root.add(box([4.7,.35,1.4],[0,-1.95,0],materials.darkSteel));root.add(box([.35,4.3,.35],[-2.05,.05,0],materials.darkSteel));root.add(box([.35,4.3,.35],[2.05,.05,0],materials.darkSteel));const strain=state.strain,plastic=Math.max(state.plasticSet,state.strain>.055?(state.strain-.055)*.35:0);state.plasticSet=plastic;const len=3.65*(1+strain+plastic),rad=Math.max(.11,.19*(1-strain*2.6));const specimen=tagged(cyl(rad,len,[0,.1,0],state.material==='Glass'?materials.glass:state.material==='Polymer'?materials.polymer:state.material==='Copper'?materials.copper:materials.steel),'strain');root.add(specimen);const jaw=tagged(box([1.7,.5,1.0],[0,2.0+strain*7,0],materials.darkSteel),'strain');root.add(jaw);const l=textSprite(strain>.08?'plastic / necking region':strain>.055?'beyond elastic limit':'elastic loading',strain>.055?'#ffb08e':'#7be2b6',.75);l.position.set(2.1,.6,0);root.add(l);}
  function buildStress(){clearRoot();const mat=materialFor(state.material);root.add(box([5.3,.28,1.4],[-.0,2.05,0],materials.darkSteel));root.add(box([5.3,.28,1.4],[-.0,-1.8,0],materials.darkSteel));const e=state.strain;const props=materialProps(state.material);const fractured=e>props.breakE;const len=3.45*(1+Math.min(e,props.breakE));if(!fractured){const s=tagged(cyl(.18*Math.max(.55,1-e*1.8),len,[0,.1,0],mat),'strain');root.add(s);}else{const a=cyl(.15,len*.48,[0,.93,0],mat),b=cyl(.15,len*.48,[0,-.73,0],mat);a.rotation.z=.08;b.rotation.z=-.08;root.add(a,b);const sparks=new THREE.Group();for(let i=0;i<12;i++){const p=mesh(new THREE.SphereGeometry(.025,8,8),materials.yellow,[(Math.random()-.5)*.7,(Math.random()-.5)*.3,(Math.random()-.5)*.4],false);sparks.add(p);}root.add(sparks);}const tag=textSprite(fractured?'fractured':`${state.material} · E ≈ ${props.E} GPa`,fractured?'#ff9a92':'#dff7ff',.72);tag.position.set(2,.6,0);root.add(tag);}
  function materialProps(n){return {Steel:{E:200,breakS:720,breakE:.055},Copper:{E:120,breakS:350,breakE:.10},Glass:{E:70,breakS:90,breakE:.0013},Polymer:{E:3,breakS:65,breakE:.12}}[n]||{E:200,breakS:720,breakE:.055};}
  function materialFor(n){return n==='Copper'?materials.copper:n==='Glass'?materials.glass:n==='Polymer'?materials.polymer:materials.steel;}
  function buildYoung(){clearRoot();root.add(box([6,.28,1.1],[0,2.3,0],materials.darkSteel));root.add(clamp([-2.1,1.75,0]));root.add(clamp([1.55,1.75,0],0));const E=state.young*1e9,d=state.diameter*1e-3,A=Math.PI*d*d/4,F=state.mass*9.81,x=F*state.length/(A*E);const extScale=Math.min(.65,x*160);const ref=cyl(.035,3.55,[-1.0,.25,0],materials.steel);root.add(ref);const test=cyl(Math.max(.025,state.diameter*.06),3.55+extScale,[.5,.25-extScale/2,0],materials.copper);root.add(test);const pan=tagged(box([1.15,.16,.9],[.5,-1.62-extScale,0],materials.darkSteel),'mass');root.add(pan);root.add(cyl(.06,.55,[.5,-1.94-extScale,0],materials.steel));for(let i=0;i<Math.max(1,Math.round(state.mass));i++)root.add(cyl(.33,.10,[.5,-2.18-extScale-i*.11,0],materials.steel));const scale=box([.18,3.0,.08],[1.34,.2,.22],materials.white);root.add(scale);for(let i=0;i<13;i++)root.add(box([i%5===0?.26:.16,.018,.04],[1.20+(i%5===0?.04:.09),1.55-i*.25,.28],materials.darkSteel));const micro=new THREE.Group();micro.position.set(2.65,.72,.15);micro.add(cyl(.42,.85,[0,0,0],materials.steel,'x'));micro.add(cyl(.29,.35,[.48,0,0],materials.darkSteel,'x'));micro.add(box([.32,1.05,.28],[-.42,0,0],materials.darkSteel));root.add(micro);const lab=textSprite('RP4 · drag mass hanger','#dff7ff',.72);lab.position.set(-.15,-.85,-.3);root.add(lab);}
  function buildDensity(){clearRoot();const blockA=tagged(box([1.35,1.35,1.35],[-1.55,-1.25,0],materials.polymer),'densityMass');const blockB=box([1.35,1.35,1.35],[1.55,-1.25,0],materials.steel);root.add(blockA,blockB);const balance=box([4.8,.12,.38],[0,.35,0],materials.steel);balance.rotation.z=(state.densityMass-2.8)*.035;root.add(balance);root.add(cyl(.09,1.2,[0,-.25,0],materials.darkSteel));root.add(box([1.1,.18,1.1],[-1.65,.05,0],materials.darkSteel));root.add(box([1.1,.18,1.1],[1.65,.05,0],materials.darkSteel));const a=textSprite('adjust sample mass','#dff7ff',.65);a.position.set(-1.6,1.2,0);root.add(a);const b=textSprite('reference metal','#dff7ff',.65);b.position.set(1.6,1.2,0);root.add(b);}
  function buildEnergy(){clearRoot();root.add(box([5.8,.28,.7],[-.25,.85,0],materials.darkSteel));root.add(box([.35,2.8,.7],[-2.8,-.35,0],materials.darkSteel));const spring=springMesh(2.2+state.energyX*4,.28,13);spring.rotation.z=-Math.PI/2;spring.position.set(-2.55,.0,0);root.add(spring);const blockObj=tagged(box([.85,.85,.85],[.15+state.energyX*4,-.02,0],materials.polymer),'energyX');root.add(blockObj);const arrow=new THREE.ArrowHelper(new THREE.Vector3(1,0,0),new THREE.Vector3(.5+state.energyX*4,.0,0),Math.max(.5,state.energyX*5),0xffc961,.22,.12);root.add(arrow);const l=textSprite('drag block · stored elastic energy','#dff7ff',.68);l.position.set(1.8,1.15,0);root.add(l);}

  function switchScene(id){state.scene=id;$$('[data-three-scene]').forEach(b=>b.classList.toggle('active',b.dataset.threeScene===id));renderControls();if(!THREE)return;buildCurrent();updateReadout();}
  function buildCurrent(){if(state.scene==='hooke')buildHooke();if(state.scene==='deformation')buildDeformation();if(state.scene==='stress')buildStress();if(state.scene==='young')buildYoung();if(state.scene==='density')buildDensity();if(state.scene==='energy')buildEnergy();}
  function control(label,key,min,max,step,unit=''){return `<div class="three-control-v5"><label><span>${label}</span><b id="out-${key}">${Number(state[key]).toFixed(step<.01?3:step<1?2:1)} ${unit}</b></label><input type="range" data-three-key="${key}" min="${min}" max="${max}" step="${step}" value="${state[key]}"></div>`;}
  function select(label,key,options){return `<div class="three-control-v5"><label><span>${label}</span></label><select data-three-key="${key}">${options.map(o=>`<option ${state[key]===o?'selected':''}>${o}</option>`).join('')}</select></div>`;}
  function renderControls(){const c=$('#threeControlsV5');if(!c)return;let h='';if(state.scene==='hooke')h=control('Applied force','force',0,22,.5,'N')+control('Spring constant','k',80,500,10,'N m⁻¹')+control('Proportional limit','propLimit',8,20,.5,'N');if(state.scene==='deformation')h=control('Applied strain','strain',0,.12,.001,'')+select('Material','material',['Steel','Copper','Glass','Polymer'])+control('Elastic limit model','elasticLimit',12,24,.5,'N');if(state.scene==='stress')h=select('Material','material',['Steel','Copper','Glass','Polymer'])+control('Strain','strain',0,.12,.001,'');if(state.scene==='young')h=control('Load mass','mass',.5,8,.5,'kg')+control('Wire length','length',1,3,.1,'m')+control('Diameter','diameter',.30,.75,.01,'mm')+control('Young modulus','young',50,220,5,'GPa');if(state.scene==='density')h=control('Sample mass','densityMass',.3,5,.1,'kg')+control('Sample volume','densityVolume',80,800,10,'cm³');if(state.scene==='energy')h=control('Extension','energyX',0,.20,.005,'m')+control('Spring constant','energyK',80,500,10,'N m⁻¹');c.innerHTML=h;$$('[data-three-key]',c).forEach(el=>{const fn=e=>{const k=e.target.dataset.threeKey;state[k]=e.target.tagName==='SELECT'?e.target.value:+e.target.value;const out=$(`#out-${k}`);if(out)out.textContent=`${state[k]} ${out.textContent.split(' ').slice(1).join(' ')}`;if(THREE){buildCurrent();updateReadout();}};el.addEventListener('input',fn);el.addEventListener('change',fn);});}
  function updateReadout(){const title=SCENES.find(x=>x[0]===state.scene)?.[1]||'3D lab';$('#threeReadoutTitleV5').textContent=title;let t='',d='';if(state.scene==='hooke'){const x=hookeExtension();t=`F = ${state.force.toFixed(1)} N · ΔL ≈ ${(x*1000).toFixed(1)} mm`;d=state.force<=state.propLimit?`Hookean region: F/ΔL ≈ ${(state.force/Math.max(x,1e-9)).toFixed(0)} N m⁻¹.`:'Beyond the proportional limit: extension is no longer directly proportional to force.';}if(state.scene==='deformation'){const p=materialProps(state.material);t=`strain = ${state.strain.toFixed(3)} · ${state.material}`;d=state.strain>p.breakE?'Model specimen has fractured.':state.strain>.055?'Plastic / permanent deformation region.':'Elastic teaching region.';}if(state.scene==='stress'){const p=materialProps(state.material),stress=state.strain>p.breakE?0:Math.min(p.E*1000*state.strain,p.breakS);t=`σ ≈ ${stress.toFixed(1)} MPa · ε = ${state.strain.toFixed(3)}`;d=`Initial slope represents E ≈ ${p.E} GPa; fracture strain model ≈ ${p.breakE}.`;}if(state.scene==='young'){const E=state.young*1e9,dia=state.diameter*1e-3,A=Math.PI*dia*dia/4,F=state.mass*9.81,x=F*state.length/(A*E);t=`ΔL ≈ ${(x*1000).toFixed(3)} mm · F = ${F.toFixed(2)} N`;d=`A = ${A.toExponential(2)} m² · E = ${state.young} GPa. Drag the hanger or change micrometer diameter.`;}if(state.scene==='density'){const rho=state.densityMass/(state.densityVolume*1e-6);t=`ρ = ${rho.toExponential(3)} kg m⁻³`;d='Change mass or volume independently to see what density actually measures.';}if(state.scene==='energy'){const F=state.energyK*state.energyX,E=.5*state.energyK*state.energyX**2;t=`F = ${F.toFixed(1)} N · E = ${E.toFixed(3)} J`;d='Stored energy is the area under the Hookean force–extension graph.';}$('#threeReadoutV5').innerHTML=`${t}<br>${d}`;$('#threeDataV5').textContent=d;}

  function wirePointer(){const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);pointerFromEvent(e);const hits=raycaster.intersectObjects(root?.children||[],true);const hit=hits.find(h=>h.object?.userData?.drag||h.object?.parent?.userData?.drag);const obj=hit&&(hit.object.userData.drag?hit.object:hit.object.parent);if(obj?.userData?.drag){state.drag=obj.userData.drag;dragStartY=e.clientY;dragStartValue=state[state.drag];canvas.style.cursor='grabbing';}else{state.drag='orbit';dragStartY=e.clientY;state._dragX=e.clientX;state._yaw=state.yaw;state._pitch=state.pitch;}});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;if(state.drag==='orbit'){state.yaw=state._yaw+(e.clientX-state._dragX)*.006;state.pitch=Math.max(-.1,Math.min(.75,state._pitch-(e.clientY-dragStartY)*.004));updateCamera();return;}const dy=dragStartY-e.clientY;if(state.drag==='force')state.force=Math.max(0,Math.min(22,dragStartValue+dy*.06));if(state.drag==='strain')state.strain=Math.max(0,Math.min(.12,dragStartValue+dy*.00035));if(state.drag==='mass')state.mass=Math.max(.5,Math.min(8,dragStartValue+dy*.022));if(state.drag==='densityMass')state.densityMass=Math.max(.3,Math.min(5,dragStartValue+dy*.012));if(state.drag==='energyX')state.energyX=Math.max(0,Math.min(.2,dragStartValue+dy*.00065));renderControls();buildCurrent();updateReadout();});const stop=()=>{state.drag=null;canvas.style.cursor='grab'};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(4.7,Math.min(12.5,state.zoom+e.deltaY*.006));updateCamera();},{passive:false});}
  function pointerFromEvent(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(pointer,camera);}
  function resetScene(){Object.assign(state,{force:8,k:220,propLimit:14,elasticLimit:17,strain:.012,material:'Steel',young:200,length:2,diameter:.5,mass:2,densityMass:1.8,densityVolume:250,energyX:.08,energyK:250,plasticSet:0});renderControls();if(THREE){buildCurrent();updateReadout();}}
  function animateLoading(){let start=performance.now(),dur=2600,base=state.scene==='young'?state.mass:state.scene==='energy'?state.energyX:state.scene==='hooke'?state.force:state.strain;cancelAnimationFrame(state._loadAnim);const step=t=>{const p=Math.min(1,(t-start)/dur),wave=.5-.5*Math.cos(p*Math.PI*2);if(state.scene==='hooke')state.force=3+wave*15;if(state.scene==='young')state.mass=1+wave*5;if(state.scene==='energy')state.energyX=.02+wave*.14;if(state.scene==='deformation'||state.scene==='stress')state.strain=.005+wave*.07;renderControls();buildCurrent();updateReadout();if(p<1)state._loadAnim=requestAnimationFrame(step);else{if(state.scene==='hooke')state.force=base;if(state.scene==='young')state.mass=base;if(state.scene==='energy')state.energyX=base;if(state.scene==='deformation'||state.scene==='stress')state.strain=base;renderControls();buildCurrent();updateReadout();}};state._loadAnim=requestAnimationFrame(step);}
  function loop(){anim=requestAnimationFrame(loop);if(root)root.rotation.y+=0;renderer.render(scene,camera);}
  async function start(){installShell();renderControls();updateReadout();try{THREE=await import(CDN);makeMaterials();setupScene();$('#threeBadgeV5').textContent='3D · WebGL · physically based rendering';}catch(err){console.warn('3D lab could not load',err);const f=$('#threeStageV5 .three-fallback-v5');if(f)f.innerHTML='<div><strong>3D renderer unavailable on this connection.</strong><p>The existing 2D simulations, graph lab and practical tools still work. Reload when online to initialise the WebGL module.</p></div>';$('#threeBadgeV5').textContent='3D fallback';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(start,140));else setTimeout(start,140);
})();
